// web/src/components/MenuSearch.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { NModal, NInput, NScrollbar, NEmpty } from 'naive-ui'
import { Icon } from '@iconify/vue'
import { onKeyStroke } from '@vueuse/core'
import { useI18n } from 'vue-i18n'
import { useMenuFlat, type MenuLeaf } from '@/composables/useMenuFlat'

type Hit = MenuLeaf & { display: string }

const show = defineModel<boolean>('show', { default: false })
const router = useRouter()
const { t } = useI18n()
const leaves = useMenuFlat()

const q = ref('')
const cursor = ref(0)
const inputRef = ref<InstanceType<typeof NInput>>()

function label(item: MenuLeaf) {
  return item.title.includes('.') ? t(item.title) : item.title
}

const results = computed<Hit[]>(() => {
  const list: Hit[] = leaves.value.map((l) => ({ ...l, display: label(l) }))
  const kw = q.value.trim().toLowerCase()
  if (!kw) return list
  return list.filter((l) => l.display.toLowerCase().includes(kw) || l.path.toLowerCase().includes(kw))
})

watch(results, () => (cursor.value = 0))
watch(show, (v) => {
  if (v) {
    q.value = ''
    cursor.value = 0
    nextTick(() => inputRef.value?.focus())
  }
})

function go(item?: Hit) {
  if (item) router.push(item.path)
  show.value = false
}

function esc(s: string) {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] ?? c)
}
function highlight(text: string) {
  const kw = q.value.trim()
  const safe = esc(text)
  if (!kw) return safe
  const k = esc(kw)
  const i = safe.toLowerCase().indexOf(k.toLowerCase())
  if (i === -1) return safe
  return safe.slice(0, i) + '<mark>' + safe.slice(i, i + k.length) + '</mark>' + safe.slice(i + k.length)
}

// 全局热键 Ctrl/Cmd+K 开关面板
onKeyStroke('k', (e) => {
  if (e.ctrlKey || e.metaKey) {
    e.preventDefault()
    show.value = !show.value
  }
})
onKeyStroke('ArrowDown', (e) => {
  if (!show.value) return
  e.preventDefault()
  cursor.value = Math.min(cursor.value + 1, results.value.length - 1)
})
onKeyStroke('ArrowUp', (e) => {
  if (!show.value) return
  e.preventDefault()
  cursor.value = Math.max(cursor.value - 1, 0)
})
onKeyStroke('Enter', (e) => {
  if (!show.value) return
  e.preventDefault()
  go(results.value[cursor.value])
})
</script>

<template>
  <n-modal v-model:show="show" transform-origin="center">
    <div class="palette">
      <div class="search">
        <Icon icon="ph:magnifying-glass" :width="18" class="sicon" />
        <n-input
          ref="inputRef"
          v-model:value="q"
          :placeholder="t('settings.searchPlaceholder')"
          :bordered="false"
          size="large"
        />
      </div>
      <n-scrollbar style="max-height: 52vh">
        <div v-if="results.length" class="list">
          <div
            v-for="(item, i) in results"
            :key="item.path"
            class="item"
            :class="{ active: i === cursor }"
            @click="go(item)"
            @mouseenter="cursor = i"
          >
            <Icon v-if="item.icon" :icon="item.icon" :width="18" class="iicon" />
            <span class="ititle" v-html="highlight(item.display)" />
            <span class="ipath">{{ item.breadcrumb.join(' / ') }}</span>
          </div>
        </div>
        <n-empty v-else :description="t('settings.searchEmpty')" class="empty" />
      </n-scrollbar>
      <div class="hint">{{ t('settings.searchHint') }}</div>
    </div>
  </n-modal>
</template>

<style scoped>
.palette {
  width: 560px;
  max-width: 92vw;
  background: var(--color-bg-container);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-lg);
  overflow: hidden;
}
.search {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 16px;
  border-bottom: 1px solid var(--color-border);
}
.sicon {
  color: var(--color-text-tertiary);
  flex-shrink: 0;
}
.list {
  padding: 8px;
}
.item {
  display: flex;
  align-items: center;
  gap: 10px;
  height: 44px;
  padding: 0 12px;
  border-radius: var(--radius-md);
  cursor: pointer;
  color: var(--color-text-primary);
}
.item.active {
  background: var(--color-primary-light);
  color: var(--color-primary);
}
.iicon {
  flex-shrink: 0;
}
.ititle {
  font-size: var(--font-size-md);
}
.ititle :deep(mark) {
  background: transparent;
  color: var(--color-primary);
  font-weight: 600;
}
.ipath {
  margin-left: auto;
  font-size: var(--font-size-sm);
  color: var(--color-text-tertiary);
}
.empty {
  padding: 32px 0;
}
.hint {
  padding: 8px 16px;
  border-top: 1px solid var(--color-border);
  font-size: var(--font-size-sm);
  color: var(--color-text-tertiary);
}
</style>

// web-react/src/layouts/MenuSearch.tsx
import { useEffect, useMemo, useRef, useState, type KeyboardEvent, type ReactNode } from 'react'
import { Modal, Input, Empty, type InputRef } from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { flatLeaves, openIfExternal, type MenuItem, type MenuLeaf } from './menuItems'
import './menusearch.css'

// 关键词命中切成 前/命中/后 三段,用 <mark> 高亮。React 天然转义文本,免 Vue 版的 v-html + 手写 esc(即那处 XSS 面)。
function highlight(text: string, kw: string): ReactNode {
  if (!kw) return text
  const i = text.toLowerCase().indexOf(kw.toLowerCase())
  if (i === -1) return text
  return (
    <>
      {text.slice(0, i)}
      <mark>{text.slice(i, i + kw.length)}</mark>
      {text.slice(i + kw.length)}
    </>
  )
}

interface Props {
  open: boolean
  onClose: () => void
  items: MenuItem[]
}

/**
 * 命令面板:全局菜单搜索 + 键盘跳转(Ctrl/Cmd+K 由 LayoutShell 开合)。移植 Vue `components/MenuSearch.vue`。
 * 叶子取自 `flatLeaves(items)`(已翻译 label + 面包屑);内部路径 navigate、外链 window.open。
 */
export function MenuSearch({ open, onClose, items }: Props) {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const inputRef = useRef<InputRef>(null)
  const [q, setQ] = useState('')
  const [cursor, setCursor] = useState(0)

  const leaves = useMemo(() => flatLeaves(items), [items])
  const results = useMemo<MenuLeaf[]>(() => {
    const kw = q.trim().toLowerCase()
    if (!kw) return leaves
    return leaves.filter((l) => l.label.toLowerCase().includes(kw) || l.key.toLowerCase().includes(kw))
  }, [leaves, q])

  // 结果集变化(改关键词)→ 高亮光标回首项。
  useEffect(() => setCursor(0), [results])

  function go(item?: MenuLeaf) {
    if (item && !openIfExternal(item.key)) navigate(item.key)
    onClose()
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setCursor((c) => Math.min(c + 1, results.length - 1))
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setCursor((c) => Math.max(c - 1, 0))
    } else if (e.key === 'Enter') {
      e.preventDefault()
      go(results[cursor])
    }
  }

  const kw = q.trim()

  return (
    <Modal
      open={open}
      onCancel={onClose}
      footer={null}
      closable={false}
      width={560}
      styles={{ container: { padding: 0 } }}
      // 开时聚焦输入框;关时清空,下次打开是干净态。
      afterOpenChange={(o) => {
        if (o) inputRef.current?.focus()
        else {
          setQ('')
          setCursor(0)
        }
      }}
    >
      {/* onKeyDown 挂在容器:输入框的方向键/回车冒泡上来统一处理(Esc 由 Modal keyboard 关闭)。 */}
      <div className="palette" onKeyDown={onKeyDown}>
        <Input
          ref={inputRef}
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder={t('settings.searchPlaceholder')}
          prefix={<SearchOutlined />}
          variant="borderless"
          size="large"
          className="palette-input"
        />
        {results.length ? (
          <div className="palette-list">
            {results.map((item, i) => (
              <div
                key={item.key}
                className={`palette-item${i === cursor ? ' active' : ''}`}
                onClick={() => go(item)}
                onMouseEnter={() => setCursor(i)}
              >
                <span className="palette-title">{highlight(item.label, kw)}</span>
                <span className="palette-path">{item.breadcrumb.join(' / ')}</span>
              </div>
            ))}
          </div>
        ) : (
          <Empty description={t('settings.searchEmpty')} className="palette-empty" />
        )}
        <div className="palette-hint">{t('settings.searchHint')}</div>
      </div>
    </Modal>
  )
}
