// web/src/layouts/TabsBar.vue
<script setup lang="ts">
import { computed, h, nextTick, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { NDropdown, NScrollbar, type DropdownOption } from 'naive-ui'
import { Icon } from '@iconify/vue'
import { useI18n } from 'vue-i18n'
import { useTabsStore, type TabItem } from '@/stores/tabs'

const tabs = useTabsStore()
const route = useRoute()
const router = useRouter()
const { t } = useI18n()

const activePath = computed(() => route.path)
const stripRef = ref<HTMLElement>()

function tabTitle(item: TabItem) {
  return item.title.includes('.') ? t(item.title) : item.title
}
function onClick(item: TabItem) {
  if (item.path !== route.path) router.push(item.fullPath)
}

function renderIcon(name: string) {
  return () => h(Icon, { icon: name, width: 16 })
}

const ctxShow = ref(false)
const ctxX = ref(0)
const ctxY = ref(0)
const ctxTab = ref<TabItem>()
const ctxOptions = computed<DropdownOption[]>(() => [
  { label: t('tabs.refresh'), key: 'refresh', icon: renderIcon('lucide:rotate-cw') },
  // 应用首页(affix)恒固定,不提供固定/取消项;其余标签可用户手动固定。
  {
    label: ctxTab.value?.pinned ? t('tabs.unpin') : t('tabs.pin'),
    key: 'pin', icon: renderIcon('lucide:pin'), disabled: ctxTab.value?.affix,
  },
  { label: t('tabs.close'), key: 'close', icon: renderIcon('lucide:x'), disabled: ctxTab.value?.affix || ctxTab.value?.pinned },
  { label: t('tabs.closeOthers'), key: 'others', icon: renderIcon('lucide:minimize-2') },
  { label: t('tabs.closeLeft'), key: 'left', icon: renderIcon('lucide:arrow-left-to-line') },
  { label: t('tabs.closeRight'), key: 'right', icon: renderIcon('lucide:arrow-right-to-line') },
  { label: t('tabs.closeAll'), key: 'all', icon: renderIcon('lucide:list-x') },
])

function onContext(e: MouseEvent, item: TabItem) {
  e.preventDefault()
  ctxTab.value = item
  // 先关再于 nextTick 重开:菜单已展开时右键切到别的标签,只改坐标 NDropdown 不会重定位。
  ctxShow.value = false
  nextTick(() => {
    ctxX.value = e.clientX
    ctxY.value = e.clientY
    ctxShow.value = true
  })
}
function onCtxSelect(key: string) {
  ctxShow.value = false
  const tab = ctxTab.value
  if (!tab) return
  if (key === 'refresh') tabs.refreshTab(tab.name)
  else if (key === 'pin') tabs.togglePin(tab.path)
  else if (key === 'close') tabs.removeTab(tab.path)
  else if (key === 'others') tabs.closeOthers(tab.path)
  else if (key === 'left') tabs.closeLeft(tab.path)
  else if (key === 'right') tabs.closeRight(tab.path)
  else if (key === 'all') tabs.closeAll()
}

// 激活标签滚入视野
watch(activePath, () => {
  nextTick(() => stripRef.value?.querySelector('.chip.active')?.scrollIntoView({ block: 'nearest', inline: 'nearest' }))
})
</script>

<template>
  <div class="tabsbar">
    <n-scrollbar x-scrollable>
      <div ref="stripRef" class="strip">
        <!-- chip 与关闭 X 均为可点非按钮元素:补 role/tabindex/键盘激活,键盘用户也能切换/关闭标签(右键菜单是鼠标专属) -->
        <div
          v-for="item in tabs.tabs"
          :key="item.path"
          class="chip"
          :class="{ active: item.path === activePath }"
          role="button"
          tabindex="0"
          @click="onClick(item)"
          @keydown.enter="onClick(item)"
          @keydown.space.prevent="onClick(item)"
          @contextmenu="onContext($event, item)"
          @mousedown.middle.prevent
          @auxclick.middle.prevent="tabs.removeTab(item.path)"
        >
          <Icon v-if="item.icon" :icon="item.icon" :width="15" class="chip-icon" />
          <span class="chip-label">{{ tabTitle(item) }}</span>
          <!-- 固定标签(用户 pin)显示图钉、不显示关闭 X;应用首页 affix 两者都不显示 -->
          <Icon v-if="item.pinned" icon="lucide:pin" :width="12" class="chip-pin" />
          <Icon
            v-else-if="!item.affix"
            icon="lucide:x"
            :width="13"
            class="chip-close"
            role="button"
            tabindex="0"
            :aria-label="t('tabs.close')"
            @click.stop="tabs.removeTab(item.path)"
            @keydown.enter.stop="tabs.removeTab(item.path)"
            @keydown.space.stop.prevent="tabs.removeTab(item.path)"
          />
        </div>
      </div>
    </n-scrollbar>
    <n-dropdown
      trigger="manual"
      placement="bottom-start"
      :show="ctxShow"
      :x="ctxX"
      :y="ctxY"
      :options="ctxOptions"
      @select="onCtxSelect"
      @clickoutside="ctxShow = false"
    />
  </div>
</template>

<style scoped>
.tabsbar {
  height: 42px;
  display: flex;
  align-items: center;
  padding: 0 8px;
  background: var(--color-bg-container);
  border-bottom: 1px solid var(--color-border);
}
.strip {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 5px 0;
}
.chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 30px;
  padding: 0 10px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-fill);
  color: var(--color-text-secondary);
  font-size: var(--font-size-sm);
  white-space: nowrap;
  cursor: pointer;
  user-select: none;
  transition:
    color 0.15s,
    background 0.15s,
    border-color 0.15s;
}
.chip:hover {
  color: var(--color-text-primary);
}
.chip.active {
  background: var(--color-primary-light);
  border-color: var(--color-primary);
  color: var(--color-primary);
}
.chip:focus-visible,
.chip-close:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 1px;
}
.chip-pin {
  opacity: 0.7;
}
.chip-close {
  border-radius: 50%;
  opacity: 0.6;
}
.chip-close:hover {
  opacity: 1;
  background: var(--color-fill);
}
</style>

// web-react/src/layouts/TabsBar.tsx
import { useEffect, useMemo, useRef } from 'react'
import { Dropdown, type MenuProps } from 'antd'
import { useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import { useTabsStore, type TabItem } from '@/stores/tabs'
import './tabsbar.css'

/**
 * 多标签栏(替代 Vue `TabsBar.vue`)。横滚 chip 条 + 右键菜单(antd Dropdown `trigger=['contextMenu']`)+ 中键关闭。
 * store 返回导航目标,这里(有 useNavigate)负责导航。affix(应用首页)/pinned 不显示关闭 X。
 */
export function TabsBar() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { pathname } = useLocation()
  const tabs = useTabsStore((s) => s.tabs)
  const stripRef = useRef<HTMLDivElement>(null)

  const nav = (next: string | null) => {
    if (next) navigate(next)
  }
  const tabTitle = (tab: TabItem) => (tab.title.includes('.') ? t(tab.title) : tab.title)
  const goTab = (tab: TabItem) => {
    if (tab.path !== pathname) navigate(tab.fullPath)
  }
  const closeTab = (path: string) => nav(useTabsStore.getState().removeTab(path, pathname))

  const ctxItems = (tab: TabItem): MenuProps['items'] => [
    { key: 'refresh', label: t('tabs.refresh'), icon: <AppIcon icon="ph:arrow-clockwise" size={15} /> },
    // 应用首页(affix)恒固定,不提供固定/取消项。
    { key: 'pin', label: tab.pinned ? t('tabs.unpin') : t('tabs.pin'), icon: <AppIcon icon="ph:push-pin" size={15} />, disabled: tab.affix },
    { key: 'close', label: t('tabs.close'), icon: <AppIcon icon="ph:x" size={15} />, disabled: tab.affix || tab.pinned },
    { key: 'others', label: t('tabs.closeOthers'), icon: <AppIcon icon="ph:arrows-in-line-horizontal" size={15} /> },
    { key: 'left', label: t('tabs.closeLeft'), icon: <AppIcon icon="ph:arrow-line-left" size={15} /> },
    { key: 'right', label: t('tabs.closeRight'), icon: <AppIcon icon="ph:arrow-line-right" size={15} /> },
    { key: 'all', label: t('tabs.closeAll'), icon: <AppIcon icon="ph:list-dashes" size={15} /> },
  ]

  const onCtx = (tab: TabItem, key: string) => {
    const s = useTabsStore.getState()
    if (key === 'refresh') s.refreshTab(tab.path)
    else if (key === 'pin') s.togglePin(tab.path)
    else if (key === 'close') nav(s.removeTab(tab.path, pathname))
    else if (key === 'others') nav(s.closeOthers(tab.path, pathname))
    else if (key === 'left') nav(s.closeLeft(tab.path, pathname))
    else if (key === 'right') nav(s.closeRight(tab.path, pathname))
    else if (key === 'all') nav(s.closeAll(pathname))
  }

  // 激活标签滚入视野
  const activeKey = useMemo(() => tabs.find((tt) => tt.path === pathname)?.path, [tabs, pathname])
  useEffect(() => {
    stripRef.current?.querySelector('.tab-chip.active')?.scrollIntoView({ block: 'nearest', inline: 'nearest' })
  }, [activeKey])

  return (
    <div className="tabsbar">
      <div ref={stripRef} className="tab-strip">
        {tabs.map((tab) => (
          <Dropdown key={tab.path} menu={{ items: ctxItems(tab), onClick: ({ key }) => onCtx(tab, key) }} trigger={['contextMenu']}>
            {/* chip 是可点非按钮元素:补 role/tabindex/键盘激活,键盘用户也能切换(右键菜单是鼠标专属)。 */}
            <div
              className={`tab-chip${tab.path === pathname ? ' active' : ''}`}
              role="button"
              tabIndex={0}
              onClick={() => goTab(tab)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  goTab(tab)
                }
              }}
              onMouseDown={(e) => {
                // 压掉中键按下触发的浏览器自动滚动圆标(对齐 Vue @mousedown.middle.prevent);关闭本体在 onAuxClick。
                if (e.button === 1) e.preventDefault()
              }}
              onAuxClick={(e) => {
                if (e.button === 1) {
                  e.preventDefault()
                  closeTab(tab.path)
                }
              }}
            >
              {tab.icon ? <AppIcon icon={tab.icon} size={15} /> : null}
              <span className="tab-label">{tabTitle(tab)}</span>
              {tab.pinned ? (
                <AppIcon icon="ph:push-pin-fill" size={12} />
              ) : !tab.affix ? (
                <span
                  className="tab-close"
                  role="button"
                  tabIndex={0}
                  aria-label={t('tabs.close')}
                  onClick={(e) => {
                    e.stopPropagation()
                    closeTab(tab.path)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.stopPropagation()
                      e.preventDefault()
                      closeTab(tab.path)
                    }
                  }}
                >
                  <AppIcon icon="ph:x" size={13} />
                </span>
              ) : null}
            </div>
          </Dropdown>
        ))}
      </div>
    </div>
  )
}
