// web-react/src/views/workflow/start/index.tsx
// 发起流程页。菜单 component 填 `workflow/start/index`;可选 `?definitionId=` 预选已发布定义。
// 业务表单走 WfFormMount:定义有内置 formSchema 就渲染运行时表单,否则挂消费者 formComponent。
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { App, Button, Card, Form, Input, Select, Space } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { AppIcon } from '@/components/AppIcon'
import { UserSelect } from '@/components/UserSelect'
import { wfInstanceApi } from '@/api/workflow'
import { translateError } from '@/utils/error'
import { projectWfRuntimeModel } from '@/workflow/formSchema'
import { flattenChain } from '@/workflow/model'
import { classifyOutcome, useRequestKey } from '@/workflow/useRequestKey'
import type { WfStartableDefinitionDetail } from '@/types/workflow'
import { WfFormMount, type WfFormMountHandle } from '../components/WfFormMount'
import { serializeVars, type WfVarRow } from './startForm'

interface StartFormValues {
  definitionId?: number
  businessKey?: string
  varRows?: WfVarRow[]
  selectedUserIdsByNode?: Record<string, number[] | undefined>
}

export default function WfStartPage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()

  // useRequestKey 是工厂(键存在闭包里)不是 hook:useRef 固定住首个实例,否则每次渲染都换一把新键。
  const requestKey = useRef(useRequestKey()).current

  const [form] = Form.useForm<StartFormValues>()
  const [defOptions, setDefOptions] = useState<{ label: string; value: number }[]>([])
  const [defsLoading, setDefsLoading] = useState(false)
  const [snapshot, setSnapshot] = useState<WfStartableDefinitionDetail | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [runtimeVariablesJson, setRuntimeVariablesJson] = useState<string | null>(null)
  const formRuntimeRef = useRef<WfFormMountHandle | null>(null)

  const loadDefinition = useCallback(
    async (id: number | undefined) => {
      setSnapshot(null)
      setRuntimeVariablesJson(null)
      form.setFieldsValue({ varRows: [{}], selectedUserIdsByNode: {} })
      if (!id) return
      try {
        setSnapshot(await wfInstanceApi.startableDetail(id))
      } catch (e) {
        message.error(translateError(e))
      }
    },
    [form, message],
  )

  useEffect(() => {
    setDefsLoading(true)
    wfInstanceApi
      .startable()
      .then((defs) => {
        setDefOptions(
          defs.map((d) => ({ label: d.name ?? '', value: Number(d.id) })).filter((o) => o.value > 0),
        )
        // ?definitionId= 预选:定义列表到位后再落值,免得 Select 显示一个还没有选项的 id。
        const preset = Number(searchParams.get('definitionId'))
        if (Number.isFinite(preset) && preset > 0) {
          form.setFieldValue('definitionId', preset)
          void loadDefinition(preset)
        }
      })
      .catch((e: unknown) => message.error(translateError(e)))
      .finally(() => setDefsLoading(false))
  }, [form, loadDefinition, message, searchParams])

  const runtimeModel = useMemo(() => projectWfRuntimeModel(snapshot?.model), [snapshot])
  const formComponent = snapshot?.model?.formComponent ?? snapshot?.formComponent ?? null
  const formSchema = runtimeModel?.formSchema ?? null
  const hasBuiltinForm = !!formSchema?.fields.length
  const hasFormMount = !!formComponent?.trim()

  // 无内置表单时,摘要变量也要喂给消费者挂载点(与 Vue 一致:它把键值行序列化后一起传下去)。
  const varRows = Form.useWatch('varRows', form)
  const kvVariablesJson = useMemo(() => serializeVars(varRows ?? []), [varRows])
  // getFieldValue 在渲染期读不到后续变化,业务键要跟着输入走就得 useWatch 订阅。
  const businessKey = Form.useWatch('businessKey', form)

  /** 发起人自选审批人的节点:每个节点一个多选人员框,提交时按 nodeId 归拢。 */
  const selfSelectNodes = useMemo(
    () => (runtimeModel?.root ? flattenChain(runtimeModel.root).filter((n) => n.props?.assignee?.provider === 'selfSelect') : []),
    [runtimeModel],
  )

  const submit = async () => {
    const v = await form.validateFields().catch(() => null)
    if (!v?.definitionId) return
    if (hasBuiltinForm && formRuntimeRef.current?.validate() === false) return

    setSubmitting(true)
    try {
      const picked = selfSelectNodes
        .map((node) => [node.id, v.selectedUserIdsByNode?.[node.id] ?? []] as const)
        .filter(([, ids]) => ids.length > 0)
      const result = await wfInstanceApi.start({
        definitionId: v.definitionId,
        businessKey: v.businessKey?.trim() || null,
        variablesJson: hasBuiltinForm ? runtimeVariablesJson : serializeVars(v.varRows ?? []),
        selectedUserIdsByNode: Object.fromEntries(picked),
        requestId: requestKey.value(),
      })
      requestKey.settle('success')
      message.success(t('workflow.start.started'))
      navigate(`/workflow/instance/${result.instanceId}/detail`)
    } catch (e) {
      requestKey.settle(classifyOutcome(e))
      message.error(translateError(e))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Card title={t('workflow.start.title')} size="small">
      <Form form={form} labelCol={{ span: 5 }} wrapperCol={{ span: 19 }} style={{ maxWidth: 720 }} initialValues={{ varRows: [{}] }}>
        <Form.Item
          name="definitionId" label={t('workflow.start.definition')}
          rules={[{ required: true, message: t('workflow.start.definitionRequired') }]}
        >
          <Select
            options={defOptions}
            loading={defsLoading}
            allowClear
            showSearch={{ optionFilterProp: 'label' }}
            placeholder={t('workflow.start.definitionPlaceholder')}
            onChange={(id: number | undefined) => void loadDefinition(id)}
          />
        </Form.Item>

        <Form.Item name="businessKey" label={t('workflow.start.businessKey')}>
          <Input placeholder={t('workflow.start.businessKeyHint')} />
        </Form.Item>

        {hasBuiltinForm ? null : (
          <Form.Item label={t('workflow.start.variables')} extra={t('workflow.start.variablesHint')}>
            <Form.List name="varRows">
              {(fields, { add, remove }) => (
                <Space orientation="vertical" size={8} style={{ width: '100%' }}>
                  {fields.map((field) => (
                    <Space key={field.key} size={8} style={{ width: '100%' }}>
                      <Form.Item name={[field.name, 'key']} noStyle>
                        <Input placeholder={t('workflow.start.varKey')} style={{ width: 180 }} />
                      </Form.Item>
                      <Form.Item name={[field.name, 'value']} noStyle>
                        <Input placeholder={t('workflow.start.varValue')} style={{ width: 240 }} />
                      </Form.Item>
                      <Button
                        type="text" size="small" aria-label={t('common.delete')}
                        icon={<AppIcon icon="ph:x" size={14} />}
                        // 删到空就补一行空行:一行都不留时用户没有可点的输入格。
                        onClick={() => { remove(field.name); if (fields.length === 1) add({}) }}
                      />
                    </Space>
                  ))}
                  <Button type="dashed" size="small" icon={<AppIcon icon="ph:plus" size={14} />} onClick={() => add({})}>
                    {t('workflow.start.addVariable')}
                  </Button>
                </Space>
              )}
            </Form.List>
          </Form.Item>
        )}

        {selfSelectNodes.map((node) => (
          <Form.Item
            key={node.id}
            name={['selectedUserIdsByNode', node.id]}
            label={node.name || t('workflow.start.selfSelect')}
          >
            <UserSelect mode="multiple" placeholder={t('workflow.start.selfSelectHint')} />
          </Form.Item>
        ))}

      </Form>

      {hasFormMount || hasBuiltinForm ? (
        <div style={{ marginBlock: 12 }}>
          <WfFormMount
            ref={formRuntimeRef}
            formComponent={formComponent}
            formSchema={formSchema}
            mode="start"
            definitionId={snapshot?.id == null ? undefined : Number(snapshot.id)}
            businessKey={businessKey || null}
            variablesJson={hasBuiltinForm ? runtimeVariablesJson : kvVariablesJson}
            onVariablesChange={setRuntimeVariablesJson}
          />
        </div>
      ) : null}

      <Space style={{ marginTop: 16 }}>
        <Button type="primary" loading={submitting} onClick={() => void submit()}>
          {t('workflow.start.submit')}
        </Button>
      </Space>
    </Card>
  )
}

// web/src/views/workflow/start/index.vue
<script setup lang="ts">
/**
 * 发起流程页。菜单 component 填 `workflow/start/index`;
 * 可选 `?definitionId=` 预选已发布定义。含 formComponent 挂载点 + 摘要变量(键值行)。
 */
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  NButton,
  NCard,
  NForm,
  NFormItem,
  NInput,
  NSelect,
  NSpace,
  useMessage,
  type FormInst,
  type FormRules,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import UserSelect from '@/components/UserSelect/index.vue'
import { wfInstanceApi } from '@/api/workflow'
import { translateError } from '@/utils/error'
import type { WfStartableDefinitionDetail } from '@/types/workflow'
import { flattenChain } from '@/workflow/model'
import { projectWfRuntimeModel } from '@/workflow/formSchema'
import type { WfFormSchema } from '@/workflow/schema'
import { classifyOutcome, useRequestKey } from '@/workflow/useRequestKey'
import WfFormMount from '../components/WfFormMount.vue'

interface VarRow {
  key: string
  value: string
}

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const message = useMessage()

const formRef = ref<FormInst | null>(null)
const submitting = ref(false)
const defsLoading = ref(false)
const defOptions = ref<{ label: string; value: number }[]>([])
const formComponent = ref<string | null>(null)
const formSchema = ref<WfFormSchema | null>(null)
const runtimeVariablesJson = ref<string | null>(null)
const formRuntimeRef = ref<{ validate: () => boolean } | null>(null)
const snapshot = ref<WfStartableDefinitionDetail | null>(null)
const requestKey = useRequestKey()

const form = reactive({
  definitionId: null as number | null,
  businessKey: '',
  varRows: [{ key: '', value: '' }] as VarRow[],
  selectedUserIdsByNode: {} as Record<string, number[]>,
})

const rules: FormRules = {
  definitionId: {
    required: true,
    type: 'number',
    message: () => t('workflow.start.definitionRequired'),
    trigger: ['change', 'blur'],
  },
}

const hasFormMount = computed(() => !!formComponent.value?.trim())
const hasBuiltinForm = computed(() => !!formSchema.value?.fields.length)
const selfSelectNodes = computed(() => {
  const model = projectWfRuntimeModel(snapshot.value?.model)
  if (!model?.root) return []
  return flattenChain(model.root).filter((n) => n.props?.assignee?.provider === 'selfSelect')
})

const variablesJson = computed(() => serializeVars(form.varRows))

function coerceValue(raw: string): unknown {
  const s = raw.trim()
  if (s === '') return ''
  if (s === 'true') return true
  if (s === 'false') return false
  if (/^-?\d+(\.\d+)?$/.test(s)) return Number(s)
  return raw
}

function serializeVars(rows: VarRow[]): string | null {
  const obj: Record<string, unknown> = Object.create(null) as Record<string, unknown>
  for (const row of rows) {
    const k = row.key.trim()
    if (!k || k === '__proto__') continue
    obj[k] = coerceValue(row.value)
  }
  return Object.keys(obj).length ? JSON.stringify(obj) : null
}

async function loadPublishedDefs() {
  defsLoading.value = true
  try {
    defOptions.value = (await wfInstanceApi.startable())
      .map((d) => ({ label: d.name ?? '', value: Number(d.id) }))
      .filter((d) => d.value > 0)
  } catch (e) {
    message.error(translateError(e))
  } finally {
    defsLoading.value = false
  }
}

async function onDefinitionChange(id: number | null) {
  formComponent.value = null
  formSchema.value = null
  runtimeVariablesJson.value = null
  snapshot.value = null
  form.selectedUserIdsByNode = {}
  form.varRows = [{ key: '', value: '' }]
  if (!id) return
  try {
    const detail = await wfInstanceApi.startableDetail(id)
    snapshot.value = detail
    formComponent.value = detail.model?.formComponent ?? detail.formComponent ?? null
    formSchema.value = projectWfRuntimeModel(detail.model)?.formSchema ?? null
  } catch (e) {
    message.error(translateError(e))
  }
}

watch(
  () => form.definitionId,
  (id) => {
    void onDefinitionChange(id)
  },
)

onMounted(async () => {
  await loadPublishedDefs()
  const q = Number(route.query.definitionId)
  if (Number.isFinite(q) && q > 0) {
    form.definitionId = q
  }
})

async function submit() {
  try {
    await formRef.value?.validate()
  } catch {
    return
  }
  if (!form.definitionId) return
  if (hasBuiltinForm.value && !formRuntimeRef.value?.validate()) return

  submitting.value = true
  try {
    const body = {
      definitionId: form.definitionId!,
      businessKey: form.businessKey.trim() || null,
      variablesJson: hasBuiltinForm.value ? runtimeVariablesJson.value : variablesJson.value,
      selectedUserIdsByNode: Object.fromEntries(
        selfSelectNodes.value
          .map((node) => [node.id, form.selectedUserIdsByNode[node.id] ?? []] as const)
          .filter(([, ids]) => ids.length > 0),
      ),
      requestId: requestKey.value(),
    }
    const result = await wfInstanceApi.start(body)
    requestKey.settle('success')
    message.success(t('workflow.start.started'))
    await router.push(`/workflow/instance/${result.instanceId}/detail`)
  } catch (e) {
    requestKey.settle(classifyOutcome(e))
    message.error(translateError(e))
  } finally {
    submitting.value = false
  }
}

function addVarRow() {
  form.varRows.push({ key: '', value: '' })
}

function removeVarRow(i: number) {
  form.varRows.splice(i, 1)
  if (!form.varRows.length) form.varRows.push({ key: '', value: '' })
}
</script>

<template>
  <n-card :title="t('workflow.start.title')" :bordered="false" size="small">
    <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" label-width="120" style="max-width: 640px">
      <n-form-item :label="t('workflow.start.definition')" path="definitionId">
        <n-select
          v-model:value="form.definitionId"
          :options="defOptions"
          :loading="defsLoading"
          filterable
          :placeholder="t('workflow.start.definitionPlaceholder')"
        />
      </n-form-item>
      <n-form-item :label="t('workflow.start.businessKey')">
        <n-input v-model:value="form.businessKey" :placeholder="t('workflow.start.businessKeyHint')" />
      </n-form-item>
      <n-form-item v-if="!hasBuiltinForm" :label="t('workflow.start.variables')">
        <div class="wf-kv">
          <div v-for="(row, i) in form.varRows" :key="i" class="wf-kv-row">
            <n-input v-model:value="row.key" :placeholder="t('workflow.start.varKey')" />
            <n-input v-model:value="row.value" :placeholder="t('workflow.start.varValue')" />
            <n-button quaternary circle size="small" :aria-label="t('common.delete')" @click="removeVarRow(i)">
              <template #icon><AppIcon icon="ph:x" :size="14" /></template>
            </n-button>
          </div>
          <n-button dashed size="small" @click="addVarRow">
            <template #icon><AppIcon icon="ph:plus" :size="14" /></template>
            {{ t('workflow.start.addVariable') }}
          </n-button>
          <p class="wf-kv-hint">{{ t('workflow.start.variablesHint') }}</p>
        </div>
      </n-form-item>
      <n-form-item
        v-for="node in selfSelectNodes"
        :key="node.id"
        :label="node.name || t('workflow.start.selfSelect')"
      >
        <UserSelect
          v-model:value="form.selectedUserIdsByNode[node.id]"
          multiple
          :placeholder="t('workflow.start.selfSelectHint')"
        />
      </n-form-item>
    </n-form>

    <WfFormMount
      v-if="hasFormMount || hasBuiltinForm"
      ref="formRuntimeRef"
      :form-component="formComponent"
      :form-schema="formSchema"
      mode="start"
      :definition-id="form.definitionId ?? undefined"
      :business-key="form.businessKey || null"
      :variables-json="hasBuiltinForm ? runtimeVariablesJson : variablesJson"
      @variables-change="runtimeVariablesJson = $event"
    />

    <n-space style="margin-top: 16px">
      <n-button type="primary" :loading="submitting" @click="submit">
        {{ t('workflow.start.submit') }}
      </n-button>
    </n-space>
  </n-card>
</template>

<style scoped>
.wf-kv {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}
.wf-kv-row {
  display: flex;
  gap: 8px;
  align-items: center;
}
.wf-kv-hint {
  margin: 0;
  font-size: var(--font-size-xs);
  color: var(--color-text-tertiary);
  line-height: var(--line-height-xs);
}
</style>
