// web/src/views/workflow/done/index.vue
<script setup lang="ts">
/**
 * 我已办的。菜单 component 填 `workflow/done/index`。
 * 行点击或「查看」进实例详情(`/workflow/instance/:id/detail`)。
 */
import { h, ref } from 'vue'
import { useRouter } from 'vue-router'
import { NButton, NEmpty, NSpace, NTag, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import { wfTaskApi } from '@/api/workflow'
import { translateError } from '@/utils/error'
import type { WfDoneItem, WfInstanceStatus, WfTaskAction } from '@/types/workflow'

const { t } = useI18n()
const router = useRouter()
const message = useMessage()
const tableRef = ref<ProTableInst<WfDoneItem>>()

function openDetail(r: WfDoneItem) {
  if (r.instanceId == null) return
  void router.push(`/workflow/instance/${r.instanceId}/detail`)
}

/** 与 detail.vue 同一套实例状态 / 动作数字表,不另起体系。 */
function normalizeStatus(s: WfInstanceStatus | undefined): string {
  if (s == null) return 'unknown'
  const map: Record<number, string> = {
    1: 'running',
    2: 'approved',
    3: 'rejected',
    4: 'cancelled',
    5: 'terminated',
  }
  return map[s] ?? 'unknown'
}

function statusLabel(s: WfInstanceStatus | undefined): string {
  return t(`workflow.status.${normalizeStatus(s)}`, String(s ?? ''))
}

function statusType(s: WfInstanceStatus | undefined): 'default' | 'info' | 'success' | 'error' | 'warning' {
  const key = normalizeStatus(s)
  if (key === 'approved') return 'success'
  if (key === 'rejected' || key === 'terminated') return 'error'
  if (key === 'cancelled') return 'warning'
  if (key === 'running') return 'info'
  return 'default'
}

function actionLabel(a: WfTaskAction | undefined): string {
  if (a == null) return t('workflow.action.unknown')
  const map: Record<number, string> = {
    1: 'approve',
    2: 'reject',
    3: 'transfer',
    4: 'return',
    5: 'withdraw',
    6: 'delegate',
  }
  const key = map[a] ?? 'unknown'
  return t(`workflow.action.${key}`, String(a))
}

function actionTagType(a: WfTaskAction | undefined): 'default' | 'success' | 'error' | 'warning' | 'info' {
  if (a === 1) return 'success'
  if (a === 2) return 'error'
  if (a === 3) return 'warning'
  return 'info'
}

const columns: ProTableColumn<WfDoneItem>[] = [
  { key: 'definitionName', title: () => t('workflow.done.definition'), minWidth: 160, ellipsis: { tooltip: true } },
  {
    key: 'nodeName',
    title: () => t('workflow.done.node'),
    width: 140,
    ellipsis: { tooltip: true },
    render: (r) => r.nodeName || r.nodeId,
  },
  {
    key: 'action',
    title: () => t('workflow.done.action'),
    width: 88,
    render: (r) =>
      h(NTag, { size: 'small', type: actionTagType(r.action), bordered: false }, () => actionLabel(r.action)),
  },
  {
    key: 'businessKey',
    title: () => t('workflow.done.businessKey'),
    width: 140,
    ellipsis: { tooltip: true },
    render: (r) => r.businessKey || '—',
  },
  {
    key: 'instanceStatus',
    title: () => t('common.status'),
    width: 96,
    render: (r) =>
      h(
        NTag,
        { size: 'small', type: statusType(r.instanceStatus), bordered: false },
        () => statusLabel(r.instanceStatus),
      ),
  },
  { key: 'createTime', title: () => t('workflow.done.createTime'), width: 170, format: 'datetime' },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 100,
    hideInSetting: true,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        h(
          NButton,
          {
            size: 'small',
            quaternary: true,
            type: 'primary',
            onClick: (e: MouseEvent) => {
              e.stopPropagation()
              openDetail(r)
            },
          },
          () => t('workflow.done.view'),
        ),
      ]),
  },
]
</script>

<template>
  <ProTable
    ref="tableRef"
    storage-key="workflow-done"
    row-key="hisTaskId"
    :columns="columns"
    :fetcher="wfTaskApi.done"
    @row-click="(row: WfDoneItem) => openDetail(row)"
    @error="(e) => message.error(translateError(e))"
  >
    <template #empty>
      <n-empty :description="t('workflow.done.empty')" size="small" />
    </template>
  </ProTable>
</template>

// web-react/src/views/workflow/done/index.tsx
// 我已办的。菜单 component 填 `workflow/done/index`。
// 行点击或「查看」进实例详情;动作/实例状态标签走 `workflow/statusLabels`(与详情页同一套数字表)。
import { useCallback, useMemo } from 'react'
import { Button, Space, Tag } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type PageFetcher } from '@/components/DataTable'
import { wfTaskApi } from '@/api/workflow'
import {
  formatDateTime,
  instanceStatusColor,
  normalizeInstanceStatus,
  normalizeTaskAction,
  taskActionColor,
} from '@/workflow/statusLabels'
import type { WfDoneItem } from '@/types/workflow'

export default function WfDonePage() {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const fetchDone: PageFetcher<WfDoneItem> = (q) => wfTaskApi.done({ page: q.page, pageSize: q.pageSize })

  const openDetail = useCallback(
    (r: WfDoneItem) => {
      if (r.instanceId == null) return
      navigate(`/workflow/instance/${r.instanceId}/detail`)
    },
    [navigate],
  )

  const columns = useMemo<ProColumns<WfDoneItem>[]>(
    () => [
      { title: t('workflow.done.definition'), dataIndex: 'definitionName', minWidth: 160, ellipsis: true, search: false },
      {
        title: t('workflow.done.node'), dataIndex: 'nodeName', width: 140, ellipsis: true, search: false,
        render: (_, r) => r.nodeName || r.nodeId,
      },
      {
        title: t('workflow.done.action'), dataIndex: 'action', width: 96, search: false,
        render: (_, r) => (
          <Tag color={taskActionColor(r.action)}>{t(`workflow.action.${normalizeTaskAction(r.action)}`)}</Tag>
        ),
      },
      {
        title: t('workflow.done.businessKey'), dataIndex: 'businessKey', width: 140, ellipsis: true, search: false,
        render: (_, r) => r.businessKey || '—',
      },
      {
        title: t('common.status'), dataIndex: 'instanceStatus', width: 96, search: false,
        render: (_, r) => (
          <Tag color={instanceStatusColor(r.instanceStatus)}>{t(`workflow.status.${normalizeInstanceStatus(r.instanceStatus)}`)}</Tag>
        ),
      },
      {
        title: t('workflow.done.createTime'), dataIndex: 'createTime', width: 170, search: false,
        render: (_, r) => formatDateTime(r.createTime),
      },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 100, fixed: 'right',
        render: (_, r) => (
          <Space size={0}>
            {/* 行本身可点进详情,按钮须 stopPropagation 否则冒泡再触发一次 */}
            <Button type="link" size="small" onClick={(e) => { e.stopPropagation(); openDetail(r) }}>
              {t('workflow.done.view')}
            </Button>
          </Space>
        ),
      },
    ],
    [t, openDetail],
  )

  return (
    <DataTable<WfDoneItem>
      columns={columns}
      fetcher={fetchDone}
      persistKey="workflow-done"
      rowKey="hisTaskId"
      search={false}
      onRowClick={openDetail}
    />
  )
}
