// web-react/src/views/system/job/index.tsx
// 定时任务管理(G8,scheduling-ledger §11):DataTable CRUD + 四分节表单(基本/触发/载荷/失败处理)。
// 行含全列 → 编辑直接用行数据回填,不另拉详情;状态列 StatusSwitch 绑 {id}/enabled 端点,
// Panic 显红 tag(悬浮出连败次数);isSystem 行禁删(后端 47014 兜底)。纯逻辑在 jobForm.ts(变异钉)。
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { App, Button, DatePicker, Divider, Form, Input, InputNumber, Radio, Select, Space, Switch, Tag, Tooltip } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import { Can } from '@/components/Can'
import { CronEditor } from '@/components/CronEditor'
import { FormContainer } from '@/components/FormContainer'
import { StatusSwitch } from '@/components/StatusSwitch'
import { useConfirm } from '@/hooks/useConfirm'
import { useBatchDelete } from '@/hooks/useBatchDelete'
import { useHasPerm } from '@/stores/auth'
import { useTabsStore } from '@/stores/tabs'
import { jobApi } from '@/api'
import { translateError } from '@/utils/error'
import type { SysJob } from '@/types/api'
import { blankJob, describeTrigger, formToInput, rowToForm, type JobFormValues } from './jobForm'

/** ISO 时刻截到秒、去 T;空显 —。 */
const fmtTime = (s?: string | null): string => (s ? s.replace('T', ' ').slice(0, 19) : '—')

const HANDLER_TAG: Record<number, { color: string; key: string }> = {
  1: { color: 'processing', key: 'job.handler.compiled' },
  2: { color: 'success', key: 'job.handler.http' },
  3: { color: 'warning', key: 'job.handler.sql' },
}

export default function JobPage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const { confirm } = useConfirm()
  const has = useHasPerm()
  const navigate = useNavigate()

  const tableRef = useRef<DataTableHandle>(null)
  const reload = useCallback(() => tableRef.current?.reload(), [])

  // 分页取数:搜索表单值(unknown)→ 强类型入参。有意不 memo(ProTable 经 ref 读 request)。
  const fetchJobs: PageFetcher<SysJob> = (q) =>
    jobApi.page({
      page: q.page,
      pageSize: q.pageSize,
      name: typeof q.name === 'string' ? q.name : undefined,
      status: typeof q.status === 'number' ? q.status : undefined,
      handlerKind: typeof q.handlerKind === 'number' ? q.handlerKind : undefined,
      sortField: q.sortField,
      sortOrder: q.sortOrder,
    })

  // 批量删除:内置任务行禁勾(后端命中内置整批拒绝,前端先挡在勾选层)。
  const batch = useBatchDelete({ remove: jobApi.batchRemove, refresh: reload, successMsg: t('job.deleted') })

  // ── 新增/编辑弹窗(FormContainer owns loading+close)──
  const [form] = Form.useForm<JobFormValues>()
  const [open, setOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const triggerKind = Form.useWatch('triggerKind', form)
  const handlerKind = Form.useWatch('handlerKind', form)

  // 编译处理器下拉:首次开弹时拉一次(GET /handlers);失败不阻塞表单(HTTP/SQL 用不到)。
  const [handlerOptions, setHandlerOptions] = useState<string[] | null>(null)
  // SQL 载荷总闸(后端 Jobs:Sql:Enabled)。默认按"开"起手:清单没拉到就不该凭空禁掉一种载荷,
  // 真关着的话保存时后端还有 47008 兜底。
  const [sqlEnabled, setSqlEnabled] = useState(true)
  useEffect(() => {
    if (!open || handlerOptions !== null) return
    jobApi
      .handlers()
      .then((out) => {
        setHandlerOptions(out.handlers)
        setSqlEnabled(out.sqlEnabled)
      })
      .catch(() => setHandlerOptions([]))
  }, [open, handlerOptions])

  const openAdd = () => {
    setEditingId(null)
    form.resetFields()
    form.setFieldsValue(blankJob())
    setOpen(true)
  }
  const openEdit = useCallback(
    (r: SysJob) => {
      setEditingId(r.id)
      form.resetFields()
      form.setFieldsValue(rowToForm(r))
      setOpen(true)
    },
    [form],
  )

  const save = async () => {
    // 条件分节的字段卸载后不进 validateFields 结果,先用 blankJob 补齐缺省再组装
    const v: JobFormValues = { ...blankJob(), ...(await form.validateFields()) }
    try {
      if (editingId === null) await jobApi.add(formToInput(v))
      else await jobApi.update(editingId, formToInput(v))
      message.success(t('job.saved')) // 文案已含「集群下最长 30 秒后生效」
      reload()
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  const handleDelete = useCallback(
    (r: SysJob) => {
      confirm({ content: t('job.deleteConfirm', { name: r.name }), action: () => jobApi.remove(r.id), successMsg: t('job.deleted') }).then(
        (ok) => { if (ok) reload() },
      )
    },
    [confirm, t, reload],
  )

  // 执行一次(二次确认;本机执行,不影响调度节奏)。
  const handleRun = useCallback(
    (r: SysJob) => {
      void confirm({ content: t('job.runConfirm', { name: r.name }), action: () => jobApi.runOnce(r.id), successMsg: t('job.runStarted') })
    },
    [confirm, t],
  )

  // 记录:携 jobId 跳执行记录页。已开的记录页签是 KeepAlive 缓存的,先 refreshTab 换 key 重挂,
  // 新 jobId 才会进它的初始筛选(未开时 refreshTab 无害)。
  const gotoLogs = useCallback(
    (r: SysJob) => {
      useTabsStore.getState().refreshTab('/system/job-log')
      navigate(`/system/job-log?jobId=${r.id}`)
    },
    [navigate],
  )

  const columns = useMemo<ProColumns<SysJob>[]>(
    () => [
      {
        title: t('job.name'), dataIndex: 'name', // 唯一模糊搜索项
        render: (_, r) => (
          <div>
            <div>{r.name}</div>
            <div style={{ fontSize: 12, color: 'var(--color-text-secondary, #999)' }}>{r.code}</div>
          </div>
        ),
      },
      {
        title: t('job.handlerKind'), dataIndex: 'handlerKind', width: 100, valueType: 'select',
        fieldProps: {
          allowClear: true,
          options: [
            { label: t('job.handler.compiled'), value: 1 },
            { label: t('job.handler.http'), value: 2 },
            { label: t('job.handler.sql'), value: 3 },
          ],
        },
        render: (_, r) => {
          const tag = HANDLER_TAG[r.handlerKind]
          return tag ? <Tag color={tag.color}>{t(tag.key)}</Tag> : '—'
        },
      },
      {
        title: t('job.trigger.title'), dataIndex: 'triggerKind', search: false, ellipsis: true,
        render: (_, r) => <span style={{ fontFamily: 'var(--font-mono, ui-monospace, monospace)', fontSize: 12 }}>{describeTrigger(r, t)}</span>,
      },
      {
        title: t('common.status'), dataIndex: 'status', width: 110, valueType: 'select',
        fieldProps: {
          allowClear: true,
          options: [
            { label: t('job.status.ready'), value: 1 },
            { label: t('job.status.paused'), value: 2 },
            { label: t('job.status.completed'), value: 3 },
            { label: t('job.status.panic'), value: 4 },
          ],
        },
        render: (_, r) => {
          if (r.status === 4) {
            return (
              <Tooltip title={t('job.panicTip', { count: r.consecutiveErrors })}>
                <Tag color="error">{t('job.status.panic')}</Tag>
              </Tooltip>
            )
          }
          if (r.status === 3) return <Tag>{t('job.status.completed')}</Tag>
          return (
            <StatusSwitch
              value={r.status === 1}
              disabled={!has('PUT:/api/v1/sys/job/{id}/enabled')}
              request={(next) => jobApi.setEnabled(r.id, next)}
              onChange={reload}
            />
          )
        },
      },
      { title: t('job.nextRunTime'), dataIndex: 'nextRunTime', search: false, width: 160, render: (_, r) => fmtTime(r.nextRunTime) },
      { title: t('job.lastRunTime'), dataIndex: 'lastRunTime', search: false, width: 160, render: (_, r) => fmtTime(r.lastRunTime) },
      {
        title: t('job.counts'), key: 'counts', search: false, width: 90,
        render: (_, r) => (
          <span>
            {r.numberOfRuns} / <span style={{ color: r.numberOfErrors > 0 ? 'var(--color-danger, #d03050)' : undefined }}>{r.numberOfErrors}</span>
          </span>
        ),
      },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 230, fixed: 'right',
        render: (_, r) => (
          <Space size={0}>
            {has('PUT:/api/v1/sys/job/{id}') && <Button type="link" size="small" onClick={() => openEdit(r)}>{t('common.edit')}</Button>}
            {has('POST:/api/v1/sys/job/{id}/run') && <Button type="link" size="small" onClick={() => handleRun(r)}>{t('job.run')}</Button>}
            <Button type="link" size="small" onClick={() => gotoLogs(r)}>{t('job.viewLogs')}</Button>
            {has('DELETE:/api/v1/sys/job/{id}') &&
              (r.isSystem ? (
                <Tooltip title={t('job.systemProtected')}>
                  <Button type="link" size="small" danger disabled>{t('common.delete')}</Button>
                </Tooltip>
              ) : (
                <Button type="link" size="small" danger onClick={() => handleDelete(r)}>{t('common.delete')}</Button>
              ))}
          </Space>
        ),
      },
    ],
    [t, has, reload, openEdit, handleRun, gotoLogs, handleDelete],
  )

  const formLayout = { labelCol: { span: 6 }, wrapperCol: { span: 17 } }

  return (
    <>
      <DataTable<SysJob>
        ref={tableRef}
        columns={columns}
        fetcher={fetchJobs}
        persistKey="sys-job"
        rowSelection={{
          selectedRowKeys: batch.selectedKeys,
          onChange: batch.setSelectedKeys,
          getCheckboxProps: (r) => ({ disabled: r.isSystem }), // 内置任务受保护,不进批删
        }}
        toolbar={
          <Space>
            <Can code="POST:/api/v1/sys/job/batch-delete">
              <Button danger disabled={!batch.hasSelection} onClick={batch.run}>{t('common.batchDelete')}</Button>
            </Can>
            <Can code="POST:/api/v1/sys/job">
              <Button type="primary" onClick={openAdd}>{t('common.add')}</Button>
            </Can>
          </Space>
        }
      />

      <FormContainer
        open={open}
        onOpenChange={setOpen}
        title={editingId === null ? t('job.addTitle') : t('job.editTitle')}
        width={720}
        confirmText={t('common.save')}
        onConfirm={save}
      >
        <Form form={form} {...formLayout} style={{ marginTop: 4 }}>
          {/* ── 基本 ── */}
          <Divider titlePlacement="start" size="small">{t('job.section.basic')}</Divider>
          <Form.Item
            name="code" label={t('job.code')}
            rules={editingId === null ? [{ required: true, whitespace: true, message: t('job.form.codeRequired') }] : undefined}
          >
            {/* 任务编码建后不可变(后端更新时忽略);编辑时置灰 */}
            <Input disabled={editingId !== null} placeholder={t('job.form.codePlaceholder')} />
          </Form.Item>
          <Form.Item name="name" label={t('job.name')} rules={[{ required: true, whitespace: true, message: t('job.form.nameRequired') }]}>
            <Input placeholder={t('job.name')} />
          </Form.Item>
          <Form.Item name="remark" label={t('job.remark')}>
            <Input.TextArea rows={2} />
          </Form.Item>

          {/* ── 触发 ── */}
          <Divider titlePlacement="start" size="small">{t('job.section.trigger')}</Divider>
          <Form.Item name="triggerKind" label={t('job.form.triggerKind')}>
            <Radio.Group
              options={[
                { label: t('job.trigger.cron'), value: 1 },
                { label: t('job.trigger.interval'), value: 2 },
                { label: t('job.trigger.oneShot'), value: 3 },
              ]}
            />
          </Form.Item>
          {triggerKind === 1 && (
            <Form.Item name="cronExpression" label={t('job.form.cron')} rules={[{ required: true, whitespace: true, message: t('job.form.cronRequired') }]}>
              <CronEditor />
            </Form.Item>
          )}
          {triggerKind === 2 && (
            <Form.Item name="intervalSeconds" label={t('job.form.interval')} rules={[{ required: true, message: t('job.form.intervalRequired') }]}>
              <InputNumber min={5} precision={0} suffix={t('job.form.seconds')} style={{ width: 180 }} />
            </Form.Item>
          )}
          {triggerKind === 3 && (
            <Form.Item name="oneShotTime" label={t('job.form.oneShotTime')} rules={[{ required: true, message: t('job.form.oneShotRequired') }]}>
              <DatePicker showTime style={{ width: 220 }} />
            </Form.Item>
          )}
          <Form.Item label={t('job.form.window')}>
            <Space size={8}>
              <Form.Item name="startTime" noStyle>
                <DatePicker showTime placeholder={t('job.form.windowStart')} style={{ width: 200 }} />
              </Form.Item>
              <span>~</span>
              <Form.Item name="endTime" noStyle>
                <DatePicker showTime placeholder={t('job.form.windowEnd')} style={{ width: 200 }} />
              </Form.Item>
            </Space>
          </Form.Item>
          <Form.Item name="misfireStrategy" label={t('job.form.misfireStrategy')}>
            <Radio.Group
              options={[
                { label: t('job.form.misfireSkip'), value: 1 },
                { label: t('job.form.misfireFireOnceNow'), value: 2 },
              ]}
            />
          </Form.Item>
          <Form.Item name="concurrencyMode" label={t('job.form.concurrencyMode')}>
            <Radio.Group
              options={[
                { label: t('job.form.concurrencySerial'), value: 1 },
                { label: t('job.form.concurrencyParallel'), value: 2 },
              ]}
            />
          </Form.Item>

          {/* ── 载荷 ── */}
          <Divider titlePlacement="start" size="small">{t('job.section.handler')}</Divider>
          <Form.Item
            name="handlerKind"
            label={t('job.handlerKind')}
            // 总闸关着就说清是"后端没开",否则用户只会看见一个莫名其妙点不动的选项
            extra={sqlEnabled ? undefined : t('job.form.sqlDisabledHint')}
          >
            <Radio.Group
              options={[
                { label: t('job.handler.compiled'), value: 1 },
                { label: t('job.handler.http'), value: 2 },
                { label: t('job.handler.sql'), value: 3, disabled: !sqlEnabled },
              ]}
            />
          </Form.Item>
          {handlerKind === 1 && (
            <>
              <Form.Item name="handlerName" label={t('job.form.handlerName')} rules={[{ required: true, message: t('job.form.handlerRequired') }]}>
                <Select
                  showSearch={{ optionFilterProp: 'label' }}
                  placeholder={t('job.form.handlerPlaceholder')}
                  loading={open && handlerOptions === null}
                  options={(handlerOptions ?? []).map((h) => ({ label: h, value: h }))}
                />
              </Form.Item>
              <Form.Item label={t('job.form.props')}>
                <Form.List name="props">
                  {(fields, { add, remove }) => (
                    <>
                      {fields.map((field) => (
                        <Space key={field.key} align="baseline" style={{ display: 'flex', marginBottom: 8 }}>
                          <Form.Item name={[field.name, 'key']} noStyle>
                            <Input placeholder={t('job.form.propKey')} style={{ width: 160 }} />
                          </Form.Item>
                          <Form.Item name={[field.name, 'value']} noStyle>
                            <Input placeholder={t('job.form.propValue')} style={{ width: 240 }} />
                          </Form.Item>
                          <Button type="link" danger size="small" onClick={() => remove(field.name)}>{t('common.delete')}</Button>
                        </Space>
                      ))}
                      <Button type="dashed" block onClick={() => add({ key: '', value: '' })}>{t('job.form.addProp')}</Button>
                    </>
                  )}
                </Form.List>
              </Form.Item>
            </>
          )}
          {handlerKind === 2 && (
            <>
              <Form.Item name="httpUrl" label="URL" rules={[{ required: true, whitespace: true, message: t('job.form.urlRequired') }]}>
                <Input placeholder="https://" />
              </Form.Item>
              <Form.Item name="httpMethod" label={t('job.form.method')}>
                <Select
                  style={{ width: 140 }}
                  options={['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD'].map((m) => ({ label: m, value: m }))}
                />
              </Form.Item>
              <Form.Item label={t('job.form.headers')} extra={t('job.form.headersMaskHint')}>
                <Form.List name="httpHeaders">
                  {(fields, { add, remove }) => (
                    <>
                      {fields.map((field) => (
                        <Space key={field.key} align="baseline" style={{ display: 'flex', marginBottom: 8 }}>
                          <Form.Item name={[field.name, 'key']} noStyle>
                            <Input placeholder={t('job.form.propKey')} style={{ width: 160 }} />
                          </Form.Item>
                          <Form.Item name={[field.name, 'value']} noStyle>
                            <Input placeholder={t('job.form.propValue')} style={{ width: 240 }} />
                          </Form.Item>
                          <Button type="link" danger size="small" onClick={() => remove(field.name)}>{t('common.delete')}</Button>
                        </Space>
                      ))}
                      <Button type="dashed" block onClick={() => add({ key: '', value: '' })}>{t('job.form.addHeader')}</Button>
                    </>
                  )}
                </Form.List>
              </Form.Item>
              <Form.Item name="httpBody" label={t('job.form.body')}>
                <Input.TextArea rows={3} placeholder={t('job.form.bodyPlaceholder')} />
              </Form.Item>
              <Form.Item name="httpSuccessStatuses" label={t('job.form.successStatuses')}>
                <Input placeholder={t('job.form.successStatusesPlaceholder')} style={{ width: 220 }} />
              </Form.Item>
            </>
          )}
          {handlerKind === 3 && (
            <Form.Item name="sql" label="SQL" rules={[{ required: true, whitespace: true, message: t('job.form.sqlRequired') }]}>
              <Input.TextArea rows={4} placeholder={t('job.form.sqlPlaceholder')} />
            </Form.Item>
          )}

          {/* ── 失败处理 ── */}
          <Divider titlePlacement="start" size="small">{t('job.section.failure')}</Divider>
          <Form.Item name="timeoutSeconds" label={t('job.form.timeoutSeconds')} extra={t('job.form.timeoutHint')}>
            <InputNumber min={0} precision={0} suffix={t('job.form.seconds')} style={{ width: 180 }} />
          </Form.Item>
          <Form.Item name="retryCount" label={t('job.form.retryCount')}>
            <InputNumber min={0} precision={0} style={{ width: 180 }} />
          </Form.Item>
          <Form.Item name="retryIntervalSeconds" label={t('job.form.retryInterval')}>
            <InputNumber min={0} precision={0} suffix={t('job.form.seconds')} style={{ width: 180 }} />
          </Form.Item>
          <Form.Item name="failAlertThreshold" label={t('job.form.failAlertThreshold')} extra={t('job.form.failAlertHint')}>
            <InputNumber min={0} precision={0} style={{ width: 180 }} />
          </Form.Item>
          <Form.Item name="alertByNotice" label={t('job.form.alertByNotice')} valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item name="alertEmails" label={t('job.form.alertEmails')}>
            <Input placeholder={t('job.form.alertEmailsPlaceholder')} />
          </Form.Item>
        </Form>
      </FormContainer>
    </>
  )
}

// web/src/views/system/job/index.vue
<script setup lang="ts">
// 定时任务(G7)= ProTable(列表/搜索/分页)+ FormContainer 四分节表单(基本/触发/载荷/失败处理)。
// 状态列走专用启停端点(非全量 update);Panic 行开关旁加红 tag(悬浮出连败次数),重新启用即清连败恢复调度;
// Completed(一次性已跑完/过生效窗口)没有未来时刻,后端拒绝恢复(47010),故只给只读 tag 不给开关。
// 属性包在表单里是键值对 UI,提交时组装成 properties 对象;HTTP 的 headers 子键值对序列化成 JSON 字符串
// 放 properties.headers——读取时后端把 headers 值掩码成 ********,不改就原样回传即"不改"。
import { h, reactive, ref } from 'vue'
import {
  NButton, NSpace, NTag, NTooltip, NPopconfirm, NForm, NFormItem, NInput, NInputNumber,
  NRadioGroup, NRadio, NSelect, NSwitch, NDatePicker, NDivider,
  useMessage, type FormInst, type FormRules,
} from 'naive-ui'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import AppIcon from '@/components/AppIcon.vue'
import FormContainer from '@/components/FormContainer/index.vue'
import StatusSwitch from '@/components/StatusSwitch/index.vue'
import CronEditor from '@/components/CronEditor/index.vue'
import { useConfirm } from '@/composables/useConfirm'
import { useBatchDelete } from '@/composables/useBatchDelete'
import { useAuthStore } from '@/stores/auth'
import { jobApi } from '@/api'
import { translateError } from '@/utils/error'
import {
  JobConcurrencyMode, JobHandlerKind, JobMisfireStrategy, JobStatus, JobTriggerKind,
  type JobInput, type SysJob,
} from '@/types/api'

const { t } = useI18n()
const message = useMessage()
const router = useRouter()
const { run, confirm } = useConfirm()
const authStore = useAuthStore()
const tableRef = ref<ProTableInst<SysJob>>()
const { checkedKeys, hasSelection, run: batchDelete } = useBatchDelete({
  remove: jobApi.batchRemove,
  refresh: () => tableRef.value?.refresh(),
  successMsg: t('job.deleted'),
})

// ── 列 ──
const handlerKindOptions = [
  { label: () => t('job.handler.compiled'), value: JobHandlerKind.Compiled, tagType: 'info' as const },
  { label: () => t('job.handler.http'), value: JobHandlerKind.Http, tagType: 'success' as const },
  { label: () => t('job.handler.sql'), value: JobHandlerKind.Sql, tagType: 'warning' as const },
]
const statusOptions = [
  { label: () => t('job.status.ready'), value: JobStatus.Ready, tagType: 'success' as const },
  { label: () => t('job.status.paused'), value: JobStatus.Paused, tagType: 'default' as const },
  { label: () => t('job.status.completed'), value: JobStatus.Completed, tagType: 'default' as const },
  { label: () => t('job.status.panic'), value: JobStatus.Panic, tagType: 'error' as const },
]

/** 触发描述:cron 原文 /「每 N 秒」/ 一次性时刻。 */
function triggerText(r: SysJob): string {
  switch (r.triggerKind) {
    case JobTriggerKind.Interval:
      return t('job.trigger.everySeconds', { n: r.intervalSeconds ?? 0 })
    case JobTriggerKind.OneShot:
      return (r.oneShotTime ?? '').slice(0, 19).replace('T', ' ') || '—'
    default:
      return r.cronExpression || '—'
  }
}

const statusTagType = { [JobStatus.Ready]: 'success', [JobStatus.Paused]: 'default', [JobStatus.Completed]: 'default', [JobStatus.Panic]: 'error' } as const
const statusText = (s: JobStatus) =>
  t(s === JobStatus.Ready ? 'job.status.ready' : s === JobStatus.Paused ? 'job.status.paused' : s === JobStatus.Completed ? 'job.status.completed' : 'job.status.panic')

function renderStatus(r: SysJob) {
  // Completed 没有未来时刻可恢复(后端 47010),不给开关
  if (r.status === JobStatus.Completed)
    return h(NTag, { size: 'small', bordered: false }, () => statusText(r.status))
  if (!authStore.hasPerm('PUT:/api/v1/sys/job/{id}/enabled'))
    return h(NTag, { size: 'small', bordered: false, type: statusTagType[r.status] }, () => statusText(r.status))
  const sw = h(StatusSwitch, {
    value: r.status === JobStatus.Ready,
    confirm: (next: boolean) => (next ? null : t('job.pauseConfirm', { name: r.name })),
    request: (next: boolean) => jobApi.setEnabled(r.id, next),
    // 启停会重算 nextRunTime / 清连败计数,本地写回拼不出来 → 直接重拉
    'onUpdate:value': () => tableRef.value?.refresh(),
  })
  if (r.status !== JobStatus.Panic) return sw
  return h(NSpace, { size: 6, wrapItem: false, align: 'center' }, () => [
    sw,
    h(NTooltip, null, {
      trigger: () => h(NTag, { size: 'small', bordered: false, type: 'error' }, () => t('job.status.panic')),
      default: () => t('job.panicTooltip', { n: r.consecutiveErrors }),
    }),
  ])
}

const columns: ProTableColumn<SysJob>[] = [
  // 内置任务禁删,批量删除同样不可含内置(后端整批拒绝 47014)
  { type: 'selection', disabled: (r: SysJob) => r.isSystem },
  {
    key: 'name',
    title: () => t('job.name'),
    search: true,
    minWidth: 160,
    render: (r) =>
      h('div', null, [
        h('div', null, r.name),
        h('div', { style: 'font-size:12px;color:var(--color-text-tertiary);' }, r.code),
      ]),
  },
  { key: 'handlerKind', title: () => t('job.handler.kind'), width: 100, tag: true, search: true, options: handlerKindOptions },
  { key: 'trigger', title: () => t('job.trigger.kind'), minWidth: 130, ellipsis: { tooltip: true }, render: (r) => triggerText(r) },
  { key: 'status', title: () => t('common.status'), width: 130, search: true, options: statusOptions, render: renderStatus },
  { key: 'nextRunTime', title: () => t('job.nextRunTime'), width: 160, format: 'datetime' },
  { key: 'lastRunTime', title: () => t('job.lastRunTime'), width: 160, format: 'datetime' },
  {
    key: 'numberOfRuns',
    title: () => t('job.runCount'),
    width: 110,
    align: 'center',
    render: (r) =>
      h('span', { class: 'tabular' }, [
        h('span', null, String(r.numberOfRuns)),
        h('span', { style: 'color:var(--color-text-tertiary);' }, ' / '),
        h('span', { style: r.numberOfErrors > 0 ? 'color:var(--color-danger);' : '' }, String(r.numberOfErrors)),
      ]),
  },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 240,
    fixed: 'right',
    hideInSetting: true,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        authStore.hasPerm('PUT:/api/v1/sys/job/{id}')
          ? h(NButton, { size: 'small', quaternary: true, type: 'primary', onClick: () => openEdit(r) }, () => t('common.edit'))
          : null,
        authStore.hasPerm('POST:/api/v1/sys/job/{id}/run')
          ? h(NButton, { size: 'small', quaternary: true, onClick: () => runOnce(r) }, () => t('job.runOnce'))
          : null,
        // 记录:携 jobId 跳执行记录页(那边 watch query 自动带上筛选)
        h(NButton, {
          size: 'small', quaternary: true,
          onClick: () => router.push({ path: '/system/job-log', query: { jobId: String(r.id) } }),
        }, () => t('job.viewLogs')),
        !authStore.hasPerm('DELETE:/api/v1/sys/job/{id}')
          ? null
          : r.isSystem
            ? h(NTooltip, null, {
                trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'error', disabled: true }, () => t('common.delete')),
                default: () => t('job.protectedTip'),
              })
            : h(NPopconfirm, {
                onPositiveClick: () =>
                  run(() => jobApi.remove(r.id), t('job.deleted')).then((ok) => {
                    if (ok) tableRef.value?.refresh()
                  }),
              }, {
                trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'error' }, () => t('common.delete')),
                default: () => t('job.deleteConfirm', { name: r.name }),
              }),
      ]),
  },
]

/** 执行一次:重操作走 dialog 确认(执行在 dialog 挂起期间跑,防连点)。 */
function runOnce(r: SysJob) {
  confirm({
    content: t('job.runConfirm', { name: r.name }),
    action: () => jobApi.run(r.id),
    successMsg: t('job.runStarted'),
  }).then((ok) => {
    if (ok) tableRef.value?.refresh()
  })
}

// ── 新增/编辑表单(四分节:基本/触发/载荷/失败处理) ──
interface KV { key: string; value: string }
interface JobForm {
  code: string
  name: string
  remark: string
  triggerKind: JobTriggerKind
  cronExpression: string
  intervalSeconds: number | null
  oneShotTime: string | null
  startTime: string | null
  endTime: string | null
  misfireStrategy: JobMisfireStrategy
  concurrencyMode: JobConcurrencyMode
  handlerKind: JobHandlerKind
  handlerName: string
  /** 编译类自定义属性包(键值对 UI,提交时装成 properties 对象)。 */
  props: KV[]
  httpUrl: string
  httpMethod: string
  headers: KV[]
  httpBody: string
  successStatuses: string
  sqlText: string
  timeoutSeconds: number
  retryCount: number
  retryIntervalSeconds: number
  failAlertThreshold: number
  alertByNotice: boolean
  alertEmails: string
}

const show = ref(false)
const formRef = ref<FormInst | null>(null)
const editingId = ref<number | null>(null)
const blank = (): JobForm => ({
  code: '', name: '', remark: '',
  triggerKind: JobTriggerKind.Cron, cronExpression: '',
  intervalSeconds: 60, oneShotTime: null, startTime: null, endTime: null,
  misfireStrategy: JobMisfireStrategy.Skip, concurrencyMode: JobConcurrencyMode.SerialSkip,
  handlerKind: JobHandlerKind.Compiled, handlerName: '', props: [],
  httpUrl: '', httpMethod: 'GET', headers: [], httpBody: '', successStatuses: '',
  sqlText: '',
  timeoutSeconds: 0, retryCount: 0, retryIntervalSeconds: 30, failAlertThreshold: 0,
  alertByNotice: true, alertEmails: '',
})
const form = reactive<JobForm>(blank())

const rules: FormRules = {
  code: { required: true, whitespace: true, message: () => t('job.codeRequired'), trigger: ['input', 'blur'] },
  name: { required: true, whitespace: true, message: () => t('job.nameRequired'), trigger: ['input', 'blur'] },
  // 条件字段的 form-item 随 triggerKind/handlerKind v-if 切换,只有挂着的才参与校验
  cronExpression: { required: true, validator: () => !!form.cronExpression.trim(), message: () => t('job.trigger.cronRequired'), trigger: ['change', 'blur'] },
  intervalSeconds: { required: true, validator: () => form.intervalSeconds != null && form.intervalSeconds >= 5, message: () => t('job.trigger.intervalRequired'), trigger: ['change', 'blur'] },
  oneShotTime: { required: true, validator: () => !!form.oneShotTime, message: () => t('job.trigger.oneShotRequired'), trigger: ['change', 'blur'] },
  handlerName: { required: true, validator: () => !!form.handlerName, message: () => t('job.handler.nameRequired'), trigger: ['change', 'blur'] },
  httpUrl: { required: true, whitespace: true, message: () => t('job.handler.httpUrlRequired'), trigger: ['input', 'blur'] },
  sqlText: { required: true, whitespace: true, message: () => t('job.handler.sqlRequired'), trigger: ['input', 'blur'] },
}

// 已注册编译处理器下拉(GET /handlers);只拉一次,失败静默(下拉空了还能手看后端日志排查)
const handlerOptions = ref<{ label: string; value: string }[]>([])
// SQL 载荷总闸(后端 Jobs:Sql:Enabled)。默认按"开"起手:清单没拉到就不该凭空禁掉一种载荷,
// 真关着的话保存时后端还有 47008 兜底。
const sqlEnabled = ref(true)
let handlersLoaded = false
async function ensureHandlers() {
  if (handlersLoaded) return
  try {
    const out = await jobApi.handlers()
    handlerOptions.value = out.handlers.map((n) => ({ label: n, value: n }))
    sqlEnabled.value = out.sqlEnabled
    handlersLoaded = true
  } catch {
    // 静默:处理器清单是配角,拉取失败不挡表单
  }
}

const httpMethodOptions = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD'].map((m) => ({ label: m, value: m }))

/** 后端 date-time 可能带小数秒,砍到秒级正好喂 n-date-picker 的 formatted-value。 */
const toLocal = (s?: string | null) => (s ? s.slice(0, 19) : null)

function openAdd() {
  editingId.value = null
  Object.assign(form, blank())
  show.value = true
  void ensureHandlers()
}

function openEdit(r: SysJob) {
  editingId.value = r.id
  Object.assign(form, blank())
  let props: Record<string, string | null> = {}
  try {
    props = JSON.parse(r.propsJson || '{}') as Record<string, string | null>
  } catch {
    // 属性包坏 JSON:别让编辑崩,当空包处理
  }
  form.code = r.code
  form.name = r.name
  form.remark = r.remark ?? ''
  form.triggerKind = r.triggerKind
  form.cronExpression = r.cronExpression ?? ''
  form.intervalSeconds = r.intervalSeconds ?? 60
  form.oneShotTime = toLocal(r.oneShotTime)
  form.startTime = toLocal(r.startTime)
  form.endTime = toLocal(r.endTime)
  form.misfireStrategy = r.misfireStrategy
  form.concurrencyMode = r.concurrencyMode
  form.handlerKind = r.handlerKind
  form.timeoutSeconds = r.timeoutSeconds
  form.retryCount = r.retryCount
  form.retryIntervalSeconds = r.retryIntervalSeconds
  form.failAlertThreshold = r.failAlertThreshold
  form.alertByNotice = r.alertByNotice
  form.alertEmails = r.alertEmails ?? ''
  if (r.handlerKind === JobHandlerKind.Http) {
    form.httpUrl = props.url ?? ''
    form.httpMethod = (props.method ?? 'GET').toUpperCase()
    form.httpBody = props.body ?? ''
    form.successStatuses = props.successStatuses ?? ''
    // headers 值已被后端掩码成 ********;原样回传 = 不改,改了哪条就生效哪条
    let headers: Record<string, string> = {}
    try {
      headers = JSON.parse(props.headers || '{}') as Record<string, string>
    } catch {
      // headers 整体被掩码(非 JSON)时无从回填,置空
    }
    form.headers = Object.entries(headers).map(([key, value]) => ({ key, value: value ?? '' }))
  } else if (r.handlerKind === JobHandlerKind.Sql) {
    form.sqlText = props.sql ?? ''
  } else {
    form.handlerName = r.handlerName
    form.props = Object.entries(props).map(([key, value]) => ({ key, value: value ?? '' }))
  }
  show.value = true
  void ensureHandlers()
}

/** 表单态 → JobInput:按载荷类型装 properties;HTTP 的 headers 序列化成 JSON 字符串子键。 */
function buildInput(): JobInput {
  const properties: Record<string, string> = {}
  if (form.handlerKind === JobHandlerKind.Http) {
    properties.url = form.httpUrl.trim()
    properties.method = form.httpMethod
    const headers: Record<string, string> = {}
    for (const kv of form.headers) if (kv.key.trim()) headers[kv.key.trim()] = kv.value
    if (Object.keys(headers).length) properties.headers = JSON.stringify(headers)
    if (form.httpBody.trim()) properties.body = form.httpBody
    if (form.successStatuses.trim()) properties.successStatuses = form.successStatuses.trim()
  } else if (form.handlerKind === JobHandlerKind.Sql) {
    properties.sql = form.sqlText
  } else {
    for (const kv of form.props) if (kv.key.trim()) properties[kv.key.trim()] = kv.value
  }
  return {
    code: form.code.trim(),
    name: form.name.trim(),
    handlerKind: form.handlerKind,
    // HTTP/SQL 的处理器名由服务端固定填内置处理器,这里传空即可
    handlerName: form.handlerKind === JobHandlerKind.Compiled ? form.handlerName : '',
    properties,
    triggerKind: form.triggerKind,
    cronExpression: form.triggerKind === JobTriggerKind.Cron ? form.cronExpression.trim() : null,
    intervalSeconds: form.triggerKind === JobTriggerKind.Interval ? form.intervalSeconds : null,
    oneShotTime: form.triggerKind === JobTriggerKind.OneShot ? form.oneShotTime : null,
    startTime: form.startTime || null,
    endTime: form.endTime || null,
    misfireStrategy: form.misfireStrategy,
    concurrencyMode: form.concurrencyMode,
    timeoutSeconds: form.timeoutSeconds,
    retryCount: form.retryCount,
    retryIntervalSeconds: form.retryIntervalSeconds,
    failAlertThreshold: form.failAlertThreshold,
    alertByNotice: form.alertByNotice,
    alertEmails: form.alertEmails.trim() || null,
    remark: form.remark.trim() || null,
  }
}

async function save() {
  await formRef.value?.validate()
  try {
    if (editingId.value === null) await jobApi.add(buildInput())
    else await jobApi.update(editingId.value, buildInput())
    // 文案里带「集群下最长 30 秒后生效」——各节点按 ReloadSeconds 周期重载任务表
    message.success(t('job.saved'))
    await tableRef.value?.refresh()
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}
</script>

<template>
  <ProTable
    ref="tableRef"
    :columns="columns"
    :fetcher="jobApi.page"
    storage-key="sys-job"
    :checked-row-keys="checkedKeys"
    @update:checked-row-keys="(keys: (string | number)[]) => (checkedKeys = keys)"
    @error="(e) => message.error(translateError(e))"
  >
    <template #toolbar>
      <n-button v-auth="'POST:/api/v1/sys/job'" type="primary" @click="openAdd">
        <template #icon><AppIcon icon="ph:plus" :size="16" /></template>{{ t('common.add') }}
      </n-button>
      <n-button v-auth="'POST:/api/v1/sys/job/batch-delete'" type="error" :disabled="!hasSelection" @click="batchDelete">
        <template #icon><AppIcon icon="ph:trash" :size="16" /></template>{{ t('common.batchDelete') }}
      </n-button>
    </template>
  </ProTable>

  <FormContainer
    v-model:show="show"
    :title="editingId === null ? t('job.addTitle') : t('job.editTitle')"
    :width="680"
    :on-confirm="save"
    :confirm-text="t('common.save')"
  >
    <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" :label-width="110">
      <!-- ── 基本 ── -->
      <n-divider title-placement="left" class="job-sec">{{ t('job.form.sectionBasic') }}</n-divider>
      <n-form-item :label="t('job.code')" path="code">
        <n-input v-model:value="form.code" :placeholder="t('job.codePlaceholder')" :disabled="editingId !== null" />
      </n-form-item>
      <n-form-item :label="t('job.name')" path="name">
        <n-input v-model:value="form.name" :placeholder="t('job.name')" />
      </n-form-item>
      <n-form-item :label="t('job.remark')">
        <n-input v-model:value="form.remark" type="textarea" :autosize="{ minRows: 1, maxRows: 3 }" />
      </n-form-item>

      <!-- ── 触发 ── -->
      <n-divider title-placement="left" class="job-sec">{{ t('job.form.sectionTrigger') }}</n-divider>
      <n-form-item :label="t('job.trigger.kind')">
        <n-radio-group v-model:value="form.triggerKind">
          <n-space>
            <n-radio :value="JobTriggerKind.Cron">{{ t('job.trigger.cron') }}</n-radio>
            <n-radio :value="JobTriggerKind.Interval">{{ t('job.trigger.interval') }}</n-radio>
            <n-radio :value="JobTriggerKind.OneShot">{{ t('job.trigger.oneShot') }}</n-radio>
          </n-space>
        </n-radio-group>
      </n-form-item>
      <n-form-item v-if="form.triggerKind === JobTriggerKind.Cron" :label="t('job.trigger.cronExpression')" path="cronExpression">
        <CronEditor v-model:model-value="form.cronExpression" />
      </n-form-item>
      <n-form-item v-if="form.triggerKind === JobTriggerKind.Interval" :label="t('job.trigger.intervalSeconds')" path="intervalSeconds">
        <n-input-number v-model:value="form.intervalSeconds" :min="5" style="width: 200px">
          <template #suffix>{{ t('job.trigger.seconds') }}</template>
        </n-input-number>
      </n-form-item>
      <n-form-item v-if="form.triggerKind === JobTriggerKind.OneShot" :label="t('job.trigger.oneShotTime')" path="oneShotTime">
        <n-date-picker
          v-model:formatted-value="form.oneShotTime"
          type="datetime"
          value-format="yyyy-MM-dd'T'HH:mm:ss"
          clearable
          style="width: 240px"
        />
      </n-form-item>
      <n-form-item :label="t('job.form.startTime')">
        <n-date-picker
          v-model:formatted-value="form.startTime"
          type="datetime"
          value-format="yyyy-MM-dd'T'HH:mm:ss"
          clearable
          :placeholder="t('job.form.windowPlaceholder')"
          style="width: 240px"
        />
      </n-form-item>
      <n-form-item :label="t('job.form.endTime')">
        <n-date-picker
          v-model:formatted-value="form.endTime"
          type="datetime"
          value-format="yyyy-MM-dd'T'HH:mm:ss"
          clearable
          :placeholder="t('job.form.windowPlaceholder')"
          style="width: 240px"
        />
      </n-form-item>
      <n-form-item :label="t('job.form.misfireStrategy')">
        <n-radio-group v-model:value="form.misfireStrategy">
          <n-space>
            <n-radio :value="JobMisfireStrategy.Skip">{{ t('job.form.misfireSkip') }}</n-radio>
            <n-radio :value="JobMisfireStrategy.FireOnceNow">{{ t('job.form.misfireFireOnceNow') }}</n-radio>
          </n-space>
        </n-radio-group>
      </n-form-item>
      <n-form-item :label="t('job.form.concurrencyMode')">
        <n-radio-group v-model:value="form.concurrencyMode">
          <n-space>
            <n-radio :value="JobConcurrencyMode.SerialSkip">{{ t('job.form.concurrencySerial') }}</n-radio>
            <n-radio :value="JobConcurrencyMode.Parallel">{{ t('job.form.concurrencyParallel') }}</n-radio>
          </n-space>
        </n-radio-group>
      </n-form-item>

      <!-- ── 载荷 ── -->
      <n-divider title-placement="left" class="job-sec">{{ t('job.form.sectionHandler') }}</n-divider>
      <n-form-item :label="t('job.handler.kind')">
        <n-radio-group v-model:value="form.handlerKind">
          <n-space>
            <n-radio :value="JobHandlerKind.Compiled">{{ t('job.handler.compiled') }}</n-radio>
            <n-radio :value="JobHandlerKind.Http">{{ t('job.handler.http') }}</n-radio>
            <n-radio :value="JobHandlerKind.Sql" :disabled="!sqlEnabled">{{ t('job.handler.sql') }}</n-radio>
          </n-space>
        </n-radio-group>
      </n-form-item>
      <!-- 总闸关着就说清是"后端没开",否则用户只会看见一个莫名其妙点不动的选项 -->
      <n-form-item v-if="!sqlEnabled" :show-label="false">
        <span class="job-hint">{{ t('job.handler.sqlDisabledHint') }}</span>
      </n-form-item>
      <template v-if="form.handlerKind === JobHandlerKind.Compiled">
        <n-form-item :label="t('job.handler.name')" path="handlerName">
          <n-select v-model:value="form.handlerName" filterable :options="handlerOptions" :placeholder="t('job.handler.namePlaceholder')" />
        </n-form-item>
        <n-form-item :label="t('job.handler.props')">
          <div class="kv-editor">
            <div v-for="(kv, i) in form.props" :key="i" class="kv-row">
              <n-input v-model:value="kv.key" size="small" :placeholder="t('job.handler.propKey')" />
              <n-input v-model:value="kv.value" size="small" :placeholder="t('job.handler.propValue')" />
              <n-button quaternary circle size="small" @click="form.props.splice(i, 1)">
                <template #icon><AppIcon icon="ph:x" :size="14" /></template>
              </n-button>
            </div>
            <n-button dashed size="small" @click="form.props.push({ key: '', value: '' })">
              <template #icon><AppIcon icon="ph:plus" :size="14" /></template>{{ t('job.handler.addProp') }}
            </n-button>
          </div>
        </n-form-item>
      </template>
      <template v-if="form.handlerKind === JobHandlerKind.Http">
        <n-form-item :label="t('job.handler.httpUrl')" path="httpUrl">
          <n-input v-model:value="form.httpUrl" placeholder="https://example.com/api/task" />
        </n-form-item>
        <n-form-item :label="t('job.handler.httpMethod')">
          <n-select v-model:value="form.httpMethod" :options="httpMethodOptions" style="width: 160px" />
        </n-form-item>
        <n-form-item :label="t('job.handler.httpHeaders')">
          <div class="kv-editor">
            <div v-for="(kv, i) in form.headers" :key="i" class="kv-row">
              <n-input v-model:value="kv.key" size="small" :placeholder="t('job.handler.propKey')" />
              <n-input v-model:value="kv.value" size="small" :placeholder="t('job.handler.propValue')" />
              <n-button quaternary circle size="small" @click="form.headers.splice(i, 1)">
                <template #icon><AppIcon icon="ph:x" :size="14" /></template>
              </n-button>
            </div>
            <n-button dashed size="small" @click="form.headers.push({ key: '', value: '' })">
              <template #icon><AppIcon icon="ph:plus" :size="14" /></template>{{ t('job.handler.addProp') }}
            </n-button>
            <span v-if="editingId !== null" class="kv-hint">{{ t('job.handler.headersMaskHint') }}</span>
          </div>
        </n-form-item>
        <n-form-item :label="t('job.handler.httpBody')">
          <n-input v-model:value="form.httpBody" type="textarea" :autosize="{ minRows: 2, maxRows: 6 }" />
        </n-form-item>
        <n-form-item :label="t('job.handler.successStatuses')">
          <n-input v-model:value="form.successStatuses" :placeholder="t('job.handler.successStatusesPlaceholder')" style="width: 240px" />
        </n-form-item>
      </template>
      <n-form-item v-if="form.handlerKind === JobHandlerKind.Sql" :label="t('job.handler.sqlText')" path="sqlText">
        <n-input v-model:value="form.sqlText" type="textarea" :autosize="{ minRows: 3, maxRows: 10 }" placeholder="UPDATE ..." />
      </n-form-item>

      <!-- ── 失败处理 ── -->
      <n-divider title-placement="left" class="job-sec">{{ t('job.form.sectionFailure') }}</n-divider>
      <n-form-item :label="t('job.form.timeoutSeconds')">
        <n-input-number v-model:value="form.timeoutSeconds" :min="0" style="width: 160px" />
        <span class="job-hint">{{ t('job.form.timeoutHint') }}</span>
      </n-form-item>
      <n-form-item :label="t('job.form.retryCount')">
        <n-input-number v-model:value="form.retryCount" :min="0" :max="10" style="width: 160px" />
      </n-form-item>
      <n-form-item :label="t('job.form.retryIntervalSeconds')">
        <n-input-number v-model:value="form.retryIntervalSeconds" :min="0" style="width: 160px" />
      </n-form-item>
      <n-form-item :label="t('job.form.failAlertThreshold')">
        <n-input-number v-model:value="form.failAlertThreshold" :min="0" style="width: 160px" />
        <span class="job-hint">{{ t('job.form.failAlertHint') }}</span>
      </n-form-item>
      <n-form-item :label="t('job.form.alertByNotice')">
        <n-switch v-model:value="form.alertByNotice" />
      </n-form-item>
      <n-form-item :label="t('job.form.alertEmails')">
        <n-input v-model:value="form.alertEmails" :placeholder="t('job.form.alertEmailsPlaceholder')" />
      </n-form-item>
    </n-form>
  </FormContainer>
</template>

<style scoped>
.job-sec {
  font-size: var(--font-size-sm);
  font-weight: 600;
}
.job-sec:first-child {
  margin-top: 0;
}
.kv-editor {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}
.kv-row {
  display: flex;
  gap: 8px;
  align-items: center;
}
.kv-hint {
  font-size: 12px;
  color: var(--color-text-tertiary);
}
.job-hint {
  margin-left: 10px;
  font-size: 12px;
  color: var(--color-text-tertiary);
}
</style>
