// web/src/views/system/file/index.vue
<script setup lang="ts">
// 文件管理 = 只读 ProTable(搜索 originalName→FileName)+ 工具栏 FileUpload 触发器 + 行内下载/删除。
// 下载走 blob(Bearer 自动带)→ createObjectURL + <a download> + revoke;删除走 useConfirm。
import { h, ref } from 'vue'
import { NButton, NSpace, NPopconfirm, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import AppIcon from '@/components/AppIcon.vue'
import FileUpload from '@/components/FileUpload/index.vue'
import { useConfirm } from '@/composables/useConfirm'
import { useBatchDelete } from '@/composables/useBatchDelete'
import { fileApi } from '@/api'
import { translateError } from '@/utils/error'
import type { SysFile } from '@/types/api'

const { t } = useI18n()
const message = useMessage()
const { run } = useConfirm()
const tableRef = ref<ProTableInst<SysFile>>()
const { checkedKeys, hasSelection, run: batchDelete } = useBatchDelete({
  remove: fileApi.batchRemove,
  refresh: () => tableRef.value?.refresh(),
  successMsg: t('file.deleted'),
})

function onUploaded() {
  message.success(t('file.uploaded'))
  tableRef.value?.refresh()
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`
  return `${(bytes / 1024 / 1024 / 1024).toFixed(1)} GB`
}

async function download(r: SysFile) {
  try {
    const blob = await fileApi.download(r.id)
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = r.originalName
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  } catch (e) {
    message.error(translateError(e))
  }
}

const columns: ProTableColumn<SysFile>[] = [
  { type: 'selection' },
  { key: 'originalName', title: () => t('file.name'), search: true, ellipsis: { tooltip: true } },
  { key: 'extension', title: () => t('file.extension'), width: 90, render: (r) => r.extension || '—' },
  { key: 'sizeBytes', title: () => t('file.size'), width: 110, render: (r) => formatSize(r.sizeBytes) },
  { key: 'contentType', title: () => t('file.contentType'), ellipsis: { tooltip: true }, render: (r) => r.contentType || '—' },
  { key: 'createTime', title: () => t('file.uploadTime'), format: 'datetime' },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 140,
    hideInSetting: true,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        h(
          NButton,
          { size: 'small', quaternary: true, type: 'primary', onClick: () => download(r) },
          { default: () => t('file.download'), icon: () => h(AppIcon, { icon: 'ph:download-simple', size: 15 }) },
        ),
        h(
          NPopconfirm,
          {
            onPositiveClick: () =>
              run(() => fileApi.remove(r.id), t('file.deleted')).then((ok) => {
                if (ok) tableRef.value?.refresh()
              }),
          },
          {
            trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'error' }, () => t('common.delete')),
            default: () => t('file.deleteConfirm', { name: r.originalName }),
          },
        ),
      ]),
  },
]
</script>

<template>
  <ProTable
    ref="tableRef"
    :columns="columns"
    :fetcher="fileApi.page"
    storage-key="sys-file"
    :checked-row-keys="checkedKeys"
    @update:checked-row-keys="(keys: (string | number)[]) => (checkedKeys = keys)"
    @error="(e) => message.error(translateError(e))"
  >
    <template #toolbar>
      <FileUpload v-auth="'POST:/api/v1/sys/file/upload'" :show-file-list="false" @uploaded="onUploaded">
        <n-button type="primary">
          <template #icon><AppIcon icon="ph:upload-simple" :size="16" /></template>{{ t('file.upload') }}
        </n-button>
      </FileUpload>
      <FileUpload v-auth="'POST:/api/v1/sys/file/chunk/init'" chunked :show-file-list="false" @uploaded="onUploaded">
        <n-button>
          <template #icon><AppIcon icon="ph:stack" :size="16" /></template>{{ t('file.uploadChunked') }}
        </n-button>
      </FileUpload>
      <n-button
        v-auth="'POST:/api/v1/sys/file/batch-delete'"
        type="error"
        :disabled="!hasSelection"
        @click="batchDelete"
      >
        <template #icon><AppIcon icon="ph:trash" :size="16" /></template>{{ t('common.batchDelete') }}
      </n-button>
    </template>
  </ProTable>
</template>

// web-react/src/views/system/file/index.tsx
// 文件管理页:只读列表(按文件名搜索)+ 工具栏上传(整传/分片)+ 行内下载/删除 + 批量删除。
// 照 B11 范式:纯逻辑抽 fileFormat.ts(formatSize/triggerBlobDownload,变异钉),本页只接线。
// 下载走 blob(Bearer 自动带)→ createObjectURL + <a download>;批删走 useBatchDelete(受控 rowSelection)。
import { useCallback, useMemo, useRef } from 'react'
import { App, Button, Space } from 'antd'
import { useTranslation } from 'react-i18next'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import type { ProColumns } from '@ant-design/pro-components'
import { Can } from '@/components/Can'
import { FileUpload } from '@/components/FileUpload'
import { useConfirm } from '@/hooks/useConfirm'
import { useBatchDelete } from '@/hooks/useBatchDelete'
import { useHasPerm } from '@/stores/auth'
import { fileApi } from '@/api'
import { translateError } from '@/utils/error'
import type { SysFile } from '@/types/api'
import { formatSize, triggerBlobDownload } from './fileFormat'

export default function FilePage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const { confirm } = useConfirm()
  const has = useHasPerm()

  const tableRef = useRef<DataTableHandle>(null)
  const reload = useCallback(() => tableRef.current?.reload(), [])

  const { selectedKeys, setSelectedKeys, hasSelection, run: batchDelete } = useBatchDelete({
    remove: fileApi.batchRemove,
    refresh: reload,
    successMsg: t('file.deleted'),
  })

  const fetchFiles: PageFetcher<SysFile> = (q) =>
    fileApi.page({ page: q.page, pageSize: q.pageSize, originalName: typeof q.originalName === 'string' ? q.originalName : undefined })

  const onUploaded = useCallback(() => {
    message.success(t('file.uploaded'))
    reload()
  }, [message, t, reload])

  const handleDownload = useCallback(
    async (r: SysFile) => {
      try {
        triggerBlobDownload(await fileApi.download(r.id), r.originalName)
      } catch (e) {
        message.error(translateError(e))
      }
    },
    [message],
  )

  const handleDelete = useCallback(
    (r: SysFile) => {
      confirm({ content: t('file.deleteConfirm', { name: r.originalName }), action: () => fileApi.remove(r.id), successMsg: t('file.deleted') }).then(
        (ok) => { if (ok) reload() },
      )
    },
    [confirm, t, reload],
  )

  const columns = useMemo<ProColumns<SysFile>[]>(
    () => [
      { title: t('file.name'), dataIndex: 'originalName', ellipsis: true },
      { title: t('file.extension'), dataIndex: 'extension', search: false, width: 90, render: (_, r) => r.extension || '—' },
      { title: t('file.size'), dataIndex: 'sizeBytes', search: false, width: 110, render: (_, r) => formatSize(r.sizeBytes) },
      { title: t('file.contentType'), dataIndex: 'contentType', search: false, ellipsis: true, render: (_, r) => r.contentType || '—' },
      { title: t('file.uploadTime'), dataIndex: 'createTime', search: false, width: 170 },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 140, fixed: 'right',
        render: (_, r) => (
          <Space size={4}>
            {has('GET:/api/v1/sys/file/{id}/download') && <Button type="link" size="small" onClick={() => handleDownload(r)}>{t('file.download')}</Button>}
            {has('DELETE:/api/v1/sys/file/{id}') && <Button type="link" size="small" danger onClick={() => handleDelete(r)}>{t('common.delete')}</Button>}
          </Space>
        ),
      },
    ],
    [t, has, handleDownload, handleDelete],
  )

  return (
    <DataTable<SysFile>
      ref={tableRef}
      columns={columns}
      fetcher={fetchFiles}
      persistKey="sys-file"
      rowSelection={{ selectedRowKeys: selectedKeys, onChange: setSelectedKeys }}
      toolbar={
        <Space>
          <Can code="POST:/api/v1/sys/file/upload">
            <FileUpload showUploadList={false} onUploaded={onUploaded}>
              <Button type="primary">{t('file.upload')}</Button>
            </FileUpload>
          </Can>
          <Can code="POST:/api/v1/sys/file/chunk/init">
            <FileUpload chunked showUploadList={false} onUploaded={onUploaded}>
              <Button>{t('file.uploadChunked')}</Button>
            </FileUpload>
          </Can>
          <Can code="POST:/api/v1/sys/file/batch-delete">
            <Button danger disabled={!hasSelection} onClick={batchDelete}>{t('common.batchDelete')}</Button>
          </Can>
        </Space>
      }
    />
  )
}
