// web-react/src/layouts/NoticeBell.tsx
// 顶栏消息通知铃铛(与 Vue layouts/NoticeBell.vue 同构):富面板 Popover —— 无页签单列表 + 正文弹层。
// 未读=圆点+加粗+淡主色底,已读=整行变淡;"读没读"是过滤器不是分类,不做成页签(参考普查结论,筛选在个人通知页)。
// 未读数双腿:订阅 noticeBus(SignalR 推送 `notice-changed` 即刻重拉)+ 30s 轮询兜底;失败静默不糊顶栏。
import { useEffect, useState } from 'react'
import { App, Badge, Button, Empty, Modal, Popover, Spin, Tag, Typography } from 'antd'
import { BellOutlined, CheckOutlined, RightOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { noticeApi } from '@/api'
import { noticeBus } from '@/composables/useRealtime'
import { MarkdownView } from '@/components/MarkdownView'
import { translateError } from '@/utils/error'
import { NoticeType, type NoticeMineItem } from '@/types/api'
import './noticebell.css'

/** 正文摘要:去掉常见 Markdown 记号,压空白,截断。ponytail: 正则够用,要精准渲染再引 md 解析。 */
function snippet(md?: string | null): string {
  if (!md) return ''
  const s = md
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '') // 图片
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // 链接留文字
    .replace(/[#>*_`~-]/g, '') // 记号
    .replace(/\s+/g, ' ')
    .trim()
  return s.length > 60 ? s.slice(0, 60) + '…' : s
}
/** 短时间戳(本地,YYYY-MM-DD HH:mm)。ponytail: 够看,要"3 分钟前"再引相对时间库。 */
const shortTime = (iso: string) => (iso ?? '').replace('T', ' ').slice(0, 16)

// 类型 → 标签色。新增类型在此补一行即可(文案见组件内 typeLabel)。
const tagColor = (ty: NoticeType) =>
  ty === NoticeType.Announcement ? 'warning' : ty === NoticeType.Message ? 'success' : 'processing'

export function NoticeBell() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const navigate = useNavigate()

  const [open, setOpen] = useState(false)
  const [unread, setUnread] = useState(0)
  const [items, setItems] = useState<NoticeMineItem[]>([])
  const [loading, setLoading] = useState(false)

  const fetchUnread = () => noticeApi.unreadCount().then(setUnread).catch(() => {})
  // 无页签单列表:恒拉最近一页混排,未读靠条目样式强调;筛选能力在"查看全部"的个人通知页。
  const fetchList = () => {
    setLoading(true)
    noticeApi
      .mine({ page: 1, pageSize: 10 })
      .then(({ items: list }) => setItems(list))
      .catch(() => setItems([]))
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    void fetchUnread()
    const id = setInterval(() => void fetchUnread(), 30000)
    const off = noticeBus.on(() => void fetchUnread())
    return () => {
      clearInterval(id)
      off()
    }
  }, [])

  const onOpenChange = (o: boolean) => {
    setOpen(o)
    if (o) fetchList()
  }

  // 正文弹层:内容随列表取回,直接渲染(Markdown);点条目即标记已读。
  const [showNotice, setShowNotice] = useState(false)
  const [viewNotice, setViewNotice] = useState<NoticeMineItem | null>(null)
  const openNotice = async (item: NoticeMineItem) => {
    setViewNotice(item)
    setShowNotice(true)
    if (item.isRead) return
    try {
      await noticeApi.markRead(item.id)
      setItems((prev) => prev.map((n) => (n.id === item.id ? { ...n, isRead: true } : n)))
      await fetchUnread()
    } catch (e) {
      message.error(translateError(e))
    }
  }
  const markAllRead = async () => {
    try {
      await noticeApi.markAllRead()
      await fetchUnread()
      fetchList()
    } catch (e) {
      message.error(translateError(e))
    }
  }

  const typeLabel = (ty: NoticeType) =>
    ty === NoticeType.Announcement ? t('notice.typeAnnouncement') : ty === NoticeType.Message ? t('notice.typeMessage') : t('notice.typeNotice')

  const panel = (
    <div className="notice-panel">
      <div className="notice-head">
        <span className="notice-title">{t('app.notice.title')}</span>
        <Button type="link" size="small" disabled={unread === 0} icon={<CheckOutlined />} onClick={() => void markAllRead()}>
          {t('app.notice.markAllRead')}
        </Button>
      </div>

      <Spin spinning={loading}>
        <div className="notice-scroll">
          {items.length === 0 ? (
            <div className="notice-empty">
              <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t('app.notice.empty')} />
            </div>
          ) : (
            <ul className="notice-list">
              {items.map((n) => (
                <li key={n.id} className={`notice-item ${n.isRead ? 'read' : 'unread'}`} onClick={() => void openNotice(n)}>
                  {!n.isRead ? <span className="dot" /> : null}
                  <div className="notice-body">
                    <div className="line1">
                      <Tag color={tagColor(n.type)}>{typeLabel(n.type)}</Tag>
                      <span className={`item-title${n.isRead ? '' : ' unread'}`}>{n.title}</span>
                    </div>
                    {snippet(n.content) ? (
                      <Typography.Text type="secondary" className="item-snippet">
                        {snippet(n.content)}
                      </Typography.Text>
                    ) : null}
                    <Typography.Text type="secondary" className="item-time">
                      {shortTime(n.publishTime)}
                    </Typography.Text>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>
      </Spin>

      <div className="notice-foot">
        <Button
          type="link"
          size="small"
          onClick={() => {
            setOpen(false)
            void navigate('/personal/notice')
          }}
        >
          {t('app.notice.viewAll')} <RightOutlined />
        </Button>
      </div>
    </div>
  )

  return (
    <>
      {/* container 去内边距:面板自带分区留白,默认 padding 会让列表两侧双重缝 */}
      <Popover open={open} onOpenChange={onOpenChange} trigger="click" placement="bottomRight" arrow={false} styles={{ container: { padding: 0 } }} content={panel}>
        <Badge count={unread} size="small" offset={[-2, 4]}>
          <Button type="text" aria-label={t('app.notice.title')} icon={<BellOutlined />} />
        </Badge>
      </Popover>

      <Modal open={showNotice} onCancel={() => setShowNotice(false)} footer={null} title={viewNotice?.title || t('notice.detailTitle')} width={640}>
        <MarkdownView value={viewNotice?.content} />
      </Modal>
    </>
  )
}

// web/src/layouts/NoticeBell.vue
<script setup lang="ts">
// 顶栏消息通知铃铛。富面板(n-popover):无页签单列表 + 正文弹层。
// 未读=圆点+加粗+淡主色底,已读=整行变淡;"读没读"是过滤器不是分类,不做成页签(筛选在个人通知页)。
// 未读数每 30s 轮询(设计 §4 消息中心轮询模型);面板展开时拉取列表。
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import {
  NPopover, NBadge, NButton, NTag, NEllipsis, NScrollbar, NText, NEmpty, NModal, NSpin,
  useMessage,
} from 'naive-ui'
import { Icon } from '@iconify/vue'
import { useIntervalFn } from '@vueuse/core'
import { useI18n } from 'vue-i18n'
import { noticeApi } from '@/api'
import { noticeBus } from '@/composables/useRealtime'
import { NoticeType, type NoticeMineItem } from '@/types/api'
import MarkdownView from '@/components/MarkdownEditor/MarkdownView.vue'
import { translateError } from '@/utils/error'

const { t } = useI18n()
const router = useRouter()
const message = useMessage()

const unread = ref(0)
const items = ref<NoticeMineItem[]>([])
const loading = ref(false)

async function fetchUnread() {
  try {
    unread.value = await noticeApi.unreadCount()
  } catch {
    /* 轮询失败静默,下次自愈 */
  }
}
// 无页签单列表:恒拉最近一页混排,未读靠条目样式强调;筛选能力在"查看全部"的个人通知页。
async function fetchList() {
  loading.value = true
  try {
    const { items: list } = await noticeApi.mine({ page: 1, pageSize: 10 })
    items.value = list
  } catch {
    items.value = []
  } finally {
    loading.value = false
  }
}
function onShow(show: boolean) {
  if (show) fetchList()
}

// 正文弹层:内容随列表取回,直接渲染(Markdown,不能纯文本直出);点条目即标记已读。
const showNotice = ref(false)
const viewNotice = ref<NoticeMineItem | null>(null)
async function openNotice(item: NoticeMineItem) {
  viewNotice.value = item
  showNotice.value = true
  if (item.isRead) return
  try {
    await noticeApi.markRead(item.id)
    item.isRead = true
    await fetchUnread()
  } catch (e) {
    message.error(translateError(e))
  }
}
async function markAllRead() {
  try {
    await noticeApi.markAllRead()
    await Promise.all([fetchUnread(), fetchList()])
  } catch (e) {
    message.error(translateError(e))
  }
}
function viewAll() {
  router.push('/personal/notice')
}

// 类型 → 标签色/文案。新增类型在此补一行即可。
const tagType = (ty: NoticeType) =>
  ty === NoticeType.Announcement ? 'warning' : ty === NoticeType.Message ? 'success' : 'info'
const typeLabel = (ty: NoticeType) =>
  ty === NoticeType.Announcement ? t('notice.typeAnnouncement')
    : ty === NoticeType.Message ? t('notice.typeMessage')
      : t('notice.typeNotice')

// 正文摘要:去掉常见 Markdown 记号,压空白,截断。ponytail: 正则够用,要精准渲染再引 md 解析。
function snippet(md?: string | null) {
  if (!md) return ''
  const s = md
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '') // 图片
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // 链接留文字
    .replace(/[#>*_`~-]/g, '') // 记号
    .replace(/\s+/g, ' ')
    .trim()
  return s.length > 60 ? s.slice(0, 60) + '…' : s
}
// 短时间戳(本地,YYYY-MM-DD HH:mm)。ponytail: 够看,要"3 分钟前"再引 formatTimeAgo。
const shortTime = (iso: string) => (iso ?? '').replace('T', ' ').slice(0, 16)

// 双腿:实时推送到达即刷新未读(SignalR 开启时,即时);30s 轮询兜底(实时关闭/连接掉线时)。
// VueUse 的 useEventBus.on 在组件卸载时自动退订。
noticeBus.on(() => { fetchUnread() })
useIntervalFn(fetchUnread, 30000)
fetchUnread()
</script>

<template>
  <n-popover trigger="click" placement="bottom-end" :show-arrow="false" style="padding: 0" @update:show="onShow">
    <template #trigger>
      <n-badge :value="unread" :max="99" :show="unread > 0">
        <n-button quaternary circle :aria-label="t('app.notice.title')">
          <Icon icon="lucide:bell" :width="18" />
        </n-button>
      </n-badge>
    </template>

    <div class="notice-panel">
      <div class="notice-head">
        <span class="notice-title">{{ t('app.notice.title') }}</span>
        <n-button text size="tiny" :disabled="unread === 0" @click="markAllRead">
          <template #icon><Icon icon="lucide:check-check" :width="15" /></template>
          {{ t('app.notice.markAllRead') }}
        </n-button>
      </div>

      <n-spin :show="loading">
        <n-scrollbar style="max-height: 360px">
          <div v-if="items.length === 0" class="notice-empty">
            <n-empty :description="t('app.notice.empty')" size="small" />
          </div>
          <ul v-else class="notice-list">
            <li v-for="n in items" :key="n.id" :class="['notice-item', n.isRead ? 'read' : 'unread']" @click="openNotice(n)">
              <span v-if="!n.isRead" class="dot" />
              <div class="notice-body">
                <div class="line1">
                  <n-tag :type="tagType(n.type)" size="tiny" :bordered="false" round>{{ typeLabel(n.type) }}</n-tag>
                  <n-ellipsis class="item-title" :class="{ unread: !n.isRead }">{{ n.title }}</n-ellipsis>
                </div>
                <n-text v-if="snippet(n.content)" depth="3" class="item-snippet">{{ snippet(n.content) }}</n-text>
                <n-text depth="3" class="item-time">{{ shortTime(n.publishTime) }}</n-text>
              </div>
            </li>
          </ul>
        </n-scrollbar>
      </n-spin>

      <div class="notice-foot">
        <n-button text size="small" @click="viewAll">
          {{ t('app.notice.viewAll') }}
          <template #icon><Icon icon="lucide:arrow-right" :width="14" /></template>
        </n-button>
      </div>
    </div>
  </n-popover>

  <n-modal
    v-model:show="showNotice"
    preset="card"
    :title="viewNotice?.title || t('notice.detailTitle')"
    style="width: 640px; max-width: 92vw"
  >
    <MarkdownView :value="viewNotice?.content" />
  </n-modal>
</template>

<style scoped>
.notice-panel {
  width: 360px;
  max-width: 92vw;
}
.notice-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px 4px;
}
.notice-title {
  font-weight: 600;
  font-size: var(--font-size-md);
}
.notice-empty {
  padding: 32px 0;
}
.notice-list {
  margin: 0;
  padding: 0;
  list-style: none;
}
.notice-item {
  position: relative;
  display: flex;
  gap: 8px;
  padding: 12px 16px;
  cursor: pointer;
  border-top: 1px solid var(--n-divider-color, rgba(128, 128, 128, 0.15));
  transition: background-color 0.2s;
}
.notice-item:hover {
  background-color: rgba(128, 128, 128, 0.08);
}
/* 未读:整行淡主色底(明暗主题都成立);已读:整行变淡 */
.notice-item.unread {
  background-color: color-mix(in srgb, var(--color-primary) 4%, transparent);
}
.notice-item.unread:hover {
  background-color: color-mix(in srgb, var(--color-primary) 9%, transparent);
}
.notice-item.read {
  opacity: 0.55;
}
.dot {
  position: absolute;
  left: 6px;
  top: 18px;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--color-primary, #d03050);
}
.notice-body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.line1 {
  display: flex;
  align-items: center;
  gap: 6px;
  min-width: 0;
}
.item-title {
  flex: 1;
  min-width: 0;
  font-size: var(--font-size-sm);
}
.item-title.unread {
  font-weight: 600;
}
.item-snippet {
  font-size: 12px;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.item-time {
  font-size: 11px;
}
.notice-foot {
  display: flex;
  justify-content: center;
  padding: 8px;
  border-top: 1px solid var(--n-divider-color, rgba(128, 128, 128, 0.15));
}
</style>
