// web-react/src/layouts/SettingsDrawer.tsx
import { type ReactNode } from 'react'
import { App, Button, ColorPicker, Divider, Drawer, Input, Popconfirm, Segmented, Select, Switch, Tabs } from 'antd'
import { CheckOutlined, CopyOutlined, DesktopOutlined, MoonOutlined, ReloadOutlined, SunOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { useAppStore, type Density, type FormStyle, type PageTransition, type ThemeScheme } from '@/stores/app'
import { ACCENTS } from '@/theme/accents'
import { LayoutModeCards } from './LayoutModeCards'
import './settings-drawer.css'

// 设置项行:左标签 + 右控件。整行 role=group + aria-label,读屏聚焦控件时能读到设置名。单一使用者,内联不单开文件。
function SettingRow({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="setting-row" role="group" aria-label={label}>
      <span className="setting-row-label">{label}</span>
      <div className="setting-row-ctl">{children}</div>
    </div>
  )
}

/**
 * 设置抽屉(对齐 Vue SettingsDrawer.vue)。三 tab:外观(主题模式/主色/密度)、布局(布局模式卡片 + 界面开关)、
 * 通用(水印 + 表单形态)。所有控件都接了生效的壳(布局模式→D2a 壳、水印/fixedHeader/pageTransition/breadcrumb 均已接线)。
 * 「复制配置」仅 DEV 显示:导出当前外观值,粘回 stores/app.ts 的 DEFAULTS 即为消费者的新默认。
 */
export function SettingsDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const themeScheme = useAppStore((s) => s.themeScheme)
  const accent = useAppStore((s) => s.accent)
  const density = useAppStore((s) => s.density)
  const showBreadcrumb = useAppStore((s) => s.showBreadcrumb)
  const showTabs = useAppStore((s) => s.showTabs)
  const fixedHeader = useAppStore((s) => s.fixedHeader)
  const pageTransition = useAppStore((s) => s.pageTransition)
  const grayscale = useAppStore((s) => s.grayscale)
  const collapsed = useAppStore((s) => s.collapsed)
  const watermark = useAppStore((s) => s.watermark)
  const watermarkText = useAppStore((s) => s.watermarkText)
  const formStyle = useAppStore((s) => s.formStyle)
  const setThemeScheme = useAppStore((s) => s.setThemeScheme)
  const setAccent = useAppStore((s) => s.setAccent)
  const setDensity = useAppStore((s) => s.setDensity)
  const setSetting = useAppStore((s) => s.setSetting)
  const toggleCollapsed = useAppStore((s) => s.toggleCollapsed)
  const resetSettings = useAppStore((s) => s.resetSettings)

  // 「复制配置」是给消费者 fork 后改 DEFAULTS 用的开发期动作,不该出现在终端管理员的设置里 —— 仅 DEV 显示。
  const showCopyConfig = import.meta.env.DEV && typeof navigator !== 'undefined' && !!navigator.clipboard
  async function copyConfig() {
    await navigator.clipboard.writeText(JSON.stringify(useAppStore.getState().exportSettings(), null, 2))
    message.success(t('settings.configCopied'))
  }

  const appearance = (
    <div className="settings-pane">
      <Divider titlePlacement="start">{t('settings.themeMode')}</Divider>
      <Segmented
        block
        value={themeScheme}
        onChange={(v) => setThemeScheme(v as ThemeScheme)}
        options={[
          { value: 'light', label: t('app.light'), icon: <SunOutlined /> },
          { value: 'dark', label: t('app.dark'), icon: <MoonOutlined /> },
          { value: 'auto', label: t('settings.auto'), icon: <DesktopOutlined /> },
        ]}
      />

      <Divider titlePlacement="start">{t('settings.themeColor')}</Divider>
      <div className="accent-dots">
        {ACCENTS.map((c) => (
          <button
            key={c}
            type="button"
            className={`accent-dot${accent === c ? ' on' : ''}`}
            style={{ background: c }}
            aria-label={`${t('settings.themeColor')} ${c}`}
            aria-pressed={accent === c}
            onClick={() => setAccent(c)}
          >
            {accent === c ? <CheckOutlined className="accent-tick" /> : null}
          </button>
        ))}
      </div>
      <ColorPicker
        value={accent}
        format="hex"
        disabledAlpha
        presets={[{ label: t('settings.custom'), colors: [...ACCENTS] }]}
        onChange={(_, css) => setAccent(css)}
      />

      <Divider titlePlacement="start">{t('app.density')}</Divider>
      <Segmented
        block
        value={density}
        onChange={(v) => setDensity(v as Density)}
        options={[
          { value: 'comfortable', label: t('app.comfortable') },
          { value: 'compact', label: t('app.compact') },
        ]}
      />
    </div>
  )

  const layout = (
    <div className="settings-pane">
      <Divider titlePlacement="start">{t('settings.layout')}</Divider>
      <LayoutModeCards />

      <Divider titlePlacement="start">{t('settings.interface')}</Divider>
      <SettingRow label={t('settings.showBreadcrumb')}>
        <Switch size="small" checked={showBreadcrumb} onChange={(v) => setSetting('showBreadcrumb', v)} />
      </SettingRow>
      <SettingRow label={t('settings.showTabs')}>
        <Switch size="small" checked={showTabs} onChange={(v) => setSetting('showTabs', v)} />
      </SettingRow>
      <SettingRow label={t('settings.fixedHeader')}>
        <Switch size="small" checked={fixedHeader} onChange={(v) => setSetting('fixedHeader', v)} />
      </SettingRow>
      <SettingRow label={t('settings.pageTransition')}>
        <Select
          size="small"
          style={{ width: 120 }}
          value={pageTransition}
          onChange={(v) => setSetting('pageTransition', v as PageTransition)}
          options={[
            { value: 'none', label: t('settings.transitionNone') },
            { value: 'fade', label: t('settings.transitionFade') },
            { value: 'fade-slide', label: t('settings.transitionFadeSlide') },
          ]}
        />
      </SettingRow>
      <SettingRow label={t('settings.grayscale')}>
        <Switch size="small" checked={grayscale} onChange={(v) => setSetting('grayscale', v)} />
      </SettingRow>
      <SettingRow label={t('app.collapse')}>
        <Switch size="small" checked={collapsed} onChange={() => toggleCollapsed()} />
      </SettingRow>
    </div>
  )

  const general = (
    <div className="settings-pane">
      <Divider titlePlacement="start">{t('settings.watermark')}</Divider>
      <SettingRow label={t('settings.watermark')}>
        <Switch size="small" checked={watermark} onChange={(v) => setSetting('watermark', v)} />
      </SettingRow>
      {watermark ? (
        <SettingRow label={t('settings.watermarkText')}>
          <Input
            size="small"
            style={{ width: 140 }}
            value={watermarkText}
            placeholder={t('settings.watermarkPlaceholder')}
            onChange={(e) => setSetting('watermarkText', e.target.value)}
          />
        </SettingRow>
      ) : null}

      <Divider titlePlacement="start">{t('settings.formStyle')}</Divider>
      {/* FormContainer 全局形态:所有 CRUD 表单弹层一键在弹窗/抽屉间切换 */}
      <Segmented
        block
        value={formStyle}
        onChange={(v) => setSetting('formStyle', v as FormStyle)}
        options={[
          { value: 'modal', label: t('settings.formStyleModal') },
          { value: 'drawer', label: t('settings.formStyleDrawer') },
        ]}
      />
    </div>
  )

  return (
    <Drawer
      title={t('settings.title')}
      placement="right"
      open={open}
      onClose={onClose}
      styles={{ section: { width: 'min(400px, 90vw)' } }}
      footer={
        <div className="settings-footer">
          {showCopyConfig ? (
            <Button block icon={<CopyOutlined />} onClick={copyConfig}>
              {t('settings.copyConfig')}
            </Button>
          ) : null}
          <Popconfirm
            title={t('settings.resetConfirm')}
            onConfirm={resetSettings}
            okText={t('common.confirm')}
            cancelText={t('common.cancel')}
          >
            <Button block icon={<ReloadOutlined />}>
              {t('common.reset')}
            </Button>
          </Popconfirm>
        </div>
      }
    >
      <Tabs
        centered
        items={[
          { key: 'appearance', label: t('settings.tabAppearance'), children: appearance },
          { key: 'layout', label: t('settings.tabLayout'), children: layout },
          { key: 'general', label: t('settings.tabGeneral'), children: general },
        ]}
      />
    </Drawer>
  )
}

// web/src/layouts/SettingsDrawer.vue
<script setup lang="ts">
import {
  NDrawer,
  NDrawerContent,
  NTabs,
  NTabPane,
  NDivider,
  NRadioGroup,
  NRadioButton,
  NColorPicker,
  NSwitch,
  NSelect,
  NInput,
  NPopconfirm,
  NButton,
} from 'naive-ui'
import { computed } from 'vue'
import { Icon } from '@iconify/vue'
import { useI18n } from 'vue-i18n'
import { useMessage } from 'naive-ui'
import { useWindowSize, useClipboard } from '@vueuse/core'
import { useAppStore } from '@/stores/app'
import { ACCENTS } from '@/theme/accents'
import SettingRow from './SettingRow.vue'
import LayoutModeCards from './LayoutModeCards.vue'

const show = defineModel<boolean>('show', { default: false })
const app = useAppStore()
const { t } = useI18n()
const message = useMessage()
const { copy, isSupported } = useClipboard()

// 复制当前外观配置(消费者 fork 后粘回 stores/app.ts 的 DEFAULTS 即为新默认)。
async function copyConfig() {
  await copy(JSON.stringify(app.exportSettings(), null, 2))
  message.success(t('settings.configCopied'))
}

// 窄屏不溢出:抽屉宽度取 min(400, 90vw)。加宽给布局卡片两列留出余量。
const { width } = useWindowSize()
const drawerWidth = computed(() => Math.min(400, Math.round(width.value * 0.9)))

// computed:t() 一次求值不随语言切换更新,故包 computed 让下拉标签跟随 locale。
const transitionOptions = computed(() => [
  { label: t('settings.transitionNone'), value: 'none' },
  { label: t('settings.transitionFade'), value: 'fade' },
  { label: t('settings.transitionFadeSlide'), value: 'fade-slide' },
])
</script>

<template>
  <n-drawer v-model:show="show" :width="drawerWidth" placement="right">
    <n-drawer-content :title="t('settings.title')" closable :native-scrollbar="false">
      <n-tabs type="segment" size="small" animated class="tabs">
        <!-- 外观 -->
        <n-tab-pane name="appearance" :tab="t('settings.tabAppearance')">
          <n-divider title-placement="left">{{ t('settings.themeMode') }}</n-divider>
          <n-radio-group v-model:value="app.themeScheme" size="small" class="seg">
            <n-radio-button value="light">
              <Icon icon="ph:sun" class="ri" />{{ t('app.light') }}
            </n-radio-button>
            <n-radio-button value="dark">
              <Icon icon="ph:moon-stars" class="ri" />{{ t('app.dark') }}
            </n-radio-button>
            <n-radio-button value="auto">
              <Icon icon="ph:circle-half" class="ri" />{{ t('settings.auto') }}
            </n-radio-button>
          </n-radio-group>

          <n-divider title-placement="left">{{ t('settings.themeColor') }}</n-divider>
          <div class="accents">
            <button
              v-for="c in ACCENTS"
              :key="c"
              type="button"
              class="dot"
              :class="{ on: app.accent === c }"
              :style="{ background: c }"
              :aria-label="`${t('settings.themeColor')} ${c}`"
              :aria-pressed="app.accent === c"
              @click="app.setAccent(c)"
            >
              <Icon v-if="app.accent === c" icon="ph:check-bold" class="tick" />
            </button>
          </div>
          <n-color-picker
            :value="app.accent"
            :modes="['hex']"
            :show-alpha="false"
            :swatches="[...ACCENTS]"
            @update:value="app.setAccent"
          />

          <n-divider title-placement="left">{{ t('app.density') }}</n-divider>
          <n-radio-group v-model:value="app.density" size="small" class="seg">
            <n-radio-button value="comfortable">{{ t('app.comfortable') }}</n-radio-button>
            <n-radio-button value="compact">{{ t('app.compact') }}</n-radio-button>
          </n-radio-group>
        </n-tab-pane>

        <!-- 布局 -->
        <n-tab-pane name="layout" :tab="t('settings.tabLayout')">
          <n-divider title-placement="left">{{ t('settings.layout') }}</n-divider>
          <LayoutModeCards />

          <n-divider title-placement="left">{{ t('settings.interface') }}</n-divider>
          <SettingRow :label="t('settings.showBreadcrumb')">
            <n-switch v-model:value="app.showBreadcrumb" size="small" />
          </SettingRow>
          <SettingRow :label="t('settings.showTabs')">
            <n-switch v-model:value="app.showTabs" size="small" />
          </SettingRow>
          <SettingRow :label="t('settings.fixedHeader')">
            <n-switch v-model:value="app.fixedHeader" size="small" />
          </SettingRow>
          <SettingRow :label="t('settings.pageTransition')">
            <n-select
              v-model:value="app.pageTransition"
              :options="transitionOptions"
              size="small"
              style="width: 120px"
            />
          </SettingRow>
          <SettingRow :label="t('settings.grayscale')">
            <n-switch v-model:value="app.grayscale" size="small" />
          </SettingRow>
          <SettingRow :label="t('app.collapse')">
            <n-switch v-model:value="app.collapsed" size="small" />
          </SettingRow>
        </n-tab-pane>

        <!-- 通用 -->
        <n-tab-pane name="general" :tab="t('settings.tabGeneral')">
          <n-divider title-placement="left">{{ t('settings.watermark') }}</n-divider>
          <SettingRow :label="t('settings.watermark')">
            <n-switch v-model:value="app.watermark" size="small" />
          </SettingRow>
          <SettingRow v-if="app.watermark" :label="t('settings.watermarkText')">
            <n-input
              v-model:value="app.watermarkText"
              size="small"
              :placeholder="t('settings.watermarkPlaceholder')"
              style="width: 140px"
            />
          </SettingRow>

          <n-divider title-placement="left">{{ t('settings.formStyle') }}</n-divider>
          <!-- FormContainer 全局形态:所有 CRUD 表单弹层一键在弹窗/抽屉间切换 -->
          <n-radio-group v-model:value="app.formStyle" size="small" class="seg">
            <n-radio-button value="modal">{{ t('settings.formStyleModal') }}</n-radio-button>
            <n-radio-button value="drawer">{{ t('settings.formStyleDrawer') }}</n-radio-button>
          </n-radio-group>
        </n-tab-pane>
      </n-tabs>

      <template #footer>
        <div class="footer-actions">
          <n-button v-if="isSupported" block tertiary @click="copyConfig">
            <Icon icon="ph:clipboard-text" class="ri" />{{ t('settings.copyConfig') }}
          </n-button>
          <n-popconfirm @positive-click="app.resetSettings()">
            <template #trigger>
              <n-button block secondary>
                <Icon icon="ph:arrow-counter-clockwise" class="ri" />{{ t('common.reset') }}
              </n-button>
            </template>
            {{ t('settings.resetConfirm') }}
          </n-popconfirm>
        </div>
      </template>
    </n-drawer-content>
  </n-drawer>
</template>

<style scoped>
.tabs {
  height: 100%;
}
.footer-actions {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}
.ri {
  margin-right: 5px;
  font-size: 15px;
}

/* 满宽三等分分段控件(主题模式 / 密度) */
.seg {
  display: flex;
  width: 100%;
}
.seg :deep(.n-radio-button) {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 精致色板 */
.accents {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 10px;
  margin-bottom: 12px;
}
.dot {
  position: relative;
  width: 100%;
  max-width: 30px;
  margin: 0 auto;
  aspect-ratio: 1;
  padding: 0;
  border: none;
  border-radius: 50%;
  cursor: pointer;
  box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.08);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}
.dot:hover {
  transform: scale(1.12);
}
.dot.on {
  transform: scale(1.1);
  box-shadow: 0 0 0 2px var(--color-bg-container), 0 0 0 4px var(--color-primary);
}
.tick {
  color: #fff;
  font-size: 14px;
  filter: drop-shadow(0 0 1px rgba(0, 0, 0, 0.35));
}
</style>
