// web-react/src/views/dashboard/workbench.tsx
// 系统工作台首页(builtin 应用,菜单 component=dashboard/workbench)。欢迎横幅 + 4 统计卡 + 趋势/分布两图。
// 统计取不到不糊用户一脸红:catch 静默 → 计数显 —、图空,页面其余照常。图 option 纯逻辑抽 chartOptions.ts(变异钉)。
import { useEffect, useMemo, useState } from 'react'
import { Card, Col, Row } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import { Chart } from '@/components/Chart'
import { useUserStore } from '@/stores/user'
import { useAppStore } from '@/stores/app'
import { btnGrad } from '@/theme/mix'
import { dashboardApi } from '@/api'
import type { DashboardSummary } from '@/types/api'
import { buildLineOption, buildPieOption, num } from './chartOptions'
import './dashboard.css'

export default function Workbench() {
  const { t } = useTranslation()
  const userInfo = useUserStore((s) => s.userInfo)
  const accent = useAppStore((s) => s.accent)
  const [summary, setSummary] = useState<DashboardSummary | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    dashboardApi
      .summary()
      .then(setSummary)
      .catch(() => {}) // 首页不因一张统计图挂了就报错糊脸
      .finally(() => setLoading(false))
  }, [])

  const stats = [
    { key: 'roles', icon: 'ph:shield-duotone', value: num(summary?.roles), color: 'var(--color-primary)' },
    { key: 'users', icon: 'ph:users-duotone', value: num(summary?.users), color: 'var(--color-success)' },
    { key: 'perms', icon: 'ph:key-duotone', value: num(summary?.perms), color: 'var(--color-warning)' },
    { key: 'online', icon: 'ph:broadcast-duotone', value: num(summary?.onlineSessions), color: 'var(--color-danger)' },
  ]

  const trendOption = useMemo(
    () => buildLineOption(summary?.trendDays ?? [], [
      { name: t('workbench.trendLogins'), data: summary?.trendLogins ?? [] },
      { name: t('workbench.trendActive'), data: summary?.trendActiveUsers ?? [] },
    ]),
    [summary, t],
  )
  // 资源分布就是前三个计数,不必让后端再返一份
  const distributionOption = useMemo(
    () => buildPieOption([
      { name: t('workbench.roles'), value: summary?.roles ?? 0 },
      { name: t('workbench.users'), value: summary?.users ?? 0 },
      { name: t('workbench.perms'), value: summary?.perms ?? 0 },
    ]),
    [summary, t],
  )

  return (
    <div className="dash-view">
      <div className="dash-banner">
        <div className="dash-avatar" style={{ background: btnGrad(accent) }}>
          <AppIcon icon="ph:user" size={26} style={{ color: '#fff' }} />
        </div>
        <div>
          <div className="dash-hi">{t('workbench.welcome', { name: userInfo?.name ?? '' })}</div>
          <div className="dash-tip">{t('workbench.subtitle')}</div>
        </div>
      </div>

      <Row gutter={[16, 16]}>
        {stats.map((s) => (
          <Col key={s.key} xs={24} sm={12} lg={6}>
            <Card>
              <div className="dash-stat">
                <div className="dash-stat-ico" style={{ color: s.color }}>
                  <AppIcon icon={s.icon} size={28} />
                </div>
                <div>
                  <div className="dash-stat-val tabular">{s.value}</div>
                  <div className="dash-stat-label">{t(`workbench.${s.key}`)}</div>
                </div>
              </div>
            </Card>
          </Col>
        ))}
      </Row>

      <Row gutter={[16, 16]}>
        <Col xs={24} lg={12}>
          <Card title={t('workbench.trendTitle')}>
            <Chart option={trendOption} loading={loading} height={300} />
          </Card>
        </Col>
        <Col xs={24} lg={12}>
          <Card title={t('workbench.distributionTitle')}>
            <Chart option={distributionOption} loading={loading} height={300} />
          </Card>
        </Col>
      </Row>
    </div>
  )
}

// web/src/views/dashboard/workbench.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { NGrid, NGi, NCard, NSpin } from 'naive-ui'
import { Icon } from '@iconify/vue'
import { useI18n } from 'vue-i18n'
import { useUserStore } from '@/stores/user'
import { useAppStore } from '@/stores/app'
import { btnGrad } from '@/theme/mix'
import { dashboardApi } from '@/api'
import type { DashboardSummary } from '@/types/api'
import LineChart from '@/components/Chart/LineChart.vue'
import PieChart from '@/components/Chart/PieChart.vue'

const { t } = useI18n()
const user = useUserStore()
const app = useAppStore()

const avatarStyle = computed(() => ({ background: btnGrad(app.accent) }))

const summary = ref<DashboardSummary | null>(null)
const loading = ref(true)

onMounted(async () => {
  try {
    summary.value = await dashboardApi.summary()
  } catch {
    // 首页不该因为一张统计图挂了就糊用户一脸红:统计取不到就显示 —,页面其余部分照常可用。
  } finally {
    loading.value = false
  }
})

/** 计数未到位时显示 —,而不是先闪个 0 再跳到真值。 */
function num(v: number | undefined) {
  return v === undefined ? '—' : v
}

const stats = computed(() => [
  { key: 'roles', icon: 'lucide:shield', value: num(summary.value?.roles), color: 'var(--color-primary)' },
  { key: 'users', icon: 'lucide:users', value: num(summary.value?.users), color: 'var(--color-success)' },
  { key: 'perms', icon: 'lucide:key', value: num(summary.value?.perms), color: 'var(--color-warning)' },
  { key: 'online', icon: 'lucide:radio-tower', value: num(summary.value?.onlineSessions), color: 'var(--color-danger)' },
])

const trendDays = computed(() => summary.value?.trendDays ?? [])
const trendSeries = computed(() => [
  { name: t('workbench.trendLogins'), data: summary.value?.trendLogins ?? [] },
  { name: t('workbench.trendActive'), data: summary.value?.trendActiveUsers ?? [] },
])
// 资源分布就是前三个计数,不必让后端再返一份
const distribution = computed(() => [
  { name: t('workbench.roles'), value: summary.value?.roles ?? 0 },
  { name: t('workbench.users'), value: summary.value?.users ?? 0 },
  { name: t('workbench.perms'), value: summary.value?.perms ?? 0 },
])
</script>

<template>
  <div class="view">
    <!-- 欢迎横幅(英雄区:btnGrad 头像)-->
    <div class="banner">
      <div class="avatar" :style="avatarStyle">
        <Icon icon="lucide:user" :width="26" color="#fff" />
      </div>
      <div>
        <div class="hi">{{ t('workbench.welcome', { name: user.userInfo?.name ?? '' }) }}</div>
        <div class="tip">{{ t('workbench.subtitle') }}</div>
      </div>
    </div>

    <n-grid :cols="'1 s:2 l:4'" responsive="screen" :x-gap="16" :y-gap="16">
      <n-gi v-for="s in stats" :key="s.key">
        <n-card :bordered="true">
          <div class="stat">
            <div class="stat-ico" :style="{ color: s.color }"><Icon :icon="s.icon" :width="28" /></div>
            <div>
              <div class="stat-val tabular">{{ s.value }}</div>
              <div class="stat-label">{{ t(`workbench.${s.key}`) }}</div>
            </div>
          </div>
        </n-card>
      </n-gi>
    </n-grid>

    <n-grid :cols="'1 l:2'" responsive="screen" :x-gap="16" :y-gap="16">
      <n-gi>
        <n-card :title="t('workbench.trendTitle')" :bordered="true">
          <n-spin :show="loading">
            <LineChart :categories="trendDays" :series="trendSeries" />
          </n-spin>
        </n-card>
      </n-gi>
      <n-gi>
        <n-card :title="t('workbench.distributionTitle')" :bordered="true">
          <n-spin :show="loading">
            <PieChart :data="distribution" />
          </n-spin>
        </n-card>
      </n-gi>
    </n-grid>
  </div>
</template>

<style scoped>
.view {
  display: flex;
  flex-direction: column;
  gap: var(--gap-card);
}
.banner {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 24px;
  border-radius: var(--radius-lg);
  background: var(--color-primary-light);
}
.avatar {
  width: 52px;
  height: 52px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.hi {
  font-size: var(--font-size-lg);
  font-weight: 600;
  color: var(--color-text-primary);
}
.tip {
  color: var(--color-text-secondary);
  margin-top: 4px;
}
.stat {
  display: flex;
  align-items: center;
  gap: 16px;
}
/* 图标底盘:取当前语义色 12% 作浅底圆角,呼应 banner 头像,避免图标"裸浮" */
.stat-ico {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  display: flex;
  align-items: center;
  justify-content: center;
  background: color-mix(in srgb, currentColor 12%, transparent);
}
.stat-val {
  font-size: 28px;
  font-weight: 700;
  color: var(--color-text-primary);
  line-height: 1.1;
}
.stat-label {
  color: var(--color-text-secondary);
  margin-top: 2px;
}
</style>
