// web/src/views/personal/password.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { NCard, NForm, NFormItem, NInput, NButton, NAlert, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import PasswordStrength from '@/components/PasswordStrength/index.vue'
import { personalApi, authApi } from '@/api'
import { useUserStore } from '@/stores/user'
import { useAuthStore } from '@/stores/auth'
import { resetRouter } from '@/router'
import { translateError } from '@/utils/error'

const { t } = useI18n()
const message = useMessage()
const router = useRouter()
const user = useUserStore()
const auth = useAuthStore()

const model = reactive({ oldPassword: '', newPassword: '', confirmPassword: '' })
const saving = ref(false)

async function submit() {
  if (!model.oldPassword || !model.newPassword) {
    message.warning(t('changePassword.required'))
    return
  }
  if (model.newPassword !== model.confirmPassword) {
    message.error(t('changePassword.mismatch'))
    return
  }
  saving.value = true
  try {
    await personalApi.updatePassword({ oldPassword: model.oldPassword, newPassword: model.newPassword })
    message.success(t('changePassword.changed'))
    // 改密后强制重新登录
    try {
      await authApi.logout()
    } catch { /* 尽力而为 */ }
    resetRouter()
    auth.reset()
    user.clear()
    router.replace('/login')
  } catch (e) {
    message.error(translateError(e))
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <n-card :bordered="true" :title="t('changePassword.title')" style="max-width: 460px">
    <n-alert v-if="user.userInfo?.mustChangePassword" type="warning" style="margin-bottom: 16px">
      {{ t('changePassword.forcedHint') }}
    </n-alert>
    <n-form :model="model" label-placement="top">
      <n-form-item :label="t('changePassword.oldPassword')">
        <n-input v-model:value="model.oldPassword" type="password" show-password-on="click" />
      </n-form-item>
      <n-form-item :label="t('changePassword.newPassword')">
        <n-input v-model:value="model.newPassword" type="password" show-password-on="click" />
      </n-form-item>
      <PasswordStrength :value="model.newPassword" />
      <n-form-item :label="t('changePassword.confirmPassword')">
        <n-input v-model:value="model.confirmPassword" type="password" show-password-on="click" @keyup.enter="submit" />
      </n-form-item>
      <n-button
        type="primary"
        block
        :loading="saving"
        :disabled="!model.oldPassword || !model.newPassword || !model.confirmPassword"
        @click="submit"
      >{{ t('common.submit') }}</n-button>
    </n-form>
  </n-card>
</template>

// web-react/src/views/personal/password.tsx
// 修改密码:old/new/confirm。复杂度不进 rules —— PasswordStrength 实时显示策略清单、后端强制(弱口令 passwordTooWeak),
// 再抄一份进 rules 就是第三处真源。成功后强制重新登录(logout → 清会话 → /login);mustChangePassword 时顶部提示。
// 本页在两处渲染:强改守卫(Protected.tsx)全屏、顶栏用户下拉壳内;自包含表单,两种上下文都可用。
import { useState } from 'react'
import { Alert, App, Button, Card, Form, Input } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { PasswordStrength } from '@/components/PasswordStrength'
import { authApi, personalApi } from '@/api'
import { useUserStore } from '@/stores/user'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'

interface PwForm {
  oldPassword: string
  newPassword: string
  confirmPassword: string
}

export default function PasswordPage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const navigate = useNavigate()
  const [form] = Form.useForm<PwForm>()
  const newPassword = Form.useWatch('newPassword', form) ?? ''
  const [saving, setSaving] = useState(false)
  const mustChange = useUserStore((s) => s.userInfo?.mustChangePassword ?? false)

  const submit = async () => {
    let v: PwForm
    try {
      v = await form.validateFields()
    } catch {
      return // 校验失败:antd 已在字段标红,静默返回(onClick 直调,须自吞 rejection 否则 unhandled)
    }
    setSaving(true)
    try {
      await personalApi.updatePassword({ oldPassword: v.oldPassword, newPassword: v.newPassword })
      message.success(t('changePassword.changed'))
      // 改密后强制重新登录:登出尽力而为,清会话 + 动态路由,回落 /login。
      try {
        await authApi.logout()
      } catch {
        /* 尽力而为 */
      }
      useAuthStore.getState().reset()
      useUserStore.getState().clear()
      navigate('/login', { replace: true })
    } catch (e) {
      message.error(translateError(e))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Card title={t('changePassword.title')} style={{ maxWidth: 460 }}>
      {mustChange && <Alert type="warning" showIcon style={{ marginBottom: 16 }} title={t('changePassword.forcedHint')} />}
      <Form form={form} layout="vertical" onFinish={submit} requiredMark={false}>
        <Form.Item name="oldPassword" label={t('changePassword.oldPassword')} rules={[{ required: true, message: t('changePassword.oldRequired') }]}>
          <Input.Password />
        </Form.Item>
        <Form.Item name="newPassword" label={t('changePassword.newPassword')} rules={[{ required: true, message: t('changePassword.newRequired') }]}>
          <Input.Password />
        </Form.Item>
        <PasswordStrength value={newPassword} />
        <Form.Item
          name="confirmPassword"
          label={t('changePassword.confirmPassword')}
          dependencies={['newPassword']}
          rules={[
            { required: true, message: t('changePassword.confirmRequired') },
            // 「等于新密码」antd 没内置规则,自写:与另一字段比对
            ({ getFieldValue }) => ({
              validator: (_, value) =>
                !value || value === getFieldValue('newPassword') ? Promise.resolve() : Promise.reject(new Error(t('changePassword.mismatch'))),
            }),
          ]}
        >
          <Input.Password />
        </Form.Item>
        <Button type="primary" block loading={saving} onClick={submit}>
          {t('common.submit')}
        </Button>
      </Form>
    </Card>
  )
}
