// web/src/views/personal/security.vue
<script setup lang="ts">
// 个人安全:TOTP 自助绑定/恢复入口(ADR 0006)。不进业务菜单,顶栏用户下拉进入。
import { useRouter } from 'vue-router'
import { NCard, NButton, NAlert, NSpace } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { useUserStore } from '@/stores/user'

const { t } = useI18n()
const router = useRouter()
const user = useUserStore()

function goBind(mode?: 'recovery') {
  const account = user.userInfo?.account
  router.push({
    path: '/mfa/bind',
    query: {
      ...(account ? { account } : {}),
      ...(mode === 'recovery' ? { mode: 'recovery' } : {}),
    },
  })
}
</script>

<template>
  <n-card :bordered="true" :title="t('personalSecurity.title')" style="max-width: 560px">
    <n-alert type="info" :bordered="false" style="margin-bottom: 16px">
      {{ t('personalSecurity.hint') }}
    </n-alert>
    <p class="sec-desc">{{ t('personalSecurity.bindDesc') }}</p>
    <n-space>
      <n-button type="primary" @click="goBind()">{{ t('personalSecurity.setupAuthenticator') }}</n-button>
      <n-button quaternary @click="goBind('recovery')">{{ t('personalSecurity.useRecovery') }}</n-button>
    </n-space>
    <p class="sec-note">{{ t('personalSecurity.note') }}</p>
  </n-card>
</template>

<style scoped>
.sec-desc { margin: 0 0 16px; color: var(--color-text-2, #666); line-height: 1.5; }
.sec-note { margin: 20px 0 0; font-size: 12px; color: var(--color-text-3, #999); line-height: 1.5; }
</style>

// web-react/src/views/personal/security.tsx
// 个人安全:TOTP 自助绑定/恢复入口(ADR 0006)。不进业务菜单,顶栏用户下拉进入。
import { Alert, Button, Card, Space, Typography } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { useUserStore } from '@/stores/user'

export default function SecurityPage() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const account = useUserStore((s) => s.userInfo?.account)

  const goBind = (mode?: 'recovery') => {
    const q = new URLSearchParams()
    if (account) q.set('account', account)
    if (mode === 'recovery') q.set('mode', 'recovery')
    const qs = q.toString()
    navigate(qs ? `/mfa/bind?${qs}` : '/mfa/bind')
  }

  return (
    <Card title={t('personalSecurity.title')} style={{ maxWidth: 560 }}>
      <Alert type="info" showIcon title={t('personalSecurity.hint')} style={{ marginBottom: 16 }} />
      <Typography.Paragraph type="secondary">{t('personalSecurity.bindDesc')}</Typography.Paragraph>
      <Space>
        <Button type="primary" onClick={() => goBind()}>{t('personalSecurity.setupAuthenticator')}</Button>
        <Button type="link" onClick={() => goBind('recovery')}>{t('personalSecurity.useRecovery')}</Button>
      </Space>
      <Typography.Paragraph type="secondary" style={{ marginTop: 20, marginBottom: 0, fontSize: 12 }}>
        {t('personalSecurity.note')}
      </Typography.Paragraph>
    </Card>
  )
}
