// web-react/src/views/workflow/monitor/index.tsx
// 流程监控。菜单 component 填 `workflow/monitor/index`。
// 参与筛选(发起人/办理人/抄送人)是业务过滤,不是数据权限;行点击进同一实例详情。
import { useCallback, useMemo } from 'react'
import { Button, Space, Tag } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type PageFetcher } from '@/components/DataTable'
import { UserSelect } from '@/components/UserSelect'
import { wfInstanceApi } from '@/api/workflow'
import { formatDateTime, instanceStatusColor, normalizeInstanceStatus } from '@/workflow/statusLabels'
import type { WfInstanceListItem } from '@/types/workflow'

/** 实例状态 1–5(与 statusLabels 的数字表同源)。 */
const STATUS_VALUES = [1, 2, 3, 4, 5] as const

export default function WfMonitorPage() {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const fetchMonitor: PageFetcher<WfInstanceListItem> = (q) =>
    wfInstanceApi.monitor({
      page: q.page,
      pageSize: q.pageSize,
      status: typeof q.status === 'number' ? q.status : undefined,
      businessKey: typeof q.businessKey === 'string' ? q.businessKey : undefined,
      starterUserId: typeof q.starterUserId === 'number' ? q.starterUserId : undefined,
      actorUserId: typeof q.actorUserId === 'number' ? q.actorUserId : undefined,
      ccUserId: typeof q.ccUserId === 'number' ? q.ccUserId : undefined,
    })

  const openDetail = useCallback(
    (r: WfInstanceListItem) => {
      if (r.id == null) return
      navigate(`/workflow/instance/${r.id}/detail`)
    },
    [navigate],
  )

  const columns = useMemo<ProColumns<WfInstanceListItem>[]>(
    () => [
      { title: t('workflow.monitor.definition'), dataIndex: 'definitionName', minWidth: 160, ellipsis: true, search: false },
      {
        title: t('workflow.monitor.version'), dataIndex: 'version', width: 80, align: 'center', search: false,
        render: (_, r) => (r.version == null ? '—' : `v${r.version}`),
      },
      {
        title: t('workflow.monitor.starter'), dataIndex: 'starterUserId', width: 140,
        // 裸返 UserSelect:value/onChange 由 pro-components cloneElement 注入,显式写会盖掉注入。
        formItemRender: () => <UserSelect placeholder={t('workflow.monitor.starter')} />,
        render: (_, r) => (r.starterUserId == null ? '—' : t('workflow.detail.userFallback', { id: r.starterUserId })),
      },
      {
        // 办理人/抄送人只作筛选条件,列表无对应列(一条实例可有多个办理人,摊不进一格)。
        title: t('workflow.monitor.actor'), dataIndex: 'actorUserId', hideInTable: true, hideInSetting: true,
        formItemRender: () => <UserSelect placeholder={t('workflow.monitor.actor')} />,
      },
      {
        title: t('workflow.monitor.cc'), dataIndex: 'ccUserId', hideInTable: true, hideInSetting: true,
        formItemRender: () => <UserSelect placeholder={t('workflow.monitor.cc')} />,
      },
      {
        title: t('workflow.monitor.businessKey'), dataIndex: 'businessKey', width: 140, ellipsis: true,
        render: (_, r) => r.businessKey || '—',
      },
      {
        title: t('common.status'), dataIndex: 'status', width: 96, valueType: 'select',
        fieldProps: {
          allowClear: true,
          options: STATUS_VALUES.map((v) => ({ label: t(`workflow.status.${normalizeInstanceStatus(v)}`), value: v })),
        },
        render: (_, r) => (
          <Tag color={instanceStatusColor(r.status)}>{t(`workflow.status.${normalizeInstanceStatus(r.status)}`)}</Tag>
        ),
      },
      {
        title: t('workflow.monitor.createTime'), dataIndex: 'createTime', width: 170, search: false,
        render: (_, r) => formatDateTime(r.createTime),
      },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 100, fixed: 'right',
        render: (_, r) => (
          <Space size={0}>
            <Button type="link" size="small" onClick={(e) => { e.stopPropagation(); openDetail(r) }}>
              {t('workflow.monitor.view')}
            </Button>
          </Space>
        ),
      },
    ],
    [t, openDetail],
  )

  return (
    <DataTable<WfInstanceListItem>
      columns={columns}
      fetcher={fetchMonitor}
      persistKey="workflow-monitor"
      rowKey="id"
      onRowClick={openDetail}
    />
  )
}

// web/src/views/workflow/monitor/index.vue
<script setup lang="ts">
/**
 * 流程监控。菜单 component 填 `workflow/monitor/index`。
 * 参与筛选是业务过滤,不是数据权限;行点击进同一详情。
 */
import { h } from 'vue'
import { useRouter } from 'vue-router'
import { NButton, NEmpty, NSpace, NTag, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn } from 'tenon-naive-pro-table'
import UserSelect from '@/components/UserSelect/index.vue'
import { wfInstanceApi } from '@/api/workflow'
import { translateError } from '@/utils/error'
import type { WfInstanceListItem, WfInstanceStatus } from '@/types/workflow'

const { t } = useI18n()
const router = useRouter()
const message = useMessage()

function openDetail(r: WfInstanceListItem) {
  if (r.id == null) return
  void router.push(`/workflow/instance/${r.id}/detail`)
}

function normalizeStatus(s: WfInstanceStatus | undefined): string {
  if (s == null) return 'unknown'
  const map: Record<number, string> = {
    1: 'running',
    2: 'approved',
    3: 'rejected',
    4: 'cancelled',
    5: 'terminated',
  }
  return map[s] ?? 'unknown'
}

function statusLabel(s: WfInstanceStatus | undefined): string {
  return t(`workflow.status.${normalizeStatus(s)}`, String(s ?? ''))
}

function statusType(s: WfInstanceStatus | undefined): 'default' | 'info' | 'success' | 'error' | 'warning' {
  const key = normalizeStatus(s)
  if (key === 'approved') return 'success'
  if (key === 'rejected' || key === 'terminated') return 'error'
  if (key === 'cancelled') return 'warning'
  if (key === 'running') return 'info'
  return 'default'
}

const columns: ProTableColumn<WfInstanceListItem>[] = [
  { key: 'definitionName', title: () => t('workflow.monitor.definition'), minWidth: 160, ellipsis: { tooltip: true } },
  {
    key: 'version',
    title: () => t('workflow.monitor.version'),
    width: 80,
    align: 'center',
    render: (r) => (r.version == null ? '—' : `v${r.version}`),
  },
  {
    key: 'starterUserId',
    title: () => t('workflow.monitor.starter'),
    width: 140,
    search: {
      key: 'starterUserId',
      label: () => t('workflow.monitor.starter'),
      render: ({ value, setValue, search }) =>
        h(UserSelect, {
          value: value as number | null,
          clearable: true,
          placeholder: t('workflow.monitor.starter'),
          'onUpdate:value': (v: number | null) => {
            setValue(v)
            search()
          },
        }),
    },
    render: (r) => (r.starterUserId == null ? '—' : t('workflow.detail.userFallback', { id: r.starterUserId })),
  },
  {
    key: 'actorUserId',
    title: () => t('workflow.monitor.actor'),
    width: 1,
    hideInTable: true,
    hideInSetting: true,
    search: {
      key: 'actorUserId',
      label: () => t('workflow.monitor.actor'),
      render: ({ value, setValue, search }) =>
        h(UserSelect, {
          value: value as number | null,
          clearable: true,
          placeholder: t('workflow.monitor.actor'),
          'onUpdate:value': (v: number | null) => {
            setValue(v)
            search()
          },
        }),
    },
  },
  {
    key: 'ccUserId',
    title: () => t('workflow.monitor.cc'),
    width: 1,
    hideInTable: true,
    hideInSetting: true,
    search: {
      key: 'ccUserId',
      label: () => t('workflow.monitor.cc'),
      render: ({ value, setValue, search }) =>
        h(UserSelect, {
          value: value as number | null,
          clearable: true,
          placeholder: t('workflow.monitor.cc'),
          'onUpdate:value': (v: number | null) => {
            setValue(v)
            search()
          },
        }),
    },
  },
  {
    key: 'businessKey',
    title: () => t('workflow.monitor.businessKey'),
    width: 140,
    ellipsis: { tooltip: true },
    search: { props: { clearable: true } },
    render: (r) => r.businessKey || '—',
  },
  {
    key: 'status',
    title: () => t('common.status'),
    width: 96,
    search: true,
    options: [
      { label: () => t('workflow.status.running'), value: 1 },
      { label: () => t('workflow.status.approved'), value: 2 },
      { label: () => t('workflow.status.rejected'), value: 3 },
      { label: () => t('workflow.status.cancelled'), value: 4 },
      { label: () => t('workflow.status.terminated'), value: 5 },
    ],
    render: (r) =>
      h(NTag, { size: 'small', type: statusType(r.status), bordered: false }, () => statusLabel(r.status)),
  },
  { key: 'createTime', title: () => t('workflow.monitor.createTime'), width: 170, format: 'datetime' },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 100,
    hideInSetting: true,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        h(
          NButton,
          {
            size: 'small',
            quaternary: true,
            type: 'primary',
            onClick: (e: MouseEvent) => {
              e.stopPropagation()
              openDetail(r)
            },
          },
          () => t('workflow.monitor.view'),
        ),
      ]),
  },
]
</script>

<template>
  <ProTable
    storage-key="workflow-monitor"
    row-key="id"
    :columns="columns"
    :fetcher="wfInstanceApi.monitor"
    @row-click="(row: WfInstanceListItem) => openDetail(row)"
    @error="(e) => message.error(translateError(e))"
  >
    <template #empty>
      <n-empty :description="t('workflow.monitor.empty')" size="small" />
    </template>
  </ProTable>
</template>
