// web/src/views/workflow/definition/components/WfFormDesigner.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  NButton, NCard, NFormItem, NInput, NInputNumber, NSelect, NSpace, NSwitch,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import {
  addWfFormField,
  createWfFormField,
  getWfFormFieldProp,
  moveWfFormField,
  removeWfFormField,
  updateWfFormFieldProp,
  validateWfFormSchema,
} from '@/workflow/formSchema'
import {
  WF_FORM_FIELD_TYPES,
  type WfFormField,
  type WfFormFieldType,
  type WfFormOption,
  type WfFormSchema,
} from '@/workflow/schema'

const props = defineProps<{ modelValue: WfFormSchema | null }>()
const emit = defineEmits<{ 'update:modelValue': [WfFormSchema | null] }>()
const { t } = useI18n()

const typeOptions = computed(() => WF_FORM_FIELD_TYPES.map((value) => ({
  value,
  label: t(`workflow.form.type.${value}`),
})))
const issues = computed(() => validateWfFormSchema(props.modelValue))
const schemaErrors = computed(() => [...new Set(
  issues.value.filter((issue) => issue.fieldIndex == null).map((issue) => t(`workflow.form.error.${issue.code}`)),
)])

function updateField(index: number, update: (field: WfFormField) => WfFormField) {
  if (!props.modelValue) return
  const fields = [...props.modelValue.fields]
  const field = fields[index]
  if (!field) return
  fields[index] = update(field)
  emit('update:modelValue', { version: 1, fields })
}

function updateProp(index: number, key: string, value: unknown) {
  const field = props.modelValue?.fields[index]
  if (!field) return
  updateField(index, (current) => updateWfFormFieldProp(current, key, value))
}

function prop(field: WfFormField, key: string): unknown {
  return getWfFormFieldProp(field, key)
}

function numberProp(field: WfFormField, key: string): number | null {
  const value = prop(field, key)
  return typeof value === 'number' ? value : null
}

function stringProp(field: WfFormField, key: string): string {
  const value = prop(field, key)
  return typeof value === 'string' ? value : ''
}

function booleanProp(field: WfFormField, key: string): boolean {
  return prop(field, key) === true
}

function options(field: WfFormField): WfFormOption[] {
  const value = prop(field, 'options')
  return Array.isArray(value) ? value : []
}

function updateOption(fieldIndex: number, optionIndex: number, patch: Partial<WfFormOption>) {
  const field = props.modelValue?.fields[fieldIndex]
  if (!field) return
  const next = options(field).map((option, index) => index === optionIndex ? { ...option, ...patch } : option)
  updateProp(fieldIndex, 'options', next)
}

function addOption(fieldIndex: number) {
  const field = props.modelValue?.fields[fieldIndex]
  if (!field) return
  const current = options(field)
  let n = current.length + 1
  while (current.some((option) => option.value === `option${n}`)) n += 1
  updateProp(fieldIndex, 'options', [...current, { label: `${t('workflow.form.option')} ${n}`, value: `option${n}` }])
}

function removeOption(fieldIndex: number, optionIndex: number) {
  const field = props.modelValue?.fields[fieldIndex]
  if (field) updateProp(fieldIndex, 'options', options(field).filter((_, index) => index !== optionIndex))
}

function changeType(index: number, type: WfFormFieldType) {
  const field = props.modelValue?.fields[index]
  if (!field) return
  updateField(index, () => ({ ...createWfFormField(type, field.key), label: field.label, required: field.required, placeholder: field.placeholder }))
}

function fieldErrors(index: number): string[] {
  return [...new Set(issues.value.filter((issue) => issue.fieldIndex === index).map((issue) => t(`workflow.form.error.${issue.code}`)))]
}

function addField(type: string) {
  if (WF_FORM_FIELD_TYPES.includes(type as WfFormFieldType)) emit('update:modelValue', addWfFormField(props.modelValue, type as WfFormFieldType))
}
</script>

<template>
  <div class="wf-form-designer">
    <div class="wf-form-toolbar">
      <n-select class="wf-form-type-select" :options="typeOptions" :value="null" :disabled="(modelValue?.fields.length ?? 0) >= 50" :placeholder="t('workflow.form.addField')" @update:value="addField" />
      <span class="wf-form-count">{{ modelValue?.fields.length ?? 0 }}/50</span>
    </div>
    <div v-if="schemaErrors.length" class="wf-form-errors">{{ schemaErrors.join('；') }}</div>

    <n-card v-for="(field, index) in modelValue?.fields ?? []" :key="index" size="small" class="wf-form-field">
      <template #header>
        <span>{{ field.label || field.key || t('workflow.form.unnamedField') }}</span>
      </template>
      <template #header-extra>
        <n-space :size="4">
          <n-button quaternary circle size="small" :disabled="index === 0" :aria-label="t('workflow.form.moveUp')" @click="emit('update:modelValue', moveWfFormField(modelValue!, index, -1))"><template #icon><AppIcon icon="ph:arrow-up" /></template></n-button>
          <n-button quaternary circle size="small" :disabled="index === modelValue!.fields.length - 1" :aria-label="t('workflow.form.moveDown')" @click="emit('update:modelValue', moveWfFormField(modelValue!, index, 1))"><template #icon><AppIcon icon="ph:arrow-down" /></template></n-button>
          <n-button quaternary circle size="small" type="error" :aria-label="t('workflow.form.removeField')" @click="emit('update:modelValue', removeWfFormField(modelValue!, index))"><template #icon><AppIcon icon="ph:trash" /></template></n-button>
        </n-space>
      </template>

      <div class="wf-form-grid">
        <n-form-item :label="t('workflow.form.fieldType')"><n-select :value="field.type" :options="typeOptions" @update:value="changeType(index, $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.key')"><n-input :value="field.key" maxlength="64" @update:value="updateField(index, (current) => ({ ...current, key: $event }))" /></n-form-item>
        <n-form-item :label="t('workflow.form.label')"><n-input :value="field.label" maxlength="128" @update:value="updateField(index, (current) => ({ ...current, label: $event }))" /></n-form-item>
        <n-form-item :label="t('workflow.form.placeholder')"><n-input :value="field.placeholder ?? ''" maxlength="256" @update:value="updateField(index, (current) => ({ ...current, placeholder: $event }))" /></n-form-item>
        <n-form-item :label="t('workflow.form.required')"><n-switch :value="field.required" @update:value="updateField(index, (current) => ({ ...current, required: $event }))" /></n-form-item>
      </div>

      <div v-if="field.type === 'text' || field.type === 'textarea'" class="wf-form-grid">
        <n-form-item :label="t('workflow.form.maxLength')"><n-input-number :value="numberProp(field, 'maxLength')" :min="1" :max="field.type === 'text' ? 256 : 4000" @update:value="updateProp(index, 'maxLength', $event)" /></n-form-item>
        <n-form-item v-if="field.type === 'textarea'" :label="t('workflow.form.rows')"><n-input-number :value="numberProp(field, 'rows')" :min="2" :max="8" @update:value="updateProp(index, 'rows', $event)" /></n-form-item>
      </div>
      <div v-else-if="field.type === 'number' || field.type === 'money'" class="wf-form-grid">
        <n-form-item :label="t('workflow.form.min')"><n-input-number :value="numberProp(field, 'min')" @update:value="updateProp(index, 'min', $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.max')"><n-input-number :value="numberProp(field, 'max')" @update:value="updateProp(index, 'max', $event)" /></n-form-item>
        <n-form-item v-if="field.type === 'number'" :label="t('workflow.form.precision')"><n-input-number :value="numberProp(field, 'precision')" :min="0" :max="6" @update:value="updateProp(index, 'precision', $event)" /></n-form-item>
      </div>
      <div v-else-if="field.type === 'date' || field.type === 'datetime'" class="wf-form-grid">
        <n-form-item :label="t('workflow.form.min')"><n-input :value="stringProp(field, 'min')" :placeholder="field.type === 'date' ? 'YYYY-MM-DD' : '2026-01-01T00:00:00+08:00'" @update:value="updateProp(index, 'min', $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.max')"><n-input :value="stringProp(field, 'max')" :placeholder="field.type === 'date' ? 'YYYY-MM-DD' : '2026-12-31T23:59:59+08:00'" @update:value="updateProp(index, 'max', $event)" /></n-form-item>
      </div>
      <template v-else-if="field.type === 'select' || field.type === 'multiSelect'">
        <div v-for="(option, optionIndex) in options(field)" :key="optionIndex" class="wf-form-option">
          <n-input :value="option.label" :placeholder="t('workflow.form.optionLabel')" @update:value="updateOption(index, optionIndex, { label: $event })" />
          <n-input :value="option.value" :placeholder="t('workflow.form.optionValue')" @update:value="updateOption(index, optionIndex, { value: $event })" />
          <n-button quaternary circle :aria-label="t('workflow.form.removeOption')" @click="removeOption(index, optionIndex)"><template #icon><AppIcon icon="ph:x" /></template></n-button>
        </div>
        <n-button dashed block @click="addOption(index)">{{ t('workflow.form.addOption') }}</n-button>
        <n-form-item v-if="field.type === 'multiSelect'" :label="t('workflow.form.maxSelected')"><n-input-number :value="numberProp(field, 'maxSelected')" :min="1" :max="100" @update:value="updateProp(index, 'maxSelected', $event)" /></n-form-item>
      </template>
      <div v-else-if="field.type === 'user'" class="wf-form-grid">
        <n-form-item :label="t('workflow.form.multiple')"><n-switch :value="booleanProp(field, 'multiple')" @update:value="updateProp(index, 'multiple', $event)" /></n-form-item>
        <n-form-item v-if="booleanProp(field, 'multiple')" :label="t('workflow.form.maxSelected')"><n-input-number :value="numberProp(field, 'maxSelected')" :min="1" :max="100" @update:value="updateProp(index, 'maxSelected', $event)" /></n-form-item>
      </div>
      <div v-else-if="field.type === 'attachment'" class="wf-form-grid">
        <n-form-item :label="t('workflow.form.multiple')"><n-switch :value="booleanProp(field, 'multiple')" @update:value="updateProp(index, 'multiple', $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.maxCount')"><n-input-number :value="numberProp(field, 'maxCount')" :min="1" :max="20" :disabled="!booleanProp(field, 'multiple')" @update:value="updateProp(index, 'maxCount', $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.accept')"><n-input :value="stringProp(field, 'accept')" placeholder=".pdf,.png,.jpg" @update:value="updateProp(index, 'accept', $event)" /></n-form-item>
        <n-form-item :label="t('workflow.form.maxSizeMb')"><n-input-number :value="numberProp(field, 'maxSizeMb')" :min="1" :max="100" @update:value="updateProp(index, 'maxSizeMb', $event)" /></n-form-item>
      </div>

      <div v-if="fieldErrors(index).length" class="wf-form-errors">{{ fieldErrors(index).join('；') }}</div>
    </n-card>
  </div>
</template>

<style scoped>
.wf-form-designer, .wf-form-field { display: flex; flex-direction: column; gap: var(--space-12); }
.wf-form-toolbar { display: flex; gap: var(--space-8); align-items: center; }
.wf-form-type-select { flex: 1; }
.wf-form-count { color: var(--color-text-tertiary); font-size: var(--font-size-sm); }
.wf-form-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0 var(--space-12); }
.wf-form-option { display: grid; grid-template-columns: 1fr 1fr auto; gap: var(--space-8); margin-bottom: var(--space-8); }
.wf-form-errors { color: var(--color-danger); font-size: var(--font-size-sm); }
</style>

// web-react/src/views/workflow/definition/components/WfFormDesigner.tsx
// 简易动态表单设计器:单列 10 控件,增删/上下移/通用属性/类型专属属性 + 即时校验。
// 对应 Vue 侧 WfFormDesigner.vue。不引入拖拽依赖(上下移按钮即排序手段)。
import { useMemo } from 'react'
import { Button, Card, Form, Input, InputNumber, Select, Space, Switch } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import {
  addWfFormField,
  createWfFormField,
  getWfFormFieldProp,
  moveWfFormField,
  removeWfFormField,
  updateWfFormFieldProp,
  validateWfFormSchema,
} from '@/workflow/formSchema'
import {
  WF_FORM_FIELD_TYPES,
  type WfFormField,
  type WfFormFieldType,
  type WfFormOption,
  type WfFormSchema,
} from '@/workflow/schema'
import './wf-designer.css'

const MAX_FIELDS = 50

export interface WfFormDesignerProps {
  value: WfFormSchema | null
  /** 删掉最后一个字段时回传 null(= 该流程无内置表单)。 */
  onChange: (value: WfFormSchema | null) => void
}

export function WfFormDesigner({ value, onChange }: WfFormDesignerProps) {
  const { t } = useTranslation()

  const typeOptions = useMemo(
    () => WF_FORM_FIELD_TYPES.map((type) => ({ value: type, label: t(`workflow.form.type.${type}`) })),
    [t],
  )
  const issues = useMemo(() => validateWfFormSchema(value), [value])
  const schemaErrors = [...new Set(
    issues.filter((issue) => issue.fieldIndex == null).map((issue) => t(`workflow.form.error.${issue.code}`)),
  )]
  const fieldErrors = (index: number) => [...new Set(
    issues.filter((issue) => issue.fieldIndex === index).map((issue) => t(`workflow.form.error.${issue.code}`)),
  )]

  const fields = value?.fields ?? []

  const updateField = (index: number, update: (field: WfFormField) => WfFormField) => {
    const field = fields[index]
    if (!field) return
    const next = [...fields]
    next[index] = update(field)
    onChange({ version: 1, fields: next })
  }

  const updateProp = (index: number, key: string, propValue: unknown) => {
    updateField(index, (current) => updateWfFormFieldProp(current, key, propValue))
  }

  const prop = (field: WfFormField, key: string): unknown => getWfFormFieldProp(field, key)
  const numberProp = (field: WfFormField, key: string): number | null => {
    const raw = prop(field, key)
    return typeof raw === 'number' ? raw : null
  }
  const stringProp = (field: WfFormField, key: string): string => {
    const raw = prop(field, key)
    return typeof raw === 'string' ? raw : ''
  }
  const booleanProp = (field: WfFormField, key: string): boolean => prop(field, key) === true
  const options = (field: WfFormField): WfFormOption[] => {
    const raw = prop(field, 'options')
    return Array.isArray(raw) ? raw : []
  }

  const updateOption = (fieldIndex: number, optionIndex: number, patch: Partial<WfFormOption>) => {
    const field = fields[fieldIndex]
    if (!field) return
    updateProp(fieldIndex, 'options', options(field).map((option, index) =>
      index === optionIndex ? { ...option, ...patch } : option))
  }

  const addOption = (fieldIndex: number) => {
    const field = fields[fieldIndex]
    if (!field) return
    const current = options(field)
    let n = current.length + 1
    while (current.some((option) => option.value === `option${n}`)) n += 1
    updateProp(fieldIndex, 'options', [...current, { label: `${t('workflow.form.option')} ${n}`, value: `option${n}` }])
  }

  const removeOption = (fieldIndex: number, optionIndex: number) => {
    const field = fields[fieldIndex]
    if (!field) return
    updateProp(fieldIndex, 'options', options(field).filter((_, index) => index !== optionIndex))
  }

  /** 换控件类型 = 重建 props(旧类型的属性对新类型是未知属性,会直接判 propUnknown),只留通用字段。 */
  const changeType = (index: number, type: WfFormFieldType) => {
    updateField(index, (field) => ({
      ...createWfFormField(type, field.key),
      label: field.label,
      required: field.required,
      placeholder: field.placeholder,
    }))
  }

  /**
   * 人员关闭多选时必须同时清掉 `maxSelected`:校验对 `multiple !== true` 且带 maxSelected 的 user 字段
   * 直接判 propInvalid,只隐藏输入框会留下一条发布不掉的脏属性。
   */
  const setUserMultiple = (index: number, multiple: boolean) => {
    updateField(index, (field) => {
      const next = updateWfFormFieldProp(field, 'multiple', multiple)
      return multiple ? next : updateWfFormFieldProp(next, 'maxSelected', undefined)
    })
  }

  return (
    <div className="wf-form-designer">
      <div className="wf-form-toolbar">
        <Select
          className="wf-form-type-select"
          options={typeOptions}
          value={null}
          disabled={fields.length >= MAX_FIELDS}
          placeholder={t('workflow.form.addField')}
          onChange={(type: WfFormFieldType) => onChange(addWfFormField(value, type))}
        />
        <span className="wf-form-count">{fields.length}/{MAX_FIELDS}</span>
      </div>
      {schemaErrors.length ? <div className="wf-form-errors">{schemaErrors.join('；')}</div> : null}

      {fields.map((field, index) => (
        <Card
          // 索引键:字段 key 可空/可重复(编辑中),索引是这里唯一稳定的标识。
          key={index}
          size="small"
          className="wf-form-field"
          title={field.label || field.key || t('workflow.form.unnamedField')}
          extra={
            <Space size={4}>
              <Button
                type="text" shape="circle" size="small" disabled={index === 0}
                aria-label={t('workflow.form.moveUp')} icon={<AppIcon icon="ph:arrow-up" />}
                onClick={() => value && onChange(moveWfFormField(value, index, -1))}
              />
              <Button
                type="text" shape="circle" size="small" disabled={index === fields.length - 1}
                aria-label={t('workflow.form.moveDown')} icon={<AppIcon icon="ph:arrow-down" />}
                onClick={() => value && onChange(moveWfFormField(value, index, 1))}
              />
              <Button
                type="text" shape="circle" size="small" danger
                aria-label={t('workflow.form.removeField')} icon={<AppIcon icon="ph:trash" />}
                onClick={() => value && onChange(removeWfFormField(value, index))}
              />
            </Space>
          }
        >
          <div className="wf-form-grid">
            <Form.Item label={t('workflow.form.fieldType')}>
              <Select value={field.type} options={typeOptions} onChange={(type: WfFormFieldType) => changeType(index, type)} />
            </Form.Item>
            <Form.Item label={t('workflow.form.key')}>
              <Input
                value={field.key} maxLength={64}
                onChange={(e) => updateField(index, (current) => ({ ...current, key: e.target.value }))}
              />
            </Form.Item>
            <Form.Item label={t('workflow.form.label')}>
              <Input
                value={field.label} maxLength={128}
                onChange={(e) => updateField(index, (current) => ({ ...current, label: e.target.value }))}
              />
            </Form.Item>
            <Form.Item label={t('workflow.form.placeholder')}>
              <Input
                value={field.placeholder ?? ''} maxLength={256}
                onChange={(e) => updateField(index, (current) => ({ ...current, placeholder: e.target.value }))}
              />
            </Form.Item>
            <Form.Item label={t('workflow.form.required')}>
              <Switch
                checked={field.required}
                onChange={(checked) => updateField(index, (current) => ({ ...current, required: checked }))}
              />
            </Form.Item>
          </div>

          {field.type === 'text' || field.type === 'textarea' ? (
            <div className="wf-form-grid">
              <Form.Item label={t('workflow.form.maxLength')}>
                <InputNumber
                  className="w-full" value={numberProp(field, 'maxLength')}
                  min={1} max={field.type === 'text' ? 256 : 4000}
                  onChange={(v) => updateProp(index, 'maxLength', v)}
                />
              </Form.Item>
              {field.type === 'textarea' ? (
                <Form.Item label={t('workflow.form.rows')}>
                  <InputNumber
                    className="w-full" value={numberProp(field, 'rows')} min={2} max={8}
                    onChange={(v) => updateProp(index, 'rows', v)}
                  />
                </Form.Item>
              ) : null}
            </div>
          ) : field.type === 'number' || field.type === 'money' ? (
            <div className="wf-form-grid">
              <Form.Item label={t('workflow.form.min')}>
                <InputNumber className="w-full" value={numberProp(field, 'min')} onChange={(v) => updateProp(index, 'min', v)} />
              </Form.Item>
              <Form.Item label={t('workflow.form.max')}>
                <InputNumber className="w-full" value={numberProp(field, 'max')} onChange={(v) => updateProp(index, 'max', v)} />
              </Form.Item>
              {field.type === 'number' ? (
                <Form.Item label={t('workflow.form.precision')}>
                  <InputNumber
                    className="w-full" value={numberProp(field, 'precision')} min={0} max={6}
                    onChange={(v) => updateProp(index, 'precision', v)}
                  />
                </Form.Item>
              ) : null}
            </div>
          ) : field.type === 'date' || field.type === 'datetime' ? (
            <div className="wf-form-grid">
              <Form.Item label={t('workflow.form.min')}>
                <Input
                  value={stringProp(field, 'min')}
                  placeholder={field.type === 'date' ? 'YYYY-MM-DD' : '2026-01-01T00:00:00+08:00'}
                  onChange={(e) => updateProp(index, 'min', e.target.value)}
                />
              </Form.Item>
              <Form.Item label={t('workflow.form.max')}>
                <Input
                  value={stringProp(field, 'max')}
                  placeholder={field.type === 'date' ? 'YYYY-MM-DD' : '2026-12-31T23:59:59+08:00'}
                  onChange={(e) => updateProp(index, 'max', e.target.value)}
                />
              </Form.Item>
            </div>
          ) : field.type === 'select' || field.type === 'multiSelect' ? (
            <>
              {options(field).map((option, optionIndex) => (
                <div key={optionIndex} className="wf-form-option">
                  <Input
                    value={option.label} placeholder={t('workflow.form.optionLabel')}
                    onChange={(e) => updateOption(index, optionIndex, { label: e.target.value })}
                  />
                  <Input
                    value={option.value} placeholder={t('workflow.form.optionValue')}
                    onChange={(e) => updateOption(index, optionIndex, { value: e.target.value })}
                  />
                  <Button
                    type="text" shape="circle" aria-label={t('workflow.form.removeOption')}
                    icon={<AppIcon icon="ph:x" />} onClick={() => removeOption(index, optionIndex)}
                  />
                </div>
              ))}
              <Button type="dashed" block onClick={() => addOption(index)}>
                {t('workflow.form.addOption')}
              </Button>
              {field.type === 'multiSelect' ? (
                <Form.Item label={t('workflow.form.maxSelected')}>
                  <InputNumber
                    className="w-full" value={numberProp(field, 'maxSelected')} min={1} max={100}
                    onChange={(v) => updateProp(index, 'maxSelected', v)}
                  />
                </Form.Item>
              ) : null}
            </>
          ) : field.type === 'user' ? (
            <div className="wf-form-grid">
              <Form.Item label={t('workflow.form.multiple')}>
                <Switch checked={booleanProp(field, 'multiple')} onChange={(checked) => setUserMultiple(index, checked)} />
              </Form.Item>
              {booleanProp(field, 'multiple') ? (
                <Form.Item label={t('workflow.form.maxSelected')}>
                  <InputNumber
                    className="w-full" value={numberProp(field, 'maxSelected')} min={1} max={100}
                    onChange={(v) => updateProp(index, 'maxSelected', v)}
                  />
                </Form.Item>
              ) : null}
            </div>
          ) : field.type === 'attachment' ? (
            <div className="wf-form-grid">
              <Form.Item label={t('workflow.form.multiple')}>
                {/* 关闭多选时 updateWfFormFieldProp 会把 maxCount 一并压回 1(校验只允许 1)。 */}
                <Switch checked={booleanProp(field, 'multiple')} onChange={(checked) => updateProp(index, 'multiple', checked)} />
              </Form.Item>
              <Form.Item label={t('workflow.form.maxCount')}>
                <InputNumber
                  className="w-full" value={numberProp(field, 'maxCount')} min={1} max={20}
                  disabled={!booleanProp(field, 'multiple')}
                  onChange={(v) => updateProp(index, 'maxCount', v)}
                />
              </Form.Item>
              <Form.Item label={t('workflow.form.accept')}>
                <Input
                  value={stringProp(field, 'accept')} placeholder=".pdf,.png,.jpg"
                  onChange={(e) => updateProp(index, 'accept', e.target.value)}
                />
              </Form.Item>
              <Form.Item label={t('workflow.form.maxSizeMb')}>
                <InputNumber
                  className="w-full" value={numberProp(field, 'maxSizeMb')} min={1} max={100}
                  onChange={(v) => updateProp(index, 'maxSizeMb', v)}
                />
              </Form.Item>
            </div>
          ) : null}

          {fieldErrors(index).length ? <div className="wf-form-errors">{fieldErrors(index).join('；')}</div> : null}
        </Card>
      ))}
    </div>
  )
}
