// web/src/views/system/role/components/GrantMenuTable.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { NButton, NCheckbox, NInput, NSelect } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import { MenuType, type MenuTreeNode } from '@/types/menu'
import type { ModuleRow } from '@/types/api'

const UNASSIGNED = 0

interface ButtonItem { id: number; title: string; checked: boolean }
interface MenuRow { id: number; title: string; checked: boolean; buttons: ButtonItem[] }
interface CatalogGroup { id: number; title: string; checked: boolean; indeterminate: boolean; menus: MenuRow[] }

const props = defineProps<{
  tree: MenuTreeNode[]
  granted: number[]
  modules: ModuleRow[]
  defaultModuleId: number
}>()

const emit = defineEmits<{ (e: 'update:checked', ids: number[]): void }>()

const { t } = useI18n()
const search = ref('')
const moduleId = ref(props.defaultModuleId)
watch(() => props.defaultModuleId, (v) => { moduleId.value = v })

const moduleOptions = computed(() => [
  ...props.modules.map((m) => ({ label: m.title, value: m.id })),
  { label: t('menu.moduleUnassigned'), value: UNASSIGNED },
])

function toMenuRow(m: MenuTreeNode, grantedSet: Set<number>): MenuRow {
  return {
    id: m.id,
    title: m.title,
    checked: grantedSet.has(m.id),
    buttons: m.children
      .filter((b) => b.type === MenuType.Button)
      .map((b) => ({ id: b.id, title: b.title, checked: grantedSet.has(b.id) })),
  }
}

function buildGroups(tree: MenuTreeNode[], grantedSet: Set<number>): CatalogGroup[] {
  return tree.map((node) => {
    // 顶级 Menu（如工作台）：自身就是菜单行，无目录壳
    const menus: MenuRow[] = node.type === MenuType.Menu
      ? [toMenuRow(node, grantedSet)]
      : node.children.filter((m) => m.type === MenuType.Menu).map((m) => toMenuRow(m, grantedSet))
    const group: CatalogGroup = {
      id: node.id,
      title: node.title,
      checked: grantedSet.has(node.id),
      indeterminate: false,
      menus,
    }
    recomputeGroup(group)
    return group
  })
}

const allGroups = reactive<CatalogGroup[]>([])

watch(
  () => [props.tree, props.granted] as const,
  ([tree, granted]) => {
    const set = new Set(granted)
    const groups = buildGroups(
      tree.filter((n) => n.type === MenuType.Catalog || n.type === MenuType.Menu),
      set,
    )
    allGroups.splice(0, allGroups.length, ...groups)
  },
  { immediate: true },
)

const filteredByModule = computed(() =>
  allGroups.filter((g) => {
    const node = props.tree.find((n) => n.id === g.id)
    return moduleId.value === UNASSIGNED ? node?.moduleId == null : node?.moduleId === moduleId.value
  }),
)

const filteredGroups = computed(() => {
  const q = search.value.trim().toLowerCase()
  if (!q) return filteredByModule.value
  return filteredByModule.value
    .map((g) => {
      if (g.title.toLowerCase().includes(q)) return g
      const menus = g.menus.filter(
        (m) => m.title.toLowerCase().includes(q) || m.buttons.some((b) => b.title.toLowerCase().includes(q)),
      )
      return menus.length ? { ...g, menus } : null
    })
    .filter(Boolean) as CatalogGroup[]
})

function recomputeGroup(group: CatalogGroup) {
  const allIds = group.menus.flatMap((m) => [m, ...m.buttons])
  const checkedCount = allIds.filter((x) => x.checked).length
  group.checked = checkedCount > 0 && checkedCount === allIds.length
  group.indeterminate = checkedCount > 0 && checkedCount < allIds.length
}

function toggleCatalog(group: CatalogGroup, val: boolean) {
  group.checked = val
  group.indeterminate = false
  group.menus.forEach((m) => {
    m.checked = val
    m.buttons.forEach((b) => { b.checked = val })
  })
  emitChecked()
}

function toggleMenu(group: CatalogGroup, menu: MenuRow, val: boolean) {
  menu.checked = val
  menu.buttons.forEach((b) => { b.checked = val })
  recomputeGroup(group)
  emitChecked()
}

function toggleButton(group: CatalogGroup, menu: MenuRow) {
  const allChecked = menu.buttons.length > 0 && menu.buttons.every((b) => b.checked)
  if (allChecked) menu.checked = true
  recomputeGroup(group)
  emitChecked()
}

function collectChecked(): number[] {
  const ids: number[] = []
  for (const g of allGroups) {
    if (g.checked || g.indeterminate) ids.push(g.id)
    for (const m of g.menus) {
      if (m.checked) ids.push(m.id)
      for (const b of m.buttons) {
        if (b.checked) ids.push(b.id)
      }
    }
  }
  return ids
}

function emitChecked() {
  emit('update:checked', collectChecked())
}

// ── 折叠/展开 ──
const collapsed = reactive(new Set<number>())
const allCollapsed = computed(() => filteredGroups.value.length > 0 && filteredGroups.value.every((g) => collapsed.has(g.id)))

function toggleCollapse(id: number) {
  collapsed.has(id) ? collapsed.delete(id) : collapsed.add(id)
}
function toggleCollapseAll() {
  if (allCollapsed.value) {
    collapsed.clear()
  } else {
    for (const g of filteredGroups.value) collapsed.add(g.id)
  }
}

defineExpose({ collectChecked })
</script>

<template>
  <div class="grant-menu-table">
    <div class="grant-toolbar">
      <n-select v-model:value="moduleId" :options="moduleOptions" :placeholder="t('menu.module')" size="small" style="width: 180px" />
      <n-input v-model:value="search" :placeholder="t('common.search')" clearable size="small" style="flex: 1" />
      <n-button size="small" quaternary @click="toggleCollapseAll">
        <template #icon><AppIcon :icon="allCollapsed ? 'ph:arrows-out-line-vertical' : 'ph:arrows-in-line-vertical'" :size="16" /></template>
        {{ allCollapsed ? t('common.expandAll') : t('common.collapseAll') }}
      </n-button>
    </div>
    <div class="grant-grid">
      <div class="grant-header">
        <div class="col-catalog">{{ t('role.catalog') }}</div>
        <div class="col-menu">{{ t('role.menuCol') }}</div>
        <div class="col-buttons">{{ t('role.buttonsCol') }}</div>
      </div>
      <template v-for="group in filteredGroups" :key="group.id">
        <div class="grant-group" :style="{ '--rows': group.menus.length }">
          <div class="col-catalog" @click="toggleCollapse(group.id)">
            <span class="collapse-arrow" :class="{ 'is-collapsed': collapsed.has(group.id) }">&#9662;</span>
            <n-checkbox :checked="group.checked" :indeterminate="group.indeterminate" @click.stop @update:checked="toggleCatalog(group, $event)">
              {{ group.title }}
            </n-checkbox>
          </div>
          <div v-show="!collapsed.has(group.id)" class="group-rows">
            <div v-for="menu in group.menus" :key="menu.id" class="grant-row">
              <div class="col-menu">
                <n-checkbox :checked="menu.checked" @update:checked="toggleMenu(group, menu, $event)">
                  {{ menu.title }}
                </n-checkbox>
              </div>
              <div class="col-buttons">
                <n-checkbox
                  v-for="btn in menu.buttons" :key="btn.id"
                  :checked="btn.checked"
                  @update:checked="(v: boolean) => { btn.checked = v; toggleButton(group, menu) }"
                >
                  {{ btn.title }}
                </n-checkbox>
                <span v-if="!menu.buttons.length" class="no-buttons">—</span>
              </div>
            </div>
          </div>
        </div>
      </template>
      <div v-if="filteredGroups.length === 0" class="grant-empty">—</div>
    </div>
  </div>
</template>

<style scoped>
.grant-menu-table {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.grant-toolbar {
  display: flex;
  gap: 8px;
}
.grant-grid {
  border: 1px solid var(--n-border-color, #e0e0e6);
  border-radius: 4px;
  font-size: 13px;
  overflow: hidden;
}
.grant-header {
  display: flex;
  background: var(--n-th-color, #fafafc);
  font-weight: 600;
  font-size: 12px;
  border-bottom: 1px solid var(--n-border-color, #e0e0e6);
}
.grant-header > div {
  padding: 8px 12px;
}
.grant-group {
  display: flex;
  border-bottom: 1px solid var(--n-border-color, #e0e0e6);
}
.grant-group:last-child {
  border-bottom: none;
}
.grant-group > .col-catalog {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 8px 12px;
  border-right: 1px solid var(--n-border-color, #e0e0e6);
  cursor: pointer;
  user-select: none;
}
.collapse-arrow {
  display: inline-block;
  font-size: 10px;
  transition: transform 0.2s;
  color: var(--n-text-color-disabled, #999);
}
.collapse-arrow.is-collapsed {
  transform: rotate(-90deg);
}
.group-rows {
  flex: 1;
  min-width: 0;
}
.grant-row {
  display: flex;
  border-bottom: 1px solid var(--n-border-color, #e0e0e6);
}
.grant-row:last-child {
  border-bottom: none;
}
.col-catalog {
  width: 130px;
  flex-shrink: 0;
}
.col-menu {
  width: 140px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  padding: 6px 12px;
  border-right: 1px solid var(--n-border-color, #e0e0e6);
}
.col-buttons {
  flex: 1;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 4px 12px;
  padding: 6px 12px;
  min-width: 0;
}
.no-buttons {
  color: var(--n-text-color-disabled, #c0c0c0);
}
.grant-empty {
  text-align: center;
  padding: 24px;
  color: var(--n-text-color-disabled, #c0c0c0);
}
</style>

// web-react/src/views/system/role/GrantMenuTable.tsx
// 授权菜单三列网格(目录|菜单|按钮)+ 三态复选。按钮已从主菜单树剥离(在 ButtonManager 管),
// 但授权是「角色能看/能点什么」,故这里把按钮拉回来一并勾。纯逻辑在 grantMenu.ts(变异钉),本组件只接线 + 渲染。
// 对齐 Vue 侧 GrantMenuTable.vue(那边就地改 reactive,React 走不可变更新 + 受控上抛)。
import { useEffect, useMemo, useState } from 'react'
import { Button, Checkbox, Input, Select } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import type { MenuTreeNode } from '@/types/menu'
import type { ModuleRow } from '@/types/api'
import {
  UNASSIGNED, buildGroups, collectChecked, filterByModule, filterBySearch,
  withButtonChecked, withCatalogChecked, withMenuChecked, type CatalogGroup,
} from './grantMenu'
import './GrantMenuTable.css'

export interface GrantMenuTableProps {
  tree: MenuTreeNode[]
  granted: number[]
  modules: ModuleRow[]
  defaultModuleId: number
  onCheckedChange: (ids: number[]) => void
}

export function GrantMenuTable({ tree, granted, modules, defaultModuleId, onCheckedChange }: GrantMenuTableProps) {
  const { t } = useTranslation()
  const [groups, setGroups] = useState<CatalogGroup[]>([])
  const [moduleId, setModuleId] = useState(defaultModuleId)
  const [search, setSearch] = useState('')
  const [collapsed, setCollapsed] = useState<Set<number>>(new Set())

  // tree/granted 变(打开抽屉/换角色)→ 重建组;不上抛(父已持有 granted 初值)。
  useEffect(() => { setGroups(buildGroups(tree, granted)) }, [tree, granted])
  // 父传的默认应用变(openMenus 盖当前应用)→ 同步筛选。
  useEffect(() => { setModuleId(defaultModuleId) }, [defaultModuleId])

  const moduleOptions = useMemo(
    () => [...modules.map((m) => ({ label: m.title, value: m.id })), { label: t('menu.moduleUnassigned'), value: UNASSIGNED }],
    [modules, t],
  )
  const filtered = useMemo(() => filterBySearch(filterByModule(groups, moduleId), search), [groups, moduleId, search])

  // 切换:从当前 groups 算出新数组 → setGroups + 上抛 collectChecked(用户事件,闭包 groups 恒新鲜)。
  const apply = (next: CatalogGroup[]) => { setGroups(next); onCheckedChange(collectChecked(next)) }
  const onCatalog = (id: number, val: boolean) => apply(groups.map((g) => (g.id === id ? withCatalogChecked(g, val) : g)))
  const onMenu = (gid: number, mid: number, val: boolean) => apply(groups.map((g) => (g.id === gid ? withMenuChecked(g, mid, val) : g)))
  const onButton = (gid: number, mid: number, bid: number, val: boolean) => apply(groups.map((g) => (g.id === gid ? withButtonChecked(g, mid, bid, val) : g)))

  const toggleCollapse = (id: number) =>
    setCollapsed((prev) => { const n = new Set(prev); if (n.has(id)) n.delete(id); else n.add(id); return n })
  const allCollapsed = filtered.length > 0 && filtered.every((g) => collapsed.has(g.id))
  const toggleCollapseAll = () => setCollapsed(allCollapsed ? new Set() : new Set(filtered.map((g) => g.id)))

  return (
    <div className="grant-menu-table">
      <div className="grant-toolbar">
        <Select value={moduleId} onChange={setModuleId} options={moduleOptions} size="small" style={{ width: 180 }} placeholder={t('menu.module')} />
        <Input value={search} onChange={(e) => setSearch(e.target.value)} allowClear size="small" placeholder={t('common.search')} style={{ flex: 1 }} />
        <Button size="small" type="text" onClick={toggleCollapseAll}
          icon={<AppIcon icon={allCollapsed ? 'ph:arrows-out-line-vertical' : 'ph:arrows-in-line-vertical'} size={16} />}>
          {allCollapsed ? t('common.expandAll') : t('common.collapseAll')}
        </Button>
      </div>

      <div className="grant-grid">
        <div className="grant-header">
          <div className="col-catalog">{t('role.catalog')}</div>
          <div className="col-menu">{t('role.menuCol')}</div>
          <div className="col-buttons">{t('role.buttonsCol')}</div>
        </div>

        {filtered.map((group) => (
          <div className="grant-group" key={group.id}>
            <div className="col-catalog" onClick={() => toggleCollapse(group.id)}>
              <span className={`collapse-arrow${collapsed.has(group.id) ? ' is-collapsed' : ''}`}>▾</span>
              {/* 勾选不该顺带折叠 → stopPropagation */}
              <span onClick={(e) => e.stopPropagation()}>
                <Checkbox checked={group.checked} indeterminate={group.indeterminate} onChange={(e) => onCatalog(group.id, e.target.checked)}>
                  {group.title}
                </Checkbox>
              </span>
            </div>
            {!collapsed.has(group.id) && (
              <div className="group-rows">
                {group.menus.map((menu) => (
                  <div className="grant-row" key={menu.id}>
                    <div className="col-menu">
                      <Checkbox checked={menu.checked} onChange={(e) => onMenu(group.id, menu.id, e.target.checked)}>{menu.title}</Checkbox>
                    </div>
                    <div className="col-buttons">
                      {menu.buttons.map((btn) => (
                        <Checkbox key={btn.id} checked={btn.checked} onChange={(e) => onButton(group.id, menu.id, btn.id, e.target.checked)}>{btn.title}</Checkbox>
                      ))}
                      {menu.buttons.length === 0 && <span className="no-buttons">—</span>}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
        {filtered.length === 0 && <div className="grant-empty">—</div>}
      </div>
    </div>
  )
}
