// web-react/src/views/system/role/index.tsx
// 角色管理 = DataTable CRUD + 3 抽屉:授权菜单(GrantMenuTable 三态勾选)、数据范围(范围类型 + 自定义机构多选)、
// 授权用户(UserPicker)。删角色会**物理**删掉用户↔角色关联(不可恢复),故单删/批删都先查一次持有人数当面告知。
// 纯逻辑抽 grantMenu.ts / roleForm.ts(变异钉),本页接线。
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { App, Button, Dropdown, Form, Input, InputNumber, Select, Space, Switch, type MenuProps } from 'antd'
import { useTranslation } from 'react-i18next'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import { Can } from '@/components/Can'
import { FormContainer } from '@/components/FormContainer'
import { OrgTreeSelect } from '@/components/OrgTreeSelect'
import { StatusSwitch } from '@/components/StatusSwitch'
import { UserPicker, type UserPickerHandle } from '@/components/UserPicker'
import { GrantMenuTable } from './GrantMenuTable'
import { useConfirm } from '@/hooks/useConfirm'
import { useBatchDelete } from '@/hooks/useBatchDelete'
import { useAuthStore, useHasPerm } from '@/stores/auth'
import { menuApi, moduleApi, roleApi, userApi } from '@/api'
import { translateError } from '@/utils/error'
import { DataScopeType, type ModuleRow, type RoleInput, type SysRole } from '@/types/api'
import type { MenuTreeNode } from '@/types/menu'
import { UNASSIGNED } from './grantMenu'
import { blankRole, roleToInput } from './roleForm'

/** 持有该角色的用户数;复用用户分页(Size=1 只要 total)。查不到(如无用户查询权限 403)→ null,退通用文案不阻断删除。 */
async function countUsers(roleId: number): Promise<number | null> {
  try {
    return (await userApi.page({ page: 1, pageSize: 1, roleId })).total
  } catch {
    return null
  }
}

export default function RolePage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const { confirm } = useConfirm()
  const has = useHasPerm()
  const isSuperAdmin = useAuthStore((s) => s.isSuperAdmin)

  const tableRef = useRef<DataTableHandle>(null)
  const reload = useCallback(() => tableRef.current?.reload(), [])

  const [modules, setModules] = useState<ModuleRow[]>([])
  useEffect(() => {
    moduleApi.list().then(setModules).catch((e: unknown) => message.error(translateError(e)))
  }, [message]) // 仅供授权抽屉「所属应用」下拉,失败不阻塞

  const fetchRoles: PageFetcher<SysRole> = (q) =>
    roleApi.page({ page: q.page, pageSize: q.pageSize, name: typeof q.name === 'string' ? q.name : undefined })

  // 批删:先查各角色持有人数,有人则警示文案。
  const batch = useBatchDelete({
    remove: roleApi.batchRemove,
    refresh: reload,
    successMsg: t('role.deleted'),
    content: async (ids) => {
      const counts = await Promise.all(ids.map(countUsers))
      if (counts.some((n) => n === null)) return t('common.batchDeleteConfirm', { count: ids.length })
      const users = counts.reduce<number>((s, n) => s + n!, 0)
      return users === 0 ? t('common.batchDeleteConfirm', { count: ids.length }) : t('role.batchDeleteWithUsers', { count: ids.length, users })
    },
  })

  const askDelete = useCallback(async (r: SysRole) => {
    const n = await countUsers(r.id)
    const content = n === null ? t('role.deleteConfirm', { name: r.name })
      : n === 0 ? t('role.deleteConfirmNoUsers', { name: r.name })
        : t('role.deleteConfirmWithUsers', { name: r.name, count: n })
    const ok = await confirm({ content, action: () => roleApi.remove(r.id), successMsg: t('role.deleted') })
    if (ok) reload()
  }, [confirm, t, reload])

  // ── 新增/编辑弹窗 ──
  const [form] = Form.useForm<RoleInput>()
  const [open, setOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const openAdd = useCallback(() => { setEditingId(null); form.setFieldsValue(blankRole()); setOpen(true) }, [form])
  const openEdit = useCallback((r: SysRole) => { setEditingId(r.id); form.setFieldsValue(roleToInput(r)); setOpen(true) }, [form])
  const save = async () => {
    const v = await form.validateFields()
    try {
      if (editingId === null) await roleApi.add(v)
      else await roleApi.update(editingId, v)
      message.success(t('role.saved'))
      reload()
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  // ── 授权菜单抽屉 ──
  const [showMenus, setShowMenus] = useState(false)
  const [menuTree, setMenuTree] = useState<MenuTreeNode[]>([])
  const [menuGranted, setMenuGranted] = useState<number[]>([])
  const [menuRoleId, setMenuRoleId] = useState<number | null>(null)
  const [defaultModuleId, setDefaultModuleId] = useState(UNASSIGNED)
  const openMenus = useCallback(async (r: SysRole) => {
    setMenuRoleId(r.id)
    try {
      const [tree, grantedIds] = await Promise.all([menuApi.tree(), roleApi.getMenus(r.id)])
      setMenuTree(tree)
      setMenuGranted(grantedIds)
      setDefaultModuleId(useAuthStore.getState().currentModuleId ?? modules[0]?.id ?? UNASSIGNED)
      setShowMenus(true)
    } catch (e) {
      message.error(translateError(e))
    }
  }, [message, modules])
  const saveMenus = async () => {
    if (menuRoleId === null) return
    try {
      await roleApi.setMenus(menuRoleId, menuGranted)
      message.success(t('role.grantSaved'))
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  // ── 授权用户(UserPicker,命令式 ref)──
  const userPickerRef = useRef<UserPickerHandle>(null)
  const [userRoleId, setUserRoleId] = useState<number | null>(null)
  const openUsers = useCallback(async (r: SysRole) => {
    setUserRoleId(r.id)
    try {
      userPickerRef.current?.open(await roleApi.getUsers(r.id))
    } catch (e) {
      message.error(translateError(e))
    }
  }, [message])
  const onUserConfirm = useCallback(async (ids: number[]) => {
    if (userRoleId === null) return
    try {
      await roleApi.setUsers(userRoleId, ids)
      message.success(t('role.grantUsersSaved'))
    } catch (e) {
      message.error(translateError(e))
    }
  }, [userRoleId, t, message])

  // ── 数据范围抽屉 ──
  const [showScope, setShowScope] = useState(false)
  const [scopeRoleId, setScopeRoleId] = useState<number | null>(null)
  const [scopeType, setScopeType] = useState<DataScopeType>(DataScopeType.Org)
  const [customOrgIds, setCustomOrgIds] = useState<number[]>([])
  const isCustom = scopeType === DataScopeType.Custom
  const scopeOptions = useMemo(() => [
    { label: t('role.scope.all'), value: DataScopeType.All },
    { label: t('role.scope.org'), value: DataScopeType.Org },
    { label: t('role.scope.orgAndChildren'), value: DataScopeType.OrgAndChildren },
    { label: t('role.scope.self'), value: DataScopeType.Self },
    { label: t('role.scope.custom'), value: DataScopeType.Custom },
  ], [t])
  const openScope = useCallback(async (r: SysRole) => {
    setScopeRoleId(r.id)
    try {
      const cfg = await roleApi.getDataScope(r.id)
      setScopeType(cfg?.scopeType ?? DataScopeType.Org)
      setCustomOrgIds(cfg?.customOrgIds ? cfg.customOrgIds.split(',').filter(Boolean).map(Number) : [])
      setShowScope(true)
    } catch (e) {
      message.error(translateError(e))
    }
  }, [message])
  const saveScope = async () => {
    if (scopeRoleId === null) return
    try {
      await roleApi.setDataScope(scopeRoleId, scopeType, isCustom ? customOrgIds : undefined)
      message.success(t('role.scopeSaved'))
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  const columns = useMemo<ProColumns<SysRole>[]>(() => [
    { title: t('role.code'), dataIndex: 'code', search: false, ellipsis: true },
    { title: t('role.name'), dataIndex: 'name' }, // 唯一可搜列
    { title: t('role.sort'), dataIndex: 'sort', search: false, width: 80 },
    {
      title: t('common.status'), dataIndex: 'enabled', search: false, width: 90,
      // StatusSwitch 悲观受控(checked 绑 value):成功后必须 onChange={reload} 重拉,否则行数据不变、开关视觉回弹误导管理员。对齐 module 页。
      render: (_, r) => (
        <StatusSwitch value={r.enabled} disabled={!isSuperAdmin || !has('PUT:/api/v1/sys/role/{id}')} request={(next) => roleApi.update(r.id, { ...roleToInput(r), enabled: next })} onChange={reload} />
      ),
    },
    { title: t('role.remark'), dataIndex: 'remark', search: false, ellipsis: true, render: (_, r) => r.remark || '—' },
    {
      title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 240, fixed: 'right',
      render: (_, r) => {
        // QA36:角色定义(编辑/删除)与角色授权面(授权菜单/数据范围)为超管专属;
        // 仅"授权用户"(角色指派面)对普通管理员开放(经 RoleGrantPolicy 收口校验)。
        const moreItems = ([
          isSuperAdmin && has('PUT:/api/v1/sys/role/menu') ? { key: 'menus', label: t('role.grantMenus') } : null,
          isSuperAdmin && has('PUT:/api/v1/sys/role/datascope') ? { key: 'scope', label: t('role.dataScope') } : null,
          has('PUT:/api/v1/sys/role/users') ? { key: 'users', label: t('role.grantUsers') } : null,
        ] as MenuProps['items'])!.filter(Boolean)
        const onMore: MenuProps['onClick'] = ({ key }) => (key === 'menus' ? openMenus(r) : key === 'scope' ? openScope(r) : openUsers(r))
        return (
          <Space size={4}>
            {isSuperAdmin && has('PUT:/api/v1/sys/role/{id}') && <Button type="link" size="small" onClick={() => openEdit(r)}>{t('common.edit')}</Button>}
            {isSuperAdmin && has('DELETE:/api/v1/sys/role/{id}') && <Button type="link" size="small" danger onClick={() => askDelete(r)}>{t('common.delete')}</Button>}
            {moreItems!.length > 0 && (
              <Dropdown menu={{ items: moreItems, onClick: onMore }} trigger={['click']}>
                <Button type="link" size="small">{t('common.more')}</Button>
              </Dropdown>
            )}
          </Space>
        )
      },
    },
  ], [t, has, isSuperAdmin, reload, openEdit, askDelete, openMenus, openScope, openUsers])

  return (
    <>
      <DataTable<SysRole>
        ref={tableRef}
        columns={columns}
        fetcher={fetchRoles}
        persistKey="sys-role"
        rowSelection={{ selectedRowKeys: batch.selectedKeys, onChange: batch.setSelectedKeys }}
        toolbar={isSuperAdmin ? (
          <Space>
            <Can code="POST:/api/v1/sys/role/add"><Button type="primary" onClick={openAdd}>{t('common.add')}</Button></Can>
            <Can code="POST:/api/v1/sys/role/batch-delete"><Button danger disabled={!batch.hasSelection} onClick={batch.run}>{t('common.batchDelete')}</Button></Can>
          </Space>
        ) : undefined}
      />

      {/* 新增/编辑 */}
      <FormContainer open={open} onOpenChange={setOpen} title={editingId === null ? t('role.addTitle') : t('role.editTitle')} width={480} confirmText={t('common.save')} onConfirm={save}>
        <Form form={form} labelCol={{ span: 5 }} wrapperCol={{ span: 19 }} style={{ marginTop: 12 }}>
          <Form.Item name="code" label={t('role.code')} rules={[{ required: true, whitespace: true, message: t('role.codeRequired') }]}>
            <Input disabled={editingId !== null} placeholder={t('role.code')} />
          </Form.Item>
          <Form.Item name="name" label={t('role.name')} rules={[{ required: true, whitespace: true, message: t('role.nameRequired') }]}>
            <Input placeholder={t('role.name')} />
          </Form.Item>
          <Form.Item name="sort" label={t('role.sort')}><InputNumber min={0} style={{ width: 160 }} /></Form.Item>
          <Form.Item name="remark" label={t('role.remark')}><Input.TextArea autoSize={{ minRows: 2 }} placeholder={t('role.remark')} /></Form.Item>
          <Form.Item name="enabled" label={t('common.status')} valuePropName="checked"><Switch /></Form.Item>
          {isSuperAdmin && <Form.Item name="isDelegatable" label={t('role.isDelegatable')} valuePropName="checked"><Switch /></Form.Item>}
        </Form>
      </FormContainer>

      {/* 授权菜单 */}
      <FormContainer open={showMenus} onOpenChange={setShowMenus} title={t('role.grantMenus')} width={820} confirmText={t('common.save')} onConfirm={saveMenus}>
        <GrantMenuTable tree={menuTree} granted={menuGranted} modules={modules} defaultModuleId={defaultModuleId} onCheckedChange={setMenuGranted} />
      </FormContainer>

      {/* 授权用户 */}
      <UserPicker ref={userPickerRef} onConfirm={onUserConfirm} />

      {/* 数据范围 */}
      <FormContainer open={showScope} onOpenChange={setShowScope} title={t('role.dataScope')} width={480} confirmText={t('common.save')} onConfirm={saveScope}>
        <Form labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} style={{ marginTop: 12 }}>
          <Form.Item label={t('role.scopeType')}>
            <Select value={scopeType} onChange={setScopeType} options={scopeOptions} />
          </Form.Item>
          {isCustom && (
            <Form.Item label={t('role.customOrgs')}>
              <OrgTreeSelect multiple value={customOrgIds} onChange={(v) => setCustomOrgIds((v as number[]) ?? [])} placeholder={t('role.customOrgsHint')} style={{ width: '100%' }} />
            </Form.Item>
          )}
        </Form>
      </FormContainer>
    </>
  )
}

// web/src/views/system/role/index.vue
<script setup lang="ts">
// 角色管理 = ProTable CRUD(照职位范式)+ 两个专属抽屉:授权菜单(勾选菜单树)、数据范围(选范围类型 + 自定义机构)。
// 删角色会**物理**删掉用户↔角色关联(不可恢复)——所以删前先查一次持有人数当面告知,单删与批量删都盖到,
// 只给行内按钮加警告的话,勾选 + 批量删就绕过去了。
import { computed, h, onMounted, reactive, ref } from 'vue'
import {
  NButton, NSpace, NInput, NInputNumber, NSwitch, NForm, NFormItem, NSelect, NDropdown,
  useMessage, type FormInst, type FormRules,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import AppIcon from '@/components/AppIcon.vue'
import FormContainer from '@/components/FormContainer/index.vue'
import StatusSwitch from '@/components/StatusSwitch/index.vue'
import OrgTreeSelect from '@/components/OrgTreeSelect/index.vue'
import UserPicker from '@/components/UserPicker/index.vue'
import GrantMenuTable from './components/GrantMenuTable.vue'
import { useConfirm } from '@/composables/useConfirm'
import { useBatchDelete } from '@/composables/useBatchDelete'
import { roleApi, menuApi, moduleApi, userApi } from '@/api'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'
import { DataScopeType, type ModuleRow, type RoleInput, type SysRole } from '@/types/api'
import type { MenuTreeNode } from '@/types/menu'

const { t } = useI18n()
const message = useMessage()
const { confirm } = useConfirm()
const auth = useAuthStore()
const tableRef = ref<ProTableInst<SysRole>>()

/** 「未分配」哨兵:雪花 id 无 0,用它表示 moduleId==null 的顶级目录分组。 */
const UNASSIGNED = 0
/** 授权抽屉的「所属应用」下拉数据源。 */
const modules = ref<ModuleRow[]>([])
onMounted(async () => {
  try {
    modules.value = await moduleApi.list()
  } catch {
    // 模块列表仅供授权抽屉的「所属应用」下拉;拉取失败不阻塞角色管理主流程。
  }
})

/**
 * 持有该角色的用户数。复用用户分页端点(Size=1 只要 total),不新开接口。
 * 查不到(如只有角色 CRUD、没有用户查询权限的管理员会 403)返回 null → 退回通用文案,不阻断删除:
 * 今天能删的人,改完照样能删,本次改动只加知情,不改变谁能删什么。
 */
async function countUsers(roleId: number): Promise<number | null> {
  try {
    const { total } = await userApi.page({ page: 1, pageSize: 1, roleId })
    return total
  } catch {
    return null
  }
}

const { checkedKeys, hasSelection, run: batchDelete } = useBatchDelete({
  remove: roleApi.batchRemove,
  refresh: () => tableRef.value?.refresh(),
  successMsg: t('role.deleted'),
  content: async (ids) => {
    const counts = await Promise.all(ids.map(countUsers))
    if (counts.some((n) => n === null)) return t('common.batchDeleteConfirm', { count: ids.length })
    const users = counts.reduce<number>((sum, n) => sum + n!, 0)
    return users === 0
      ? t('common.batchDeleteConfirm', { count: ids.length })
      : t('role.batchDeleteWithUsers', { count: ids.length, users })
  },
})

async function askDelete(r: SysRole) {
  const n = await countUsers(r.id)
  const content =
    n === null
      ? t('role.deleteConfirm', { name: r.name })
      : n === 0
        ? t('role.deleteConfirmNoUsers', { name: r.name })
        : t('role.deleteConfirmWithUsers', { name: r.name, count: n })
  const ok = await confirm({ content, type: 'error', action: () => roleApi.remove(r.id), successMsg: t('role.deleted') })
  if (ok) tableRef.value?.refresh()
}

const toInput = (r: SysRole): RoleInput => ({ name: r.name, code: r.code, sort: r.sort, enabled: r.enabled, remark: r.remark ?? '', isDelegatable: r.isDelegatable ?? false })

const columns: ProTableColumn<SysRole>[] = [
  { type: 'selection' },
  { key: 'code', title: () => t('role.code') },
  { key: 'name', title: () => t('role.name'), search: true },
  { key: 'sort', title: () => t('role.sort'), width: 80 },
  {
    key: 'enabled',
    title: () => t('common.status'),
    width: 90,
    render: (r) =>
      h(StatusSwitch, {
        value: r.enabled,
        disabled: !auth.isSuperAdmin || !auth.hasPerm('PUT:/api/v1/sys/role/{id}'),
        request: (next: boolean) => roleApi.update(r.id, { ...toInput(r), enabled: next }),
        'onUpdate:value': (v: boolean) => {
          r.enabled = v
        },
      }),
  },
  { key: 'remark', title: () => t('role.remark'), ellipsis: { tooltip: true }, render: (r) => r.remark || '—' },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 240,
    hideInSetting: true,
    render: (r) => {
      // QA36:角色定义(编辑/删除)与角色授权面(授权菜单/数据范围)为超管专属;
      // 仅"授权用户"(角色指派面)对普通管理员开放(经 RoleGrantPolicy 收口校验)。
      const dropdownOptions = [
        auth.isSuperAdmin && auth.hasPerm('PUT:/api/v1/sys/role/menu') ? { label: t('role.grantMenus'), key: 'menus' } : null,
        auth.isSuperAdmin && auth.hasPerm('PUT:/api/v1/sys/role/datascope') ? { label: t('role.dataScope'), key: 'scope' } : null,
        auth.hasPerm('PUT:/api/v1/sys/role/users') ? { label: t('role.grantUsers'), key: 'users' } : null,
      ].filter((o): o is { label: string; key: string } => o !== null)
      return h(NSpace, { size: 4, wrapItem: false }, () => [
        auth.isSuperAdmin && auth.hasPerm('PUT:/api/v1/sys/role/{id}')
          ? h(NButton, { size: 'small', quaternary: true, type: 'primary', onClick: () => openEdit(r) }, () => t('common.edit'))
          : null,
        auth.isSuperAdmin && auth.hasPerm('DELETE:/api/v1/sys/role/{id}')
          ? h(NButton, { size: 'small', quaternary: true, type: 'error', onClick: () => askDelete(r) }, () => t('common.delete'))
          : null,
        dropdownOptions.length
          ? h(NDropdown, {
              options: dropdownOptions,
              onSelect: (key: string) => {
                if (key === 'menus') openMenus(r)
                else if (key === 'scope') openScope(r)
                else openUsers(r)
              },
            }, () => h(NButton, { size: 'small', quaternary: true }, () => t('common.more')))
          : null,
      ])
    },
  },
]

// ── 新增/编辑弹窗 ──
const show = ref(false)
const formRef = ref<FormInst | null>(null)
const editingId = ref<number | null>(null)
const rules: FormRules = {
  code: { required: true, whitespace: true, message: () => t('role.codeRequired'), trigger: ['input', 'blur'] },
  name: { required: true, whitespace: true, message: () => t('role.nameRequired'), trigger: ['input', 'blur'] },
}
const blank = (): RoleInput => ({ name: '', code: '', sort: 0, enabled: true, remark: '', isDelegatable: false })
const form = reactive<RoleInput>(blank())

function openAdd() {
  editingId.value = null
  Object.assign(form, blank())
  show.value = true
}
function openEdit(r: SysRole) {
  editingId.value = r.id
  Object.assign(form, toInput(r))
  show.value = true
}
async function save() {
  await formRef.value?.validate()
  try {
    if (editingId.value === null) await roleApi.add({ ...form })
    else await roleApi.update(editingId.value, { ...form })
    message.success(t('role.saved'))
    await tableRef.value?.refresh()
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}

// ── 授权菜单抽屉(分组表格 → 全量替换角色授权)──
const showMenus = ref(false)
const menuTree = ref<MenuTreeNode[]>([])
const menuGranted = ref<number[]>([])
const menuRoleId = ref<number | null>(null)
const defaultModuleId = ref(UNASSIGNED)

async function openMenus(r: SysRole) {
  menuRoleId.value = r.id
  try {
    const [tree, granted] = await Promise.all([menuApi.tree(), roleApi.getMenus(r.id)])
    menuTree.value = tree
    menuGranted.value = granted
    defaultModuleId.value = auth.currentModuleId ?? modules.value[0]?.id ?? UNASSIGNED
    showMenus.value = true
  } catch (e) {
    message.error(translateError(e))
  }
}
function onMenuCheckedUpdate(ids: number[]) {
  menuGranted.value = ids
}
async function saveMenus() {
  if (menuRoleId.value === null) return
  try {
    await roleApi.setMenus(menuRoleId.value, menuGranted.value)
    message.success(t('role.grantSaved'))
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}

// ── 授权用户(UserPicker) ──
const userPickerRef = ref<InstanceType<typeof UserPicker> | null>(null)
const userRoleId = ref<number | null>(null)

async function openUsers(r: SysRole) {
  userRoleId.value = r.id
  try {
    const ids = await roleApi.getUsers(r.id)
    userPickerRef.value?.open(ids)
  } catch (e) {
    message.error(translateError(e))
  }
}
async function onUserConfirm(ids: number[]) {
  if (userRoleId.value === null) return
  try {
    await roleApi.setUsers(userRoleId.value, ids)
    // 连续保存时替换上一条同类成功提示,避免两条“用户授权已保存”同时挂在页面上。
    message.destroyAll()
    message.success(t('role.grantUsersSaved'))
  } catch (e) {
    message.error(translateError(e))
  }
}

// ── 数据范围抽屉 ──
const showScope = ref(false)
const scopeRoleId = ref<number | null>(null)
const scopeForm = reactive<{ scopeType: DataScopeType; customOrgIds: number[] }>({ scopeType: DataScopeType.Org, customOrgIds: [] })
const isCustom = computed(() => scopeForm.scopeType === DataScopeType.Custom)
const scopeOptions = computed(() => [
  { label: t('role.scope.all'), value: DataScopeType.All },
  { label: t('role.scope.org'), value: DataScopeType.Org },
  { label: t('role.scope.orgAndChildren'), value: DataScopeType.OrgAndChildren },
  { label: t('role.scope.self'), value: DataScopeType.Self },
  { label: t('role.scope.custom'), value: DataScopeType.Custom },
])
async function openScope(r: SysRole) {
  scopeRoleId.value = r.id
  try {
    const cfg = await roleApi.getDataScope(r.id)
    scopeForm.scopeType = cfg?.scopeType ?? DataScopeType.Org
    scopeForm.customOrgIds = cfg?.customOrgIds ? cfg.customOrgIds.split(',').filter(Boolean).map(Number) : []
    showScope.value = true
  } catch (e) {
    message.error(translateError(e))
  }
}
async function saveScope() {
  if (scopeRoleId.value === null) return
  try {
    await roleApi.setDataScope(scopeRoleId.value, scopeForm.scopeType, isCustom.value ? scopeForm.customOrgIds : undefined)
    message.success(t('role.scopeSaved'))
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}
</script>

<template>
  <ProTable
    ref="tableRef"
    :columns="columns"
    :fetcher="roleApi.page"
    storage-key="sys-role"
    :checked-row-keys="checkedKeys"
    @update:checked-row-keys="(keys: (string | number)[]) => (checkedKeys = keys)"
    @error="(e) => message.error(translateError(e))"
  >
    <template #toolbar>
      <n-button v-if="auth.isSuperAdmin" v-auth="'POST:/api/v1/sys/role/add'" type="primary" @click="openAdd">
        <template #icon><AppIcon icon="ph:plus" :size="16" /></template>{{ t('common.add') }}
      </n-button>
      <n-button
        v-if="auth.isSuperAdmin"
        v-auth="'POST:/api/v1/sys/role/batch-delete'"
        type="error"
        :disabled="!hasSelection"
        @click="batchDelete"
      >
        <template #icon><AppIcon icon="ph:trash" :size="16" /></template>{{ t('common.batchDelete') }}
      </n-button>
    </template>
  </ProTable>

  <!-- 新增/编辑 -->
  <FormContainer
    v-model:show="show"
    :title="editingId === null ? t('role.addTitle') : t('role.editTitle')"
    :width="480"
    :on-confirm="save"
    :confirm-text="t('common.save')"
  >
    <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" :label-width="80">
      <n-form-item :label="t('role.code')" path="code">
        <n-input v-model:value="form.code" :placeholder="t('role.code')" :disabled="editingId !== null" />
      </n-form-item>
      <n-form-item :label="t('role.name')" path="name">
        <n-input v-model:value="form.name" :placeholder="t('role.name')" />
      </n-form-item>
      <n-form-item :label="t('role.sort')">
        <n-input-number v-model:value="form.sort" :min="0" style="width: 160px" />
      </n-form-item>
      <n-form-item :label="t('role.remark')">
        <n-input v-model:value="(form.remark as string)" type="textarea" :rows="2" :placeholder="t('role.remark')" />
      </n-form-item>
      <n-form-item :label="t('common.status')">
        <n-switch v-model:value="form.enabled" />
      </n-form-item>
      <n-form-item v-if="auth.isSuperAdmin" :label="t('role.isDelegatable')">
        <n-switch v-model:value="(form.isDelegatable as boolean)" />
      </n-form-item>
    </n-form>
  </FormContainer>

  <!-- 授权菜单 -->
  <FormContainer
    v-model:show="showMenus"
    :title="t('role.grantMenus')"
    :width="820"
    :on-confirm="saveMenus"
    :confirm-text="t('common.save')"
  >
    <GrantMenuTable
      :tree="menuTree"
      :granted="menuGranted"
      :modules="modules"
      :default-module-id="defaultModuleId"
      @update:checked="onMenuCheckedUpdate"
    />
  </FormContainer>

  <!-- 授权用户 -->
  <UserPicker ref="userPickerRef" @confirm="onUserConfirm" />

  <!-- 数据范围 -->
  <FormContainer
    v-model:show="showScope"
    :title="t('role.dataScope')"
    :width="480"
    :on-confirm="saveScope"
    :confirm-text="t('common.save')"
  >
    <n-form :model="scopeForm" label-placement="left" :label-width="90">
      <n-form-item :label="t('role.scopeType')">
        <n-select v-model:value="scopeForm.scopeType" :options="scopeOptions" />
      </n-form-item>
      <n-form-item v-if="isCustom" :label="t('role.customOrgs')">
        <OrgTreeSelect v-model:value="scopeForm.customOrgIds" multiple :placeholder="t('role.customOrgsHint')" />
      </n-form-item>
    </n-form>
  </FormContainer>
</template>
