// web/src/components/UserPicker/index.vue
<script setup lang="ts">
import { computed, h, onMounted, reactive, ref, unref } from 'vue'
import { NButton, NEmpty, NInput, NTree, useMessage } from 'naive-ui'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import FormContainer from '@/components/FormContainer/index.vue'
import { orgApi, userApi } from '@/api'
import { buildTree } from '@/utils/tree'
import { translateError } from '@/utils/error'
import type { SysOrg, UserItem } from '@/types/api'

const props = defineProps<{ excludeIds?: number[] }>()
const emit = defineEmits<{ (e: 'confirm', ids: number[]): void }>()

const { t } = useI18n()
const message = useMessage()

const show = ref(false)
const tableRef = ref<ProTableInst<UserItem>>()

// ── 机构树(左面板) ──
const orgFlat = ref<SysOrg[]>([])
const orgTree = computed(() => {
  const all = { id: 0, parentId: -1, name: t('common.all'), children: buildTree(orgFlat.value) }
  return [all]
})
const selectedOrgKey = ref<number | null>(null)
const orgId = computed(() => (selectedOrgKey.value && selectedOrgKey.value !== 0 ? selectedOrgKey.value : undefined))

onMounted(async () => {
  try { orgFlat.value = await orgApi.list() } catch { /* 静默 */ }
})

function onOrgSelect(keys: Array<string | number>) {
  selectedOrgKey.value = (keys[0] as number) ?? null
  tableRef.value?.refresh()
}

// ── 可选用户表(中间面板) ──
const checkedKeys = ref<(string | number)[]>([])
const excludeSet = computed(() => new Set(props.excludeIds ?? []))

const fetcher = (params: { page: number; pageSize: number; name?: string }) =>
  userApi.page({ page: params.page, pageSize: params.pageSize, name: params.name, orgId: orgId.value })

const columns: ProTableColumn<UserItem>[] = [
  { type: 'selection' },
  { key: 'name', title: () => t('user.name'), width: 100 },
  { key: 'account', title: () => t('user.account'), width: 120, search: true },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 70,
    render: (r) => {
      const already = selectedSet.value.has(r.id) || excludeSet.value.has(r.id)
      return h(NButton, {
        size: 'tiny', type: 'primary', quaternary: true, disabled: already,
        onClick: () => addUsers([r]),
      }, () => already ? t('userPicker.added') : t('userPicker.add'))
    },
  },
]

// ── 已选用户(右面板) ──
const selected = reactive<UserItem[]>([])
const selectedSet = computed(() => new Set(selected.map((u) => u.id)))
const selectedSearch = ref('')
const filteredSelected = computed(() => {
  const q = selectedSearch.value.trim().toLowerCase()
  if (!q) return selected
  return selected.filter((u) => u.name.toLowerCase().includes(q) || u.account.toLowerCase().includes(q))
})

function addUsers(users: UserItem[]) {
  for (const u of users) {
    if (!selectedSet.value.has(u.id) && !excludeSet.value.has(u.id)) {
      selected.push(u)
    }
  }
}

function addChecked() {
  const rows = unref(tableRef.value?.rows)?.filter((r) => checkedKeys.value.includes(r.id)) ?? []
  addUsers(rows)
  checkedKeys.value = []
}

function removeUser(id: number) {
  const idx = selected.findIndex((u) => u.id === id)
  if (idx >= 0) selected.splice(idx, 1)
}

function clearSelected() {
  selected.splice(0, selected.length)
}

// ── 公共 API ──
async function open(ids?: number[]) {
  selected.splice(0, selected.length)
  checkedKeys.value = []
  selectedSearch.value = ''
  selectedOrgKey.value = null
  show.value = true

  if (ids?.length) {
    try {
      // ponytail: 拉一页足够大的列表,靠 id 过滤;admin 系统用户量有限,9999 够用
      const { items } = await userApi.page({ page: 1, pageSize: 9999 })
      const all = items.filter((u) => ids.includes(u.id))
      // 没拉到的 id(翻页之外),退回只显示 id
      const found = new Set(all.map((u) => u.id))
      for (const u of all) selected.push(u)
      for (const id of ids) {
        if (!found.has(id)) selected.push({ id, account: String(id), name: String(id) } as UserItem)
      }
    } catch {
      for (const id of ids) selected.push({ id, account: String(id), name: String(id) } as UserItem)
    }
  }
}

async function handleConfirm() {
  const ids = selected.map((u) => u.id)
  emit('confirm', ids)
}

defineExpose({ open })
</script>

<template>
  <FormContainer
    v-model:show="show"
    :title="t('userPicker.title')"
    :width="1100"
    :on-confirm="handleConfirm"
    :confirm-text="t('common.confirm')"
  >
    <div class="user-picker">
      <!-- 左面板:机构树 -->
      <div class="picker-tree">
        <div class="panel-header">{{ t('org.title') }}</div>
        <n-tree
          :data="orgTree"
          key-field="id"
          label-field="name"
          children-field="children"
          selectable
          block-line
          default-expand-all
          :selected-keys="selectedOrgKey != null ? [selectedOrgKey] : []"
          @update:selected-keys="onOrgSelect"
        />
      </div>

      <!-- 中间面板:可选用户 -->
      <div class="picker-table">
        <div class="panel-header">
          <span>{{ t('userPicker.available') }}</span>
          <n-button size="tiny" type="primary" :disabled="checkedKeys.length === 0" @click="addChecked">
            {{ t('userPicker.addChecked') }}({{ checkedKeys.length }})
          </n-button>
        </div>
        <ProTable
          ref="tableRef"
          :columns="columns"
          :fetcher="fetcher"
          :pagination="{ pageSize: 10 }"
          size="small"
          storage-key="user-picker"
          :tool-button="false"
          :checked-row-keys="checkedKeys"
          @update:checked-row-keys="(keys: (string | number)[]) => (checkedKeys = keys)"
          @error="(e) => message.error(translateError(e))"
        />
      </div>

      <!-- 右面板:已选用户 -->
      <div class="picker-selected">
        <div class="panel-header">
          <span>{{ t('userPicker.selected') }}({{ selected.length }})</span>
          <n-button size="tiny" quaternary type="error" :disabled="selected.length === 0" @click="clearSelected">
            {{ t('userPicker.clear') }}
          </n-button>
        </div>
        <n-input
          v-model:value="selectedSearch"
          size="small"
          clearable
          :placeholder="t('common.search')"
          style="margin-bottom: 8px"
        />
        <div class="selected-list">
          <div v-for="u in filteredSelected" :key="u.id" class="selected-item">
            <span class="selected-name">{{ u.name }}<span class="selected-account">({{ u.account }})</span></span>
            <n-button size="tiny" quaternary type="error" @click="removeUser(u.id)">
              <template #icon><AppIcon icon="ph:x" :size="14" /></template>
            </n-button>
          </div>
          <n-empty v-if="filteredSelected.length === 0" :description="t('common.noData')" style="padding: 24px 0" />
        </div>
      </div>
    </div>
  </FormContainer>
</template>

<style scoped>
.user-picker {
  display: flex;
  gap: 12px;
  min-height: 400px;
}
.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 13px;
  font-weight: 600;
  padding: 0 0 8px;
  border-bottom: 1px solid var(--n-border-color, #e0e0e6);
  margin-bottom: 8px;
}
.picker-tree {
  width: 160px;
  flex-shrink: 0;
  overflow: auto;
  border-right: 1px solid var(--n-border-color, #e0e0e6);
  padding-right: 12px;
}
.picker-table {
  flex: 1;
  min-width: 0;
  overflow: hidden;
}
.picker-selected {
  width: 200px;
  flex-shrink: 0;
  border-left: 1px solid var(--n-border-color, #e0e0e6);
  padding-left: 12px;
  display: flex;
  flex-direction: column;
}
.selected-list {
  flex: 1;
  overflow: auto;
  max-height: 380px;
}
.selected-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 4px 0;
  font-size: 13px;
  border-bottom: 1px solid var(--n-border-color, #e0e0e6);
}
.selected-item:last-child { border-bottom: none; }
.selected-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.selected-account { color: var(--n-text-color-disabled, #999); font-size: 12px; margin-left: 2px; }
</style>

// web-react/src/components/UserPicker.tsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState, type CSSProperties } from 'react'
import { Button, Empty, Input, Tree, type TreeProps } from 'antd'
import { useTranslation } from 'react-i18next'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import type { ProColumns } from '@ant-design/pro-components'
import { FormContainer } from '@/components/FormContainer'
import { orgApi, userApi } from '@/api'
import { buildTree } from '@/utils/tree'
import type { SysOrg, UserItem } from '@/types/api'

/** 面板里只需要这三个字段;open(ids) 回显时找不到的用户也只造得出这三个(占位)。 */
export type PickedUser = Pick<UserItem, 'id' | 'name' | 'account'>

// ── 纯逻辑(变异钉死;组件只做接线)──────────────────────────────

/** 机构树选中 key → orgId 过滤值:根「全部」(key 0)或未选(null)→ undefined(不按部门过滤)。
 *  `|| undefined`:0 与 null 都 falsy → undefined;别写成 `?? undefined`(那会把 key 0「全部」当有效部门传下去)。 */
export function orgIdFromKey(key: number | null): number | undefined {
  return key || undefined
}

/** 追加用户,去重:已在 current 或在 excludeIds 里的跳过。返回新数组(不改原)。 */
export function addUsers(current: PickedUser[], toAdd: PickedUser[], excludeIds: Set<number>): PickedUser[] {
  const has = new Set(current.map((u) => u.id))
  const out = [...current]
  for (const u of toAdd) {
    if (!has.has(u.id) && !excludeIds.has(u.id)) {
      has.add(u.id)
      out.push(u)
    }
  }
  return out
}

/** 移除指定 id。 */
export function removeUser(current: PickedUser[], id: number): PickedUser[] {
  return current.filter((u) => u.id !== id)
}

/** 已选列表本地搜索:按姓名/账号大小写不敏感包含;空 query 返回原列表。 */
export function filterSelected(list: PickedUser[], query: string): PickedUser[] {
  const q = query.trim().toLowerCase()
  if (!q) return list
  return list.filter((u) => u.name.toLowerCase().includes(q) || u.account.toLowerCase().includes(q))
}

/** open(ids) 回显:按 ids 顺序,fetched 里找得到的用真数据,找不到的(翻页之外)退回只显 id 的占位行。 */
export function hydrateSelected(ids: number[], fetched: PickedUser[]): PickedUser[] {
  const map = new Map(fetched.map((u) => [u.id, u]))
  return ids.map((id) => map.get(id) ?? { id, account: String(id), name: String(id) })
}

// ── 组件 ───────────────────────────────────────────────────────

export interface UserPickerHandle {
  /** 打开弹窗;传 ids 则预选回显(命令式,父经 ref 调用)。 */
  open: (ids?: number[]) => void
}
export interface UserPickerProps {
  /** 排除项(如别处已占用的用户 id):不可再选、行内「添加」置灰。 */
  excludeIds?: number[]
  onConfirm: (ids: number[]) => void
}

const panelHeader: CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  fontSize: 13, fontWeight: 600, padding: '0 0 8px',
  borderBottom: '1px solid var(--color-border, #e0e0e6)', marginBottom: 8,
}
const rowItem: CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  padding: '4px 0', fontSize: 13, borderBottom: '1px solid var(--color-border, #e0e0e6)',
}

/**
 * 人员选择弹窗:左机构树 / 中可选用户表 / 右已选列表。命令式 `open(ids)` 经 ref 暴露,确认回调 `onConfirm(ids)`。
 * 固定 modal 形态(三面板不适合抽屉)。中间表用 <DataTable>(隔离 pro-components);**本版只保留每行「添加」,
 * 不做批量勾选** —— 勾选依赖 DataTable 尚未支持的 rowSelection + 当前页数据,待批量删除页需要它时统一补(ponytail)。
 */
export const UserPicker = forwardRef<UserPickerHandle, UserPickerProps>(function UserPicker({ excludeIds, onConfirm }, ref) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)
  const [orgFlat, setOrgFlat] = useState<SysOrg[]>([])
  const [selectedKey, setSelectedKey] = useState<number | null>(null)
  const [selected, setSelected] = useState<PickedUser[]>([])
  const [search, setSearch] = useState('')
  const tableRef = useRef<DataTableHandle>(null)

  const excludeSet = useMemo(() => new Set(excludeIds ?? []), [excludeIds])
  const selectedIds = useMemo(() => new Set(selected.map((u) => u.id)), [selected])
  const orgId = orgIdFromKey(selectedKey)

  useImperativeHandle(
    ref,
    () => ({
      open: async (ids?: number[]) => {
        setSelected([])
        setSearch('')
        setSelectedKey(null)
        setOpen(true)
        try {
          setOrgFlat(await orgApi.list())
        } catch {
          /* 静默:机构是配角 */
        }
        if (ids?.length) {
          try {
            // ponytail: 拉一页足够大的列表靠 id 过滤;admin 用户量有限,9999 够用
            const { items } = await userApi.page({ page: 1, pageSize: 9999 })
            setSelected(hydrateSelected(ids, items))
          } catch {
            setSelected(hydrateSelected(ids, [])) // 拉失败:全退占位,不丢 id
          }
        }
      },
    }),
    [],
  )

  // orgId(部门过滤)变化即重取中间表;open=false 时表未挂载,reload 是 no-op。
  useEffect(() => {
    tableRef.current?.reload()
  }, [orgId])

  const orgTree = useMemo(
    () => [{ id: 0, parentId: -1, name: t('common.all'), children: buildTree(orgFlat) }],
    [orgFlat, t],
  )

  const fetchUsers: PageFetcher<UserItem> = (q) =>
    userApi.page({ page: q.page, pageSize: q.pageSize, name: typeof q.name === 'string' ? q.name : undefined, orgId })

  const columns = useMemo<ProColumns<UserItem>[]>(
    () => [
      { title: t('user.name'), dataIndex: 'name', search: false },
      { title: t('user.account'), dataIndex: 'account' },
      {
        title: t('common.operation'), key: 'op', search: false, width: 72,
        render: (_, r) => {
          const already = selectedIds.has(r.id) || excludeSet.has(r.id)
          return (
            <Button
              type="link" size="small" disabled={already}
              onClick={() => setSelected((cur) => addUsers(cur, [r], excludeSet))}
            >
              {already ? t('userPicker.added') : t('userPicker.add')}
            </Button>
          )
        },
      },
    ],
    [t, selectedIds, excludeSet],
  )

  const onOrgSelect: TreeProps['onSelect'] = (keys) => setSelectedKey((keys[0] as number) ?? null)
  const filtered = filterSelected(selected, search)

  return (
    <FormContainer
      open={open}
      onOpenChange={setOpen}
      variant="modal"
      title={t('userPicker.title')}
      width={1100}
      onConfirm={() => onConfirm(selected.map((u) => u.id))}
    >
      <div style={{ display: 'flex', gap: 12, minHeight: 400 }}>
        {/* 左:机构树 */}
        <div style={{ width: 180, flexShrink: 0, overflow: 'auto', borderRight: '1px solid var(--color-border, #e0e0e6)', paddingRight: 12 }}>
          <div style={panelHeader}>{t('org.title')}</div>
          <Tree
            treeData={orgTree as unknown as TreeProps['treeData']}
            fieldNames={{ title: 'name', key: 'id', children: 'children' }}
            selectedKeys={selectedKey != null ? [selectedKey] : []}
            onSelect={onOrgSelect}
            defaultExpandAll
            blockNode
          />
        </div>

        {/* 中:可选用户表 */}
        <div style={{ flex: 1, minWidth: 0, overflow: 'hidden' }}>
          <div style={panelHeader}>{t('userPicker.available')}</div>
          <DataTable<UserItem> ref={tableRef} columns={columns} fetcher={fetchUsers} rowKey="id" />
        </div>

        {/* 右:已选列表 */}
        <div style={{ width: 220, flexShrink: 0, borderLeft: '1px solid var(--color-border, #e0e0e6)', paddingLeft: 12, display: 'flex', flexDirection: 'column' }}>
          <div style={panelHeader}>
            <span>{t('userPicker.selected')}({selected.length})</span>
            <Button type="link" size="small" danger disabled={selected.length === 0} onClick={() => setSelected([])}>
              {t('userPicker.clear')}
            </Button>
          </div>
          <Input value={search} onChange={(e) => setSearch(e.target.value)} allowClear size="small" placeholder={t('common.search')} style={{ marginBottom: 8 }} />
          <div style={{ flex: 1, overflow: 'auto', maxHeight: 380 }}>
            {filtered.map((u) => (
              <div key={u.id} style={rowItem}>
                <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {u.name}
                  <span style={{ color: 'var(--color-text-3, #999)', fontSize: 12, marginLeft: 2 }}>({u.account})</span>
                </span>
                <Button type="link" size="small" danger onClick={() => setSelected((cur) => removeUser(cur, u.id))}>
                  {t('common.delete')}
                </Button>
              </div>
            ))}
            {filtered.length === 0 && <Empty description={t('common.noData')} style={{ padding: '24px 0' }} />}
          </div>
        </div>
      </div>
    </FormContainer>
  )
})
