// web-react/src/views/workflow/definition/components/WfAddNode.tsx
// 节点间大圆加号;Popover 提供当前可插入节点。对应 Vue 侧 WfAddNode.vue。
import { useState } from 'react'
import { Popover } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import type { WfInsertableNodeType } from '@/workflow/schema'
import './wf-designer.css'
import '../../wf-identity.css'

const MENU: ReadonlyArray<{ type: WfInsertableNodeType; icon: string }> = [
  { type: 'approval', icon: 'ph:user-circle-check' },
  { type: 'cc', icon: 'ph:paper-plane-tilt' },
  { type: 'branch', icon: 'ph:git-branch' },
  { type: 'parallel', icon: 'ph:git-merge' },
  { type: 'webhook', icon: 'ph:webhooks-logo' },
]

export interface WfAddNodeProps {
  /**
   * 默认展示并行;仅并行臂内由父链显式传 false。Vue 侧曾因布尔缺省吞掉菜单项而整条并行入口消失,
   * 这里同样**必须**默认 true——调用方漏传不能退化成禁用。
   */
  allowParallel?: boolean
  onAdd: (type: WfInsertableNodeType) => void
}

export function WfAddNode({ allowParallel = true, onAdd }: WfAddNodeProps) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)

  const pick = (type: WfInsertableNodeType) => {
    setOpen(false)
    onAdd(type)
  }

  const content = (
    <div className="wf-add-grid">
      {MENU.filter((item) => item.type !== 'parallel' || allowParallel !== false).map((item) => (
        <button key={item.type} type="button" className="wf-add-item" onClick={() => pick(item.type)}>
          <span className={`wf-add-icon is-${item.type}`}><AppIcon icon={item.icon} size={22} /></span>
          <span className="wf-add-label">{t(`workflow.node.${item.type}`)}</span>
        </button>
      ))}
    </div>
  )

  return (
    <div className="wf-add">
      <Popover open={open} onOpenChange={setOpen} trigger="click" placement="rightTop" arrow={false} content={content}>
        <button type="button" className="wf-add-btn" aria-label={t('workflow.designer.addNode')} title={t('workflow.designer.addNode')}>
          <AppIcon icon="ph:plus-bold" size={16} />
        </button>
      </Popover>
    </div>
  )
}

// web/src/views/workflow/definition/components/WfAddNode.vue
<script setup lang="ts">
// 节点间大圆加号;Popover 提供当前可插入节点。
import { ref } from 'vue'
import { NPopover } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import type { WfInsertableNodeType } from '@/workflow/schema'
import '../../wf-identity.css'

const emit = defineEmits<{ add: [type: WfInsertableNodeType] }>()
/** 默认展示并行;仅并行臂内由父链显式传 false。未传时不能落成 false(Vue 布尔缺省会吞掉菜单项)。 */
withDefaults(defineProps<{ allowParallel?: boolean }>(), { allowParallel: true })
const { t } = useI18n()
const open = ref(false)

function pick(type: WfInsertableNodeType) {
  open.value = false
  emit('add', type)
}
</script>

<template>
  <div class="wf-add">
    <n-popover v-model:show="open" trigger="click" placement="right-start" :show-arrow="false">
      <template #trigger>
        <button type="button" class="wf-add-btn" :aria-label="t('workflow.designer.addNode')" :title="t('workflow.designer.addNode')">
          <AppIcon icon="ph:plus-bold" :size="16" />
        </button>
      </template>
      <div class="wf-add-grid">
        <button type="button" class="wf-add-item" @click="pick('approval')">
          <span class="wf-add-icon is-approval"><AppIcon icon="ph:user-circle-check" :size="22" /></span>
          <span class="wf-add-label">{{ t('workflow.node.approval') }}</span>
        </button>
        <button type="button" class="wf-add-item" @click="pick('cc')">
          <span class="wf-add-icon is-cc"><AppIcon icon="ph:paper-plane-tilt" :size="22" /></span>
          <span class="wf-add-label">{{ t('workflow.node.cc') }}</span>
        </button>
        <button type="button" class="wf-add-item" @click="pick('branch')">
          <span class="wf-add-icon is-branch"><AppIcon icon="ph:git-branch" :size="22" /></span>
          <span class="wf-add-label">{{ t('workflow.node.branch') }}</span>
        </button>
        <button v-if="allowParallel !== false" type="button" class="wf-add-item" @click="pick('parallel')">
          <span class="wf-add-icon is-parallel"><AppIcon icon="ph:git-merge" :size="22" /></span>
          <span class="wf-add-label">{{ t('workflow.node.parallel') }}</span>
        </button>
        <button type="button" class="wf-add-item" @click="pick('webhook')">
          <span class="wf-add-icon is-webhook"><AppIcon icon="ph:webhooks-logo" :size="22" /></span>
          <span class="wf-add-label">{{ t('workflow.node.webhook') }}</span>
        </button>
      </div>
    </n-popover>
  </div>
</template>

<style scoped>
.wf-add {
  position: relative;
  display: flex;
  justify-content: center;
  width: 220px;
  padding: 18px 0 26px;
  flex-shrink: 0;
}
.wf-add::before {
  content: '';
  position: absolute;
  inset: 0;
  margin: auto;
  width: 2px;
  height: 100%;
  background: #c8c9cc;
  z-index: 0;
}
.wf-add-btn {
  position: relative;
  z-index: 1;
  width: 32px;
  height: 32px;
  border: none;
  border-radius: 50%;
  background: var(--wf-accent);
  color: #fff;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(24, 26, 42, 0.16);
  transition: transform 0.28s cubic-bezier(0.645, 0.045, 0.355, 1), box-shadow var(--transition-base);
}
.wf-add-btn:hover {
  transform: scale(1.28);
  box-shadow: 0 8px 18px rgba(24, 26, 42, 0.16);
}
.wf-add-btn:active {
  transform: scale(1);
}
.wf-add-btn:focus-visible {
  outline: 2px solid var(--wf-accent);
  outline-offset: 3px;
}

.wf-add-grid {
  width: min(360px, calc(100vw - 64px));
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(104px, 1fr));
  gap: 8px;
}
.wf-add-item {
  display: flex;
  align-items: center;
  gap: 10px;
  margin: 0;
  padding: 10px 12px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-fill);
  cursor: pointer;
  text-align: left;
  color: var(--color-text-primary);
  transition: background var(--transition-fast), box-shadow var(--transition-fast), border-color var(--transition-fast);
}
.wf-add-item:hover {
  background: var(--color-bg-elevated);
  border-color: var(--color-border-strong);
  box-shadow: var(--shadow-1);
}
.wf-add-icon {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  background: var(--color-bg-container);
  border: 1px solid var(--color-border);
}
.wf-add-icon.is-approval { color: var(--wf-approval); }
.wf-add-icon.is-cc { color: var(--wf-cc); }
.wf-add-icon.is-branch { color: var(--color-primary); }
.wf-add-icon.is-parallel { color: var(--color-warning); }
.wf-add-icon.is-webhook { color: var(--color-info); }
.wf-add-label {
  font-size: var(--font-size-sm);
  font-weight: 500;
}

:global(html[data-theme='dark']) .wf-add::before {
  background: #5a5c64;
}
</style>
