// web-react/src/views/workflow/definition/components/WfNodeChain.tsx
// 单条局部链的递归展示层:只上抛稳定 Id/节点类型/名称,不修改传入模型。对应 Vue 侧 WfNodeChain.vue。
import type { FocusEvent, KeyboardEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import type { WfInsertableNodeType, WfNode } from '@/workflow/schema'
import { WfAddNode } from './WfAddNode'
import { WfNodeCard } from './WfNodeCard'
import './wf-designer.css'
import '../../wf-identity.css'

/** 分支臂与并行臂的显示交集(并行臂没有 isDefault)。 */
interface WfDisplayArm {
  id: string
  name: string
  next?: WfNode | null
  isDefault?: boolean
}

export interface WfNodeChainProps {
  root?: WfNode | null
  selectedId?: string | null
  errorSet: Set<string>
  terminal?: boolean
  readonly?: boolean
  visitedSet?: Set<string>
  currentSet?: Set<string>
  /** 设计器默认可插并行;并行臂内递归显式传 false 禁止嵌套。 */
  allowParallel?: boolean
  onSelect: (nodeId: string) => void
  onAddAfter: (afterId: string, type: WfInsertableNodeType) => void
  onAddAtArmHead: (ownerId: string, armId: string, type: WfInsertableNodeType) => void
  onRemoveNode: (nodeId: string) => void
  onAddArm: (ownerId: string) => void
  onRemoveArm: (ownerId: string, armId: string) => void
  onRenameArm: (ownerId: string, armId: string, name: string) => void
}

/** 本组件只展开当前局部 next 链;分支臂由下面递归渲染,避免把臂节点重复画进主链。 */
function chainOf(root: WfNode | null | undefined): WfNode[] {
  const nodes: WfNode[] = []
  let current = root ?? null
  while (current) {
    nodes.push(current)
    current = current.next ?? null
  }
  return nodes
}

function armsFor(node: WfNode): WfDisplayArm[] {
  if (node.type === 'branch') return node.conditions ?? []
  if (node.type === 'parallel') return node.parallelArms ?? []
  return []
}

export function WfNodeChain(props: WfNodeChainProps) {
  const {
    root, selectedId, errorSet, terminal, readonly, visitedSet, currentSet, allowParallel = true,
    onSelect, onAddAfter, onAddAtArmHead, onRemoveNode, onAddArm, onRemoveArm, onRenameArm,
  } = props
  const { t } = useTranslation()

  return (
    <div className="wf-chain">
      {chainOf(root).map((node) => {
        const arms = armsFor(node)
        const isOwner = node.type === 'branch' || node.type === 'parallel'
        // 并行臂内禁止再嵌套并行;非并行节点沿用父链的许可。
        const armAllowParallel = node.type !== 'parallel' && allowParallel
        const addArmKey = node.type === 'parallel' ? 'workflow.designer.addParallelArm' : 'workflow.designer.addArm'

        return (
          <div key={node.id} className="wf-chain-node">
            <WfNodeCard
              node={node}
              active={selectedId === node.id}
              error={errorSet.has(node.id)}
              readonly={readonly}
              visited={visitedSet?.has(node.id) ?? false}
              current={currentSet?.has(node.id) ?? false}
              onSelect={() => onSelect(node.id)}
              onRemove={() => onRemoveNode(node.id)}
            />

            {isOwner ? (
              <section
                className={`wf-branch${node.type === 'parallel' ? ' wf-parallel' : ''}`}
                aria-label={t(`workflow.node.${node.type}`)}
              >
                <div className="wf-branch-toolbar">
                  <span>
                    {node.type === 'parallel'
                      ? t('workflow.designer.parallelArmCount', { count: arms.length })
                      : t('workflow.designer.armCount', { count: arms.length })}
                  </span>
                  {!readonly ? (
                    <button
                      type="button"
                      className="wf-arm-action wf-arm-add"
                      aria-label={t(addArmKey)}
                      onClick={() => onAddArm(node.id)}
                    >
                      <AppIcon icon="ph:plus-bold" size={13} />
                      <span>{t(addArmKey)}</span>
                    </button>
                  ) : null}
                </div>

                <div className="wf-branch-arms">
                  {arms.map((arm) => (
                    <article key={arm.id} className="wf-arm">
                      <header className="wf-arm-head">
                        {!readonly ? (
                          <ArmNameInput
                            armId={arm.id}
                            name={arm.name}
                            placeholder={t('workflow.designer.armName')}
                            onRename={(name) => onRenameArm(node.id, arm.id, name)}
                          />
                        ) : (
                          <span className="wf-arm-name">{arm.name || t('workflow.designer.armName')}</span>
                        )}
                        {arm.isDefault ? (
                          <span className="wf-arm-default">{t('common.isDefault')}</span>
                        ) : !readonly ? (
                          <button
                            type="button"
                            className="wf-arm-action wf-arm-remove"
                            aria-label={t('common.delete')}
                            title={t('common.delete')}
                            onClick={() => onRemoveArm(node.id, arm.id)}
                          >
                            <AppIcon icon="ph:x" size={13} />
                          </button>
                        ) : null}
                      </header>

                      <div className="wf-arm-body">
                        {!readonly ? (
                          <WfAddNode
                            allowParallel={armAllowParallel}
                            onAdd={(type) => onAddAtArmHead(node.id, arm.id, type)}
                          />
                        ) : null}
                        {arm.next ? (
                          <WfNodeChain
                            {...props}
                            root={arm.next}
                            allowParallel={armAllowParallel}
                            terminal={false}
                          />
                        ) : null}
                        <div className="wf-arm-merge">
                          <span className="wf-arm-merge-dot" />
                          <span>{t('workflow.designer.merge')}</span>
                        </div>
                      </div>
                    </article>
                  ))}
                </div>
              </section>
            ) : null}

            {!readonly ? (
              <WfAddNode allowParallel={allowParallel} onAdd={(type) => onAddAfter(node.id, type)} />
            ) : null}
          </div>
        )
      })}

      {terminal ? (
        <div className="wf-chain-terminal">
          <span className="wf-chain-terminal-dot" />
          <span>{t('workflow.designer.end')}</span>
        </div>
      ) : null}
    </div>
  )
}

interface ArmNameInputProps {
  armId: string
  name: string
  placeholder: string
  onRename: (name: string) => void
}

/**
 * 臂名输入:**非受控**。每次按键都上抛会让整棵树 clone + 重挂,输入焦点与光标随之丢失
 * (Vue 侧用的是 `@change`,同一语义),因此只在失焦与回车时结算。
 */
function ArmNameInput({ armId, name, placeholder, onRename }: ArmNameInputProps) {
  const commit = (event: FocusEvent<HTMLInputElement> | KeyboardEvent<HTMLInputElement>) => {
    const value = event.currentTarget.value
    if (value !== name) onRename(value)
  }
  return (
    <input
      // armId 作 key:重命名后模型换了新对象但 key 不变,不会把用户正在编辑的输入重挂回旧值。
      key={armId}
      className="wf-arm-name"
      type="text"
      defaultValue={name}
      placeholder={placeholder}
      aria-label={placeholder}
      onBlur={commit}
      onKeyDown={(event) => {
        if (event.key === 'Enter') commit(event)
      }}
    />
  )
}

// web/src/views/workflow/definition/components/WfNodeChain.vue
<script setup lang="ts">
// 单条局部链的递归展示层:只上抛稳定 Id/节点类型/名称,不修改传入模型。
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import type { WfInsertableNodeType, WfNode } from '@/workflow/schema'
import WfAddNode from './WfAddNode.vue'
import WfNodeCard from './WfNodeCard.vue'
import '../../wf-identity.css'

const props = withDefaults(defineProps<{
  root: WfNode | null | undefined
  selectedId?: string | null
  errorSet: Set<string>
  terminal?: boolean
  readonly?: boolean
  visitedSet?: Set<string>
  currentSet?: Set<string>
  /** 设计器默认可插并行;并行臂内递归会显式传 false 禁止嵌套。 */
  allowParallel?: boolean
}>(), {
  allowParallel: true,
})
const emit = defineEmits<{
  select: [nodeId: string]
  'add-after': [afterId: string, type: WfInsertableNodeType]
  'add-at-arm-head': [branchId: string, armId: string, type: WfInsertableNodeType]
  'remove-node': [nodeId: string]
  'add-arm': [branchId: string]
  'remove-arm': [branchId: string, armId: string]
  'rename-arm': [branchId: string, armId: string, name: string]
}>()

const { t } = useI18n()

/** 本组件只展开当前局部 next 链;分支臂由模板递归,避免把臂节点重复渲染到主链。 */
const chain = computed(() => {
  const nodes: WfNode[] = []
  let current = props.root ?? null
  while (current) {
    nodes.push(current)
    current = current.next ?? null
  }
  return nodes
})

interface WfDisplayArm {
  id: string
  name: string
  next?: WfNode | null
  isDefault?: boolean
}

function armsFor(node: WfNode): WfDisplayArm[] {
  if (node.type === 'branch') return node.conditions ?? []
  if (node.type === 'parallel') return node.parallelArms ?? []
  return []
}

function renameArm(branchId: string, armId: string, event: Event) {
  emit('rename-arm', branchId, armId, (event.target as HTMLInputElement).value)
}

</script>

<template>
  <div class="wf-chain">
    <div v-for="node in chain" :key="node.id" class="wf-chain-node">
      <WfNodeCard
        :node="node"
        :active="selectedId === node.id"
        :error="errorSet.has(node.id)"
        :readonly="readonly"
        :visited="visitedSet?.has(node.id) ?? false"
        :current="currentSet?.has(node.id) ?? false"
        @select="emit('select', node.id)"
        @remove="emit('remove-node', node.id)"
      />

      <section
        v-if="node.type === 'branch' || node.type === 'parallel'"
        class="wf-branch"
        :class="{ 'wf-parallel': node.type === 'parallel' }"
        :aria-label="t(`workflow.node.${node.type}`)"
      >
        <div class="wf-branch-toolbar">
          <span>
            {{ node.type === 'parallel'
              ? t('workflow.designer.parallelArmCount', { count: armsFor(node).length })
              : t('workflow.designer.armCount', { count: armsFor(node).length }) }}
          </span>
          <button
            v-if="!readonly"
            type="button"
            class="wf-arm-action wf-arm-add"
            :aria-label="t(node.type === 'parallel' ? 'workflow.designer.addParallelArm' : 'workflow.designer.addArm')"
            @click="emit('add-arm', node.id)"
          >
            <AppIcon icon="ph:plus-bold" :size="13" />
            <span>{{ t(node.type === 'parallel' ? 'workflow.designer.addParallelArm' : 'workflow.designer.addArm') }}</span>
          </button>
        </div>

        <div class="wf-branch-arms">
          <article v-for="arm in armsFor(node)" :key="arm.id" class="wf-arm">
            <header class="wf-arm-head">
              <input
                v-if="!readonly"
                class="wf-arm-name"
                type="text"
                :value="arm.name"
                :placeholder="t('workflow.designer.armName')"
                :aria-label="t('workflow.designer.armName')"
                @change="renameArm(node.id, arm.id, $event)"
              >
              <span v-else class="wf-arm-name">{{ arm.name || t('workflow.designer.armName') }}</span>
              <span v-if="arm.isDefault" class="wf-arm-default">{{ t('common.isDefault') }}</span>
              <button
                v-else-if="!readonly"
                type="button"
                class="wf-arm-action wf-arm-remove"
                :aria-label="t('common.delete')"
                :title="t('common.delete')"
                @click="emit('remove-arm', node.id, arm.id)"
              >
                <AppIcon icon="ph:x" :size="13" />
              </button>
            </header>

            <div class="wf-arm-body">
              <WfAddNode
                v-if="!readonly"
                :allow-parallel="node.type !== 'parallel' && allowParallel"
                @add="(type) => emit('add-at-arm-head', node.id, arm.id, type)"
              />
              <WfNodeChain
                v-if="arm.next"
                :root="arm.next"
                :selected-id="selectedId"
                :error-set="errorSet"
                :readonly="readonly"
                :visited-set="visitedSet"
                :current-set="currentSet"
                :allow-parallel="node.type !== 'parallel' && allowParallel"
                :terminal="false"
                @select="(nodeId) => emit('select', nodeId)"
                @add-after="(afterId, type) => emit('add-after', afterId, type)"
                @add-at-arm-head="(branchId, armId, type) => emit('add-at-arm-head', branchId, armId, type)"
                @remove-node="(nodeId) => emit('remove-node', nodeId)"
                @add-arm="(branchId) => emit('add-arm', branchId)"
                @remove-arm="(branchId, armId) => emit('remove-arm', branchId, armId)"
                @rename-arm="(branchId, armId, name) => emit('rename-arm', branchId, armId, name)"
              />
              <div class="wf-arm-merge">
                <span class="wf-arm-merge-dot" />
                <span>{{ t('workflow.designer.merge') }}</span>
              </div>
            </div>
          </article>
        </div>
      </section>

      <WfAddNode v-if="!readonly" :allow-parallel="allowParallel" @add="(type) => emit('add-after', node.id, type)" />
    </div>

    <div v-if="terminal" class="wf-chain-terminal">
      <span class="wf-chain-terminal-dot" />
      <span>{{ t('workflow.designer.end') }}</span>
    </div>
  </div>
</template>

<style scoped>
.wf-chain,
.wf-chain-node {
  display: flex;
  flex-direction: column;
  align-items: center;
  min-width: max-content;
}

.wf-branch {
  position: relative;
  margin-top: var(--space-24);
  padding: var(--space-12) var(--space-16) var(--space-16);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: color-mix(in srgb, var(--color-bg-container) 92%, var(--color-primary-light));
  box-shadow: var(--shadow-1);
}
.wf-parallel {
  background: color-mix(in srgb, var(--color-bg-container) 92%, var(--color-warning-bg));
}
.wf-branch::before {
  content: '';
  position: absolute;
  top: calc(-1 * var(--space-24));
  left: 50%;
  width: 2px;
  height: var(--space-24);
  transform: translateX(-50%);
  background: var(--color-border-strong);
}
.wf-branch-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-16);
  min-height: var(--space-32);
  color: var(--color-text-tertiary);
  font-size: var(--font-size-xs);
}
.wf-branch-arms {
  display: flex;
  align-items: stretch;
  gap: var(--space-16);
  padding-top: var(--space-8);
}
.wf-arm {
  flex: 0 0 auto;
  width: max-content;
  min-width: calc(220px + var(--space-32));
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-bg-container);
}
.wf-arm-head {
  display: flex;
  align-items: center;
  gap: var(--space-8);
  min-height: var(--space-32);
  padding: var(--space-4) var(--space-8);
  border-bottom: 1px solid var(--color-border);
  background: var(--color-fill);
}
.wf-arm-name {
  flex: 1;
  min-width: 0;
  height: calc(var(--space-24) + 2px);
  padding: 0 var(--space-8);
  border: 1px solid transparent;
  border-radius: var(--radius-sm);
  outline: none;
  background: transparent;
  color: var(--color-text-primary);
  font: inherit;
  font-size: var(--font-size-sm);
}
.wf-arm-name:hover {
  border-color: var(--color-border-strong);
  background: var(--color-bg-container);
}
.wf-arm-name:focus-visible {
  border-color: var(--color-primary);
  background: var(--color-bg-container);
  box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 20%, transparent);
}
.wf-arm-default {
  flex-shrink: 0;
  padding: var(--space-4) var(--space-8);
  border-radius: 999px;
  background: var(--color-primary-light);
  color: var(--color-primary);
  font-size: var(--font-size-xs);
}
.wf-arm-action {
  border: 0;
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--color-text-secondary);
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-4);
}
.wf-arm-action:hover {
  background: var(--color-fill-hover);
  color: var(--color-text-primary);
}
.wf-arm-action:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 2px;
}
.wf-arm-add {
  min-height: calc(var(--space-24) + 2px);
  padding: 0 var(--space-8);
  color: var(--color-primary);
}
.wf-arm-remove {
  width: calc(var(--space-24) + 2px);
  height: calc(var(--space-24) + 2px);
  flex-shrink: 0;
}
.wf-arm-body {
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: calc(5 * var(--space-24) + var(--space-4));
  padding: 0 var(--space-16) var(--space-16);
}
.wf-arm-merge,
.wf-chain-terminal {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--space-4);
  color: var(--color-text-tertiary);
  font-size: var(--font-size-xs);
  letter-spacing: 0.04em;
}
.wf-arm-merge {
  position: relative;
  width: 100%;
  padding-top: var(--space-24);
}
.wf-arm-merge::before {
  content: '';
  position: absolute;
  top: 0;
  left: 50%;
  width: 2px;
  height: var(--space-24);
  transform: translateX(-50%);
  background: var(--color-border-strong);
}
.wf-arm-merge-dot,
.wf-chain-terminal-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--wf-end);
  box-shadow: 0 0 0 4px color-mix(in srgb, var(--wf-end) 16%, transparent);
}
.wf-chain-terminal {
  margin-top: calc(-1 * var(--space-8));
}

:global(html[data-theme='dark']) .wf-branch {
  background: color-mix(in srgb, var(--color-bg-container) 90%, var(--color-primary-light));
}
:global(html[data-theme='dark']) .wf-parallel {
  background: color-mix(in srgb, var(--color-bg-container) 90%, var(--color-warning-bg));
}
</style>
