// web-react/src/views/workflow/definition/components/WfNodeTree.tsx
// 整棵工作流的唯一 mutation coordinator:clone → model helper → 一次性回调。对应 Vue 侧 WfNodeTree.vue。
import { useMemo } from 'react'
import {
  addBranchArm,
  addParallelArm,
  cloneNode,
  createNode,
  findNode,
  insertAfter,
  insertIntoBranchArm,
  insertIntoParallelArm,
  removeBranchArm,
  removeParallelArm,
  removeNode,
} from '@/workflow/model'
import type { WfInsertableNodeType, WfModel, WfNode } from '@/workflow/schema'
import { WfNodeChain } from './WfNodeChain'
import './wf-designer.css'
import '../../wf-identity.css'

export interface WfNodeTreeProps {
  model: WfModel
  selectedId?: string | null
  errorIds?: Set<string> | string[]
  readonly?: boolean
  visitedIds?: Set<string> | string[]
  currentIds?: Set<string> | string[]
  onModelChange: (model: WfModel) => void
  onSelect: (node: WfNode) => void
}

function toSet(ids: Set<string> | string[] | undefined): Set<string> {
  if (!ids) return new Set<string>()
  return ids instanceof Set ? ids : new Set(ids)
}

export function WfNodeTree({
  model, selectedId, errorIds, readonly, visitedIds, currentIds, onModelChange, onSelect,
}: WfNodeTreeProps) {
  const errorSet = useMemo(() => toSet(errorIds), [errorIds])
  const visitedSet = useMemo(() => toSet(visitedIds), [visitedIds])
  const currentSet = useMemo(() => toSet(currentIds), [currentIds])

  const bump = (root: WfNode) => onModelChange({ ...model, root })

  const handleSelect = (nodeId: string) => {
    if (readonly) return
    const node = findNode(model.root, nodeId)
    if (node) onSelect(node)
  }

  const handleAddAfter = (afterId: string, type: WfInsertableNodeType) => {
    if (readonly) return
    const root = cloneNode(model.root)
    const node = createNode(type)
    if (!insertAfter(root, afterId, node)) return
    bump(root)
    // 插入后立刻选中新节点:用户点加号就是为了配它。
    onSelect(node)
  }

  const handleAddAtArmHead = (ownerId: string, armId: string, type: WfInsertableNodeType) => {
    if (readonly) return
    const root = cloneNode(model.root)
    const node = createNode(type)
    if (!insertIntoBranchArm(root, ownerId, armId, node)
      && !insertIntoParallelArm(root, ownerId, armId, node)) return
    bump(root)
    onSelect(node)
  }

  const handleRemoveNode = (nodeId: string) => {
    if (readonly) return
    const root = cloneNode(model.root)
    if (!removeNode(root, nodeId)) return
    bump(root)
  }

  const handleAddArm = (ownerId: string) => {
    if (readonly) return
    const root = cloneNode(model.root)
    const owner = findNode(root, ownerId)
    if (!owner || (!addBranchArm(owner) && !addParallelArm(owner))) return
    bump(root)
  }

  const handleRemoveArm = (ownerId: string, armId: string) => {
    if (readonly) return
    const root = cloneNode(model.root)
    const owner = findNode(root, ownerId)
    if (!owner || (!removeBranchArm(owner, armId) && !removeParallelArm(owner, armId))) return
    bump(root)
  }

  const handleRenameArm = (ownerId: string, armId: string, name: string) => {
    if (readonly) return
    const root = cloneNode(model.root)
    const owner = findNode(root, ownerId)
    const arms = owner?.type === 'branch'
      ? owner.conditions
      : owner?.type === 'parallel' ? owner.parallelArms : undefined
    const arm = arms?.find((item) => item.id === armId)
    if (!arm) return
    arm.name = name
    bump(root)
  }

  return (
    <div className="wf-tree">
      <WfNodeChain
        root={model.root}
        selectedId={selectedId}
        errorSet={errorSet}
        readonly={readonly}
        visitedSet={visitedSet}
        currentSet={currentSet}
        // 顶层链恒可插并行(臂内由 WfNodeChain 自己降级);漏传即等于菜单缺项,Vue 侧踩过。
        allowParallel
        terminal
        onSelect={handleSelect}
        onAddAfter={handleAddAfter}
        onAddAtArmHead={handleAddAtArmHead}
        onRemoveNode={handleRemoveNode}
        onAddArm={handleAddArm}
        onRemoveArm={handleRemoveArm}
        onRenameArm={handleRenameArm}
      />
    </div>
  )
}

// web/src/views/workflow/definition/components/WfNodeTree.vue
<script setup lang="ts">
// 整棵工作流的唯一 mutation coordinator:clone → model helper → 一次性 emit。
import { computed } from 'vue'
import {
  addBranchArm,
  addParallelArm,
  cloneNode,
  createNode,
  findNode,
  insertAfter,
  insertIntoBranchArm,
  insertIntoParallelArm,
  removeBranchArm,
  removeParallelArm,
  removeNode,
} from '@/workflow/model'
import type { WfInsertableNodeType, WfModel, WfNode } from '@/workflow/schema'
import WfNodeChain from './WfNodeChain.vue'
import '../../wf-identity.css'

const props = defineProps<{
  model: WfModel
  selectedId?: string | null
  errorIds?: Set<string> | string[]
  readonly?: boolean
  visitedIds?: Set<string> | string[]
  currentIds?: Set<string> | string[]
}>()
const emit = defineEmits<{
  'update:model': [WfModel]
  select: [node: WfNode]
}>()

const errorSet = computed(() => {
  if (!props.errorIds) return new Set<string>()
  return props.errorIds instanceof Set ? props.errorIds : new Set(props.errorIds)
})

const visitedSet = computed(() => {
  if (!props.visitedIds) return new Set<string>()
  return props.visitedIds instanceof Set ? props.visitedIds : new Set(props.visitedIds)
})

const currentSet = computed(() => {
  if (!props.currentIds) return new Set<string>()
  return props.currentIds instanceof Set ? props.currentIds : new Set(props.currentIds)
})

function bump(root: WfNode) {
  emit('update:model', { ...props.model, root })
}

function onSelect(nodeId: string) {
  if (props.readonly) return
  const node = findNode(props.model.root, nodeId)
  if (node) emit('select', node)
}

function onAddAfter(afterId: string, type: WfInsertableNodeType) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  const node = createNode(type)
  if (!insertAfter(root, afterId, node)) return
  bump(root)
  emit('select', node)
}

function onAddAtArmHead(ownerId: string, armId: string, type: WfInsertableNodeType) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  const node = createNode(type)
  if (!insertIntoBranchArm(root, ownerId, armId, node)
    && !insertIntoParallelArm(root, ownerId, armId, node)) return
  bump(root)
  emit('select', node)
}

function onRemoveNode(nodeId: string) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  if (!removeNode(root, nodeId)) return
  bump(root)
}

function onAddArm(ownerId: string) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  const owner = findNode(root, ownerId)
  if (!owner || (!addBranchArm(owner) && !addParallelArm(owner))) return
  bump(root)
}

function onRemoveArm(ownerId: string, armId: string) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  const owner = findNode(root, ownerId)
  if (!owner || (!removeBranchArm(owner, armId) && !removeParallelArm(owner, armId))) return
  bump(root)
}

function onRenameArm(ownerId: string, armId: string, name: string) {
  if (props.readonly) return
  const root = cloneNode(props.model.root)
  const owner = findNode(root, ownerId)
  const arms = owner?.type === 'branch' ? owner.conditions : owner?.type === 'parallel' ? owner.parallelArms : undefined
  const arm = arms?.find((item) => item.id === armId)
  if (!arm) return
  arm.name = name
  bump(root)
}
</script>

<template>
  <div class="wf-tree">
    <WfNodeChain
      :root="model.root"
      :selected-id="selectedId"
      :error-set="errorSet"
      :readonly="readonly"
      :visited-set="visitedSet"
      :current-set="currentSet"
      terminal
      @select="onSelect"
      @add-after="onAddAfter"
      @add-at-arm-head="onAddAtArmHead"
      @remove-node="onRemoveNode"
      @add-arm="onAddArm"
      @remove-arm="onRemoveArm"
      @rename-arm="onRenameArm"
    />
  </div>
</template>

<style scoped>
.wf-tree {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  min-width: min-content;
  padding: 28px 48px 64px;
}
</style>
