// web/src/views/system/config/index.vue
<script setup lang="ts">
// 分类配置中心:按分类 Tab 组织。系统基础=结构化表单(字段级 UI);安全策略=锁定/密码/会话结构化表单
// (后端 ISecurityPolicyProvider 强制执行,改值即时生效);其他配置=任意 key 扁平 CRUD 兜底。
import { NTabs, NTabPane, NCard } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import SysBaseConfig from './components/SysBaseConfig.vue'
import SecurityConfig from './components/SecurityConfig.vue'
import UploadConfig from './components/UploadConfig.vue'
import OtherConfig from './components/OtherConfig.vue'

const { t } = useI18n()
</script>

<template>
  <n-tabs type="line" animated>
    <n-tab-pane name="base" :tab="t('config.tab.base')">
      <n-card :bordered="false" :title="t('config.tab.base')">
        <sys-base-config />
      </n-card>
    </n-tab-pane>
    <n-tab-pane name="security" :tab="t('config.tab.security')">
      <n-card :bordered="false" :title="t('config.tab.security')">
        <security-config />
      </n-card>
    </n-tab-pane>
    <n-tab-pane name="upload" :tab="t('config.tab.upload')">
      <n-card :bordered="false" :title="t('config.tab.upload')">
        <upload-config />
      </n-card>
    </n-tab-pane>
    <n-tab-pane name="other" :tab="t('config.tab.other')">
      <other-config />
    </n-tab-pane>
  </n-tabs>
</template>

// web-react/src/views/system/config/index.tsx
// 分类配置中心:按分类 Tab 组织。base/security/upload = 结构化表单(字段级 UI,运维不需知道 config key);
// other = 任意 key 扁平 CRUD 兜底。对齐 Vue 侧 config/index.vue。
// antd Tabs 默认 destroyOnHidden=false → 面板懒挂(首访才 mount+拉数据)+ 保活(切走只隐藏不销毁),
// 各面板未保存改动跨 Tab 切换存活,正合 Vue 的 display-directive="show:lazy"。
// 面板内不再套「与 Tab 标签同名的 Card 标题」(Vue 那层 n-card 标题与 tab 名重复),页级一个 Card 收边。
import { useMemo } from 'react'
import { Card, Tabs } from 'antd'
import { useTranslation } from 'react-i18next'
import SysBaseConfig from './SysBaseConfig'
import SecurityConfig from './SecurityConfig'
import UploadConfig from './UploadConfig'
import OtherConfig from './OtherConfig'

export default function ConfigPage() {
  const { t } = useTranslation()
  const items = useMemo(
    () => [
      { key: 'base', label: t('config.tab.base'), children: <SysBaseConfig /> },
      { key: 'security', label: t('config.tab.security'), children: <SecurityConfig /> },
      { key: 'upload', label: t('config.tab.upload'), children: <UploadConfig /> },
      { key: 'other', label: t('config.tab.other'), children: <OtherConfig /> },
    ],
    [t],
  )
  return (
    <Card>
      <Tabs type="line" items={items} />
    </Card>
  )
}
