// web/src/views/system/config/components/SysBaseConfig.vue
<script setup lang="ts">
// 系统基础配置 = 分类配置中心「结构化表单」范式:字段绑定固定 config key,运维不需知道 key。
// 载入走 configApi.listByGroup('sys') 回填,保存走 configApi.saveBatch(仅回写值)。后续加参数=加一个 FIELDS 项 + 一个 n-form-item。
import { onMounted, reactive, ref } from 'vue'
import { NForm, NFormItem, NInput, NButton, NSpin, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import { configApi } from '@/api'
import { useSite } from '@/composables/useSite'
import { translateError } from '@/utils/error'

const { t } = useI18n()
const message = useMessage()
const { loadSite } = useSite()

// 结构化字段:key 绑定后端配置键(GroupCode='sys'),label 走 i18n。全部经匿名 siteInfo 下发,
// 真实消费点在登录页/侧栏/顶栏/页脚(见 useSite)。加参数 = 加一个 FIELDS 项 + 一条 config.base i18n。
const FIELDS = [
  { key: 'sys.site.title', label: () => t('config.base.siteTitle') },
  { key: 'sys.site.subtitle', label: () => t('config.base.siteSubtitle') },
  { key: 'sys.site.copyright', label: () => t('config.base.copyright') },
  { key: 'sys.site.copyrightUrl', label: () => t('config.base.copyrightUrl') },
] as const

const values = reactive<Record<string, string>>({})
const loading = ref(true)
const saving = ref(false)

onMounted(async () => {
  try {
    const rows = await configApi.listByGroup('sys')
    for (const f of FIELDS) values[f.key] = rows.find((r) => r.configKey === f.key)?.configValue ?? ''
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
})

async function save() {
  saving.value = true
  try {
    await configApi.saveBatch(FIELDS.map((f) => ({ configKey: f.key, configValue: values[f.key] })))
    message.success(t('config.saved'))
    // 即时生效:重取全站共用的站点信息(侧栏/顶栏/登录页品牌随之更新)+ 同步浏览器标题。
    await loadSite(true)
    if (values['sys.site.title']) document.title = values['sys.site.title']
  } catch (e) {
    message.error(translateError(e))
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <n-spin :show="loading">
    <n-form label-placement="left" :label-width="90" style="max-width: 560px">
      <n-form-item v-for="f in FIELDS" :key="f.key" :label="f.label()">
        <n-input v-model:value="values[f.key]" :placeholder="f.label()" />
      </n-form-item>
      <n-form-item :label="' '" :show-feedback="false">
        <n-button v-auth="'PUT:/api/v1/sys/config/batch'" type="primary" :loading="saving" @click="save">
          <template #icon><AppIcon icon="ph:floppy-disk" :size="16" /></template>{{ t('common.save') }}
        </n-button>
      </n-form-item>
    </n-form>
  </n-spin>
</template>

// web-react/src/views/system/config/SysBaseConfig.tsx
// 系统基础 = 结构化表单:字段绑定固定 config key(GroupCode='sys')。载入 listByGroup('sys') 回填,
// 保存 saveBatch(仅回写值)。保存后 loadSite(true) 即时生效(侧栏/顶栏/登录页品牌随之更新)+ 同步浏览器标题。
// 加参数 = SYS_FIELDS 加一项 + LABEL_KEY 加一条 + 一条 config.base i18n。
import { useEffect, useState } from 'react'
import { App, Button, Form, Input, Spin } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import { Can } from '@/components/Can'
import { configApi } from '@/api'
import { useSiteStore } from '@/stores/site'
import { translateError } from '@/utils/error'
import { SYS_FIELDS, parseBase, serializeBase } from './configForm'

// config key → i18n label 键(SYS_FIELDS 与之一一对应)
const LABEL_KEY: Record<(typeof SYS_FIELDS)[number], string> = {
  'sys.site.title': 'config.base.siteTitle',
  'sys.site.logo': 'config.base.logo',
  'sys.site.subtitle': 'config.base.siteSubtitle',
  'sys.site.copyright': 'config.base.copyright',
  'sys.site.copyrightUrl': 'config.base.copyrightUrl',
}

export default function SysBaseConfig() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const loadSite = useSiteStore((s) => s.load)
  const [values, setValues] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    configApi
      .listByGroup('sys')
      .then((rows) => setValues(parseBase(rows)))
      .catch((e) => message.error(translateError(e)))
      .finally(() => setLoading(false))
  }, [message])

  const save = async () => {
    setSaving(true)
    try {
      await configApi.saveBatch(serializeBase(values))
      message.success(t('config.saved'))
      // 即时生效:重取全站共用站点信息 + 同步浏览器标题。
      await loadSite(true)
      if (values['sys.site.title']) document.title = values['sys.site.title']
    } catch (e) {
      message.error(translateError(e))
    } finally {
      setSaving(false)
    }
  }

  const set = (k: string, v: string) => setValues((prev) => ({ ...prev, [k]: v }))

  return (
    <Spin spinning={loading}>
      <Form labelCol={{ flex: '0 0 90px' }} labelAlign="left" style={{ maxWidth: 560 }}>
        {SYS_FIELDS.map((k) => (
          <Form.Item key={k} label={t(LABEL_KEY[k])}>
            <Input value={values[k] ?? ''} onChange={(e) => set(k, e.target.value)} placeholder={t(LABEL_KEY[k])} />
          </Form.Item>
        ))}
        <Form.Item label=" " colon={false}>
          <Can code="PUT:/api/v1/sys/config/batch">
            <Button type="primary" loading={saving} onClick={save} icon={<AppIcon icon="ph:floppy-disk" size={16} />}>
              {t('common.save')}
            </Button>
          </Can>
        </Form.Item>
      </Form>
    </Spin>
  )
}
