// web/src/views/integration/outbound-log/index.vue
<script setup lang="ts">
// 出站调用记录 = 只读 ProTable + 详情抽屉 + 出站目标清单。记录不含请求/响应正文与任何请求头(出站秘密只在请求头里);
// 地址不含查询串。支持从「可靠投递」详情带 ?deliveryId= / ?callId= 深链进入(刷新保持筛选)。
import { computed, h, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  NAlert, NButton, NDataTable, NDescriptions, NDescriptionsItem, NDrawer, NDrawerContent, NSpace, NTag, useMessage,
  type DataTableColumns,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn } from 'tenon-naive-pro-table'
import { integrationOutboundLogApi } from '@/api/integration'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'
import type { OutboundLogRow, OutboundTarget } from '@/types/integration'
import { PERM, enumLabel, fmtDateTime, methodTagType, outboundAuthTypeKey, outboundOutcomeTag, queryText } from '../shared'

const { t } = useI18n()
const message = useMessage()
const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

/** 深链筛选:投递详情带入 deliveryId / callId;清除即回到全部。 */
const linkedDeliveryId = computed(() => queryText(route.query, 'deliveryId'))
const linkedCallId = computed(() => queryText(route.query, 'callId'))
const tableParams = computed(() => ({
  ...(linkedDeliveryId.value ? { deliveryId: linkedDeliveryId.value } : {}),
  ...(linkedCallId.value ? { callId: linkedCallId.value } : {}),
}))
const clearLink = (key: string) => {
  const query = { ...route.query }
  delete query[key]
  void router.replace({ path: route.path, query })
}

const outcomeOptions = Object.entries(outboundOutcomeTag).map(([value, tag]) => ({
  label: () => t(tag.key),
  value: Number(value),
  tagType: tag.type,
}))

const columns: ProTableColumn<OutboundLogRow>[] = [
  { key: 'createTime', title: () => t('integration.outboundLog.time'), format: 'datetime', width: 170, search: { type: 'daterange' } },
  { key: 'target', title: () => t('integration.outboundLog.target'), width: 130, search: true },
  { key: 'operation', title: () => t('integration.outboundLog.operation'), width: 140, search: true, render: (r) => r.operation || '—' },
  {
    key: 'httpMethod',
    title: () => t('integration.outboundLog.method'),
    width: 90,
    render: (r) => h(NTag, { size: 'small', bordered: false, type: methodTagType(r.httpMethod) }, () => r.httpMethod),
  },
  { key: 'url', title: () => t('integration.outboundLog.url'), ellipsis: { tooltip: true } },
  { key: 'statusCode', title: () => t('integration.outboundLog.status'), width: 100, render: (r) => (r.statusCode == null ? '—' : String(r.statusCode)) },
  {
    key: 'outcome',
    title: () => t('integration.outboundLog.outcome'),
    width: 110,
    tag: true,
    options: outcomeOptions,
    search: { props: { clearable: true } },
  },
  { key: 'reason', title: () => t('integration.outboundLog.reason'), width: 150, ellipsis: { tooltip: true }, render: (r) => r.reason || '—' },
  { key: 'elapsedMs', title: () => t('integration.outboundLog.elapsed'), width: 100, render: (r) => `${r.elapsedMs} ms` },
  { key: 'callId', title: () => t('integration.outboundLog.callId'), hideInTable: true, search: true },
  { key: 'traceId', title: () => t('integration.outboundLog.traceId'), hideInTable: true, search: true },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 90,
    hideInSetting: true,
    render: (r) => h(NButton, { size: 'small', quaternary: true, type: 'primary', onClick: () => openDetail(r) }, () => t('integration.outboundLog.detail')),
  },
]

const showDetail = ref(false)
const detailRow = ref<OutboundLogRow | null>(null)
function openDetail(r: OutboundLogRow) {
  detailRow.value = r
  showDetail.value = true
}

// ── 出站目标清单(只回答是否取得到凭据,永不显示凭据)──
const showTargets = ref(false)
const targets = ref<OutboundTarget[]>([])
const targetsLoading = ref(false)
async function openTargets() {
  showTargets.value = true
  targetsLoading.value = true
  try {
    targets.value = await integrationOutboundLogApi.targets()
  } catch (e) {
    message.error(translateError(e))
  } finally {
    targetsLoading.value = false
  }
}
const targetColumns = computed<DataTableColumns<OutboundTarget>>(() => [
  { key: 'name', title: t('integration.outboundLog.targetName'), width: 140 },
  { key: 'baseUrl', title: t('integration.outboundLog.baseUrl'), ellipsis: { tooltip: true } },
  { key: 'timeoutSeconds', title: t('integration.outboundLog.timeout'), width: 80, render: (r) => `${r.timeoutSeconds}s` },
  {
    key: 'authType',
    title: t('integration.outboundLog.auth'),
    width: 150,
    render: (r) => {
      const label = t(outboundAuthTypeKey[Number(r.authType ?? 0)] ?? 'integration.outbound.authNone')
      return r.authHeaderName ? `${label}(${r.authHeaderName})` : label
    },
  },
  {
    key: 'trustedCidrs',
    title: t('integration.outboundLog.trustedCidrs'),
    width: 180,
    render: (r) =>
      r.trustedCidrs?.length
        ? h(NSpace, { size: 4 }, () => r.trustedCidrs!.map((c) => h(NTag, { size: 'small', bordered: false }, () => c)))
        : t('integration.outboundLog.noTrusted'),
  },
  {
    key: 'hasCredential',
    title: t('integration.outboundLog.credential'),
    width: 90,
    render: (r) =>
      h(NTag, { size: 'small', bordered: false, type: r.hasCredential ? 'success' : 'default' }, () =>
        t(r.hasCredential ? 'integration.outboundLog.credentialSet' : 'integration.outboundLog.credentialMissing'),
      ),
  },
])
</script>

<template>
  <ProTable
    :columns="columns"
    :fetcher="integrationOutboundLogApi.page"
    :params="tableParams"
    storage-key="integration-outbound-log"
    @error="(e) => message.error(translateError(e))"
  >
    <template #toolbar>
      <n-space :size="8">
        <n-button v-if="authStore.hasPerm(PERM.outboundTargets)" data-testid="outbound-targets" @click="openTargets">
          {{ t('integration.outboundLog.targets') }}
        </n-button>
        <n-tag v-if="linkedDeliveryId" closable type="info" :bordered="false" @close="clearLink('deliveryId')">
          {{ t('integration.outboundLog.filterDelivery') }}:{{ linkedDeliveryId }}
        </n-tag>
        <n-tag v-if="linkedCallId" closable type="info" :bordered="false" @close="clearLink('callId')">
          {{ t('integration.outboundLog.filterCall') }}:{{ linkedCallId }}
        </n-tag>
      </n-space>
    </template>
    <template #empty>{{ t('integration.outboundLog.empty') }}</template>
  </ProTable>

  <n-drawer v-model:show="showDetail" :width="560" placement="right">
    <n-drawer-content :title="t('integration.outboundLog.detail')" closable>
      <n-descriptions v-if="detailRow" :column="1" label-placement="left" bordered size="small">
        <n-descriptions-item :label="t('integration.outboundLog.time')">{{ fmtDateTime(detailRow.createTime) }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.target')">{{ detailRow.target }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.operation')">{{ detailRow.operation || '—' }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.method')">{{ detailRow.httpMethod }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.url')">{{ detailRow.url }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.status')">{{ detailRow.statusCode ?? '—' }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.outcome')">{{ enumLabel(t, outboundOutcomeTag, detailRow.outcome) }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.reason')">{{ detailRow.reason || '—' }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.errorSummary')">{{ detailRow.errorSummary || '—' }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.elapsed')">{{ detailRow.elapsedMs }} ms</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.callId')">{{ detailRow.callId }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.traceId')">{{ detailRow.traceId || '—' }}</n-descriptions-item>
        <n-descriptions-item :label="t('integration.outboundLog.delivery')">
          {{ detailRow.deliveryId ? `${detailRow.deliveryId} · #${detailRow.attemptNo ?? '—'}` : '—' }}
        </n-descriptions-item>
      </n-descriptions>
    </n-drawer-content>
  </n-drawer>

  <n-drawer v-model:show="showTargets" :width="860" placement="right">
    <n-drawer-content :title="t('integration.outboundLog.targetsTitle')" closable>
      <n-alert type="info" :show-icon="false" style="margin-bottom: 12px">{{ t('integration.outboundLog.targetsHint') }}</n-alert>
      <n-data-table :columns="targetColumns" :data="targets" :loading="targetsLoading" :row-key="(r: OutboundTarget) => r.name ?? ''" size="small" />
    </n-drawer-content>
  </n-drawer>
</template>

// web-react/src/views/integration/outbound-log/index.tsx
// 出站调用记录 = 只读 DataTable + 详情抽屉 + 出站目标清单。记录不含请求/响应正文与任何请求头(出站秘密只在请求头里);
// 地址不含查询串。支持从「可靠投递」详情带 ?deliveryId= / ?callId= 深链进入(刷新保持筛选)。
import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Alert, App, Button, Descriptions, Drawer, Space, Table, Tag, type TableColumnsType } from 'antd'
import { useTranslation } from 'react-i18next'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type PageFetcher } from '@/components/DataTable'
import { Can } from '@/components/Can'
import { integrationOutboundLogApi } from '@/api/integration'
import { translateError } from '@/utils/error'
import type { OutboundLogRow, OutboundTarget } from '@/types/integration'
import { PERM, fmtDateTime, methodTagType, outboundAuthTypeKey, outboundOutcomeTag } from '../shared'

export default function IntegrationOutboundLogPage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const [searchParams, setSearchParams] = useSearchParams()
  const [detailRow, setDetailRow] = useState<OutboundLogRow | null>(null)

  /** 深链筛选:投递详情带入 deliveryId / callId;清除即回到全部。 */
  const linkedDeliveryId = searchParams.get('deliveryId') || null
  const linkedCallId = searchParams.get('callId') || null
  const params = useMemo(
    () => ({ ...(linkedDeliveryId ? { deliveryId: linkedDeliveryId } : {}), ...(linkedCallId ? { callId: linkedCallId } : {}) }),
    [linkedDeliveryId, linkedCallId],
  )
  const clearLink = (key: string) => {
    const next = new URLSearchParams(searchParams)
    next.delete(key)
    setSearchParams(next, { replace: true })
  }

  const outcomeOptions = Object.entries(outboundOutcomeTag).map(([value, tag]) => ({ label: t(tag.key), value: Number(value) }))
  const outcomeTag = (v?: number | null) => {
    const tag = v == null ? undefined : outboundOutcomeTag[Number(v)]
    return tag ? <Tag variant="filled" color={tag.type}>{t(tag.key)}</Tag> : '—'
  }

  const fetchLogs: PageFetcher<OutboundLogRow> = (q) =>
    integrationOutboundLogApi.page({
      page: q.page,
      pageSize: q.pageSize,
      target: typeof q.target === 'string' ? q.target : undefined,
      operation: typeof q.operation === 'string' ? q.operation : undefined,
      outcome: typeof q.outcome === 'number' ? q.outcome : undefined,
      deliveryId: typeof q.deliveryId === 'string' || typeof q.deliveryId === 'number' ? q.deliveryId : undefined,
      callId: typeof q.callId === 'string' ? q.callId : undefined,
      traceId: typeof q.traceId === 'string' ? q.traceId : undefined,
      createTime: (q.createTime as [string, string] | undefined) ?? null,
    })

  const columns: ProColumns<OutboundLogRow>[] = [
    { title: t('integration.outboundLog.time'), dataIndex: 'createTime', valueType: 'dateRange', width: 170, render: (_, r) => fmtDateTime(r.createTime) },
    { title: t('integration.outboundLog.target'), dataIndex: 'target', width: 130 },
    { title: t('integration.outboundLog.operation'), dataIndex: 'operation', width: 140, render: (_, r) => r.operation || '—' },
    {
      title: t('integration.outboundLog.method'), dataIndex: 'httpMethod', search: false, width: 90,
      render: (_, r) => <Tag variant="filled" color={methodTagType(r.httpMethod)}>{r.httpMethod}</Tag>,
    },
    { title: t('integration.outboundLog.url'), dataIndex: 'url', search: false, ellipsis: true },
    { title: t('integration.outboundLog.status'), dataIndex: 'statusCode', search: false, width: 100, render: (_, r) => (r.statusCode == null ? '—' : String(r.statusCode)) },
    {
      title: t('integration.outboundLog.outcome'), dataIndex: 'outcome', valueType: 'select', width: 110,
      fieldProps: { allowClear: true, options: outcomeOptions },
      render: (_, r) => outcomeTag(r.outcome),
    },
    { title: t('integration.outboundLog.reason'), dataIndex: 'reason', search: false, width: 150, ellipsis: true, render: (_, r) => r.reason || '—' },
    { title: t('integration.outboundLog.elapsed'), dataIndex: 'elapsedMs', search: false, width: 100, render: (_, r) => `${r.elapsedMs} ms` },
    { title: t('integration.outboundLog.callId'), dataIndex: 'callId', hideInTable: true },
    { title: t('integration.outboundLog.traceId'), dataIndex: 'traceId', hideInTable: true },
    {
      title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 90, fixed: 'right',
      render: (_, r) => <Button type="link" size="small" onClick={() => setDetailRow(r)}>{t('integration.outboundLog.detail')}</Button>,
    },
  ]

  // ── 出站目标清单(只回答是否取得到凭据,永不显示凭据)──
  const [targetsOpen, setTargetsOpen] = useState(false)
  const [targets, setTargets] = useState<OutboundTarget[]>([])
  const [targetsLoading, setTargetsLoading] = useState(false)
  const openTargets = async () => {
    setTargetsOpen(true)
    setTargetsLoading(true)
    try {
      setTargets(await integrationOutboundLogApi.targets())
    } catch (e) {
      message.error(translateError(e))
    } finally {
      setTargetsLoading(false)
    }
  }
  const targetColumns: TableColumnsType<OutboundTarget> = [
    { title: t('integration.outboundLog.targetName'), dataIndex: 'name', width: 140 },
    { title: t('integration.outboundLog.baseUrl'), dataIndex: 'baseUrl', ellipsis: true },
    { title: t('integration.outboundLog.timeout'), dataIndex: 'timeoutSeconds', width: 80, render: (_, r) => `${r.timeoutSeconds}s` },
    {
      title: t('integration.outboundLog.auth'), dataIndex: 'authType', width: 150,
      render: (_, r) => {
        const label = t(outboundAuthTypeKey[Number(r.authType ?? 0)] ?? 'integration.outbound.authNone')
        return r.authHeaderName ? `${label}(${r.authHeaderName})` : label
      },
    },
    {
      title: t('integration.outboundLog.trustedCidrs'), dataIndex: 'trustedCidrs', width: 180,
      render: (_, r) =>
        r.trustedCidrs?.length
          ? <Space size={4} wrap>{r.trustedCidrs.map((c) => <Tag key={c} variant="filled">{c}</Tag>)}</Space>
          : t('integration.outboundLog.noTrusted'),
    },
    {
      title: t('integration.outboundLog.credential'), dataIndex: 'hasCredential', width: 90,
      render: (_, r) => (
        <Tag variant="filled" color={r.hasCredential ? 'success' : 'default'}>
          {t(r.hasCredential ? 'integration.outboundLog.credentialSet' : 'integration.outboundLog.credentialMissing')}
        </Tag>
      ),
    },
  ]

  return (
    <>
      <DataTable<OutboundLogRow>
        columns={columns}
        fetcher={fetchLogs}
        params={params}
        persistKey="integration-outbound-log"
        toolbar={
          <Space size={8}>
            <Can code={PERM.outboundTargets}>
              <Button data-testid="outbound-targets" onClick={() => void openTargets()}>{t('integration.outboundLog.targets')}</Button>
            </Can>
            {linkedDeliveryId && (
              <Tag closable color="processing" onClose={() => clearLink('deliveryId')}>
                {t('integration.outboundLog.filterDelivery')}:{linkedDeliveryId}
              </Tag>
            )}
            {linkedCallId && (
              <Tag closable color="processing" onClose={() => clearLink('callId')}>
                {t('integration.outboundLog.filterCall')}:{linkedCallId}
              </Tag>
            )}
          </Space>
        }
      />
      <Drawer open={!!detailRow} onClose={() => setDetailRow(null)} title={t('integration.outboundLog.detail')} size={560}>
        {detailRow && (
          <Descriptions column={1} bordered size="small" items={[
            { key: 'time', label: t('integration.outboundLog.time'), children: fmtDateTime(detailRow.createTime) },
            { key: 'target', label: t('integration.outboundLog.target'), children: detailRow.target },
            { key: 'operation', label: t('integration.outboundLog.operation'), children: detailRow.operation || '—' },
            { key: 'method', label: t('integration.outboundLog.method'), children: detailRow.httpMethod },
            { key: 'url', label: t('integration.outboundLog.url'), children: detailRow.url },
            { key: 'status', label: t('integration.outboundLog.status'), children: detailRow.statusCode ?? '—' },
            { key: 'outcome', label: t('integration.outboundLog.outcome'), children: outcomeTag(detailRow.outcome) },
            { key: 'reason', label: t('integration.outboundLog.reason'), children: detailRow.reason || '—' },
            { key: 'errorSummary', label: t('integration.outboundLog.errorSummary'), children: detailRow.errorSummary || '—' },
            { key: 'elapsed', label: t('integration.outboundLog.elapsed'), children: `${detailRow.elapsedMs} ms` },
            { key: 'callId', label: t('integration.outboundLog.callId'), children: detailRow.callId },
            { key: 'traceId', label: t('integration.outboundLog.traceId'), children: detailRow.traceId || '—' },
            {
              key: 'delivery', label: t('integration.outboundLog.delivery'),
              children: detailRow.deliveryId ? `${detailRow.deliveryId} · #${detailRow.attemptNo ?? '—'}` : '—',
            },
          ]} />
        )}
      </Drawer>
      <Drawer open={targetsOpen} onClose={() => setTargetsOpen(false)} title={t('integration.outboundLog.targetsTitle')} size={860}>
        <Alert type="info" title={t('integration.outboundLog.targetsHint')} style={{ marginBottom: 12 }} />
        <Table<OutboundTarget>
          rowKey={(r) => r.name ?? ''}
          columns={targetColumns}
          dataSource={targets}
          loading={targetsLoading}
          pagination={false}
          size="small"
        />
      </Drawer>
    </>
  )
}
