// web-react/src/views/workflow/definition/index.tsx
// 流程定义列表。菜单 component 填 `workflow/definition/index`。
// 「新建」与「设计」都跳设计器(`/workflow/definition/designer`,可带 `?id=`)—— 建草稿的逻辑留在设计器空态,本页不重复一份。
import { useCallback, useMemo, useRef } from 'react'
import { Button, Dropdown, Space, Tag } from 'antd'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import type { ProColumns } from '@ant-design/pro-components'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import { AppIcon } from '@/components/AppIcon'
import { Can } from '@/components/Can'
import { useConfirm } from '@/hooks/useConfirm'
import { useHasPerm } from '@/stores/auth'
import { wfDefinitionApi } from '@/api/workflow'
import { DEF_STATUS, formatDateTime } from '@/workflow/statusLabels'
import type { WfDefinitionRow } from '@/types/workflow'

/** 后端 WfDefinitionStatus:0 草稿 / 1 已发布 / 2 停用(色与 Vue 侧 tagType 一致)。 */
const STATUS_TAG: Record<number, { color: string; key: string }> = {
  [DEF_STATUS.DRAFT]: { color: 'default', key: 'workflow.definition.status.draft' },
  [DEF_STATUS.PUBLISHED]: { color: 'success', key: 'workflow.definition.status.published' },
  [DEF_STATUS.DISABLED]: { color: 'warning', key: 'workflow.definition.status.disabled' },
}

export default function WfDefinitionPage() {
  const { t } = useTranslation()
  const { confirm } = useConfirm()
  const has = useHasPerm()
  const navigate = useNavigate()

  const tableRef = useRef<DataTableHandle>(null)
  const reload = useCallback(() => tableRef.current?.reload(), [])

  // 有意不 memo(同 position / notice 页,ProTable 经 ref 读 request)。
  const fetchDefinitions: PageFetcher<WfDefinitionRow> = (q) =>
    wfDefinitionApi.page({
      page: q.page,
      pageSize: q.pageSize,
      name: typeof q.name === 'string' ? q.name : undefined,
      groupName: typeof q.groupName === 'string' ? q.groupName : undefined,
      status: typeof q.status === 'number' ? q.status : undefined,
    })

  const openDesigner = useCallback(
    (r?: WfDefinitionRow) => {
      navigate(r?.id == null ? '/workflow/definition/designer' : `/workflow/definition/designer?id=${r.id}`)
    },
    [navigate],
  )

  const handlePublish = useCallback(
    (r: WfDefinitionRow) => {
      confirm({
        content: t('workflow.definition.publishConfirm', { name: r.name ?? '' }),
        action: () => wfDefinitionApi.publish(r.id!),
        successMsg: t('workflow.definition.publishOk'),
      }).then((ok) => { if (ok) reload() })
    },
    [confirm, t, reload],
  )

  const handleDisable = useCallback(
    (r: WfDefinitionRow) => {
      confirm({
        content: t('workflow.definition.disableConfirm', { name: r.name ?? '' }),
        action: () => wfDefinitionApi.disable(r.id!),
        successMsg: t('workflow.definition.disableOk'),
      }).then((ok) => { if (ok) reload() })
    },
    [confirm, t, reload],
  )

  const handleDelete = useCallback(
    (r: WfDefinitionRow) => {
      confirm({
        content: t('workflow.definition.deleteConfirm', { name: r.name ?? '' }),
        action: () => wfDefinitionApi.remove(r.id!),
      }).then((ok) => { if (ok) reload() })
    },
    [confirm, t, reload],
  )

  const columns = useMemo<ProColumns<WfDefinitionRow>[]>(
    () => [
      {
        title: t('workflow.definition.name'), dataIndex: 'name', ellipsis: true, minWidth: 180,
        render: (_, r) => (
          <Space size={6}>
            {r.icon ? <AppIcon icon={r.icon} size={18} /> : null}
            {r.name || '—'}
          </Space>
        ),
      },
      {
        title: t('workflow.definition.group'), dataIndex: 'groupName', width: 140, ellipsis: true,
        render: (_, r) => r.groupName || '—',
      },
      {
        title: t('common.status'), dataIndex: 'status', width: 110, valueType: 'select',
        fieldProps: {
          allowClear: true,
          options: Object.entries(STATUS_TAG).map(([v, s]) => ({ label: t(s.key), value: Number(v) })),
        },
        render: (_, r) => {
          const s = STATUS_TAG[Number(r.status)]
          return s ? <Tag color={s.color}>{t(s.key)}</Tag> : '—'
        },
      },
      {
        title: t('workflow.definition.version'), dataIndex: 'currentVersion', width: 100, align: 'center', search: false,
        // 草稿的 currentVersion 是 0:显示 v0 会被当成「有个 0 版」,直接给「未发布」更实。
        render: (_, r) =>
          Number(r.currentVersion) >= 1
            ? `v${r.currentVersion}`
            : <span style={{ color: 'var(--color-text-tertiary)' }}>{t('workflow.definition.unpublished')}</span>,
      },
      {
        title: t('common.createTime'), dataIndex: 'createTime', width: 170, search: false,
        render: (_, r) => formatDateTime(r.createTime),
      },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 150, fixed: 'right',
        render: (_, r) => {
          // 发布/停用按各自权限码显隐,且按当前状态取舍:已停用不再给「停用」。
          const items = [
            has('POST:/api/v1/workflow/definition/publish')
              ? { key: 'publish', label: t('workflow.definition.publish') }
              : null,
            has('POST:/api/v1/workflow/definition/disable') && Number(r.status) !== DEF_STATUS.DISABLED
              ? { key: 'disable', label: t('workflow.definition.disable') }
              : null,
            has('DELETE:/api/v1/workflow/definition/{id:long}')
              ? { key: 'delete', label: t('common.delete'), danger: true }
              : null,
          ].filter((o): o is { key: string; label: string; danger?: boolean } => o !== null)

          return (
            <Space size={0}>
              {has('GET:/api/v1/workflow/definition/{id:long}') && (
                <Button type="link" size="small" onClick={() => openDesigner(r)}>{t('workflow.definition.design')}</Button>
              )}
              {items.length > 0 && (
                <Dropdown
                  trigger={['click']}
                  menu={{
                    items,
                    onClick: ({ key }) => {
                      if (key === 'publish') handlePublish(r)
                      else if (key === 'disable') handleDisable(r)
                      else handleDelete(r)
                    },
                  }}
                >
                  <Button type="link" size="small">{t('common.more')}</Button>
                </Dropdown>
              )}
            </Space>
          )
        },
      },
    ],
    [t, has, openDesigner, handlePublish, handleDisable, handleDelete],
  )

  return (
    <DataTable<WfDefinitionRow>
      ref={tableRef}
      columns={columns}
      fetcher={fetchDefinitions}
      persistKey="workflow-definition"
      rowKey="id"
      toolbar={
        <Can code="POST:/api/v1/workflow/definition/add">
          <Button type="primary" icon={<AppIcon icon="ph:plus" size={16} />} onClick={() => openDesigner()}>
            {t('workflow.definition.create')}
          </Button>
        </Can>
      }
    />
  )
}

// web/src/views/workflow/definition/index.vue
<script setup lang="ts">
/**
 * 流程定义列表。菜单 component 填 `workflow/definition/index`。
 * 「新建」与「设计」都跳设计器(`/workflow/definition/designer`,可带 `?id=`)——
 * 建草稿的逻辑留在设计器的空态里,本页不重复一份。
 */
import { h, ref } from 'vue'
import { useRouter } from 'vue-router'
import { NButton, NDropdown, NEmpty, NSpace, useMessage } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import AppIcon from '@/components/AppIcon.vue'
import { useConfirm } from '@/composables/useConfirm'
import { useAuthStore } from '@/stores/auth'
import { wfDefinitionApi } from '@/api/workflow'
import { translateError } from '@/utils/error'
import type { WfDefinitionRow } from '@/types/workflow'

const { t } = useI18n()
const router = useRouter()
const message = useMessage()
const { confirm } = useConfirm()
const authStore = useAuthStore()
const tableRef = ref<ProTableInst<WfDefinitionRow>>()

// 后端 WfDefinitionStatus:0 草稿 / 1 已发布 / 2 停用(与 detail.vue 的实例状态同用就地数字表)。
const DRAFT = 0
const PUBLISHED = 1
const DISABLED = 2

const statusOptions = [
  { label: () => t('workflow.definition.status.draft'), value: DRAFT, tagType: 'default' as const },
  { label: () => t('workflow.definition.status.published'), value: PUBLISHED, tagType: 'success' as const },
  { label: () => t('workflow.definition.status.disabled'), value: DISABLED, tagType: 'warning' as const },
]

function openDesigner(r?: WfDefinitionRow) {
  const id = r?.id
  void router.push(id ? `/workflow/definition/designer?id=${id}` : '/workflow/definition/designer')
}

async function onPublish(r: WfDefinitionRow) {
  const ok = await confirm({
    content: t('workflow.definition.publishConfirm', { name: r.name ?? '' }),
    action: () => wfDefinitionApi.publish(Number(r.id)),
    successMsg: t('workflow.definition.publishOk'),
  })
  if (ok) await tableRef.value?.refresh()
}

async function onDisable(r: WfDefinitionRow) {
  const ok = await confirm({
    content: t('workflow.definition.disableConfirm', { name: r.name ?? '' }),
    type: 'warning',
    action: () => wfDefinitionApi.disable(Number(r.id)),
    successMsg: t('workflow.definition.disableOk'),
  })
  if (ok) await tableRef.value?.refresh()
}

async function onDelete(r: WfDefinitionRow) {
  const ok = await confirm({
    content: t('workflow.definition.deleteConfirm', { name: r.name ?? '' }),
    type: 'warning',
    action: () => wfDefinitionApi.remove(Number(r.id)),
    successMsg: t('common.deleted'),
  })
  if (ok) await tableRef.value?.refresh()
}

const columns: ProTableColumn<WfDefinitionRow>[] = [
  {
    key: 'name',
    title: () => t('workflow.definition.name'),
    search: true,
    minWidth: 180,
    ellipsis: { tooltip: true },
    render: (r) =>
      h(NSpace, { align: 'center', size: 6, wrapItem: false }, () => [
        r.icon ? h(AppIcon, { icon: r.icon, size: 18 }) : null,
        r.name || '—',
      ]),
  },
  {
    key: 'groupName',
    title: () => t('workflow.definition.group'),
    search: true,
    width: 140,
    ellipsis: { tooltip: true },
    render: (r) => r.groupName || '—',
  },
  { key: 'status', title: () => t('common.status'), width: 110, tag: true, search: true, options: statusOptions },
  {
    key: 'currentVersion',
    title: () => t('workflow.definition.version'),
    width: 100,
    align: 'center',
    // 草稿的 currentVersion 是 0:显示 v0 会被当成「有个 0 版」,直接给「未发布」更实。
    render: (r) =>
      Number(r.currentVersion) >= 1
        ? `v${r.currentVersion}`
        : h('span', { style: 'color:var(--color-text-tertiary);' }, t('workflow.definition.unpublished')),
  },
  { key: 'createTime', title: () => t('common.createTime'), width: 170, format: 'datetime' },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 150,
    fixed: 'right',
    hideInSetting: true,
    render: (r) => {
      // 发布/停用按各自权限码显隐,且按当前状态取舍:已发布不再重复给「发布」,已停用不再给「停用」。
      const dropdownOptions = [
        authStore.hasPerm('POST:/api/v1/workflow/definition/publish')
          ? { key: 'publish', label: t('workflow.definition.publish') }
          : null,
        authStore.hasPerm('POST:/api/v1/workflow/definition/disable') && Number(r.status) !== DISABLED
          ? { key: 'disable', label: t('workflow.definition.disable') }
          : null,
        authStore.hasPerm('DELETE:/api/v1/workflow/definition/{id:long}')
          ? { key: 'delete', label: t('common.delete') }
          : null,
      ].filter((o): o is { key: string; label: string } => o !== null)

      return h(NSpace, { size: 2, wrapItem: false }, () => [
        authStore.hasPerm('GET:/api/v1/workflow/definition/{id:long}')
          ? h(
              NButton,
              { size: 'small', quaternary: true, type: 'primary', onClick: () => openDesigner(r) },
              () => t('workflow.definition.design'),
            )
          : null,
        dropdownOptions.length
          ? h(
              NDropdown,
              {
                trigger: 'click',
                options: dropdownOptions,
                onSelect: (key: string) => {
                  if (key === 'publish') void onPublish(r)
                  else if (key === 'disable') void onDisable(r)
                  else void onDelete(r)
                },
              },
              () => h(NButton, { size: 'small', quaternary: true }, () => t('common.more')),
            )
          : null,
      ])
    },
  },
]
</script>

<template>
  <ProTable
    ref="tableRef"
    storage-key="workflow-definition"
    row-key="id"
    :columns="columns"
    :fetcher="wfDefinitionApi.page"
    @error="(e) => message.error(translateError(e))"
  >
    <template #toolbar>
      <n-button
        v-auth="'POST:/api/v1/workflow/definition/add'"
        type="primary"
        @click="openDesigner()"
      >
        <template #icon><AppIcon icon="ph:plus" :size="16" /></template>
        {{ t('workflow.definition.create') }}
      </n-button>
    </template>
    <template #empty>
      <n-empty :description="t('workflow.definition.empty')" size="small" />
    </template>
  </ProTable>
</template>
