// web/src/views/system/module/index.vue
<script setup lang="ts">
import { h, onMounted, reactive, ref } from 'vue'
import {
  NCard, NButton, NSpace, NDataTable, NTag, NForm, NFormItem, NInput, NInputNumber, NSwitch,
  NPopconfirm, useMessage, type DataTableColumns, type FormInst, type FormRules,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import IconPicker from '@/components/IconPicker/index.vue'
import FormContainer from '@/components/FormContainer/index.vue'
import StatusSwitch from '@/components/StatusSwitch/index.vue'
import { useConfirm } from '@/composables/useConfirm'
import { moduleApi } from '@/api'
import { translateError } from '@/utils/error'
import type { ModuleInput, ModuleRow } from '@/types/api'

const { t } = useI18n()
const message = useMessage()
const { run } = useConfirm()

const loading = ref(false)
const rows = ref<ModuleRow[]>([])

/** 内置 system 模块受保护(后端 42013),前端据 code 禁删,避免明知不可为的请求。 */
const isBuiltin = (r: ModuleRow) => r.code === 'system'

async function load() {
  loading.value = true
  try {
    rows.value = await moduleApi.list()
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
}
onMounted(load)

// ── 新增/编辑弹窗(FormContainer:loading/底栏/关闭时机由容器按 onConfirm 协议接管)──
const show = ref(false)
const formRef = ref<FormInst | null>(null)
const rules: FormRules = {
  // whitespace: 保留原「.trim() 禁用保存」的语义,纯空白不算填写
  code: { required: true, whitespace: true, message: () => t('module.codeRequired'), trigger: ['input', 'blur'] },
  title: { required: true, whitespace: true, message: () => t('module.nameRequired'), trigger: ['input', 'blur'] },
}
const editingId = ref<number | null>(null)
const blank = (): ModuleInput => ({ code: '', title: '', icon: '', defaultRoute: '', apiPrefix: '', sort: 0, enabled: true, remark: '' })
const form = reactive<ModuleInput>(blank())

/** 行数据 → 完整入参:openEdit 回填与 StatusSwitch 行内改状态共用(后端无独立启停端点,均走全量 update)。 */
const toInput = (r: ModuleRow): ModuleInput => ({
  code: r.code, title: r.title, icon: r.icon ?? '', defaultRoute: r.defaultRoute ?? '',
  apiPrefix: r.apiPrefix ?? '', sort: r.sort, enabled: r.enabled, remark: r.remark ?? '',
})

function openAdd() {
  editingId.value = null
  Object.assign(form, blank())
  show.value = true
}
function openEdit(r: ModuleRow) {
  editingId.value = r.id
  Object.assign(form, toInput(r))
  show.value = true
}

/** FormContainer onConfirm:校验失败 reject / API 失败 return false → 弹层不关;成功正常返回自动关。 */
async function save() {
  await formRef.value?.validate()
  try {
    if (editingId.value === null) await moduleApi.add({ ...form })
    else await moduleApi.update(editingId.value, { ...form })
    message.success(t('module.saved'))
    await load()
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}

const columns: DataTableColumns<ModuleRow> = [
  { title: () => t('module.code'), key: 'code' },
  {
    title: () => t('module.name'),
    key: 'title',
    render: (r) =>
      h(NSpace, { align: 'center', size: 6, wrapItem: false }, () => [
        r.icon ? h(AppIcon, { icon: r.icon, size: 18 }) : null,
        r.title,
        isBuiltin(r) ? h(NTag, { size: 'small', type: 'info', bordered: false }, () => t('module.builtin')) : null,
      ]),
  },
  { title: () => t('module.defaultRoute'), key: 'defaultRoute', render: (r) => r.defaultRoute || '—' },
  { title: () => t('module.apiPrefix'), key: 'apiPrefix', width: 120, render: (r) => r.apiPrefix || '—' },
  { title: () => t('module.sort'), key: 'sort', width: 80 },
  {
    title: () => t('common.status'),
    key: 'enabled',
    width: 90,
    render: (r) =>
      h(StatusSwitch, {
        value: r.enabled,
        // 内置 system 应用停用会让门户失联(模块/菜单管理页都在它下面,停了就没法从 UI 恢复)——
        // 与「禁删」同级的前端保护;后端 UpdateAsync 暂未拦内置模块,只护删除(42013)。
        disabled: isBuiltin(r),
        // 停用会把应用从门户隐藏,先确认;启用无副作用,跳过确认(返回 null)。
        confirm: (next: boolean) => (next ? null : t('module.disableConfirm', { title: r.title })),
        request: (next: boolean) => moduleApi.update(r.id, { ...toInput(r), enabled: next }),
        'onUpdate:value': (v: boolean) => {
          r.enabled = v
        },
      }),
  },
  {
    title: () => t('common.operation'),
    key: 'op',
    width: 140,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        h(NButton, { size: 'small', quaternary: true, type: 'primary', onClick: () => openEdit(r) }, () => t('common.edit')),
        isBuiltin(r)
          ? null
          : h(
              NPopconfirm,
              {
                // popconfirm 留在模板层当触发器,「执行→toast」后半段交给 useConfirm().run。
                onPositiveClick: () =>
                  run(() => moduleApi.remove(r.id), t('module.deleted')).then((ok) => {
                    if (ok) load()
                  }),
              },
              {
                trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'error' }, () => t('common.delete')),
                default: () => t('module.deleteConfirm', { title: r.title }),
              },
            ),
      ]),
  },
]
</script>

<template>
  <div class="view">
    <n-card :bordered="true">
      <div class="bar">
        <n-button type="primary" @click="openAdd">
          <template #icon><AppIcon icon="ph:plus" :size="16" /></template>{{ t('common.add') }}
        </n-button>
      </div>
      <n-data-table :columns="columns" :data="rows" :loading="loading" :row-key="(r: ModuleRow) => r.id" />
    </n-card>

    <FormContainer
      v-model:show="show"
      :title="editingId === null ? t('module.addTitle') : t('module.editTitle')"
      :width="520"
      :on-confirm="save"
      :confirm-text="t('common.save')"
    >
      <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" :label-width="90">
        <n-form-item :label="t('module.code')" path="code">
          <n-input v-model:value="form.code" :placeholder="t('module.code')" :disabled="editingId !== null" />
        </n-form-item>
        <n-form-item :label="t('module.name')" path="title">
          <n-input v-model:value="form.title" :placeholder="t('module.name')" />
        </n-form-item>
        <n-form-item :label="t('module.icon')">
          <IconPicker :model-value="form.icon ?? ''" @update:model-value="(v: string) => (form.icon = v)" />
        </n-form-item>
        <n-form-item :label="t('module.defaultRoute')">
          <n-input v-model:value="(form.defaultRoute as string)" placeholder="/system/user" />
        </n-form-item>
        <n-form-item :label="t('module.apiPrefix')">
          <n-space vertical :size="2" style="width: 100%">
            <n-input v-model:value="(form.apiPrefix as string)" placeholder="sys" />
            <span class="hint">{{ t('module.apiPrefixHint') }}</span>
          </n-space>
        </n-form-item>
        <n-form-item :label="t('module.sort')">
          <n-input-number v-model:value="form.sort" :min="0" style="width: 160px" />
        </n-form-item>
        <n-form-item :label="t('common.status')">
          <n-switch v-model:value="form.enabled" />
        </n-form-item>
        <n-form-item :label="t('module.remark')">
          <n-input v-model:value="(form.remark as string)" type="textarea" :autosize="{ minRows: 2 }" />
        </n-form-item>
      </n-form>
    </FormContainer>
  </div>
</template>

<style scoped>
.view {
  display: flex;
  flex-direction: column;
  gap: var(--gap-card);
}
.bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}
.bar h3 {
  font-size: var(--font-size-md);
  font-weight: 600;
  color: var(--color-text-primary);
}
.hint {
  font-size: 12px;
  color: var(--color-text-secondary, #999);
}
</style>

// web-react/src/views/system/module/index.tsx
// 应用(模块)管理 = 标准 CRUD:moduleApi.list 静态列表 + 表单弹窗。≠ B7 门户选择器(那是切应用)。
// 内置 system 应用受保护:禁删 + 禁停(停了门户失联,模块/菜单管理页都在它下面)。无独立启停端点 → StatusSwitch 走全量 update。
// 纯逻辑抽 moduleForm.ts(变异钉),本页接线。
import { useCallback, useEffect, useMemo, useState } from 'react'
import { App, Button, Card, Form, Input, InputNumber, Space, Switch, Table, Tag, type TableColumnsType } from 'antd'
import { useTranslation } from 'react-i18next'
import { AppIcon } from '@/components/AppIcon'
import { Can } from '@/components/Can'
import { FormContainer } from '@/components/FormContainer'
import { IconPicker } from '@/components/IconPicker'
import { StatusSwitch } from '@/components/StatusSwitch'
import { useConfirm } from '@/hooks/useConfirm'
import { useHasPerm } from '@/stores/auth'
import { moduleApi } from '@/api'
import { translateError } from '@/utils/error'
import type { ModuleInput, ModuleRow } from '@/types/api'
import { blankModule, isBuiltin, moduleToInput } from './moduleForm'

export default function ModulePage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const { confirm } = useConfirm()
  const has = useHasPerm()

  const [rows, setRows] = useState<ModuleRow[]>([])
  const [loading, setLoading] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      setRows(await moduleApi.list())
    } catch (e) {
      message.error(translateError(e))
    } finally {
      setLoading(false)
    }
  }, [message])
  useEffect(() => { void load() }, [load])

  // ── 新增/编辑弹窗 ──
  const [form] = Form.useForm<ModuleInput>()
  const [open, setOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)

  const openAdd = useCallback(() => { setEditingId(null); form.setFieldsValue(blankModule()); setOpen(true) }, [form])
  const openEdit = useCallback((r: ModuleRow) => { setEditingId(r.id); form.setFieldsValue(moduleToInput(r)); setOpen(true) }, [form])
  const save = async () => {
    const v = await form.validateFields() // 表单渲染全部 8 字段 → validateFields 即全量(无 C9 那种未注册漏字段)
    try {
      if (editingId === null) await moduleApi.add(v)
      else await moduleApi.update(editingId, v)
      message.success(t('module.saved'))
      await load()
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  const handleDelete = useCallback((r: ModuleRow) => {
    confirm({ content: t('module.deleteConfirm', { title: r.title }), action: () => moduleApi.remove(r.id), successMsg: t('module.deleted') }).then(
      (ok) => { if (ok) void load() },
    )
  }, [confirm, t, load])

  const columns = useMemo<TableColumnsType<ModuleRow>>(() => [
    { title: t('module.code'), dataIndex: 'code', ellipsis: true },
    {
      title: t('module.name'), dataIndex: 'title',
      render: (_, r) => (
        <Space size={6}>
          {r.icon ? <AppIcon icon={r.icon} size={18} /> : null}
          {r.title}
          {isBuiltin(r) && <Tag variant="filled" color="blue">{t('module.builtin')}</Tag>}
        </Space>
      ),
    },
    { title: t('module.defaultRoute'), dataIndex: 'defaultRoute', ellipsis: true, render: (_, r) => r.defaultRoute || '—' },
    { title: t('module.apiPrefix'), dataIndex: 'apiPrefix', width: 120, render: (_, r) => r.apiPrefix || '—' },
    { title: t('module.sort'), dataIndex: 'sort', width: 80 },
    {
      title: t('common.status'), dataIndex: 'enabled', width: 90,
      // 无启停权限者退化为只读状态标签(保留可见性);内置应用禁停(停了门户失联)。
      render: (_, r) =>
        has('PUT:/api/v1/sys/module/{id}') ? (
          <StatusSwitch
            value={r.enabled}
            disabled={isBuiltin(r)}
            confirm={(next) => (next ? null : t('module.disableConfirm', { title: r.title }))}
            request={(next) => moduleApi.update(r.id, { ...moduleToInput(r), enabled: next })}
            onChange={() => void load()}
          />
        ) : (
          <Tag variant="filled" color={r.enabled ? 'green' : undefined}>{t(r.enabled ? 'common.enabled' : 'common.disabled')}</Tag>
        ),
    },
    {
      title: t('common.operation'), key: 'op', width: 140,
      render: (_, r) => (
        <Space size={4}>
          {has('PUT:/api/v1/sys/module/{id}') && <Button type="link" size="small" onClick={() => openEdit(r)}>{t('common.edit')}</Button>}
          {/* 内置应用禁删(后端 42013 兜底) */}
          {!isBuiltin(r) && has('DELETE:/api/v1/sys/module/{id}') && (
            <Button type="link" size="small" danger onClick={() => handleDelete(r)}>{t('common.delete')}</Button>
          )}
        </Space>
      ),
    },
  ], [t, has, openEdit, handleDelete, load])

  return (
    <Card>
      <div style={{ marginBottom: 12 }}>
        <Can code="POST:/api/v1/sys/module/add">
          <Button type="primary" onClick={openAdd}>{t('common.add')}</Button>
        </Can>
      </div>
      <Table<ModuleRow> rowKey="id" columns={columns} dataSource={rows} loading={loading} pagination={false} size="small" />

      <FormContainer
        open={open}
        onOpenChange={setOpen}
        title={editingId === null ? t('module.addTitle') : t('module.editTitle')}
        width={520}
        confirmText={t('common.save')}
        onConfirm={save}
      >
        <Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} style={{ marginTop: 12 }}>
          <Form.Item name="code" label={t('module.code')} rules={[{ required: true, whitespace: true, message: t('module.codeRequired') }]}>
            {/* 应用编码建后不可改;编辑时置灰 */}
            <Input disabled={editingId !== null} placeholder={t('module.code')} />
          </Form.Item>
          <Form.Item name="title" label={t('module.name')} rules={[{ required: true, whitespace: true, message: t('module.nameRequired') }]}>
            <Input placeholder={t('module.name')} />
          </Form.Item>
          <Form.Item name="icon" label={t('module.icon')}>
            <IconPicker />
          </Form.Item>
          <Form.Item name="defaultRoute" label={t('module.defaultRoute')}>
            <Input placeholder="/system/user" />
          </Form.Item>
          <Form.Item name="apiPrefix" label={t('module.apiPrefix')} extra={t('module.apiPrefixHint')}>
            <Input placeholder="sys" />
          </Form.Item>
          <Form.Item name="sort" label={t('module.sort')}>
            <InputNumber min={0} style={{ width: 160 }} />
          </Form.Item>
          <Form.Item name="enabled" label={t('common.status')} valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item name="remark" label={t('module.remark')}>
            <Input.TextArea autoSize={{ minRows: 2 }} />
          </Form.Item>
        </Form>
      </FormContainer>
    </Card>
  )
}
