// web/src/views/integration/app/components/AppFormModal.vue
<script setup lang="ts">
// 接入应用新增/编辑。编码创建后不可改(调用记录与排障的稳定锚点);启停走列表行内开关的独立接口。
import { reactive, ref } from 'vue'
import { NForm, NFormItem, NInput, NInputNumber, NSwitch, useMessage, type FormInst, type FormRules } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import FormContainer from '@/components/FormContainer/index.vue'
import OrgTreeSelect from '@/components/OrgTreeSelect/index.vue'
import { integrationAppApi } from '@/api/integration'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'
import type { IntegrationAppRow } from '@/types/integration'

const emit = defineEmits<{ saved: [] }>()
const { t } = useI18n()
const message = useMessage()
const authStore = useAuthStore()

const show = ref(false)
const formRef = ref<FormInst | null>(null)
const editingId = ref<number | string | null>(null)

interface AppForm {
  code: string
  name: string
  description: string
  ownerOrgId: number | null
  rateLimitPerMinute: number | null
  enabled: boolean
}
const blank = (): AppForm => ({ code: '', name: '', description: '', ownerOrgId: null, rateLimitPerMinute: null, enabled: authStore.isSuperAdmin })
const form = reactive<AppForm>(blank())

const rules: FormRules = {
  code: [
    { required: true, whitespace: true, message: () => t('integration.app.codeRequired'), trigger: ['input', 'blur'] },
    { pattern: /^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$/, message: () => t('integration.app.codeHint'), trigger: ['input', 'blur'] },
  ],
  name: { required: true, whitespace: true, message: () => t('integration.app.nameRequired'), trigger: ['input', 'blur'] },
}

function openAdd() {
  editingId.value = null
  Object.assign(form, blank())
  show.value = true
}

function openEdit(r: IntegrationAppRow) {
  editingId.value = r.id ?? null
  Object.assign(form, {
    code: r.code ?? '',
    name: r.name ?? '',
    description: r.description ?? '',
    ownerOrgId: r.ownerOrgId == null ? null : Number(r.ownerOrgId),
    rateLimitPerMinute: r.rateLimitPerMinute == null ? null : Number(r.rateLimitPerMinute),
    enabled: !!r.enabled,
  })
  show.value = true
}
defineExpose({ openAdd, openEdit })

async function save() {
  await formRef.value?.validate()
  const common = {
    name: form.name.trim(),
    description: form.description.trim() || null,
    ownerOrgId: form.ownerOrgId,
    rateLimitPerMinute: form.rateLimitPerMinute,
  }
  try {
    if (editingId.value === null) await integrationAppApi.add({ ...common, code: form.code.trim(), enabled: authStore.isSuperAdmin && form.enabled })
    else await integrationAppApi.update(editingId.value, common)
    message.success(t('integration.app.saved'))
    emit('saved')
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}
</script>

<template>
  <FormContainer
    v-model:show="show"
    :title="editingId === null ? t('integration.app.add') : t('integration.app.edit')"
    :on-confirm="save"
    :confirm-text="t('common.save')"
  >
    <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" :label-width="110">
      <n-form-item :label="t('integration.app.code')" path="code">
        <n-input v-model:value="form.code" :disabled="editingId !== null" :placeholder="t('integration.app.codeHint')" />
      </n-form-item>
      <n-form-item :label="t('integration.app.name')" path="name">
        <n-input v-model:value="form.name" :maxlength="64" />
      </n-form-item>
      <n-form-item :label="t('integration.app.description')" path="description">
        <n-input v-model:value="form.description" type="textarea" :maxlength="256" :autosize="{ minRows: 2, maxRows: 4 }" />
      </n-form-item>
      <n-form-item :label="t('integration.app.ownerOrg')" path="ownerOrgId">
        <OrgTreeSelect v-model:value="form.ownerOrgId" :disabled="!authStore.isSuperAdmin" :placeholder="t('integration.app.ownerOrgHint')" />
      </n-form-item>
      <n-form-item :label="t('integration.app.rateLimit')" path="rateLimitPerMinute">
        <n-input-number
          v-model:value="form.rateLimitPerMinute"
          :min="0"
          :max="1000000"
          clearable
          :placeholder="t('integration.app.rateLimitHint')"
          style="width: 100%"
        />
      </n-form-item>
      <n-form-item v-if="editingId === null && authStore.isSuperAdmin" :label="t('integration.app.enabled')" path="enabled">
        <n-switch v-model:value="form.enabled" />
      </n-form-item>
    </n-form>
  </FormContainer>
</template>

// web-react/src/views/integration/app/components/AppFormModal.tsx
// 接入应用新增/编辑。编码创建后不可改(调用记录与排障的稳定锚点);启停走列表行内开关的独立接口。
import { forwardRef, useImperativeHandle, useState } from 'react'
import { App, Form, Input, InputNumber, Switch } from 'antd'
import { useTranslation } from 'react-i18next'
import { FormContainer } from '@/components/FormContainer'
import { OrgTreeSelect } from '@/components/OrgTreeSelect'
import { integrationAppApi } from '@/api/integration'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'
import type { IntegrationAppRow } from '@/types/integration'

export interface AppFormModalHandle {
  openAdd: () => void
  openEdit: (row: IntegrationAppRow) => void
}

interface AppForm {
  code: string
  name: string
  description?: string
  ownerOrgId?: number | null
  rateLimitPerMinute?: number | null
  enabled: boolean
}

const CODE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$/

export const AppFormModal = forwardRef<AppFormModalHandle, { onSaved: () => void }>(function AppFormModal({ onSaved }, ref) {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const isSuperAdmin = useAuthStore((s) => s.isSuperAdmin)
  const [form] = Form.useForm<AppForm>()
  const [open, setOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | string | null>(null)

  useImperativeHandle(ref, () => ({
    openAdd: () => {
      setEditingId(null)
      form.resetFields()
      form.setFieldsValue({ code: '', name: '', description: '', ownerOrgId: null, rateLimitPerMinute: null, enabled: isSuperAdmin })
      setOpen(true)
    },
    openEdit: (r) => {
      setEditingId(r.id ?? null)
      form.resetFields()
      form.setFieldsValue({
        code: r.code ?? '',
        name: r.name ?? '',
        description: r.description ?? '',
        ownerOrgId: r.ownerOrgId == null ? null : Number(r.ownerOrgId),
        rateLimitPerMinute: r.rateLimitPerMinute == null ? null : Number(r.rateLimitPerMinute),
        enabled: !!r.enabled,
      })
      setOpen(true)
    },
  }), [form, isSuperAdmin])

  const save = async () => {
    const v = await form.validateFields()
    const common = {
      name: v.name.trim(),
      description: v.description?.trim() || null,
      ownerOrgId: v.ownerOrgId ?? null,
      rateLimitPerMinute: v.rateLimitPerMinute ?? null,
    }
    try {
      if (editingId === null) await integrationAppApi.add({ ...common, code: v.code.trim(), enabled: isSuperAdmin && !!v.enabled })
      else await integrationAppApi.update(editingId, common)
      message.success(t('integration.app.saved'))
      onSaved()
    } catch (e) {
      message.error(translateError(e))
      return false
    }
  }

  return (
    <FormContainer
      open={open}
      onOpenChange={setOpen}
      title={editingId === null ? t('integration.app.add') : t('integration.app.edit')}
      confirmText={t('common.save')}
      onConfirm={save}
    >
      <Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} style={{ marginTop: 12 }}>
        <Form.Item
          name="code"
          label={t('integration.app.code')}
          rules={[
            { required: true, whitespace: true, message: t('integration.app.codeRequired') },
            { pattern: CODE_PATTERN, message: t('integration.app.codeHint') },
          ]}
        >
          <Input disabled={editingId !== null} placeholder={t('integration.app.codeHint')} />
        </Form.Item>
        <Form.Item name="name" label={t('integration.app.name')} rules={[{ required: true, whitespace: true, message: t('integration.app.nameRequired') }]}>
          <Input maxLength={64} />
        </Form.Item>
        <Form.Item name="description" label={t('integration.app.description')}>
          <Input.TextArea maxLength={256} autoSize={{ minRows: 2, maxRows: 4 }} />
        </Form.Item>
        <Form.Item name="ownerOrgId" label={t('integration.app.ownerOrg')}>
          <OrgTreeSelect placeholder={t('integration.app.ownerOrgHint')} allowClear disabled={!isSuperAdmin} />
        </Form.Item>
        <Form.Item name="rateLimitPerMinute" label={t('integration.app.rateLimit')} extra={t('integration.app.rateLimitHint')}>
          <InputNumber min={0} max={1000000} style={{ width: '100%' }} />
        </Form.Item>
        {editingId === null && isSuperAdmin && (
          <Form.Item name="enabled" label={t('integration.app.enabled')} valuePropName="checked">
            <Switch />
          </Form.Item>
        )}
      </Form>
    </FormContainer>
  )
})
