// web/src/views/system/recycle/index.vue
<script setup lang="ts">
import { h, ref } from 'vue'
import { NButton, NSpace, NTabs, NTabPane, NPopconfirm, useMessage } from 'naive-ui'
import { ProTable, type ProTableColumn, type ProTableInst } from 'tenon-naive-pro-table'
import { useI18n } from 'vue-i18n'
import { useConfirm } from '@/composables/useConfirm'
import { recycleApi, type RecycleBinItem } from '@/api'
import { translateError } from '@/utils/error'

const { t } = useI18n()
const message = useMessage()
const { run } = useConfirm()

const types = ['user', 'role', 'org', 'position', 'module', 'config', 'dict', 'menu'] as const
type RecycleType = (typeof types)[number]
const activeTab = ref<RecycleType>('user')
const tableRefs = ref<Record<string, ProTableInst<RecycleBinItem>>>({})

function setTableRef(type: string) {
  return (el: any) => { if (el) tableRefs.value[type] = el }
}

function refreshTab(type: string) {
  tableRefs.value[type]?.refresh()
}

const columns: ProTableColumn<RecycleBinItem>[] = [
  { key: 'name', title: () => t('recycle.name') },
  { key: 'code', title: () => t('recycle.code') },
  { key: 'deletedAt', title: () => t('recycle.deletedAt'), format: 'datetime', width: 180 },
  {
    key: 'op',
    title: () => t('common.operation'),
    width: 180,
    hideInSetting: true,
    render: (r) =>
      h(NSpace, { size: 4, wrapItem: false }, () => [
        h(
          NPopconfirm,
          {
            onPositiveClick: () =>
              run(() => recycleApi.restore(activeTab.value, r.id), t('recycle.restored')).then((ok) => {
                if (ok) refreshTab(activeTab.value)
              }),
          },
          {
            trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'primary' }, () => t('recycle.restore')),
            default: () => t('recycle.restoreConfirm', { name: r.name }),
          },
        ),
        h(
          NPopconfirm,
          {
            onPositiveClick: () =>
              run(() => recycleApi.purge(activeTab.value, r.id), t('recycle.purged')).then((ok) => {
                if (ok) refreshTab(activeTab.value)
              }),
          },
          {
            trigger: () => h(NButton, { size: 'small', quaternary: true, type: 'error' }, () => t('recycle.purge')),
            default: () => t('recycle.purgeConfirm', { name: r.name }),
          },
        ),
      ]),
  },
]
</script>

<template>
  <div class="view">
    <n-tabs v-model:value="activeTab" type="line" animated>
      <n-tab-pane v-for="type in types" :key="type" :name="type" :tab="t(`recycle.tabs.${type}`)">
        <ProTable
          :ref="setTableRef(type)"
          :columns="columns"
          :fetcher="recycleApi.page(type)"
          :storage-key="`sys-recycle-${type}`"
          @error="(e: unknown) => message.error(translateError(e))"
        />
      </n-tab-pane>
    </n-tabs>
  </div>
</template>

<style scoped>
.view {
  display: flex;
  flex-direction: column;
  gap: var(--gap-card);
}
</style>

// web-react/src/views/system/recycle/index.tsx
// 回收站页:8 类实体各一页签,每页签一张只读列表 + 行内「恢复 / 彻底删除」。
// antd Tabs(items API)只做切页签;单个 DataTable 用 `key={activeTab}` 随切页重挂(拉当前类型的数据)。
// 恢复/彻底删走 useConfirm 二次确认,按 activeTab + 行 id 定位(选错类型会还原错实体,是会静默出错的点)。
import { useCallback, useMemo, useRef, useState } from 'react'
import { Button, Space, Tabs } from 'antd'
import { useTranslation } from 'react-i18next'
import { DataTable, type DataTableHandle, type PageFetcher } from '@/components/DataTable'
import type { ProColumns } from '@ant-design/pro-components'
import { useConfirm } from '@/hooks/useConfirm'
import { useHasPerm } from '@/stores/auth'
import { recycleApi, type RecycleBinItem } from '@/api'

const RECYCLE_TYPES = ['user', 'role', 'org', 'position', 'module', 'config', 'dict', 'menu'] as const
type RecycleType = (typeof RECYCLE_TYPES)[number]

export default function RecyclePage() {
  const { t } = useTranslation()
  const { confirm } = useConfirm()
  const has = useHasPerm()

  const [activeTab, setActiveTab] = useState<RecycleType>('user')
  const tableRef = useRef<DataTableHandle>(null)
  const reload = useCallback(() => tableRef.current?.reload(), [])

  // fetcher 按当前页签类型拉数(recycleApi.page 是「按 type 柯里化」出的分页函数)。
  const fetchRecycle: PageFetcher<RecycleBinItem> = (q) => recycleApi.page(activeTab)({ page: q.page, pageSize: q.pageSize })

  const handleRestore = useCallback(
    (r: RecycleBinItem) => {
      confirm({ content: t('recycle.restoreConfirm', { name: r.name }), action: () => recycleApi.restore(activeTab, r.id), successMsg: t('recycle.restored') }).then(
        (ok) => { if (ok) reload() },
      )
    },
    [confirm, t, activeTab, reload],
  )
  const handlePurge = useCallback(
    (r: RecycleBinItem) => {
      confirm({ content: t('recycle.purgeConfirm', { name: r.name }), action: () => recycleApi.purge(activeTab, r.id), successMsg: t('recycle.purged') }).then(
        (ok) => { if (ok) reload() },
      )
    },
    [confirm, t, activeTab, reload],
  )

  const columns = useMemo<ProColumns<RecycleBinItem>[]>(
    () => [
      { title: t('recycle.name'), dataIndex: 'name', search: false },
      { title: t('recycle.code'), dataIndex: 'code', search: false, render: (_, r) => r.code || '—' },
      { title: t('recycle.deletedAt'), dataIndex: 'deletedAt', search: false, width: 180 },
      {
        title: t('common.operation'), key: 'op', search: false, hideInSetting: true, width: 180, fixed: 'right',
        render: (_, r) => (
          <Space size={4}>
            {has('POST:/api/v1/sys/recycle/{type}/{id}/restore') && <Button type="link" size="small" onClick={() => handleRestore(r)}>{t('recycle.restore')}</Button>}
            {has('DELETE:/api/v1/sys/recycle/{type}/{id}') && <Button type="link" size="small" danger onClick={() => handlePurge(r)}>{t('recycle.purge')}</Button>}
          </Space>
        ),
      },
    ],
    [t, has, handleRestore, handlePurge],
  )

  return (
    <>
      <Tabs
        activeKey={activeTab}
        onChange={(k) => setActiveTab(k as RecycleType)}
        items={RECYCLE_TYPES.map((type) => ({ key: type, label: t(`recycle.tabs.${type}`) }))}
      />
      <DataTable<RecycleBinItem>
        key={activeTab}
        ref={tableRef}
        columns={columns}
        fetcher={fetchRecycle}
        persistKey={`sys-recycle-${activeTab}`}
      />
    </>
  )
}
