// web/src/views/system/org/index.vue
<script setup lang="ts">
// 机构管理 = 树表:ProTable 静态数据 + children 树模式(无分页)。
// org list 平铺 → buildTree 拼 children;上级机构用 OrgTreeSelect(剪自身子树防成环);
// 无独立启停端点,StatusSwitch 走全量 update;删除有子机构后端拒,前端照调由 translateError 弹码。
import { computed, h, onMounted, reactive, ref, watch } from 'vue'
import {
  NButton, NSpace, NForm, NFormItem, NInput, NInputNumber, NSwitch,
  NDropdown, NModal, NCard, useMessage, type FormInst, type FormRules,
} from 'naive-ui'
import { ProTable, type ProTableColumn } from 'tenon-naive-pro-table'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import DictSelect from '@/components/DictSelect/index.vue'
import DictTag from '@/components/DictTag/index.vue'
import FormContainer from '@/components/FormContainer/index.vue'
import OrgTreeSelect from '@/components/OrgTreeSelect/index.vue'
import UserSelect from '@/components/UserSelect/index.vue'
import StatusSwitch from '@/components/StatusSwitch/index.vue'
import { useConfirm } from '@/composables/useConfirm'
import { orgApi } from '@/api'
import { useAuthStore } from '@/stores/auth'
import { translateError } from '@/utils/error'
import { buildTree, expandableIds, filterTree, type Tree } from '@/utils/tree'
import type { OrgInput, SysOrg } from '@/types/api'

const { t } = useI18n()
const message = useMessage()
const { run, confirm } = useConfirm()
const authStore = useAuthStore()

const loading = ref(false)
const tree = ref<Tree<SysOrg>[]>([])

async function load() {
  loading.value = true
  try {
    tree.value = buildTree(await orgApi.list())
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
}
onMounted(load)

// ── 搜索 + 展开控制 ───────────────────────────────────────────────
// ProTable 静态 data 模式不做任何前端过滤(它只在 fetcher 模式下发请求),所以过滤得自己算。
// 关键字放 #toolbar 而不是用列的 search 配置:树表没有分页,搜索卡片会白占一整块高度。
const keyword = ref('')
const filteredTree = computed(() => {
  const kw = keyword.value.trim().toLowerCase()
  if (!kw) return tree.value
  return filterTree(tree.value, (n) => n.name.toLowerCase().includes(kw) || n.code.toLowerCase().includes(kw))
})

// 展开受控:一旦传了 expanded-row-keys,naive 就以它为准,default-expand-all 会被初始值直接覆盖成"全折叠",
// 所以"默认全展开"得自己播种。data 变了受控 keys 也不会自动跟着变 —— 搜索后要重算,否则命中结果藏在折叠的祖先里看不见。
const expandedKeys = ref<number[]>([])
watch(filteredTree, (t) => (expandedKeys.value = expandableIds(t)), { immediate: true })

const allExpanded = computed(() => expandedKeys.value.length > 0)
const toggleExpandAll = () => (expandedKeys.value = allExpanded.value ? [] : expandableIds(filteredTree.value))

// ── 弹窗表单(parentId 可空:OrgTreeSelect clearable → null,save 时归一为 0=根)──
interface OrgForm {
  parentId: number | null
  name: string
  code: string
  category: string | null
  sort: number
  enabled: boolean
  leaderUserId: number | null
}
const show = ref(false)
const formRef = ref<FormInst | null>(null)
const editingId = ref<number | null>(null)
const rules: FormRules = {
  name: { required: true, whitespace: true, message: () => t('org.nameRequired'), trigger: ['input', 'blur'] },
}
const blank = (): OrgForm => ({ parentId: 0, name: '', code: '', category: null, sort: 0, enabled: true, leaderUserId: null })
const form = reactive<OrgForm>(blank())

// 行数据 → 完整入参:openEdit 回填与 StatusSwitch 行内改状态共用(后端无独立启停端点,均走全量 update)。
const toInput = (r: SysOrg): OrgInput => ({
  parentId: r.parentId,
  name: r.name,
  code: r.code,
  category: r.category ?? null,
  sort: r.sort,
  enabled: r.enabled,
  leaderUserId: r.leaderUserId ?? null,
})

function openAdd(parentId = 0) {
  editingId.value = null
  Object.assign(form, blank(), { parentId })
  show.value = true
}
function openEdit(r: SysOrg) {
  editingId.value = r.id
  Object.assign(form, toInput(r))
  show.value = true
}

/** FormContainer onConfirm:校验失败 reject / API 失败 return false → 弹层不关;成功正常返回自动关。 */
async function save() {
  await formRef.value?.validate()
  try {
    const payload: OrgInput = { ...form, parentId: form.parentId ?? 0 }
    if (editingId.value === null) await orgApi.add(payload)
    else await orgApi.update(editingId.value, payload)
    message.success(t('org.saved'))
    await load()
  } catch (e) {
    message.error(translateError(e))
    return false
  }
}

// ── 复制弹窗 ──────────────────────────────────────────────────────
const copyShow = ref(false)
const copyId = ref(0)
const copySourceName = ref('')
const copyName = ref('')

function openCopy(r: SysOrg) {
  copyId.value = r.id
  copySourceName.value = r.name
  copyName.value = r.name + '-副本'
  copyShow.value = true
}
async function confirmCopy() {
  const ok = await run(() => orgApi.copy(copyId.value, { name: copyName.value }), t('org.copied'))
  if (ok) { copyShow.value = false; load() }
}

/** 删除:下拉菜单项不适合内联 popconfirm,走 useConfirm().confirm 的 dialog(它的设计用途)。 */
const onDelete = (r: SysOrg) =>
  confirm({
    content: t('org.deleteConfirm', { name: r.name }),
    type: 'error',
    action: () => orgApi.remove(r.id),
    successMsg: t('org.deleted'),
  }).then((ok) => {
    if (ok) load()
  })

const columns: ProTableColumn<Tree<SysOrg>>[] = [
  // 树列左对齐,展开缩进才好读;fixed 是为了横向滚动时不丢失「这是哪一行」。
  { title: () => t('org.name'), key: 'name', align: 'left', minWidth: 220, fixed: 'left', ellipsis: { tooltip: true } },
  { title: () => t('org.code'), key: 'code', ellipsis: { tooltip: true } },
  { title: () => t('org.category'), key: 'category', width: 100, render: (r) => h(DictTag, { typeCode: 'org_category', value: r.category }) },
  { title: () => t('org.sort'), key: 'sort', width: 80 },
  {
    title: () => t('common.status'),
    key: 'enabled',
    width: 90,
    render: (r) =>
      h(StatusSwitch, {
        value: r.enabled,
        disabled: !authStore.hasPerm('PUT:/api/v1/sys/org/{id}'),
        request: (next: boolean) => orgApi.update(r.id, { ...toInput(r), enabled: next }),
        // 重拉而非往行对象上写:搜索态下的祖先行是 filterTree 的浅拷贝,写它不会回到源树(开关会弹回去)。
        // StatusSwitch 是悲观更新(请求成功才 emit),所以这里重拉一次就是最终态,和本页其余变更的做法一致。
        'onUpdate:value': () => load(),
      }),
  },
  // 操作收敛成「编辑 + 更多▾」:4 个操作塞 260px 会换行、行高参差,且没 fixed 时横向滚动够不着。
  {
    title: () => t('common.operation'),
    key: 'op',
    width: 150,
    fixed: 'right',
    render: (r) => {
      // 每个操作按各自权限码显隐;更多▾下拉只保留已授权项,全无则不出下拉。
      const dropdownOptions = [
        authStore.hasPerm('POST:/api/v1/sys/org/add') ? { key: 'addChild', label: t('org.addChild') } : null,
        authStore.hasPerm('POST:/api/v1/sys/org/{id}/copy') ? { key: 'copy', label: t('org.copy') } : null,
        authStore.hasPerm('DELETE:/api/v1/sys/org/{id}') ? { key: 'delete', label: t('common.delete') } : null,
      ].filter((o): o is { key: string; label: string } => o !== null)
      return h(NSpace, { size: 2, wrapItem: false, justify: 'center' }, () => [
        authStore.hasPerm('PUT:/api/v1/sys/org/{id}')
          ? h(NButton, { size: 'small', quaternary: true, type: 'primary', onClick: () => openEdit(r) }, () => t('common.edit'))
          : null,
        dropdownOptions.length
          ? h(
              NDropdown,
              {
                trigger: 'click',
                options: dropdownOptions,
                onSelect: (key: string) => {
                  if (key === 'addChild') openAdd(r.id)
                  else if (key === 'copy') openCopy(r)
                  else onDelete(r)
                },
              },
              () => h(NButton, { size: 'small', quaternary: true }, () => t('common.more')),
            )
          : null,
      ])
    },
  },
]
</script>

<template>
  <div class="view">
    <!-- expanded-row-keys / update:expanded-row-keys 不是 ProTable 的 prop —— 它 inheritAttrs:false + v-bind="attrs",
         未声明的 attr 原样透传给内层 n-data-table(现有的 :loading、原来的 default-expand-all 走的都是这条路)。 -->
    <ProTable
      :columns="columns"
      :data="filteredTree"
      :loading="loading"
      row-key="id"
      :pagination="false"
      :toolbar="{ refresh: false }"
      storage-key="sys-org"
      :expanded-row-keys="expandedKeys"
      @update:expanded-row-keys="(keys: number[]) => (expandedKeys = keys)"
    >
      <template #toolbar>
        <n-input v-model:value="keyword" clearable :placeholder="t('org.searchPlaceholder')" style="width: 220px">
          <template #prefix><AppIcon icon="ph:magnifying-glass" :size="16" /></template>
        </n-input>
        <n-button quaternary :loading="loading" @click="load">
          <template #icon><AppIcon icon="ph:arrow-clockwise" :size="16" /></template>
        </n-button>
        <n-button quaternary @click="toggleExpandAll">
          <template #icon>
            <AppIcon :icon="allExpanded ? 'ph:arrows-in-line-vertical' : 'ph:arrows-out-line-vertical'" :size="16" />
          </template>
          {{ allExpanded ? t('common.collapseAll') : t('common.expandAll') }}
        </n-button>
        <n-button v-auth="'POST:/api/v1/sys/org/add'" type="primary" @click="openAdd(0)">
          <template #icon><AppIcon icon="ph:plus" :size="16" /></template>{{ t('common.add') }}
        </n-button>
      </template>
    </ProTable>

    <FormContainer
      v-model:show="show"
      :title="editingId === null ? t('org.addTitle') : t('org.editTitle')"
      :width="480"
      :on-confirm="save"
      :confirm-text="t('common.save')"
    >
      <n-form ref="formRef" :model="form" :rules="rules" label-placement="left" :label-width="80">
        <n-form-item :label="t('org.parent')">
          <OrgTreeSelect
            v-model:value="form.parentId"
            clearable
            :exclude-subtree-of="editingId"
            :placeholder="t('org.parentPlaceholder')"
          />
        </n-form-item>
        <n-form-item :label="t('org.name')" path="name">
          <n-input v-model:value="form.name" :placeholder="t('org.name')" />
        </n-form-item>
        <n-form-item :label="t('org.code')">
          <n-input v-model:value="form.code" :placeholder="t('org.codePlaceholder')" :disabled="editingId !== null" />
        </n-form-item>
        <n-form-item :label="t('org.category')">
          <DictSelect v-model:value="form.category" type-code="org_category" clearable :placeholder="t('org.categoryPlaceholder')" />
        </n-form-item>
        <n-form-item :label="t('org.sort')">
          <n-input-number v-model:value="form.sort" :min="0" style="width: 160px" />
        </n-form-item>
        <n-form-item :label="t('org.leader')">
          <UserSelect v-model:value="form.leaderUserId" clearable :placeholder="t('org.leaderPlaceholder')" />
        </n-form-item>
        <n-form-item :label="t('common.status')">
          <n-switch v-model:value="form.enabled" />
        </n-form-item>
      </n-form>
    </FormContainer>

    <n-modal v-model:show="copyShow" :mask-closable="false">
      <n-card :title="t('org.copyTitle')" style="width: 420px" :bordered="false" closable @close="copyShow = false">
        <p style="margin: 0 0 12px">{{ t('org.copyConfirm', { name: copySourceName }) }}</p>
        <n-input v-model:value="copyName" :placeholder="t('org.copyNameLabel')" />
        <template #action>
          <n-space justify="end">
            <n-button @click="copyShow = false">{{ t('common.cancel') }}</n-button>
            <n-button type="primary" @click="confirmCopy">{{ t('common.confirm') }}</n-button>
          </n-space>
        </template>
      </n-card>
    </n-modal>
  </div>
</template>

<style scoped>
.view {
  display: flex;
  flex-direction: column;
  gap: var(--gap-card);
}
</style>

// web-react/src/views/system/org/index.tsx
// 机构管理 = 树表:orgApi.list 平铺 → buildTree 拼 children,静态数据 + 受控展开(无分页)。
// 上级机构用 OrgTreeSelect(剪自身子树防成环);无独立启停端点,StatusSwitch 走全量 update。
// filterTree 是浅拷贝,故 StatusSwitch 成功后**重拉整树**而非写行(写浅拷贝的祖先行不会回源树,开关会弹回)。
// 照 B11 范式:纯逻辑抽 orgForm.ts(变异钉),本页只接线。
import { useCallback, useEffect, useMemo, useState } from 'react'
import { App, Button, Dropdown, Form, Input, InputNumber, Space, Switch, Tooltip, type MenuProps } from 'antd'
import { useTranslation } from 'react-i18next'
import { ProColumns } from '@ant-design/pro-components'
import { AppIcon } from '@/components/AppIcon'
import { TreeTable } from '@/components/TreeTable'
import { Can } from '@/components/Can'
import { DictSelect } from '@/components/DictSelect'
import { DictTag } from '@/components/DictTag'
import { FormContainer } from '@/components/FormContainer'
import { OrgTreeSelect } from '@/components/OrgTreeSelect'
import { StatusSwitch } from '@/components/StatusSwitch'
import { useConfirm } from '@/hooks/useConfirm'
import { useHasPerm } from '@/stores/auth'
import { orgApi } from '@/api'
import { translateError } from '@/utils/error'
import { buildTree, expandableIds, filterTree, type Tree } from '@/utils/tree'
import type { OrgInput, SysOrg } from '@/types/api'
import { blankForm, rowToInput } from './orgForm'

export default function OrgPage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const { confirm, run } = useConfirm()
  const has = useHasPerm()

  const [tree, setTree] = useState<Tree<SysOrg>[]>([])
  const [loading, setLoading] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [expandedKeys, setExpandedKeys] = useState<number[]>([])

  const load = useCallback(async () => {
    setLoading(true)
    try {
      setTree(buildTree(await orgApi.list()))
    } catch (e) {
      message.error(translateError(e))
    } finally {
      setLoading(false)
    }
  }, [message])
  useEffect(() => { void load() }, [load])

  // 静态树自己算过滤(ProTable dataSource 模式不做前端筛选);关键字放工具栏而非列 search:树表无分页,搜索卡片白占高度。
  const filteredTree = useMemo(() => {
    const kw = keyword.trim().toLowerCase()
    if (!kw) return tree
    return filterTree(tree, (n) => n.name.toLowerCase().includes(kw) || n.code.toLowerCase().includes(kw))
  }, [tree, keyword])

  // 展开受控:默认全展开须自己播种,data 变(搜索/重拉)后重算——否则命中藏在折叠祖先里看不见。
  // 手动展开/折叠只改 expandedKeys、不动 filteredTree,故不会被这条重置。
  useEffect(() => { setExpandedKeys(expandableIds(filteredTree)) }, [filteredTree])
  const allExpanded = expandedKeys.length > 0
  const toggleExpandAll = () => setExpandedKeys(allExpanded ? [] : expandableIds(filteredTree))

  // ── 新增/编辑弹窗(FormContainer owns loading+close)──
  const [form] = Form.useForm<OrgInput>()
  const [open, setOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)

  const openAdd = useCallback((parentId = 0) => {
    setEditingId(null)
    form.setFieldsValue(blankForm(parentId))
    setOpen(true)
  }, [form])
  const openEdit = useCallback((r: SysOrg) => {
    setEditingId(r.id)
    form.setFieldsValue(rowToInput(r))
    setOpen(true)
  }, [form])

  const save = async () => {
    const v = await form.validateFields() // 校验失败抛 → FormContainer 不关
    try {
      // OrgTreeSelect 可清空 → parentId 可能 undefined/null,归一为 0=根。
      const payload: OrgInput = { ...v, parentId: v.parentId ?? 0 }
      if (editingId === null) await orgApi.add(payload)
      else await orgApi.update(editingId, payload)
      message.success(t('org.saved'))
      await load()
    } catch (e) {
      message.error(translateError(e))
      return false // 留在弹层
    }
  }

  // ── 复制弹窗 ──
  const [copyOpen, setCopyOpen] = useState(false)
  const [copyId, setCopyId] = useState(0)
  const [copySourceName, setCopySourceName] = useState('')
  const [copyName, setCopyName] = useState('')

  const openCopy = useCallback((r: SysOrg) => {
    setCopyId(r.id)
    setCopySourceName(r.name)
    setCopyName(`${r.name}-副本`)
    setCopyOpen(true)
  }, [])
  const confirmCopy = async () => {
    const ok = await run(() => orgApi.copy(copyId, { name: copyName }), t('org.copied'))
    if (ok) await load()
    return ok
  }

  const handleDelete = useCallback((r: SysOrg) => {
    confirm({ content: t('org.deleteConfirm', { name: r.name }), action: () => orgApi.remove(r.id), successMsg: t('org.deleted') }).then(
      (ok) => { if (ok) void load() },
    )
  }, [confirm, t, load])

  const columns = useMemo<ProColumns<Tree<SysOrg>>[]>(() => [
    { title: t('org.name'), dataIndex: 'name', ellipsis: true }, // 树列须排首位(承载展开箭头)
    { title: t('org.code'), dataIndex: 'code', ellipsis: true },
    { title: t('org.category'), dataIndex: 'category', width: 110, render: (_, r) => <DictTag typeCode="org_category" value={r.category} /> },
    { title: t('org.sort'), dataIndex: 'sort', width: 80 },
    {
      title: t('common.status'), dataIndex: 'enabled', width: 90,
      render: (_, r) => (
        <StatusSwitch
          value={r.enabled}
          disabled={!has('PUT:/api/v1/sys/org/{id}')}
          request={(next) => orgApi.update(r.id, { ...rowToInput(r), enabled: next })}
          onChange={() => void load()} // 重拉而非写行:filterTree 浅拷贝写不回源树
        />
      ),
    },
    {
      // 操作收敛成「编辑 + 更多▾」:4 个操作平铺会换行、fixed 才够得着;各项按各自权限码显隐,全无则不出下拉。
      title: t('common.operation'), key: 'op', width: 150, fixed: 'right',
      render: (_, r) => {
        const moreItems = ([
          has('POST:/api/v1/sys/org/add') ? { key: 'addChild', label: t('org.addChild') } : null,
          has('POST:/api/v1/sys/org/{id}/copy') ? { key: 'copy', label: t('org.copy') } : null,
          has('DELETE:/api/v1/sys/org/{id}') ? { key: 'delete', label: t('common.delete'), danger: true } : null,
        ] as MenuProps['items'])!.filter(Boolean)
        const onMore: MenuProps['onClick'] = ({ key }) => {
          if (key === 'addChild') openAdd(r.id)
          else if (key === 'copy') openCopy(r)
          else handleDelete(r)
        }
        return (
          <Space size={4}>
            {has('PUT:/api/v1/sys/org/{id}') && <Button type="link" size="small" onClick={() => openEdit(r)}>{t('common.edit')}</Button>}
            {moreItems!.length > 0 && (
              <Dropdown menu={{ items: moreItems, onClick: onMore }} trigger={['click']}>
                <Button type="link" size="small">{t('common.more')}</Button>
              </Dropdown>
            )}
          </Space>
        )
      },
    },
  ], [t, has, load, openAdd, openEdit, openCopy, handleDelete])

  return (
    <>
      <TreeTable<Tree<SysOrg>>
        columns={columns}
        data={filteredTree}
        loading={loading}
        expandedRowKeys={expandedKeys}
        onExpandedRowKeysChange={(keys) => setExpandedKeys(keys as number[])}
        persistKey="sys-org"
        toolbar={
          <Space>
            <Input
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              allowClear
              placeholder={t('org.searchPlaceholder')}
              style={{ width: 220 }}
            />
            {/* icon-only(对齐 Vue):文案键复用 proTable.refresh,不新增 common 键 */}
            <Tooltip title={t('proTable.refresh')}>
              <Button
                icon={<AppIcon icon="ph:arrow-clockwise" size={16} />}
                aria-label={t('proTable.refresh')}
                onClick={() => void load()}
                loading={loading}
              />
            </Tooltip>
            <Button onClick={toggleExpandAll}>{allExpanded ? t('common.collapseAll') : t('common.expandAll')}</Button>
            <Can code="POST:/api/v1/sys/org/add">
              <Button type="primary" onClick={() => openAdd(0)}>{t('common.add')}</Button>
            </Can>
          </Space>
        }
      />

      <FormContainer
        open={open}
        onOpenChange={setOpen}
        title={editingId === null ? t('org.addTitle') : t('org.editTitle')}
        width={480}
        confirmText={t('common.save')}
        onConfirm={save}
      >
        <Form form={form} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} style={{ marginTop: 12 }}>
          <Form.Item name="parentId" label={t('org.parent')}>
            {/* 编辑时剪掉自身子树,防把机构挂到自己后代下成环 */}
            <OrgTreeSelect excludeSubtreeOf={editingId} allowClear placeholder={t('org.parentPlaceholder')} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item name="name" label={t('org.name')} rules={[{ required: true, whitespace: true, message: t('org.nameRequired') }]}>
            <Input placeholder={t('org.name')} />
          </Form.Item>
          <Form.Item name="code" label={t('org.code')}>
            {/* 机构编码建后不可改(后端也拒);编辑时置灰 */}
            <Input disabled={editingId !== null} placeholder={t('org.codePlaceholder')} />
          </Form.Item>
          <Form.Item name="category" label={t('org.category')}>
            <DictSelect typeCode="org_category" allowClear placeholder={t('org.categoryPlaceholder')} />
          </Form.Item>
          <Form.Item name="sort" label={t('org.sort')}>
            <InputNumber min={0} style={{ width: 160 }} />
          </Form.Item>
          <Form.Item name="enabled" label={t('common.status')} valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </FormContainer>

      <FormContainer
        open={copyOpen}
        onOpenChange={setCopyOpen}
        onConfirm={confirmCopy}
        variant="modal"
        title={t('org.copyTitle')}
      >
        <p style={{ margin: '0 0 12px' }}>{t('org.copyConfirm', { name: copySourceName })}</p>
        <Input value={copyName} onChange={(e) => setCopyName(e.target.value)} placeholder={t('org.copyNameLabel')} />
      </FormContainer>
    </>
  )
}
