// web-react/src/views/login/LoginForm.tsx
import { useEffect, useRef, useState } from 'react'
import { App, Button, Checkbox, Form, Input, Modal } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { authApi, externalAuthApi, ApiError, type ExternalProvider } from '@/api'
import { useUserStore } from '@/stores/user'
import { useAuthStore } from '@/stores/auth'
import { useSiteStore, appVersion } from '@/stores/site'
import { translateError } from '@/utils/error'
import { TenonLogo } from '@/components/TenonLogo'
import { AppIcon } from '@/components/AppIcon'
import './loginform.css'

interface FormValues {
  account: string
  password: string
  phone?: string
  smsCode?: string
  captchaCode?: string
  remember: boolean
}

/**
 * 共享登录表单(账号密码路径)。移植 Vue `views/login/LoginForm.vue` 的账号密码那条主干。
 *
 * 三套皮肤(Spotlight/SplitPanel/AuroraGlass)各自提供卡片 chrome + 背景,只内嵌这个表单——
 * 故本组件不再自带 100vh 居中与 Card 外壳,只排版 品牌 / 表单 / 页脚 三段。皮肤外壳自绘品牌栏时
 * (双栏)传 `showBrand={false}` / `showFooter={false}` 关掉卡内重复。文字色走 `--lf-title` / `--lf-hint`
 * 变量(默认跟随应用令牌;深色玻璃皮肤覆写为浅色)。
 *
 * 含第三方登录(SSO)按钮区与短信路径:短信免密登录(`site.smsLoginEnabled` 运行时驱动)
 * + 密码后短信二次验证(40009) / TOTP 挑战(40018) / 强制 MFA 未绑定引导(40020)。
 * 登录页默认不常驻「设置身份验证器」;自愿绑定走个人中心。
 */
export function LoginForm({ showBrand = true, showFooter = true }: { showBrand?: boolean; showFooter?: boolean }) {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const navigate = useNavigate()
  const site = useSiteStore((s) => s.site)
  const loadSite = useSiteStore((s) => s.load)
  const setSession = useUserStore((s) => s.setSession)
  const year = new Date().getFullYear()

  const [loading, setLoading] = useState(false)
  const [captcha, setCaptcha] = useState<{ id: string; svg: string; type: string } | null>(null)
  // 第三方登录:后端 GET providers 驱动(仅点亮已启用的);空数组 = 整段 SSO 区不显。
  const [ssoProviders, setSsoProviders] = useState<ExternalProvider[]>([])
  const [form] = Form.useForm<FormValues>()

  // 登录形态:账号密码 / 短信免密 / 短信二次验证(40009) / TOTP 二次验证(40018)
  // 强制 MFA 未绑定(40020)用 Modal 引导,不切 mode
  const [mode, setMode] = useState<'account' | 'sms' | 'mfa' | 'totp'>('account')
  // 二次验证挑战(40009 信令 args 下发);码输入是单字段小表单,走受控 state 不进 antd Form
  const [mfa, setMfa] = useState({ challengeId: '', phoneMask: '' })
  const [mfaCode, setMfaCode] = useState('')
  const [totp, setTotp] = useState({ challengeId: '' })
  const [totpCode, setTotpCode] = useState('')
  // 强制 MFA 但未绑定(40020):弹窗 + 带到 /mfa/bind 的账号
  const [bindRequiredOpen, setBindRequiredOpen] = useState(false)
  const [bindAccount, setBindAccount] = useState('')

  // 发码/重发共用倒计时(同一时刻只有一个发码入口可见)
  const [countdown, setCountdown] = useState(0)
  const timerRef = useRef<number | undefined>(undefined)
  const startCountdown = (s: number) => {
    window.clearInterval(timerRef.current)
    setCountdown(s)
    timerRef.current = window.setInterval(() => {
      setCountdown((c) => {
        if (c <= 1) window.clearInterval(timerRef.current)
        return c - 1
      })
    }, 1000)
  }
  useEffect(() => () => window.clearInterval(timerRef.current), [])

  async function loadCaptcha() {
    try {
      const c = await authApi.captcha()
      setCaptcha({ id: c.captchaId, svg: c.svg, type: c.type || 'char' })
    } catch {
      // 拉取失败不阻塞登录页渲染;点击图形可重试
    }
  }

  useEffect(() => {
    // 站点信息全站共用(store 内部去重);验证码开关据此**运行时驱动**,启用才拉图。
    void loadSite().then(() => {
      if (useSiteStore.getState().site.captchaEnabled) void loadCaptcha()
    })
    // 未配置外部登录或拉取失败:静默,整段 SSO 区不显
    externalAuthApi.providers().then(setSsoProviders).catch(() => {})

    // SSO 回调带回的 TOTP 挑战
    const ch = new URLSearchParams(window.location.search).get('totpChallenge')
    if (ch) {
      setTotp({ challengeId: ch })
      setTotpCode('')
      setMode('totp')
    }
  }, [loadSite])

  /** 点击第三方登录:顶层导航到 authorize,后端 302 跳 IdP(OAuth2 授权码往返)。 */
  function onSso(code: string) {
    window.location.href = externalAuthApi.authorizeUrl(code)
  }

  /** 验证码一次性消费:任何用掉票据的请求失败后必刷新,避免复用作废票据。 */
  async function refreshCaptchaAfterUse() {
    if (site.captchaEnabled) {
      form.setFieldValue('captchaCode', '')
      await loadCaptcha()
    }
  }

  function finishLogin(res: Awaited<ReturnType<typeof authApi.login>>) {
    // 每次登录清授权态,否则 routesReady 残留 true 会跳过 enterInitial → 空菜单/全 404。
    useAuthStore.getState().reset()
    setSession(res)
    message.success(t('login.success'))
    void navigate('/', { replace: true })
  }

  async function onFinish(values: FormValues) {
    setLoading(true)
    try {
      const res =
        mode === 'sms'
          ? await authApi.smsLogin({ phone: values.phone!, code: values.smsCode! })
          : await authApi.login({
              account: values.account,
              password: values.password,
              captchaId: captcha?.id,
              captchaCode: values.captchaCode,
            })
      finishLogin(res)
    } catch (err) {
      if (err instanceof ApiError && err.code === 40018 && err.args) {
        setTotp({ challengeId: String(err.args.challengeId ?? '') })
        setTotpCode('')
        setMode('totp')
      } else if (err instanceof ApiError && err.code === 40020) {
        // 40020 = 强制 MFA 未绑定 → Modal 引导自助设置(登录页默认不常驻链接)
        const account = String(values.account ?? '').trim()
        setBindAccount(account)
        setBindRequiredOpen(true)
      } else if (err instanceof ApiError && err.code === 40009 && err.args) {
        // 40009 = 密码已过、需短信二次验证
        setMfa({ challengeId: String(err.args.challengeId ?? ''), phoneMask: String(err.args.phoneMask ?? '') })
        setMfaCode('')
        setMode('mfa')
        startCountdown(Number(err.args.resendSeconds ?? 60))
      } else {
        message.error(translateError(err))
      }
      await refreshCaptchaAfterUse()
    } finally {
      setLoading(false)
    }
  }

  function goBindAuthenticator() {
    const account = bindAccount || String(form.getFieldValue('account') ?? '').trim()
    setBindRequiredOpen(false)
    void navigate(account ? `/mfa/bind?account=${encodeURIComponent(account)}` : '/mfa/bind')
  }

  function goRecovery() {
    const account = String(form.getFieldValue('account') ?? '').trim() || bindAccount
    const q = new URLSearchParams({ mode: 'recovery' })
    if (account) q.set('account', account)
    void navigate(`/mfa/bind?${q.toString()}`)
  }

  /** 短信免密:发码。护发码的验证码在此消费(账号模式的验证码护登录本身)。 */
  async function onSendSmsCode() {
    if (countdown > 0) return
    const phone = form.getFieldValue('phone') as string | undefined
    if (!phone) {
      message.warning(t('login.phonePlaceholder'))
      return
    }
    const captchaCode = form.getFieldValue('captchaCode') as string | undefined
    if (site.captchaEnabled && !captchaCode) {
      message.warning(t('login.captchaRequired'))
      return
    }
    try {
      const r = await authApi.smsLoginSend({ phone, captchaId: captcha?.id, captchaCode })
      message.success(t('login.smsSent'))
      startCountdown(r.resendSeconds)
    } catch (err) {
      message.error(translateError(err))
    }
    await refreshCaptchaAfterUse()
  }

  async function onMfaSubmit() {
    if (!mfaCode) {
      message.warning(t('login.smsCodePlaceholder'))
      return
    }
    setLoading(true)
    try {
      finishLogin(await authApi.smsChallengeLogin({ challengeId: mfa.challengeId, code: mfaCode }))
    } catch (err) {
      message.error(translateError(err))
    } finally {
      setLoading(false)
    }
  }

  async function onTotpSubmit() {
    if (!totpCode) {
      message.warning(t('login.totpPlaceholder'))
      return
    }
    setLoading(true)
    try {
      finishLogin(await authApi.totpChallengeLogin({ challengeId: totp.challengeId, code: totpCode }))
    } catch (err) {
      message.error(translateError(err))
    } finally {
      setLoading(false)
    }
  }

  async function onMfaResend() {
    if (countdown > 0) return
    try {
      const r = await authApi.smsChallengeResend({ challengeId: mfa.challengeId })
      message.success(t('login.smsSent'))
      startCountdown(r.resendSeconds)
    } catch (err) {
      message.error(translateError(err))
    }
  }

  function backToAccount() {
    setMode('account')
    setMfa({ challengeId: '', phoneMask: '' })
    setMfaCode('')
    setTotp({ challengeId: '' })
    setTotpCode('')
  }

  return (
    <div className="login-form" data-testid="login-card">
      {showBrand ? (
        <>
          <div className="lf-brand">
            {/* logo 由后端 sys_config 下发(可空);空时回退内置矢量 logo。 */}
            {site.logo ? <img src={site.logo} alt={site.title} className="lf-logo" /> : <TenonLogo size={34} />}
            <span className="lf-word">{site.title}</span>
          </div>
        </>
      ) : null}

      {/* 短信/TOTP 二次验证态:标题换挑战提示;其余态显常规标题(随 showBrand) */}
      {mode === 'mfa' ? (
        <>
          <h2 className="lf-title">{t('login.mfaTitle', { phone: mfa.phoneMask })}</h2>
          <p className="lf-hint-line">{t('login.mfaSub')}</p>
        </>
      ) : mode === 'totp' ? (
        <>
          <h2 className="lf-title">{t('login.totpTitle')}</h2>
          <p className="lf-hint-line">{t('login.totpSub')}</p>
        </>
      ) : showBrand ? (
        <h2 className="lf-title">{t('login.title')}</h2>
      ) : null}

      {mode === 'mfa' ? (
        <>
          {/* 短信二次验证:密码已过,凭挑战 + 短信码完成登录。单字段小表单,受控 state 即可 */}
          <Input
            size="large"
            maxLength={6}
            value={mfaCode}
            onChange={(e) => setMfaCode(e.target.value)}
            placeholder={t('login.smsCodePlaceholder')}
            onPressEnter={() => void onMfaSubmit()}
          />
          <div className="row lf-between">
            <a className="lf-link" onClick={backToAccount}>
              {t('login.backToPassword')}
            </a>
            <a className={`lf-link${countdown > 0 ? ' lf-link-disabled' : ''}`} onClick={() => void onMfaResend()}>
              {countdown > 0 ? t('login.resendAfter', { s: countdown }) : t('login.sendCode')}
            </a>
          </div>
          <Button type="primary" size="large" block loading={loading} onClick={() => void onMfaSubmit()}>
            {t('login.submit')}
          </Button>
        </>
      ) : mode === 'totp' ? (
        <>
          <Input
            size="large"
            maxLength={6}
            value={totpCode}
            onChange={(e) => setTotpCode(e.target.value)}
            placeholder={t('login.totpPlaceholder')}
            onPressEnter={() => void onTotpSubmit()}
          />
          <div className="row lf-between">
            <a className="lf-link" onClick={backToAccount}>
              {t('login.backToPassword')}
            </a>
            <a className="lf-link" onClick={goRecovery}>
              {t('login.useRecovery')}
            </a>
          </div>
          <Button type="primary" size="large" block loading={loading} onClick={() => void onTotpSubmit()}>
            {t('login.submit')}
          </Button>
        </>
      ) : (
        <>
          <Form<FormValues>
            form={form}
            layout="vertical"
            requiredMark={false}
            // ponytail: 开发环境预填超管账号密码,免得每次手敲;生产构建下 import.meta.env.DEV 为 false,留空。
            initialValues={
              import.meta.env.DEV
                ? { account: 'superAdmin', password: 'Aa123456', remember: true }
                : { account: '', password: '', remember: true }
            }
            onFinish={(v) => void onFinish(v)}
          >
            {mode === 'account' ? (
              <>
                <Form.Item name="account" label={t('login.account')} rules={[{ required: true, message: t('login.required') }]}>
                  <Input size="large" autoComplete="username" placeholder={t('login.accountPlaceholder')} />
                </Form.Item>

                <Form.Item name="password" label={t('login.password')} rules={[{ required: true, message: t('login.required') }]}>
                  <Input.Password size="large" autoComplete="current-password" placeholder={t('login.passwordPlaceholder')} />
                </Form.Item>
              </>
            ) : (
              <Form.Item name="phone" label={t('login.phone')} rules={[{ required: true, message: t('login.phonePlaceholder') }]}>
                <Input size="large" autoComplete="tel" maxLength={20} placeholder={t('login.phonePlaceholder')} />
              </Form.Item>
            )}

            {site.captchaEnabled ? (
              <Form.Item label={t('login.captcha')} required>
                <div className="lf-captcha">
                  {/* 必填规则仅账号态:账号模式验证码护登录本身;短信模式护的是发码,由 onSendSmsCode 前置校验,
                      发码后 refreshCaptchaAfterUse 会清空字段,提交时不能再拦。 */}
                  <Form.Item
                    name="captchaCode"
                    noStyle
                    rules={mode === 'account' ? [{ required: true, message: t('login.captchaRequired') }] : []}
                  >
                    <Input
                      size="large"
                      placeholder={captcha?.type === 'math' ? t('login.captchaMathPlaceholder') : t('login.captchaPlaceholder')}
                    />
                  </Form.Item>
                  {/* 后端下发的是 SVG 源码。这是本模板唯一一处 dangerouslySetInnerHTML,来源是自家后端的
                      验证码端点(与 Vue 侧 `v-html` 同一处理);**别把这个先例扩大到任何用户输入上**。
                      内置三个 provider 的 SVG 全服务端自生成、零请求输入入串,可信;但 ICaptchaProvider
                      是可替换扩展点,契约见后端 `ICaptchaProvider` 注释(Svg 不得嵌入不可信输入)。 */}
                  {/* 键盘可达:验证码看不清要能换一张,不能只有鼠标能点。role+tabIndex+Enter/Space+aria-label。 */}
                  <div
                    role="button"
                    tabIndex={0}
                    aria-label={t('login.captcha')}
                    onClick={() => void loadCaptcha()}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault()
                        void loadCaptcha()
                      }
                    }}
                    title={t('login.captcha')}
                    className="lf-captcha-img"
                    data-testid="captcha-img"
                    dangerouslySetInnerHTML={{ __html: captcha?.svg ?? '' }}
                  />
                </div>
              </Form.Item>
            ) : null}

            {mode === 'sms' ? (
              <Form.Item label={t('login.smsCode')} required>
                <div className="lf-captcha">
                  <Form.Item name="smsCode" noStyle rules={[{ required: true, message: t('login.smsCodePlaceholder') }]}>
                    <Input size="large" maxLength={6} placeholder={t('login.smsCodePlaceholder')} />
                  </Form.Item>
                  <button type="button" className="lf-send-btn" disabled={countdown > 0} onClick={() => void onSendSmsCode()}>
                    {countdown > 0 ? t('login.resendAfter', { s: countdown }) : t('login.sendCode')}
                  </button>
                </div>
              </Form.Item>
            ) : null}

            {/* 左:记住我(仅账号态);右:账号↔短信切换(后端 smsLoginEnabled 驱动,关则整链不显) */}
            <div className="row lf-between">
              {mode === 'account' ? (
                <Form.Item name="remember" valuePropName="checked" noStyle>
                  <Checkbox>{t('login.remember')}</Checkbox>
                </Form.Item>
              ) : (
                <span />
              )}
              {site.smsLoginEnabled ? (
                <a className="lf-link" onClick={() => setMode(mode === 'account' ? 'sms' : 'account')}>
                  {mode === 'account' ? t('login.smsLogin') : t('login.accountLogin')}
                </a>
              ) : null}
            </div>

            <Button type="primary" size="large" block htmlType="submit" loading={loading}>
              {t('login.submit')}
            </Button>
          </Form>

          {/* 第三方登录:后端 providers 驱动;无启用项则整段不显。 */}
          {ssoProviders.length > 0 ? (
            <>
              <div className="lf-divider">
                <span>{t('login.otherMethods')}</span>
              </div>
              <div className="lf-sso">
                {ssoProviders.map((p) => (
                  <button key={p.code} className="lf-sso-btn" type="button" onClick={() => onSso(p.code)}>
                    {p.icon ? <AppIcon icon={p.icon} size={18} className="lf-sso-icon" /> : null}
                    {p.displayName}
                  </button>
                ))}
              </div>
            </>
          ) : null}
        </>
      )}

      {showFooter ? (
        <footer className="lf-foot">
          {/* 以 copyrightUrl 为门(对齐 Vue LoginForm.vue 与兄弟皮肤 SplitPanel):配了链接就带链接,文案回退 title。 */}
          <span>
            © {year}{' '}
            {site.copyrightUrl ? (
              <a href={site.copyrightUrl} target="_blank" rel="noreferrer">
                {site.copyright || site.title}
              </a>
            ) : (
              site.copyright || site.title
            )}
          </span>
          {appVersion ? <span className="lf-ver">v{appVersion}</span> : null}
        </footer>
      ) : null}

      {/* 强制 MFA 未绑定(40020):遮罩 Modal,账密表单仍在底下;默认登录页不常驻绑定链接 */}
      <Modal
        open={bindRequiredOpen}
        title={t('login.totpBindTitle')}
        okText={t('login.setupAuthenticator')}
        cancelText={t('common.cancel')}
        onOk={goBindAuthenticator}
        onCancel={() => setBindRequiredOpen(false)}
        destroyOnHidden
      >
        <p style={{ margin: 0 }}>{t('login.totpBindSub')}</p>
      </Modal>
    </div>
  )
}

// web/src/views/login/LoginForm.vue
<script setup lang="ts">
import { reactive, ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRouter } from 'vue-router'
import { NForm, NFormItem, NInput, NCheckbox, NModal, useMessage } from 'naive-ui'
import { Icon } from '@iconify/vue'
import { useI18n } from 'vue-i18n'
import { authApi, externalAuthApi, ApiError } from '@/api'
import type { LoginOutput } from '@/types/api'
import { useUserStore } from '@/stores/user'
import { useAuthStore } from '@/stores/auth'
import { useAppStore } from '@/stores/app'
import { useSite } from '@/composables/useSite'
import { resetRouter } from '@/router'
import { btnGrad, glowSh } from '@/theme/mix'
import { translateError } from '@/utils/error'
import TenonLogo from '@/components/TenonLogo.vue'

// 皮肤外壳自带品牌栏时(如双栏),不再在卡内重复 logo/标题/页脚(showFooter=false 由外壳自绘版权)。
withDefaults(defineProps<{ showLogo?: boolean; showTitle?: boolean; showFooter?: boolean }>(), {
  showLogo: true,
  showTitle: true,
  showFooter: true,
})

const router = useRouter()
const message = useMessage()
const { t } = useI18n()
const user = useUserStore()
const auth = useAuthStore()
const app = useAppStore()
const { site, appVersion, loadSite } = useSite()
const year = new Date().getFullYear()

// ponytail: 开发环境预填超管账号密码,免得每次手敲;生产(build)下 import.meta.env.DEV 为 false,留空
const model = reactive(
  import.meta.env.DEV
    ? { account: 'superAdmin', password: 'Aa123456', remember: true }
    : { account: '', password: '', remember: true },
)
const loading = ref(false)

// 登录形态:账号密码 / 短信免密 / 短信二次验证(40009) / TOTP 二次验证(40018)
// 强制 MFA 未绑定(40020)用 Modal 引导,不切 mode,登录页默认也不常驻绑定链接
const mode = ref<'account' | 'sms' | 'mfa' | 'totp'>('account')

// 短信免密登录
const smsModel = reactive({ phone: '', code: '' })
// 二次验证挑战(40009 信令 args 下发)
const mfa = reactive({ challengeId: '', phoneMask: '', code: '' })
// TOTP 挑战(40018)
const totp = reactive({ challengeId: '', code: '' })
// 强制 MFA 但未绑定(40020):弹窗 + 带到 /mfa/bind 的账号
const bindRequiredShow = ref(false)
const bindAccount = ref('')

// 发码/重发共用倒计时(同一时刻只有一个发码入口可见)
const countdown = ref(0)
let timer: number | undefined
function startCountdown(s: number) {
  countdown.value = s
  window.clearInterval(timer)
  timer = window.setInterval(() => {
    countdown.value -= 1
    if (countdown.value <= 0) window.clearInterval(timer)
  }, 1000)
}
onBeforeUnmount(() => window.clearInterval(timer))

// 验证码:是否启用由匿名站点信息(sys.security.captcha.enabled)运行时驱动;启用才拉取并展示。
// 账号模式护登录,短信模式护发码(发码端点防脚本滥用)。
const captchaEnabled = ref(false)
const captchaId = ref('')
const captchaSvg = ref('')
const captchaCode = ref('')
const captchaType = ref('char')

// math 类型需算出结果再输入,提示语不同;其余类型统一“请输入验证码”。
const captchaHint = computed(() =>
  captchaType.value === 'math' ? t('login.captchaMathPlaceholder') : t('login.captchaPlaceholder'),
)

async function loadCaptcha() {
  try {
    const c = await authApi.captcha()
    captchaId.value = c.captchaId
    captchaSvg.value = c.svg
    captchaType.value = c.type || 'char'
  } catch {
    // 拉取失败不阻塞登录页渲染;点击图形可重试
  }
}

/** 验证码一次性消费:任何用掉票据的请求失败后必刷新,避免复用作废票据 */
async function refreshCaptchaAfterUse() {
  if (captchaEnabled.value) {
    captchaCode.value = ''
    await loadCaptcha()
  }
}

onMounted(async () => {
  // 站点信息全站共用(useSite 去重);验证码开关据此运行时驱动,启用才拉图。
  await loadSite()
  if (site.captchaEnabled) {
    captchaEnabled.value = true
    await loadCaptcha()
  }
  void loadSsoProviders()

  // SSO 回调带回的 TOTP 挑战:直接进入 totp 完成态
  const q = router.currentRoute.value.query
  const ch = typeof q.totpChallenge === 'string' ? q.totpChallenge : ''
  if (ch) {
    totp.challengeId = ch
    totp.code = ''
    mode.value = 'totp'
  }
})

// 英雄按钮:accent 派生渐变 + 发光(仅登录页/英雄区)。
const heroStyle = computed(() => ({ background: btnGrad(app.accent), boxShadow: glowSh(app.accent) }))

// 第三方登录:后端 GET providers 驱动(仅点亮已启用的)。点击顶层导航到 authorize,后端 302 跳 IdP。
const ssoProviders = ref<{ code: string; displayName: string; icon?: string | null }[]>([])
async function loadSsoProviders() {
  try {
    ssoProviders.value = await externalAuthApi.providers()
  } catch {
    // 未配置外部登录或拉取失败:整段 SSO 区不显
  }
}
function onSso(code: string) {
  window.location.href = externalAuthApi.authorizeUrl(code)
}

function finishLogin(res: LoginOutput) {
  // 每次登录都清动态路由/授权态,否则上次会话的 routesReady=true 会跳过 enterInitial,
  // 菜单壳在、业务路由未重建 → 进系统后处处 404(绑定 MFA 后回登录再登最易踩中)。
  resetRouter()
  auth.reset()
  user.setSession(res)
  message.success(t('login.success'))
  router.replace('/')
}

async function onSubmit() {
  if (mode.value === 'mfa') return onMfaSubmit()
  if (mode.value === 'totp') return onTotpSubmit()
  if (mode.value === 'sms') return onSmsSubmit()

  if (!model.account || !model.password) {
    message.warning(t('login.required'))
    return
  }
  if (captchaEnabled.value && !captchaCode.value) {
    message.warning(t('login.captchaRequired'))
    return
  }
  loading.value = true
  try {
    const res = await authApi.login({
      account: model.account,
      password: model.password,
      ...(captchaEnabled.value ? { captchaId: captchaId.value, captchaCode: captchaCode.value } : {}),
    })
    finishLogin(res)
  } catch (e) {
    // 40018 = 密码已过、需 TOTP 二次验证
    if (e instanceof ApiError && e.code === 40018 && e.args) {
      totp.challengeId = String(e.args.challengeId ?? '')
      totp.code = ''
      mode.value = 'totp'
    } else if (e instanceof ApiError && e.code === 40020) {
      // 40020 = 强制 MFA 未绑定 → Modal 引导自助设置(登录页默认不常驻链接)
      bindAccount.value = model.account.trim()
      bindRequiredShow.value = true
    } else if (e instanceof ApiError && e.code === 40009 && e.args) {
      // 40009 = 密码已过、需短信二次验证
      mfa.challengeId = String(e.args.challengeId ?? '')
      mfa.phoneMask = String(e.args.phoneMask ?? '')
      mfa.code = ''
      mode.value = 'mfa'
      startCountdown(Number(e.args.resendSeconds ?? 60))
    } else {
      message.error(translateError(e))
    }
    await refreshCaptchaAfterUse()
  } finally {
    loading.value = false
  }
}

function closeBindRequired() {
  bindRequiredShow.value = false
}

function goBindAuthenticator() {
  const account = bindAccount.value || model.account.trim()
  bindRequiredShow.value = false
  void router.push({ path: '/mfa/bind', query: account ? { account } : {} })
}

function goRecovery() {
  const account = model.account.trim() || bindAccount.value
  void router.push({ path: '/mfa/bind', query: { ...(account ? { account } : {}), mode: 'recovery' } })
}

async function onMfaSubmit() {
  if (!mfa.code) {
    message.warning(t('login.smsCodePlaceholder'))
    return
  }
  loading.value = true
  try {
    finishLogin(await authApi.smsChallengeLogin({ challengeId: mfa.challengeId, code: mfa.code }))
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
}

async function onTotpSubmit() {
  if (!totp.code) {
    message.warning(t('login.totpPlaceholder'))
    return
  }
  loading.value = true
  try {
    finishLogin(await authApi.totpChallengeLogin({ challengeId: totp.challengeId, code: totp.code }))
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
}

async function onMfaResend() {
  if (countdown.value > 0) return
  try {
    const r = await authApi.smsChallengeResend({ challengeId: mfa.challengeId })
    message.success(t('login.smsSent'))
    startCountdown(r.resendSeconds)
  } catch (e) {
    message.error(translateError(e))
  }
}

function backToAccount() {
  mode.value = 'account'
  mfa.challengeId = ''
  mfa.code = ''
  totp.challengeId = ''
  totp.code = ''
}

async function onSendSmsCode() {
  if (countdown.value > 0) return
  if (!smsModel.phone) {
    message.warning(t('login.phonePlaceholder'))
    return
  }
  if (captchaEnabled.value && !captchaCode.value) {
    message.warning(t('login.captchaRequired'))
    return
  }
  try {
    const r = await authApi.smsLoginSend({
      phone: smsModel.phone,
      ...(captchaEnabled.value ? { captchaId: captchaId.value, captchaCode: captchaCode.value } : {}),
    })
    message.success(t('login.smsSent'))
    startCountdown(r.resendSeconds)
  } catch (e) {
    message.error(translateError(e))
  }
  await refreshCaptchaAfterUse()
}

async function onSmsSubmit() {
  if (!smsModel.phone || !smsModel.code) {
    message.warning(t('login.smsRequired'))
    return
  }
  loading.value = true
  try {
    finishLogin(await authApi.smsLogin({ phone: smsModel.phone, code: smsModel.code }))
  } catch (e) {
    message.error(translateError(e))
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="login-form">
    <div v-if="showLogo" class="lf-brand">
      <!-- 站点 logo:后台配了图片地址用 <img>,否则回退内置矢量 logo(留空即回退) -->
      <img v-if="site.logo" :src="site.logo" :alt="site.title" class="lf-logo" />
      <TenonLogo v-else :size="34" />
      <span class="lf-word">{{ site.title }}</span>
    </div>

    <!-- 短信二次验证:密码已过,凭挑战 + 短信码完成登录 -->
    <template v-if="mode === 'mfa'">
      <h2 v-if="showTitle" class="lf-title">{{ t('login.mfaTitle', { phone: mfa.phoneMask }) }}</h2>
      <p class="lf-hint-line">{{ t('login.mfaSub') }}</p>
      <n-form @keyup.enter="onSubmit">
        <n-form-item :label="t('login.smsCode')" path="code">
          <n-input v-model:value="mfa.code" :placeholder="t('login.smsCodePlaceholder')" size="large" :maxlength="6">
            <template #prefix><Icon icon="ph:chat-circle-text" /></template>
          </n-input>
        </n-form-item>
        <div class="row lf-between">
          <a class="lf-link" @click="backToAccount">{{ t('login.backToPassword') }}</a>
          <a class="lf-link" :class="{ 'lf-link-disabled': countdown > 0 }" @click="onMfaResend">
            {{ countdown > 0 ? t('login.resendAfter', { s: countdown }) : t('login.sendCode') }}
          </a>
        </div>
        <button class="hero-btn" type="button" :style="heroStyle" :disabled="loading" @click.prevent="onSubmit">
          {{ loading ? t('common.loading') : t('login.submit') }}
        </button>
      </n-form>
    </template>

    <!-- TOTP 二次验证:密码已过,凭 Authenticator 动态口令完成登录 -->
    <template v-else-if="mode === 'totp'">
      <h2 v-if="showTitle" class="lf-title">{{ t('login.totpTitle') }}</h2>
      <p class="lf-hint-line">{{ t('login.totpSub') }}</p>
      <n-form @keyup.enter="onSubmit">
        <n-form-item :label="t('login.totpCode')" path="code">
          <n-input v-model:value="totp.code" :placeholder="t('login.totpPlaceholder')" size="large" :maxlength="6">
            <template #prefix><Icon icon="ph:shield-check" /></template>
          </n-input>
        </n-form-item>
        <div class="row lf-between">
          <a class="lf-link" @click="backToAccount">{{ t('login.backToPassword') }}</a>
          <a class="lf-link" @click="goRecovery">{{ t('login.useRecovery') }}</a>
        </div>
        <button class="hero-btn" type="button" :style="heroStyle" :disabled="loading" @click.prevent="onSubmit">
          {{ loading ? t('common.loading') : t('login.submit') }}
        </button>
      </n-form>
    </template>

    <template v-else>
      <h2 v-if="showTitle" class="lf-title">{{ t('login.title') }}</h2>
      <n-form :model="mode === 'account' ? model : smsModel" @keyup.enter="onSubmit">
        <template v-if="mode === 'account'">
          <n-form-item :label="t('login.account')" path="account">
            <n-input v-model:value="model.account" :placeholder="t('login.accountPlaceholder')" size="large">
              <template #prefix><Icon icon="ph:user" /></template>
            </n-input>
          </n-form-item>
          <n-form-item :label="t('login.password')" path="password">
            <n-input
              v-model:value="model.password"
              type="password"
              show-password-on="click"
              :placeholder="t('login.passwordPlaceholder')"
              size="large"
            >
              <template #prefix><Icon icon="ph:lock" /></template>
            </n-input>
          </n-form-item>
        </template>
        <template v-else>
          <n-form-item :label="t('login.phone')" path="phone">
            <n-input v-model:value="smsModel.phone" :placeholder="t('login.phonePlaceholder')" size="large" :maxlength="20">
              <template #prefix><Icon icon="ph:device-mobile" /></template>
            </n-input>
          </n-form-item>
        </template>
        <n-form-item v-if="captchaEnabled" :label="t('login.captcha')" path="captcha">
          <div class="lf-captcha">
            <n-input
              v-model:value="captchaCode"
              :placeholder="captchaHint"
              size="large"
              @keyup.enter="onSubmit"
            >
              <template #prefix><Icon icon="ph:shield-check" /></template>
            </n-input>
            <!-- SVG 来自本站后端;点击重取一张(一次性票据) -->
            <button type="button" class="lf-captcha-img" :title="t('login.captchaPlaceholder')" @click="loadCaptcha" v-html="captchaSvg" />
          </div>
        </n-form-item>
        <n-form-item v-if="mode === 'sms'" :label="t('login.smsCode')" path="code">
          <div class="lf-captcha">
            <n-input v-model:value="smsModel.code" :placeholder="t('login.smsCodePlaceholder')" size="large" :maxlength="6">
              <template #prefix><Icon icon="ph:chat-circle-text" /></template>
            </n-input>
            <button type="button" class="lf-send-btn" :disabled="countdown > 0" @click="onSendSmsCode">
              {{ countdown > 0 ? t('login.resendAfter', { s: countdown }) : t('login.sendCode') }}
            </button>
          </div>
        </n-form-item>
        <div class="row lf-between">
          <n-checkbox v-if="mode === 'account'" v-model:checked="model.remember">{{ t('login.remember') }}</n-checkbox>
          <span v-else />
          <a v-if="site.smsLoginEnabled" class="lf-link" @click="mode = mode === 'account' ? 'sms' : 'account'">
            {{ mode === 'account' ? t('login.smsLogin') : t('login.accountLogin') }}
          </a>
        </div>
        <button class="hero-btn" type="button" :style="heroStyle" :disabled="loading" @click.prevent="onSubmit">
          {{ loading ? t('common.loading') : t('login.submit') }}
        </button>
      </n-form>

      <!-- 第三方登录:后端 providers 驱动;无启用项则整段不显。点击顶层跳转到 IdP(OAuth2 授权码往返)。 -->
      <template v-if="ssoProviders.length">
        <div class="lf-divider"><span>{{ t('login.otherMethods') }}</span></div>
        <div class="lf-sso">
          <button v-for="p in ssoProviders" :key="p.code" class="lf-sso-btn" type="button" @click="onSso(p.code)">
            <Icon v-if="p.icon" :icon="p.icon" class="lf-sso-icon" />
            {{ p.displayName }}
          </button>
        </div>
      </template>
    </template>

    <!-- 页脚:版权(可选链接)+ 构建期版本号。皮肤自绘页脚时(如双栏)传 :show-footer="false" 关掉。 -->
    <footer v-if="showFooter" class="lf-foot">
      <span>
        © {{ year }}
        <a v-if="site.copyrightUrl" :href="site.copyrightUrl" target="_blank" rel="noopener">{{ site.copyright || site.title }}</a>
        <template v-else>{{ site.copyright || site.title }}</template>
      </span>
      <span v-if="appVersion" class="lf-ver">v{{ appVersion }}</span>
    </footer>

    <!-- 强制 MFA 未绑定(40020):遮罩 Modal,账密表单仍在底下;默认登录页不常驻绑定链接 -->
    <n-modal
      v-model:show="bindRequiredShow"
      preset="dialog"
      type="warning"
      :title="t('login.totpBindTitle')"
      :content="t('login.totpBindSub')"
      :positive-text="t('login.setupAuthenticator')"
      :negative-text="t('common.cancel')"
      @positive-click="goBindAuthenticator"
      @negative-click="closeBindRequired"
    />
  </div>
</template>

<style scoped>
/* 文字色默认跟随应用令牌;皮肤可通过 --lf-title / --lf-hint 覆盖(如极光深色皮肤强制浅色)。 */
.login-form {
  width: 100%;
}
.lf-brand {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 18px;
}
/* 后台配置的品牌 logo:限高与内置矢量 logo 齐平,宽度自适应不变形 */
.lf-logo {
  height: 34px;
  width: auto;
  object-fit: contain;
  display: block;
}
.lf-word {
  font-size: 18px;
  font-weight: 700;
  letter-spacing: 0.2px;
  color: var(--lf-title, var(--color-text-primary));
}
.lf-title {
  font-size: var(--font-size-lg);
  font-weight: 600;
  margin: 0 0 22px;
  color: var(--lf-title, var(--color-text-primary));
}
/* 二次验证副标题:标题下的弱化说明行 */
.lf-hint-line {
  margin: -14px 0 18px;
  font-size: 13px;
  color: var(--lf-hint, var(--color-text-tertiary));
}
.row {
  margin: 4px 0 20px;
}
.lf-between {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
/* 模式切换/重发:文字链接,复用主题色 */
.lf-link {
  font-size: 13px;
  color: var(--color-primary);
  cursor: pointer;
  user-select: none;
}
.lf-link:hover {
  opacity: 0.85;
}
.lf-link-disabled {
  color: var(--lf-hint, var(--color-text-tertiary));
  cursor: default;
  pointer-events: none;
}
/* 验证码:输入框 + 可点击刷新的 SVG 图形(等高对齐) */
.lf-captcha {
  display: flex;
  gap: 10px;
  width: 100%;
  align-items: stretch;
}
.lf-captcha-img {
  flex: 0 0 auto;
  height: 40px;
  min-width: 96px;
  padding: 0;
  border: 1px solid var(--lf-border, var(--color-border));
  border-radius: var(--radius-md);
  background: #fff;
  cursor: pointer;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}
.lf-captcha-img :deep(svg) {
  height: 100%;
  width: auto;
}
/* 发码按钮:与验证码图形同尺寸位,文字化 */
.lf-send-btn {
  flex: 0 0 auto;
  height: 40px;
  min-width: 96px;
  padding: 0 12px;
  border: 1px solid var(--lf-border, var(--color-border));
  border-radius: var(--radius-md);
  background: var(--color-fill);
  font-size: 13px;
  color: var(--lf-title, var(--color-text-secondary));
  cursor: pointer;
  transition:
    border-color var(--transition-fast),
    color var(--transition-fast);
}
.lf-send-btn:hover:not(:disabled) {
  border-color: var(--color-primary);
  color: var(--color-primary);
}
.lf-send-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.hero-btn {
  width: 100%;
  height: 48px;
  border: none;
  border-radius: var(--radius-md);
  color: #fff;
  font-size: var(--font-size-md);
  font-weight: 600;
  cursor: pointer;
  transition:
    transform var(--transition-fast),
    box-shadow var(--transition-fast);
}
.hero-btn:hover {
  transform: translateY(-2px);
}
.hero-btn:active {
  transform: translateY(0);
}
.hero-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}
/* 第三方登录:分隔线 + 等宽按钮(设计稿 §Variant A) */
.lf-divider {
  display: flex;
  align-items: center;
  gap: 14px;
  margin: 24px 0 16px;
}
.lf-divider::before,
.lf-divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: var(--lf-border, var(--color-border));
}
.lf-divider span {
  font-size: 12px;
  color: var(--lf-hint, var(--color-text-tertiary));
}
.lf-sso {
  display: flex;
  gap: 12px;
}
.lf-sso-btn {
  flex: 1;
  height: 44px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  border: 1.5px solid var(--lf-border, var(--color-border));
  border-radius: 11px;
  background: var(--color-fill);
  font-size: 13px;
  color: var(--lf-title, var(--color-text-secondary));
  cursor: pointer;
  transition:
    border-color var(--transition-fast),
    color var(--transition-fast),
    background var(--transition-fast);
}
.lf-sso-btn:hover {
  border-color: var(--color-primary);
  color: var(--color-primary);
  background: var(--color-primary-light);
}
.lf-sso-btn:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 2px;
}
/* 页脚:版权 + 版本号,弱化色,与 SSO 区留白 */
.lf-foot {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  margin-top: 24px;
  font-size: 12px;
  color: var(--lf-hint, var(--color-text-tertiary));
}
.lf-foot a {
  color: inherit;
  text-decoration: none;
}
.lf-foot a:hover {
  color: var(--color-primary);
}
.lf-ver {
  opacity: 0.75;
}
</style>
