// web/src/views/workflow/components/WfFormMount.vue
<script setup lang="ts">
/**
 * 业务表单入口:优先渲染定义级 formSchema,否则按 formComponent(views 相对路径)动态加载消费者组件。
 * 路径约定与菜单 component 一致,如 `biz/leave/form` → `/src/views/biz/leave/form.vue`。
 * 组件不存在时显示占位提示,不抛错打断审批主流程;非法双配置保留消费者挂载点。
 */
import { computed, defineAsyncComponent, type Component } from 'vue'
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import type { WfInstanceStatus } from '@/types/workflow'
import type { WfFormFieldPerm, WfFormSchema } from '@/workflow/schema'
import { parseWfFormValuesResult, serializeWfFormValues, type WfFormValues } from '@/workflow/formRuntime'
import WfBuiltinForm from './WfBuiltinForm.vue'

const props = defineProps<{
  formComponent?: string | null
  formSchema?: WfFormSchema | null
  mode: 'start' | 'approve' | 'view'
  permissions?: WfFormFieldPerm[] | null
  definitionId?: number
  instanceId?: number
  businessKey?: string | null
  variablesJson?: string | null
  status?: WfInstanceStatus
}>()
const emit = defineEmits<{ 'variables-change': [value: string | null] }>()

const { t } = useI18n()
const builtinRef = ref<{ validate: () => boolean } | null>(null)
const initialParse = parseWfFormValuesResult(props.variablesJson)
const builtinValues = ref<WfFormValues>(initialParse.values)
const parseError = ref(initialParse.error)

watch(() => props.variablesJson, (json) => {
  const result = parseWfFormValuesResult(json)
  builtinValues.value = result.values
  parseError.value = result.error
})

const viewModules = import.meta.glob('/src/views/**/*.vue') as Record<
  string,
  () => Promise<{ default: Component }>
>

function normalizeViewPath(raw: string): string {
  let p = raw.trim().replace(/\\/g, '/')
  if (p.startsWith('views/')) p = p.slice('views/'.length)
  if (p.startsWith('/')) p = p.slice(1)
  if (p.endsWith('.vue')) p = p.slice(0, -4)
  return p
}

const resolved = computed(() => {
  const raw = props.formComponent?.trim()
  if (!raw) return null
  const key = `/src/views/${normalizeViewPath(raw)}.vue`
  const loader = viewModules[key]
  if (!loader) return { missing: true as const, key }
  return {
    missing: false as const,
    key,
    component: defineAsyncComponent(loader),
  }
})

const builtinSchema = computed(() => {
  if (props.formComponent?.trim()) return null
  return props.formSchema?.fields?.length ? props.formSchema : null
})

function onBuiltinUpdate(value: WfFormValues) {
  builtinValues.value = value
  emit('variables-change', serializeWfFormValues(value))
}

function validate(): boolean {
  if (parseError.value) return false
  return builtinRef.value?.validate() ?? true
}

defineExpose({ validate })
</script>

<template>
  <div v-if="builtinSchema && parseError" class="wf-form-error">
    {{ t('workflow.form.runtime.invalidVariables') }}
  </div>
  <div v-else-if="builtinSchema" class="wf-form-mount">
    <WfBuiltinForm
      ref="builtinRef"
      :schema="builtinSchema"
      :model-value="builtinValues"
      :mode="mode"
      :permissions="permissions"
      @update:model-value="onBuiltinUpdate"
    />
  </div>
  <div v-else-if="formComponent" class="wf-form-mount">
    <div v-if="resolved?.missing" class="wf-form-missing">
      {{ t('workflow.form.missing', { path: formComponent }) }}
    </div>
    <component
      v-else-if="resolved && !resolved.missing"
      :is="resolved.component"
      :mode="mode"
      :definition-id="definitionId"
      :instance-id="instanceId"
      :business-key="businessKey"
      :variables-json="variablesJson"
      :status="status"
    />
  </div>
</template>

<style scoped>
.wf-form-mount {
  margin-block: 12px;
}
.wf-form-missing {
  padding: 12px 16px;
  border: 1px dashed var(--color-border);
  border-radius: var(--radius-md, 8px);
  color: var(--color-text-secondary);
  font-size: var(--font-size-sm, 13px);
}
.wf-form-error {
  padding: 12px 16px;
  border: 1px solid var(--color-danger);
  border-radius: var(--radius-md, 8px);
  color: var(--color-danger);
  font-size: var(--font-size-sm, 13px);
}
</style>

// web-react/src/views/workflow/components/WfFormMount.tsx
// 业务表单入口:优先渲染定义级 formSchema,否则按 formComponent(views 相对路径)动态加载消费者组件。
// 路径约定与菜单 component 一致,如 `biz/leave/form` → `/src/views/biz/leave/form.tsx`(同 buildRoutes 的 glob)。
// 组件不存在时给告警占位,不抛错打断审批主流程;非法双配置保留消费者挂载点。对应 Vue 侧 WfFormMount.vue。
import {
  Suspense,
  forwardRef,
  lazy,
  useImperativeHandle,
  useMemo,
  useRef,
  type ComponentType,
  type LazyExoticComponent,
} from 'react'
import { Alert } from 'antd'
import { useTranslation } from 'react-i18next'
import type { WfInstanceStatus } from '@/types/workflow'
import { parseWfFormValuesResult, serializeWfFormValues } from '@/workflow/formRuntime'
import type { WfFormFieldPerm, WfFormSchema } from '@/workflow/schema'
import { WfBuiltinForm, type WfBuiltinFormHandle, type WfFormMode } from './WfBuiltinForm'

/** 消费者业务表单组件收到的 props;新增项必须同步 Vue 侧,否则两套模板的挂载点契约会漂移。 */
export interface WfFormComponentProps {
  mode: WfFormMode
  definitionId?: number
  instanceId?: number
  businessKey?: string | null
  variablesJson?: string | null
  status?: WfInstanceStatus
}

type FormModule = { default: ComponentType<WfFormComponentProps> }
export type WfFormGlob = Record<string, () => Promise<FormModule>>

const viewModules = import.meta.glob<FormModule>([
  '/src/views/**/*.tsx',
  '!/src/views/**/*.spec.tsx',
]) as WfFormGlob

const lazyComponents = new WeakMap<() => Promise<FormModule>, LazyExoticComponent<ComponentType<WfFormComponentProps>>>()

/** loader → lazy 组件缓存:同一个挂载点重渲染不能换组件身份,否则消费者表单每次都重挂、丢内部状态。 */
function lazyFor(loader: () => Promise<FormModule>): LazyExoticComponent<ComponentType<WfFormComponentProps>> {
  const cached = lazyComponents.get(loader)
  if (cached) return cached
  const created = lazy(loader)
  lazyComponents.set(loader, created)
  return created
}

/** `views/biz/leave/form.tsx` / `/biz/leave/form` 等写法统一成 glob 键的相对部分。 */
export function normalizeViewPath(raw: string): string {
  let path = raw.trim().replace(/\\/g, '/')
  if (path.startsWith('views/')) path = path.slice('views/'.length)
  if (path.startsWith('/')) path = path.slice(1)
  if (path.endsWith('.tsx')) path = path.slice(0, -4)
  return path
}

export interface WfFormMountHandle {
  /** 提交前校验;变量 JSON 本身坏掉时直接拒绝,不给「看着没填错却提交了脏数据」的机会。 */
  validate: () => boolean
}

export interface WfFormMountProps {
  formComponent?: string | null
  formSchema?: WfFormSchema | null
  mode: WfFormMode
  permissions?: WfFormFieldPerm[] | null
  definitionId?: number
  instanceId?: number
  businessKey?: string | null
  variablesJson?: string | null
  status?: WfInstanceStatus
  onVariablesChange?: (json: string | null) => void
  /** 测试注入用;默认取真实 `import.meta.glob`(与 buildRoutes 同一套约定)。 */
  viewGlob?: WfFormGlob
}

export const WfFormMount = forwardRef<WfFormMountHandle, WfFormMountProps>(function WfFormMount(
  {
    formComponent, formSchema, mode, permissions,
    definitionId, instanceId, businessKey, variablesJson, status,
    onVariablesChange, viewGlob = viewModules,
  },
  ref,
) {
  const { t } = useTranslation()
  const builtinRef = useRef<WfBuiltinFormHandle | null>(null)

  // 值不留本地副本:JSON 是唯一真相,父级回写后重新解析(与 Vue 的 watch 回环等价,但没有两份状态)。
  const parsed = useMemo(() => parseWfFormValuesResult(variablesJson), [variablesJson])

  // formComponent 与 formSchema 双配置属非法定义:保留消费者挂载点,内置表单让位。
  const builtinSchema = formComponent?.trim()
    ? null
    : formSchema?.fields?.length ? formSchema : null

  const resolved = useMemo(() => {
    const raw = formComponent?.trim()
    if (!raw) return null
    const key = `/src/views/${normalizeViewPath(raw)}.tsx`
    const loader = viewGlob[key]
    return loader ? { component: lazyFor(loader) } : { component: null }
  }, [formComponent, viewGlob])

  useImperativeHandle(ref, () => ({
    validate: () => {
      if (parsed.error) return false
      return builtinRef.current?.validate() ?? true
    },
  }), [parsed.error])

  if (builtinSchema && parsed.error) {
    return <Alert type="error" showIcon message={t('workflow.form.runtime.invalidVariables')} />
  }

  if (builtinSchema) {
    return (
      <WfBuiltinForm
        ref={builtinRef}
        schema={builtinSchema}
        value={parsed.values}
        mode={mode}
        permissions={permissions}
        onChange={(values) => onVariablesChange?.(serializeWfFormValues(values))}
      />
    )
  }

  if (!resolved) return null

  if (!resolved.component) {
    return <Alert type="warning" showIcon message={t('workflow.form.missing', { path: formComponent })} />
  }

  const Consumer = resolved.component
  return (
    <Suspense fallback={null}>
      <Consumer
        mode={mode}
        definitionId={definitionId}
        instanceId={instanceId}
        businessKey={businessKey}
        variablesJson={variablesJson}
        status={status}
      />
    </Suspense>
  )
})
